-- $Id: 9dbd572f67ce1b038246448ae408a03fc8a6026c $
DROP TABLE ENTEXAM_MIRAI_FS_REP_DAT

CREATE TABLE ENTEXAM_MIRAI_FS_REP_DAT \
( \
    MIRAI_FS_CD         VARCHAR(10) NOT NULL, \
    FS_CD               VARCHAR(7), \
    REGISTERCD          VARCHAR(10),  \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_MIRAI_FS_REP_DAT ADD CONSTRAINT \
PK_EEXAM_MR_FSRP PRIMARY KEY (MIRAI_FS_CD)
