-- $Id: aa0ddd9db3957c6d7aff426cd42da92780e0dc94 $

drop view V_AFT_DISEASE_ADDITION410_DAT

create view V_AFT_DISEASE_ADDITION410_DAT \
   (EDBOARD_SCHOOLCD, \
    YEAR, \
    COURSECD, \
    MAJORCD, \
    SEX, \
    SHINGAKU_DAIGAKU, \
    SHINGAKU_TANDAI, \
    SHINGAKU_SENMON, \
    SHINGAKU_SONOTA, \
    SHINGAKU_REMARK, \
    SHINGAKU_GOUKEI, \
    SHUSHOKU_KENNAI, \
    SHUSHOKU_KENNAI_KOUMUIN, \
    SHUSHOKU_KENGAI, \
    SHUSHOKU_KENGAI_KOUMUIN, \
    SHUSHOKU_SONOTA, \
    SHUSHOKU_REMARK, \
    SHUSHOKU_GOUKEI, \
    SONOTA_GOUKEI, \
    ZENTAI_GOUKEI \
    ) \
as  \
SELECT \
    T1.EDBOARD_SCHOOLCD, \
    T1.YEAR, \
    T1.COURSECD, \
    T1.MAJORCD, \
    T1.SEX, \
    L1.COUNT, \
    L2.COUNT, \
    L3.COUNT, \
    L4.COUNT, \
    L5.COUNT, \
    L6.COUNT, \
    W1.COUNT, \
    W2.COUNT, \
    W3.COUNT, \
    W4.COUNT, \
    W5.COUNT, \
    W6.COUNT, \
    W7.COUNT, \
    E1.COUNT, \
    S1.COUNT \
FROM \
    (SELECT \
        AFT1.EDBOARD_SCHOOLCD, \
        AFT1.YEAR, \
        AFT1.COURSECD, \
        AFT1.MAJORCD, \
        AFT1.SEX \
     FROM \
        AFT_DISEASE_ADDITION410_DAT AFT1 \
    GROUP BY \
        AFT1.EDBOARD_SCHOOLCD, \
        AFT1.YEAR, \
        AFT1.COURSECD, \
        AFT1.MAJORCD, \
        AFT1.SEX \
    ) T1 \
    LEFT JOIN AFT_DISEASE_ADDITION410_DAT L1 ON T1.EDBOARD_SCHOOLCD = L1.EDBOARD_SCHOOLCD \
         AND T1.YEAR = L1.YEAR \
         AND T1.COURSECD = L1.COURSECD \
         AND T1.MAJORCD = L1.MAJORCD \
         AND T1.SEX = L1.SEX \
         AND L1.LARGE_DIV = '10' \
         AND L1.MIDDLE_DIV = '99' \
         AND L1.SMALL_DIV = '004' \
    LEFT JOIN AFT_DISEASE_ADDITION410_DAT L2 ON T1.EDBOARD_SCHOOLCD = L2.EDBOARD_SCHOOLCD \
         AND T1.YEAR = L2.YEAR \
         AND T1.COURSECD = L2.COURSECD \
         AND T1.MAJORCD = L2.MAJORCD \
         AND T1.SEX = L2.SEX \
         AND L2.LARGE_DIV = '10' \
         AND L2.MIDDLE_DIV = '99' \
         AND L2.SMALL_DIV = '005' \
    LEFT JOIN AFT_DISEASE_ADDITION410_DAT L3 ON T1.EDBOARD_SCHOOLCD = L3.EDBOARD_SCHOOLCD \
         AND T1.YEAR = L3.YEAR \
         AND T1.COURSECD = L3.COURSECD \
         AND T1.MAJORCD = L3.MAJORCD \
         AND T1.SEX = L3.SEX \
         AND L3.LARGE_DIV = '10' \
         AND L3.MIDDLE_DIV = '99' \
         AND L3.SMALL_DIV = '006' \
    LEFT JOIN AFT_DISEASE_ADDITION410_DAT L4 ON T1.EDBOARD_SCHOOLCD = L4.EDBOARD_SCHOOLCD \
         AND T1.YEAR = L4.YEAR \
         AND T1.COURSECD = L4.COURSECD \
         AND T1.MAJORCD = L4.MAJORCD \
         AND T1.SEX = L4.SEX \
         AND L4.LARGE_DIV = '10' \
         AND L4.MIDDLE_DIV = '99' \
         AND L4.SMALL_DIV = '008' \
     LEFT JOIN AFT_DISEASE_ADDITION410_DAT L5 ON T1.EDBOARD_SCHOOLCD = L5.EDBOARD_SCHOOLCD \
         AND T1.YEAR = L5.YEAR \
         AND T1.COURSECD = L5.COURSECD \
         AND T1.MAJORCD = L5.MAJORCD \
         AND T1.SEX = L5.SEX \
         AND L5.LARGE_DIV = '10' \
         AND L5.MIDDLE_DIV = '99' \
         AND L5.SMALL_DIV = '009' \
     LEFT JOIN AFT_DISEASE_ADDITION410_DAT L6 ON T1.EDBOARD_SCHOOLCD = L6.EDBOARD_SCHOOLCD \
         AND T1.YEAR = L6.YEAR \
         AND T1.COURSECD = L6.COURSECD \
         AND T1.MAJORCD = L6.MAJORCD \
         AND T1.SEX = L6.SEX \
         AND L6.LARGE_DIV = '10' \
         AND L6.MIDDLE_DIV = '99' \
         AND L6.SMALL_DIV = '999' \
     LEFT JOIN AFT_DISEASE_ADDITION410_DAT W1 ON T1.EDBOARD_SCHOOLCD = W1.EDBOARD_SCHOOLCD \
         AND T1.YEAR = W1.YEAR \
         AND T1.COURSECD = W1.COURSECD \
         AND T1.MAJORCD = W1.MAJORCD \
         AND T1.SEX = W1.SEX \
         AND W1.LARGE_DIV = '20' \
         AND W1.MIDDLE_DIV = '01' \
         AND W1.SMALL_DIV = '999' \
     LEFT JOIN AFT_DISEASE_ADDITION410_DAT W2 ON T1.EDBOARD_SCHOOLCD = W2.EDBOARD_SCHOOLCD \
         AND T1.YEAR = W2.YEAR \
         AND T1.COURSECD = W2.COURSECD \
         AND T1.MAJORCD = W2.MAJORCD \
         AND T1.SEX = W2.SEX \
         AND W2.LARGE_DIV = '20' \
         AND W2.MIDDLE_DIV = '01' \
         AND W2.SMALL_DIV = '003' \
     LEFT JOIN AFT_DISEASE_ADDITION410_DAT W3 ON T1.EDBOARD_SCHOOLCD = W3.EDBOARD_SCHOOLCD \
         AND T1.YEAR = W3.YEAR \
         AND T1.COURSECD = W3.COURSECD \
         AND T1.MAJORCD = W3.MAJORCD \
         AND T1.SEX = W3.SEX \
         AND W3.LARGE_DIV = '20' \
         AND W3.MIDDLE_DIV = '02' \
         AND W3.SMALL_DIV = '999' \
     LEFT JOIN AFT_DISEASE_ADDITION410_DAT W4 ON T1.EDBOARD_SCHOOLCD = W4.EDBOARD_SCHOOLCD \
         AND T1.YEAR = W4.YEAR \
         AND T1.COURSECD = W4.COURSECD \
         AND T1.MAJORCD = W4.MAJORCD \
         AND T1.SEX = W4.SEX \
         AND W4.LARGE_DIV = '20' \
         AND W4.MIDDLE_DIV = '02' \
         AND W4.SMALL_DIV = '003' \
     LEFT JOIN AFT_DISEASE_ADDITION410_DAT W5 ON T1.EDBOARD_SCHOOLCD = W5.EDBOARD_SCHOOLCD \
         AND T1.YEAR = W5.YEAR \
         AND T1.COURSECD = W5.COURSECD \
         AND T1.MAJORCD = W5.MAJORCD \
         AND T1.SEX = W5.SEX \
         AND W5.LARGE_DIV = '20' \
         AND W5.MIDDLE_DIV = '08' \
         AND W5.SMALL_DIV = '999' \
     LEFT JOIN AFT_DISEASE_ADDITION410_DAT W6 ON T1.EDBOARD_SCHOOLCD = W6.EDBOARD_SCHOOLCD \
         AND T1.YEAR = W6.YEAR \
         AND T1.COURSECD = W6.COURSECD \
         AND T1.MAJORCD = W6.MAJORCD \
         AND T1.SEX = W6.SEX \
         AND W6.LARGE_DIV = '20' \
         AND W6.MIDDLE_DIV = '09' \
         AND W6.SMALL_DIV = '999' \
     LEFT JOIN AFT_DISEASE_ADDITION410_DAT W7 ON T1.EDBOARD_SCHOOLCD = W7.EDBOARD_SCHOOLCD \
         AND T1.YEAR = W7.YEAR \
         AND T1.COURSECD = W7.COURSECD \
         AND T1.MAJORCD = W7.MAJORCD \
         AND T1.SEX = W7.SEX \
         AND W7.LARGE_DIV = '20' \
         AND W7.MIDDLE_DIV = '99' \
         AND W7.SMALL_DIV = '999' \
     LEFT JOIN AFT_DISEASE_ADDITION410_DAT E1 ON T1.EDBOARD_SCHOOLCD = E1.EDBOARD_SCHOOLCD \
         AND T1.YEAR = E1.YEAR \
         AND T1.COURSECD = E1.COURSECD \
         AND T1.MAJORCD = E1.MAJORCD \
         AND T1.SEX = E1.SEX \
         AND E1.LARGE_DIV = '30' \
         AND E1.MIDDLE_DIV = '99' \
         AND E1.SMALL_DIV = '999' \
     LEFT JOIN AFT_DISEASE_ADDITION410_DAT S1 ON T1.EDBOARD_SCHOOLCD = S1.EDBOARD_SCHOOLCD \
         AND T1.YEAR = S1.YEAR \
         AND T1.COURSECD = S1.COURSECD \
         AND T1.MAJORCD = S1.MAJORCD \
         AND T1.SEX = S1.SEX \
         AND S1.LARGE_DIV = '99' \
         AND S1.MIDDLE_DIV = '99' \
         AND S1.SMALL_DIV = '999'
