-- $Id: d3ad430d71253dda5b66dc0cf394cff0e50b54e5 $

DROP VIEW V_ATTEND_SUBCLASS_DAT

CREATE VIEW V_ATTEND_SUBCLASS_DAT \
   (COPYCD, \
    YEAR, \
    MONTH, \
    SEMESTER, \
    SCHREGNO, \
    CLASSCD, \
    SCHOOL_KIND, \
    CURRICULUM_CD, \
    SUBCLASSCD, \
    APPOINTED_DAY, \
    LESSON, \
    OFFDAYS, \
    ABSENT, \
    SUSPEND, \
    MOURNING, \
    ABROAD, \
    SICK, \
    NOTICE, \
    NONOTICE, \
    NURSEOFF, \
    LATE, \
    EARLY, \
    VIRUS, \
    KOUDOME, \
    KEKKA_JISU) \
AS \
SELECT \
    T1.COPYCD, \
    T1.YEAR, \
    T1.MONTH, \
    T1.SEMESTER, \
    T1.SCHREGNO, \
    T1.CLASSCD, \
    T1.SCHOOL_KIND, \
    T1.CURRICULUM_CD, \
    T1.SUBCLASSCD, \
    T1.APPOINTED_DAY, \
    T1.LESSON, \
    T1.OFFDAYS, \
    T1.ABSENT, \
    T1.SUSPEND, \
    T1.MOURNING, \
    T1.ABROAD, \
    T1.SICK, \
    T1.NOTICE, \
    T1.NONOTICE, \
    T1.NURSEOFF, \
    T1.LATE, \
    T1.EARLY, \
    T1.VIRUS, \
    T1.KOUDOME, \
    VALUE(L1.CNT, 0) AS KEKKA_JISU \
FROM \
    ATTEND_SUBCLASS_DAT T1 \
    LEFT JOIN ATTEND_SUBCLASS_DETAIL_DAT L1 ON T1.COPYCD = L1.COPYCD \
         AND T1.YEAR = L1.YEAR \
         AND T1.MONTH = L1.MONTH \
         AND T1.SEMESTER = L1.SEMESTER \
         AND T1.SCHREGNO = L1.SCHREGNO \
         AND T1.CLASSCD = L1.CLASSCD \
         AND T1.SCHOOL_KIND = L1.SCHOOL_KIND \
         AND T1.CURRICULUM_CD = L1.CURRICULUM_CD \
         AND T1.SUBCLASSCD = L1.SUBCLASSCD \
         AND L1.SEQ = '001'
