-- $Id: 16befeae3e689478297730b11f315d33579d89ce $

DROP VIEW V_ATTEND_SEMES_DAT

CREATE VIEW V_ATTEND_SEMES_DAT \
   (COPYCD, \
    YEAR, \
    MONTH, \
    SEMESTER, \
    SCHREGNO, \
    APPOINTED_DAY, \
    LESSON, \
    OFFDAYS, \
    ABSENT, \
    SUSPEND, \
    MOURNING, \
    ABROAD, \
    SICK, \
    NOTICE, \
    NONOTICE, \
    LATE, \
    EARLY, \
    KEKKA_JISU, \
    KEKKA, \
    LATEDETAIL, \
    VIRUS, \
    KOUDOME, \
    REIHAI_KEKKA, \
    M_KEKKA_JISU, \
    REIHAI_TIKOKU, \
    JYUGYOU_TIKOKU, \
    JYUGYOU_SOUTAI, \
    JYUGYOU_JISU_DECIMAL, \
    TOCHU_KEKKA \
  ) \
AS \
SELECT \
    T1.COPYCD, \
    T1.YEAR, \
    T1.MONTH, \
    T1.SEMESTER, \
    T1.SCHREGNO, \
    T1.APPOINTED_DAY, \
    T1.LESSON, \
    T1.OFFDAYS, \
    T1.ABSENT, \
    T1.SUSPEND, \
    T1.MOURNING, \
    T1.ABROAD, \
    T1.SICK, \
    T1.NOTICE, \
    T1.NONOTICE, \
    T1.LATE, \
    T1.EARLY, \
    T1.KEKKA_JISU, \
    T1.KEKKA, \
    T1.LATEDETAIL, \
    T1.VIRUS, \
    T1.KOUDOME, \
    VALUE(L1.CNT, 0) AS REIHAI_KEKKA, \
    VALUE(L2.CNT, 0) AS M_KEKKA_JISU, \
    VALUE(L3.CNT, 0) AS REIHAI_TIKOKU, \
    VALUE(L4.CNT, 0) AS JYUGYOU_TIKOKU, \
    VALUE(L5.CNT, 0) AS JYUGYOU_SOUTAI, \
    VALUE(L101.CNT_DECIMAL, 0.0) AS JYUGYOU_JISU_DECIMAL, \
    VALUE(L102.CNT, 0) AS TOCHU_KEKKA \
FROM \
    ATTEND_SEMES_DAT T1 \
    LEFT JOIN ATTEND_SEMES_DETAIL_DAT L1 ON T1.COPYCD = L1.COPYCD \
         AND T1.YEAR = L1.YEAR \
         AND T1.MONTH = L1.MONTH \
         AND T1.SEMESTER = L1.SEMESTER \
         AND T1.SCHREGNO = L1.SCHREGNO \
         AND L1.SEQ = '001' \
    LEFT JOIN ATTEND_SEMES_DETAIL_DAT L2 ON T1.COPYCD = L2.COPYCD \
         AND T1.YEAR = L2.YEAR \
         AND T1.MONTH = L2.MONTH \
         AND T1.SEMESTER = L2.SEMESTER \
         AND T1.SCHREGNO = L2.SCHREGNO \
         AND L2.SEQ = '002' \
    LEFT JOIN ATTEND_SEMES_DETAIL_DAT L3 ON T1.COPYCD = L3.COPYCD \
         AND T1.YEAR = L3.YEAR \
         AND T1.MONTH = L3.MONTH \
         AND T1.SEMESTER = L3.SEMESTER \
         AND T1.SCHREGNO = L3.SCHREGNO \
         AND L3.SEQ = '003' \
    LEFT JOIN ATTEND_SEMES_DETAIL_DAT L4 ON T1.COPYCD = L4.COPYCD \
         AND T1.YEAR = L4.YEAR \
         AND T1.MONTH = L4.MONTH \
         AND T1.SEMESTER = L4.SEMESTER \
         AND T1.SCHREGNO = L4.SCHREGNO \
         AND L4.SEQ = '004' \
    LEFT JOIN ATTEND_SEMES_DETAIL_DAT L5 ON T1.COPYCD = L5.COPYCD \
         AND T1.YEAR = L5.YEAR \
         AND T1.MONTH = L5.MONTH \
         AND T1.SEMESTER = L5.SEMESTER \
         AND T1.SCHREGNO = L5.SCHREGNO \
         AND L5.SEQ = '005' \
    LEFT JOIN ATTEND_SEMES_DETAIL_DAT L101 ON T1.COPYCD = L101.COPYCD \
         AND T1.YEAR = L101.YEAR \
         AND T1.MONTH = L101.MONTH \
         AND T1.SEMESTER = L101.SEMESTER \
         AND T1.SCHREGNO = L101.SCHREGNO \
         AND L101.SEQ = '101' \
    LEFT JOIN ATTEND_SEMES_DETAIL_DAT L102 ON T1.COPYCD = L102.COPYCD \
         AND T1.YEAR = L102.YEAR \
         AND T1.MONTH = L102.MONTH \
         AND T1.SEMESTER = L102.SEMESTER \
         AND T1.SCHREGNO = L102.SCHREGNO \
         AND L102.SEQ = '102'
