-- $Id: fcc0d32e1be9bc77b7806ae618aadec9bb14bba6 $

drop view V_CHALLENGED_ASSESSMENT_STATUS_GROWUP_DAT

create view V_CHALLENGED_ASSESSMENT_STATUS_GROWUP_DAT \
   (YEAR, \
    WINDOW_PTRN_DIV, \
    STATUS_NAME, \
    GROWUP_NAME, \
    ITEM1, \
    ITEM2, \
    ITEM3, \
    ITEM4, \
    ITEM5, \
    ITEM6, \
    ITEM7, \
    ITEM8, \
    ITEM9, \
    ITEM10, \
    ITEM11, \
    ITEM12, \
    ITEM13, \
    ITEM14, \
    ITEM15, \
    ITEM16, \
    ITEM17, \
    ITEM18, \
    ITEM19, \
    ITEM20  \
    ) \
as  \
select \
    YEAR, \
    MIN( CASE WHEN DATA_DIV = '0'  \
    THEN CASE WHEN GROWUP_NAME IS NOT NULL THEN '2' ELSE '1' END \
    ELSE NULL \
    END ) AS WINDOW_PTRN_DIV, \
    MIN(CASE WHEN DATA_DIV = '0' THEN STATUS_NAME ELSE NULL END ) AS STATUS_NAME, \
    MIN(CASE WHEN DATA_DIV = '0' THEN GROWUP_NAME ELSE NULL END ) AS GROWUP_NAME, \
    MIN(CASE WHEN DATA_DIV = '1' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM1, \
    MIN(CASE WHEN DATA_DIV = '2' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM2, \
    MIN(CASE WHEN DATA_DIV = '3' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM3, \
    MIN(CASE WHEN DATA_DIV = '4' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM4, \
    MIN(CASE WHEN DATA_DIV = '5' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM5, \
    MIN(CASE WHEN DATA_DIV = '6' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM6, \
    MIN(CASE WHEN DATA_DIV = '7' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM7, \
    MIN(CASE WHEN DATA_DIV = '8' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM8, \
    MIN(CASE WHEN DATA_DIV = '9' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM9, \
    MIN(CASE WHEN DATA_DIV = '10' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM10, \
    MIN(CASE WHEN DATA_DIV = '11' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM11, \
    MIN(CASE WHEN DATA_DIV = '12' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM12, \
    MIN(CASE WHEN DATA_DIV = '13' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM13, \
    MIN(CASE WHEN DATA_DIV = '14' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM14, \
    MIN(CASE WHEN DATA_DIV = '15' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM15, \
    MIN(CASE WHEN DATA_DIV = '16' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM16, \
    MIN(CASE WHEN DATA_DIV = '17' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM17, \
    MIN(CASE WHEN DATA_DIV = '18' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM18, \
    MIN(CASE WHEN DATA_DIV = '19' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM19, \
    MIN(CASE WHEN DATA_DIV = '20' THEN DATA_DIV_NAME ELSE NULL END ) AS ITEM20 \
from \
    CHALLENGED_ASSESSMENT_STATUS_GROWUP_DAT \
group by \
    YEAR 
