-- $Id: f8cea1363e421af11b5fe7672d3c6b0f30f6fc60 $

DROP VIEW V_COLLECT_GRP_DAT

CREATE VIEW V_COLLECT_GRP_DAT \
   (SCHOOLCD, \
    SCHOOL_KIND, \
    YEAR, \
    COLLECT_GRP_CD, \
    COLLECT_GRP_NAME, \
    COLLECT_L_CD, \
    COLLECT_M_CD, \
    COLLECT_S_CD, \
    COLLECT_KOJIN_FLG \
    ) \
AS \
SELECT \
    T1.SCHOOLCD, \
    T1.SCHOOL_KIND, \
    T1.YEAR, \
    T1.COLLECT_GRP_CD, \
    T2.COLLECT_GRP_NAME, \
    T1.COLLECT_L_CD, \
    T1.COLLECT_M_CD, \
    T1.COLLECT_S_CD, \
    VALUE(T2.COLLECT_KOJIN_FLG, '0') AS COLLECT_KOJIN_FLG \
FROM \
    COLLECT_GRP_DAT T1, \
    COLLECT_GRP_MST T2 \
WHERE \
    T1.SCHOOLCD = T2.SCHOOLCD \
    AND T1.SCHOOL_KIND = T2.SCHOOL_KIND \
    AND T1.YEAR = T2.YEAR \
    AND T1.COLLECT_GRP_CD = T2.COLLECT_GRP_CD
