-- $Id: 03f500146c268da1734e0c5a3cd32e2b85c78c0a $

DROP VIEW V_COURSE_MAJOR_MST 
create view V_COURSE_MAJOR_MST \
    (YEAR, COURSECD, MAJORCD, COURSENAME, MAJORNAME, MAJORNAME2, MAJORNAME3, COURSEABBV, MAJORABBV, COURSEENG, MAJORENG, MAJORBANKCD, SCHOOLDIV) as \
select \
    T1.YEAR, \
    T1.COURSECD, \
    T2.MAJORCD, \
    T1.COURSENAME, \
    T2.MAJORNAME, \
    T2.MAJORNAME2, \
    T2.MAJORNAME3, \
    T1.COURSEABBV, \
    T2.MAJORABBV, \
    T1.COURSEENG, \
    T2.MAJORENG, \
    T2.MAJORBANKCD, \
    T2.SCHOOLDIV \
from \
    V_COURSE_MST T1, \
    V_MAJOR_MST  T2 \
where \
    T1.YEAR     = T2.YEAR AND \
    T1.COURSECD = T2.COURSECD
