-- $Id: e9ed69a5d6ddd565a0c03eab40daf555df9ba2ea $

DROP VIEW V_CREDIT_MST
CREATE VIEW V_CREDIT_MST \
    ( \
        YEAR, \
        COURSECD, \
        MAJORCD, \
        GRADE, \
        COURSECODE, \
        CLASSCD, \
        SCHOOL_KIND, \
        CURRICULUM_CD, \
        SUBCLASSCD, \
        CREDITS, \
        ABSENCE_HIGH, \
        GET_ABSENCE_HIGH, \
        ABSENCE_WARN_SHUTOKU_SEM1, \
        ABSENCE_WARN_RISHU_SEM1, \
        ABSENCE_WARN_SHUTOKU_SEM2, \
        ABSENCE_WARN_RISHU_SEM2, \
        ABSENCE_WARN_SHUTOKU_SEM3, \
        ABSENCE_WARN_RISHU_SEM3, \
        ABSENCE_WARN, \
        ABSENCE_WARN2, \
        ABSENCE_WARN3, \
        REQUIRE_FLG, \
        AUTHORIZE_FLG, \
        COMP_UNCONDITION_FLG, \
        TIME_UNIT, \
        RATE, \
        UPDATED \
    ) AS \
SELECT \
    YEAR, \
    COURSECD, \
    MAJORCD, \
    GRADE, \
    COURSECODE, \
    CLASSCD, \
    SCHOOL_KIND, \
    CURRICULUM_CD, \
    SUBCLASSCD, \
    CREDITS, \
    ABSENCE_HIGH, \
    GET_ABSENCE_HIGH, \
    (ABSENCE_WARN  * CREDITS) AS ABSENCE_WARN_SHUTOKU_SEM1, \
    (ABSENCE_WARN  * CREDITS) AS ABSENCE_WARN_RISHU_SEM1, \
    (ABSENCE_WARN2 * CREDITS) AS ABSENCE_WARN_SHUTOKU_SEM2, \
    (ABSENCE_WARN2 * CREDITS) AS ABSENCE_WARN_RISHU_SEM2, \
    (ABSENCE_WARN3 * CREDITS) AS ABSENCE_WARN_SHUTOKU_SEM3, \
    (ABSENCE_WARN3 * CREDITS) AS ABSENCE_WARN_RISHU_SEM3, \
    ABSENCE_WARN, \
    ABSENCE_WARN2, \
    ABSENCE_WARN3, \
    REQUIRE_FLG, \
    AUTHORIZE_FLG, \
    COMP_UNCONDITION_FLG, \
    TIME_UNIT, \
    RATE, \
    UPDATED \
FROM \
    CREDIT_MST