-- $Id: f1745996d97eac3531e58853d9e146f39225fc51 $

DROP VIEW V_EDBOARD_COURSE_MST 
CREATE VIEW V_EDBOARD_COURSE_MST \
    (EDBOARD_SCHOOLCD, YEAR, COURSECD, COURSENAME, COURSEABBV, COURSEENG, UPDATED) AS \
SELECT \
    T1.EDBOARD_SCHOOLCD, \
    T1.YEAR, \
    T2.COURSECD, \
    T2.COURSENAME, \
    T2.COURSEABBV, \
    T2.COURSEENG, \
    T2.UPDATED \
FROM \
    EDBOARD_COURSE_YDAT T1, \
    EDBOARD_COURSE_MST T2 \
WHERE \
    T1.EDBOARD_SCHOOLCD = T2.EDBOARD_SCHOOLCD AND \
    T1.COURSECD         = T2.COURSECD
