-- $Id: 20da52e499abc54f4bb39e8d494f77ef6d544540 $

DROP VIEW V_EDBOARD_COURSE_MAJOR_MST 
CREATE VIEW V_EDBOARD_COURSE_MAJOR_MST \
    (EDBOARD_SCHOOLCD, YEAR, COURSECD, MAJORCD, COURSENAME, MAJORNAME, MAJORNAME2, MAJORNAME3, COURSEABBV, MAJORABBV, COURSEENG, MAJORENG, MAJORBANKCD, SCHOOLDIV) AS \
SELECT \
    T1.EDBOARD_SCHOOLCD, \
    T1.YEAR, \
    T1.COURSECD, \
    T2.MAJORCD, \
    T1.COURSENAME, \
    T2.MAJORNAME, \
    T2.MAJORNAME2, \
    T2.MAJORNAME3, \
    T1.COURSEABBV, \
    T2.MAJORABBV, \
    T1.COURSEENG, \
    T2.MAJORENG, \
    T2.MAJORBANKCD, \
    T2.SCHOOLDIV \
FROM \
    V_EDBOARD_COURSE_MST T1, \
    V_EDBOARD_MAJOR_MST  T2 \
WHERE \
    T1.EDBOARD_SCHOOLCD = T2.EDBOARD_SCHOOLCD AND \
    T1.YEAR             = T2.YEAR AND \
    T1.COURSECD         = T2.COURSECD
