-- $Id: 03be667669be961530e8c62b05c465322a69dca5 $

DROP VIEW V_EDBOARD_MAJOR_MST
CREATE VIEW V_EDBOARD_MAJOR_MST \
    (EDBOARD_SCHOOLCD, \
     YEAR, \
     COURSECD, \
     MAJORCD, \
     MAJORNAME, \
     MAJORNAME2, \
     MAJORNAME3, \
     MAJORABBV, \
     MAJORENG, \
     MAJORBANKCD, \
     SCHOOLDIV, \
     UDPATED \
    ) AS \
SELECT \
    T1.EDBOARD_SCHOOLCD, \
    T1.YEAR, \
    T2.COURSECD, \
    T2.MAJORCD, \
    T2.MAJORNAME, \
    T2.MAJORNAME2, \
    T2.MAJORNAME3, \
    T2.MAJORABBV, \
    T2.MAJORENG, \
    T2.MAJORBANKCD, \
    T1.SCHOOLDIV, \
    T2.UPDATED \
FROM \
    EDBOARD_MAJOR_YDAT T1, \
    EDBOARD_MAJOR_MST T2 \
WHERE \
    T1.EDBOARD_SCHOOLCD = T2.EDBOARD_SCHOOLCD AND \
    T1.COURSECD         = T2.COURSECD AND \
    T1.MAJORCD          = T2.MAJORCD
