-- $Id: 8152f7f4dfc24bcce2f703f1ae8e255385556849 $

DROP VIEW V_ELECTCLASS_MST

CREATE VIEW V_ELECTCLASS_MST \
   (YEAR, \
    GROUPCD, \
    GROUPNAME, \
    GROUPABBV, \
    REMARK, \
    SHOWORDER, \
    UPDATED) AS  \
SELECT \
    YEAR, \
    GROUPCD, \
    GROUPNAME, \
    GROUPABBV, \
    REMARK, \
    SHOWORDER, \
    UPDATED \
FROM \
    ELECTCLASS_DAT
