-- $Id: d24ca6f96c1de66b3916b039877d172e70561a4f $
DROP VIEW V_FACILITY_MST

CREATE VIEW V_FACILITY_MST \
    (YEAR, \
     FACCD, \
     FACILITYNAME, \
     FACILITYABBV, \
     CAPACITY, \
     CHR_CAPACITY, \
     UPDATED) \
AS SELECT \
    T1.YEAR, \
    T2.FACCD, \
    T2.FACILITYNAME, \
    T2.FACILITYABBV, \
    T2.CAPACITY, \
    T2.CHR_CAPACITY, \
    T2.UPDATED \
FROM     FACILITY_YDAT T1, \
    FACILITY_MST T2 \
WHERE    T1.FACCD = T2.FACCD

 
