-- $Id: 4902a174d463ed6b6e269ed453e34175c475cfe3 $

DROP VIEW V_FINHIGHSCHOOL_MST

CREATE VIEW V_FINHIGHSCHOOL_MST \
  ( YEAR, \
    FINSCHOOLCD, \
    FINSCHOOL_DISTCD, \
    FINSCHOOL_NAME, \
    FINSCHOOL_KANA, \
    PRINCNAME, \
    PRINCNAME_SHOW, \
    PRINCKANA, \
    DISTRICTCD, \
    FINSCHOOL_PREF_CD, \
    FINSCHOOL_ZIPCD, \
    FINSCHOOL_ADDR1, \
    FINSCHOOL_ADDR2, \
    FINSCHOOL_TELNO, \
    FINSCHOOL_FAXNO, \
    EDBOARDCD, \
    UPDATED ) \
AS SELECT \
    T1.YEAR, \
    T2.FINSCHOOLCD, \
    T2.FINSCHOOL_DISTCD, \
    T2.FINSCHOOL_NAME, \
    T2.FINSCHOOL_KANA, \
    T2.PRINCNAME, \
    T2.PRINCNAME_SHOW, \
    T2.PRINCKANA, \
    T2.DISTRICTCD, \
    T2.FINSCHOOL_PREF_CD, \
    T2.FINSCHOOL_ZIPCD, \
    T2.FINSCHOOL_ADDR1, \
    T2.FINSCHOOL_ADDR2, \
    T2.FINSCHOOL_TELNO, \
    T2.FINSCHOOL_FAXNO, \
    T2.EDBOARDCD, \
    T2.UPDATED \
FROM     FINHIGHSCHOOL_YDAT T1, \
    FINHIGHSCHOOL_MST T2 \
WHERE    T1.FINSCHOOLCD = T2.FINSCHOOLCD

