-- $Id: 08a3e688a067ae4c15fbfe3f7e273f198b0401ea $

DROP VIEW V_HREPORT_SELFRELIANCE_SCHREG_REMARK_DAT

create view V_HREPORT_SELFRELIANCE_SCHREG_REMARK_DAT \
   (YEAR, \
    SEMESTER, \
    SCHREGNO, \
    GOALS, \
    ACCOMMODATION, \
    KEY_GOALS, \
    GOALS_REASON, \
    LONG_GOALS1, \
    SHORT_GOALS1, \
    MEANS1, \
    EVALUATION1, \
    LONG_GOALS2, \
    SHORT_GOALS2, \
    MEANS2, \
    EVALUATION2, \
    LONG_GOALS3, \
    SHORT_GOALS3, \
    MEANS3, \
    EVALUATION3, \
    LONG_GOALS4, \
    SHORT_GOALS4, \
    MEANS4, \
    EVALUATION4 \
    ) \
as  \
SELECT \
    MAIN_T.YEAR, \
    MAIN_T.SEMESTER, \
    MAIN_T.SCHREGNO, \
    DAT.GOALS, \
    DAT.ACCOMMODATION, \
    DAT.KEY_GOALS, \
    DAT.GOALS_REASON, \
    DIV1.LONG_GOALS AS LONG_GOALS1, \
    DIV1.SHORT_GOALS AS SHORT_GOALS1, \
    DIV1.MEANS AS MEANS1, \
    DIV1.EVALUATION AS EVALUATION1, \
    DIV2.LONG_GOALS AS LONG_GOALS2, \
    DIV2.SHORT_GOALS AS SHORT_GOALS2, \
    DIV2.MEANS AS MEANS2, \
    DIV2.EVALUATION AS EVALUATION2, \
    DIV3.LONG_GOALS AS LONG_GOALS3, \
    DIV3.SHORT_GOALS AS SHORT_GOALS3, \
    DIV3.MEANS AS MEANS3, \
    DIV3.EVALUATION AS EVALUATION3, \
    DIV4.LONG_GOALS AS LONG_GOALS4, \
    DIV4.SHORT_GOALS AS SHORT_GOALS4, \
    DIV4.MEANS AS MEANS4, \
    DIV4.EVALUATION AS EVALUATION4 \
FROM \
    ( \
    SELECT \
        YEAR, \
        SEMESTER, \
        SCHREGNO \
    FROM \
        HREPORT_SELFRELIANCE_SCHREG_REMARK_DAT \
    GROUP BY \
        YEAR, \
        SEMESTER, \
        SCHREGNO \
    UNION \
    SELECT \
        YEAR, \
        SEMESTER, \
        SCHREGNO \
    FROM \
        HREPORT_SELFRELIANCE_SCHREG_REMARK_DIV_DAT \
    GROUP BY \
        YEAR, \
        SEMESTER, \
        SCHREGNO \
    ) AS MAIN_T \
    LEFT JOIN HREPORT_SELFRELIANCE_SCHREG_REMARK_DAT DAT ON MAIN_T.YEAR = DAT.YEAR \
         AND MAIN_T.SEMESTER = DAT.SEMESTER \
         AND MAIN_T.SCHREGNO = DAT.SCHREGNO \
    LEFT JOIN HREPORT_SELFRELIANCE_SCHREG_REMARK_DIV_DAT DIV1 ON MAIN_T.YEAR = DIV1.YEAR \
         AND MAIN_T.SEMESTER = DIV1.SEMESTER \
         AND MAIN_T.SCHREGNO = DIV1.SCHREGNO \
         AND DIV1.DIV = '01' \
    LEFT JOIN HREPORT_SELFRELIANCE_SCHREG_REMARK_DIV_DAT DIV2 ON MAIN_T.YEAR = DIV2.YEAR \
         AND MAIN_T.SEMESTER = DIV2.SEMESTER \
         AND MAIN_T.SCHREGNO = DIV2.SCHREGNO \
         AND DIV2.DIV = '02' \
    LEFT JOIN HREPORT_SELFRELIANCE_SCHREG_REMARK_DIV_DAT DIV3 ON MAIN_T.YEAR = DIV3.YEAR \
         AND MAIN_T.SEMESTER = DIV3.SEMESTER \
         AND MAIN_T.SCHREGNO = DIV3.SCHREGNO \
         AND DIV3.DIV = '03' \
    LEFT JOIN HREPORT_SELFRELIANCE_SCHREG_REMARK_DIV_DAT DIV4 ON MAIN_T.YEAR = DIV4.YEAR \
         AND MAIN_T.SEMESTER = DIV4.SEMESTER \
         AND MAIN_T.SCHREGNO = DIV4.SCHREGNO \
         AND DIV4.DIV = '04'
