-- kanji=Š¿Žš
-- $Id: 755d982f425f8c16f50066057a4a72af5e0e21ab $

DROP VIEW V_MAJOR_MST

CREATE VIEW V_MAJOR_MST \
    (YEAR, \
     COURSECD, \
     MAJORCD, \
     MAJORNAME, \
     MAJORNAME2, \
     MAJORNAME3, \
     MAJORABBV, \
     MAJORENG, \
     MAJORBANKCD, \
     SCHOOLDIV, \
     UDPATED \
    ) \
AS SELECT \
    T1.YEAR, \
    T2.COURSECD, \
    T2.MAJORCD, \
    T2.MAJORNAME, \
    T2.MAJORNAME2, \
    T2.MAJORNAME3, \
    T2.MAJORABBV, \
    T2.MAJORENG, \
    T2.MAJORBANKCD, \
    T1.SCHOOLDIV, \
    T2.UPDATED \
FROM \
    MAJOR_YDAT T1, \
    MAJOR_MST T2 \
WHERE \
    T1.COURSECD = T2.COURSECD \
AND T1.MAJORCD  = T2.MAJORCD
