-- kanji=Š¿Žš
-- $Id: e7a1c332ce082f653bcb5dff46b1b0ccd0dbfd24 $

DROP VIEW V_MEDEXAM_TOOTH_DAT

CREATE VIEW V_MEDEXAM_TOOTH_DAT \
   (YEAR, \
    SCHREGNO, \
    JAWS_JOINTCD, \
    JAWS_JOINTCD2, \
    JAWS_JOINTCD3, \
    PLAQUECD, \
    GUMCD, \
    CALCULUS, \
    ORTHODONTICS, \
    UP_R_BABY5, \
    UP_R_BABY4, \
    UP_R_BABY3, \
    UP_R_BABY2, \
    UP_R_BABY1, \
    UP_L_BABY1, \
    UP_L_BABY2, \
    UP_L_BABY3, \
    UP_L_BABY4, \
    UP_L_BABY5, \
    LW_R_BABY5, \
    LW_R_BABY4, \
    LW_R_BABY3, \
    LW_R_BABY2, \
    LW_R_BABY1, \
    LW_L_BABY1, \
    LW_L_BABY2, \
    LW_L_BABY3, \
    LW_L_BABY4, \
    LW_L_BABY5, \
    BABYTOOTH, \
    REMAINBABYTOOTH, \
    TREATEDBABYTOOTH, \
    BRACK_BABYTOOTH, \
    UP_R_ADULT8, \
    UP_R_ADULT7, \
    UP_R_ADULT6, \
    UP_R_ADULT5, \
    UP_R_ADULT4, \
    UP_R_ADULT3, \
    UP_R_ADULT2, \
    UP_R_ADULT1, \
    UP_L_ADULT1, \
    UP_L_ADULT2, \
    UP_L_ADULT3, \
    UP_L_ADULT4, \
    UP_L_ADULT5, \
    UP_L_ADULT6, \
    UP_L_ADULT7, \
    UP_L_ADULT8, \
    LW_R_ADULT8, \
    LW_R_ADULT7, \
    LW_R_ADULT6, \
    LW_R_ADULT5, \
    LW_R_ADULT4, \
    LW_R_ADULT3, \
    LW_R_ADULT2, \
    LW_R_ADULT1, \
    LW_L_ADULT1, \
    LW_L_ADULT2, \
    LW_L_ADULT3, \
    LW_L_ADULT4, \
    LW_L_ADULT5, \
    LW_L_ADULT6, \
    LW_L_ADULT7, \
    LW_L_ADULT8, \
    ADULTTOOTH, \
    REMAINADULTTOOTH, \
    TREATEDADULTTOOTH, \
    LOSTADULTTOOTH, \
    BRACK_ADULTTOOTH, \
    CHECKADULTTOOTH, \
    OTHERDISEASECD, \
    OTHERDISEASE, \
    OTHERDISEASECD3, \
    OTHERDISEASECD4, \
    OTHERDISEASECD2, \
    OTHERDISEASE2, \
    DENTISTREMARKCD, \
    DENTISTREMARK, \
    DENTISTREMARKCD2, \
    DENTISTREMARK2, \
    DENTISTREMARKCD3, \
    DENTISTREMARK3, \
    DENTISTREMARKDATE, \
    DENTISTREMARK_CO, \
    DENTISTREMARK_GO, \
    DENTISTREMARK_G, \
    DENTISTTREATCD, \
    DENTISTTREAT, \
    DENTISTTREAT2, \
    DENTISTTREAT3, \
    DENTISTTREATCD2, \
    DENTISTTREAT2_1, \
    DOC_NAME, \
    REGISTERCD, \
    UPDATED \
    ) \
AS SELECT \
    T1.YEAR, \
    T1.SCHREGNO, \
    T1.JAWS_JOINTCD, \
    T1.JAWS_JOINTCD2, \
    T1.JAWS_JOINTCD3, \
    T1.PLAQUECD, \
    T1.GUMCD, \
    T1.CALCULUS, \
    T1.ORTHODONTICS, \
    T1.UP_R_BABY5, \
    T1.UP_R_BABY4, \
    T1.UP_R_BABY3, \
    T1.UP_R_BABY2, \
    T1.UP_R_BABY1, \
    T1.UP_L_BABY1, \
    T1.UP_L_BABY2, \
    T1.UP_L_BABY3, \
    T1.UP_L_BABY4, \
    T1.UP_L_BABY5, \
    T1.LW_R_BABY5, \
    T1.LW_R_BABY4, \
    T1.LW_R_BABY3, \
    T1.LW_R_BABY2, \
    T1.LW_R_BABY1, \
    T1.LW_L_BABY1, \
    T1.LW_L_BABY2, \
    T1.LW_L_BABY3, \
    T1.LW_L_BABY4, \
    T1.LW_L_BABY5, \
    T1.BABYTOOTH, \
    T1.REMAINBABYTOOTH, \
    T1.TREATEDBABYTOOTH, \
    T1.BRACK_BABYTOOTH, \
    T1.UP_R_ADULT8, \
    T1.UP_R_ADULT7, \
    T1.UP_R_ADULT6, \
    T1.UP_R_ADULT5, \
    T1.UP_R_ADULT4, \
    T1.UP_R_ADULT3, \
    T1.UP_R_ADULT2, \
    T1.UP_R_ADULT1, \
    T1.UP_L_ADULT1, \
    T1.UP_L_ADULT2, \
    T1.UP_L_ADULT3, \
    T1.UP_L_ADULT4, \
    T1.UP_L_ADULT5, \
    T1.UP_L_ADULT6, \
    T1.UP_L_ADULT7, \
    T1.UP_L_ADULT8, \
    T1.LW_R_ADULT8, \
    T1.LW_R_ADULT7, \
    T1.LW_R_ADULT6, \
    T1.LW_R_ADULT5, \
    T1.LW_R_ADULT4, \
    T1.LW_R_ADULT3, \
    T1.LW_R_ADULT2, \
    T1.LW_R_ADULT1, \
    T1.LW_L_ADULT1, \
    T1.LW_L_ADULT2, \
    T1.LW_L_ADULT3, \
    T1.LW_L_ADULT4, \
    T1.LW_L_ADULT5, \
    T1.LW_L_ADULT6, \
    T1.LW_L_ADULT7, \
    T1.LW_L_ADULT8, \
    T1.ADULTTOOTH, \
    T1.REMAINADULTTOOTH, \
    T1.TREATEDADULTTOOTH, \
    T1.LOSTADULTTOOTH, \
    T1.BRACK_ADULTTOOTH, \
    T1.CHECKADULTTOOTH, \
    T1.OTHERDISEASECD, \
    T1.OTHERDISEASE, \
    L3.TOOTH_REMARK3 AS OTHERDISEASECD3, \
    L3.TOOTH_REMARK4 AS OTHERDISEASECD4, \
    L2.TOOTH_REMARK1 AS OTHERDISEASECD2, \
    L2.TOOTH_REMARK2 AS OTHERDISEASE2, \
    T1.DENTISTREMARKCD, \
    T1.DENTISTREMARK, \
    L5.TOOTH_REMARK1 AS DENTISTREMARKCD2, \
    L5.TOOTH_REMARK2 AS DENTISTREMARK2, \
    L5.TOOTH_REMARK3 AS DENTISTREMARKCD3, \
    L5.TOOTH_REMARK4 AS DENTISTREMARK3, \
    T1.DENTISTREMARKDATE, \
    T1.DENTISTREMARK_CO, \
    T1.DENTISTREMARK_GO, \
    T1.DENTISTREMARK_G, \
    T1.DENTISTTREATCD, \
    T1.DENTISTTREAT, \
    L1.TOOTH_REMARK2 AS DENTISTTREAT2, \
    L1.TOOTH_REMARK3 AS DENTISTTREAT3, \
    L5.TOOTH_REMARK5 AS DENTISTTREATCD2, \
    L5.TOOTH_REMARK6 AS DENTISTTREAT2_1, \
    L4.TOOTH_REMARK1 AS DOC_NAME, \
    T1.REGISTERCD, \
    T1.UPDATED \
FROM \
    MEDEXAM_TOOTH_DAT T1 \
    LEFT JOIN MEDEXAM_TOOTH_DETAIL_DAT L1 ON L1.YEAR      = T1.YEAR \
                                         AND L1.SCHREGNO  = T1.SCHREGNO \
                                         AND L1.TOOTH_SEQ = '001' \
    LEFT JOIN MEDEXAM_TOOTH_DETAIL_DAT L2 ON L2.YEAR      = T1.YEAR \
                                         AND L2.SCHREGNO  = T1.SCHREGNO \
                                         AND L2.TOOTH_SEQ = '002' \
    LEFT JOIN MEDEXAM_TOOTH_DETAIL_DAT L3 ON L3.YEAR      = T1.YEAR \
                                         AND L3.SCHREGNO  = T1.SCHREGNO \
                                         AND L3.TOOTH_SEQ = '003' \
    LEFT JOIN MEDEXAM_TOOTH_DETAIL_DAT L4 ON L4.YEAR      = T1.YEAR \
                                         AND L4.SCHREGNO  = T1.SCHREGNO \
                                         AND L4.TOOTH_SEQ = '004' \
    LEFT JOIN MEDEXAM_TOOTH_DETAIL_DAT L5 ON L5.YEAR      = T1.YEAR \
                                         AND L5.SCHREGNO  = T1.SCHREGNO \
                                         AND L5.TOOTH_SEQ = '005'
