-- kanji=´Á»ú
-- $Id: 6f69cb22fdd18f1674b6e0f9ad6542eb9fb8929b $

DROP VIEW V_MEDEXAM_DET_DAT

CREATE VIEW V_MEDEXAM_DET_DAT \
    (YEAR, \
     SCHREGNO, \
     HEIGHT, \
     WEIGHT, \
     SITHEIGHT, \
     CHEST, \
     NO_PRINT_OBESITY_INDEX, \
     R_BAREVISION, \
     R_BAREVISION_MARK, \
     L_BAREVISION, \
     L_BAREVISION_MARK, \
     R_VISION, \
     R_VISION_MARK, \
     R_VISION_CANTMEASURE, \
     L_VISION, \
     L_VISION_MARK, \
     L_VISION_CANTMEASURE, \
     VISION_CANTMEASURE, \
     R_EAR, \
     R_EAR_DB, \
     R_EAR_DB_4000, \
     R_EAR_CANTMEASURE, \
     R_EAR_IN, \
     R_EAR_DB_IN, \
     R_EAR_DB_4000_IN, \
     L_EAR, \
     L_EAR_DB, \
     L_EAR_DB_4000, \
     L_EAR_CANTMEASURE, \
     L_EAR_IN, \
     L_EAR_DB_IN, \
     L_EAR_DB_4000_IN, \
     ALBUMINURIA1CD, \
     URICSUGAR1CD, \
     URICBLEED1CD, \
     URICPH1, \
     ALBUMINURIA2CD, \
     URICSUGAR2CD, \
     URICBLEED2CD, \
     URICPH2, \
     URICOTHERTESTCD, \
     URICOTHERTEST, \
     URI_ADVISECD, \
     NUTRITIONCD, \
     NUTRITIONCD_REMARK, \
     SPINERIBCD, \
     SPINERIBCD_REMARK, \
     SPINERIBCD1, \
     SPINERIBCD_REMARK1, \
     SPINERIBCD2, \
     SPINERIBCD_REMARK2, \
     SPINERIBCD3, \
     SPINERIBCD_REMARK3, \
     EYEDISEASECD, \
     EYEDISEASECD2, \
     EYEDISEASECD3, \
     EYEDISEASECD4, \
     EYEDISEASECD5, \
     EYE_TEST_RESULT, \
     EYE_TEST_RESULT2, \
     EYE_TEST_RESULT3, \
     NOSEDISEASECD, \
     NOSEDISEASECD2, \
     NOSEDISEASECD3, \
     NOSEDISEASECD4, \
     NOSEDISEASECD5, \
     NOSEDISEASECD6, \
     NOSEDISEASECD7, \
     NOSEDISEASECD_REMARK, \
     NOSEDISEASECD_REMARK1, \
     NOSEDISEASECD_REMARK2, \
     NOSEDISEASECD_REMARK3, \
     SKINDISEASECD, \
     SKINDISEASECD_REMARK, \
     HEART_MEDEXAM, \
     HEART_MEDEXAM_REMARK, \
     HEARTDISEASECD, \
     HEARTDISEASECD_REMARK, \
     MANAGEMENT_DIV, \
     MANAGEMENT_REMARK, \
     TB_DATE, \
     TB_REACT, \
     TB_RESULT, \
     TB_BCGDATE, \
     TB_FILMDATE, \
     TB_FILMNO, \
     TB_REMARKCD, \
     TB_OTHERTESTCD, \
     TB_OTHERTEST_REMARK1, \
     TB_NAMECD, \
     TB_NAME_REMARK1, \
     TB_ADVISECD, \
     TB_ADVISE_REMARK1, \
     TB_X_RAY, \
     TB_RE_EXAMINATION_DATE, \
     TB_RE_EXAMINATION_RESULT, \
     TB_RE_EXAMINATION_FILMNO, \
     ANEMIA_REMARK, \
     HEMOGLOBIN, \
     PARASITE, \
     OTHERDISEASECD, \
     OTHER_ADVISECD, \
     OTHER_REMARK, \
     OTHER_REMARK2, \
     OTHER_REMARK3, \
     DOC_CD, \
     DOC_NAME, \
     DOC_REMARK, \
     DOC_DATE, \
     TREATCD, \
     TREATCD2, \
     TREAT_REMARK1, \
     TREAT_REMARK2, \
     TREAT_REMARK3, \
     TREATCD2_REMARK1, \
     REMARK, \
     NUTRITION_RESULT, \
     EYEDISEASE_RESULT, \
     SKINDISEASE_RESULT, \
     SPINERIB_RESULT, \
     NOSEDISEASE_RESULT, \
     OTHERDISEASE_RESULT, \
     HEARTDISEASE_RESULT, \
     GUIDE_DIV, \
     JOINING_SPORTS_CLUB, \
     MEDICAL_HISTORY1, \
     MEDICAL_HISTORY2, \
     MEDICAL_HISTORY3, \
     DIAGNOSIS_NAME, \
     MESSAGE, \
     R_EAR_DB_1000, \
     L_EAR_DB_1000, \
     HEART_GRAPH_NO, \
     DETAILED_EXAMINATION, \
     REGISTERCD, \
     UPDATED \
    ) \
AS SELECT \
     T1.YEAR, \
     T1.SCHREGNO, \
     T1.HEIGHT, \
     T1.WEIGHT, \
     T1.SITHEIGHT, \
     T1.CHEST, \
     L012.DET_REMARK5 AS NO_PRINT_OBESITY_INDEX, \
     T1.R_BAREVISION, \
     T1.R_BAREVISION_MARK, \
     T1.L_BAREVISION, \
     T1.L_BAREVISION_MARK, \
     T1.R_VISION, \
     T1.R_VISION_MARK, \
     L012.DET_REMARK1 AS R_VISION_CANTMEASURE, \
     T1.L_VISION, \
     T1.L_VISION_MARK, \
     L012.DET_REMARK2 AS L_VISION_CANTMEASURE, \
     L2.DET_REMARK8 AS VISION_CANTMEASURE, \
     T1.R_EAR, \
     T1.R_EAR_DB, \
     L9.DET_REMARK2 AS R_EAR_DB_4000, \
     L012.DET_REMARK3 AS R_EAR_CANTMEASURE, \
     L018.DET_REMARK1 AS R_EAR_IN, \
     L018.DET_REMARK2 AS R_EAR_DB_IN, \
     L018.DET_REMARK3 AS R_EAR_DB_4000_IN, \
     T1.L_EAR, \
     T1.L_EAR_DB, \
     L9.DET_REMARK3 AS L_EAR_DB_4000, \
     L012.DET_REMARK4 AS L_EAR_CANTMEASURE, \
     L018.DET_REMARK4 AS L_EAR_IN, \
     L018.DET_REMARK5 AS L_EAR_DB_IN, \
     L018.DET_REMARK6 AS L_EAR_DB_4000_IN, \
     T1.ALBUMINURIA1CD, \
     T1.URICSUGAR1CD, \
     T1.URICBLEED1CD, \
     L017.DET_REMARK1 AS URICPH1, \
     T1.ALBUMINURIA2CD, \
     T1.URICSUGAR2CD, \
     T1.URICBLEED2CD, \
     L017.DET_REMARK2 AS URICPH2, \
     L7.DET_REMARK1 AS URICOTHERTESTCD, \
     T1.URICOTHERTEST, \
     T1.URI_ADVISECD, \
     T1.NUTRITIONCD, \
     L9.DET_REMARK1 AS NUTRITIONCD_REMARK, \
     T1.SPINERIBCD, \
     T1.SPINERIBCD_REMARK, \
     L014.DET_REMARK1 AS SPINERIBCD1, \
     L014.DET_REMARK2 AS SPINERIBCD_REMARK1, \
     L014.DET_REMARK3 AS SPINERIBCD2, \
     L014.DET_REMARK4 AS SPINERIBCD_REMARK2, \
     L014.DET_REMARK5 AS SPINERIBCD3, \
     L014.DET_REMARK6 AS SPINERIBCD_REMARK3, \
     T1.EYEDISEASECD, \
     L2.DET_REMARK4 AS EYEDISEASECD2, \
     L2.DET_REMARK5 AS EYEDISEASECD3, \
     L2.DET_REMARK6 AS EYEDISEASECD4, \
     L2.DET_REMARK7 AS EYEDISEASECD5, \
     T1.EYE_TEST_RESULT, \
     L2.DET_REMARK2 AS EYE_TEST_RESULT2, \
     L2.DET_REMARK3 AS EYE_TEST_RESULT3, \
     T1.NOSEDISEASECD, \
     L3.DET_REMARK4  AS NOSEDISEASECD2, \
     L3.DET_REMARK5  AS NOSEDISEASECD3, \
     L3.DET_REMARK6  AS NOSEDISEASECD4, \
     L3.DET_REMARK7  AS NOSEDISEASECD5, \
     L3.DET_REMARK8  AS NOSEDISEASECD6, \
     L3.DET_REMARK9  AS NOSEDISEASECD7, \
     T1.NOSEDISEASECD_REMARK, \
     L3.DET_REMARK1 AS NOSEDISEASECD_REMARK1, \
     L3.DET_REMARK2 AS NOSEDISEASECD_REMARK2, \
     L3.DET_REMARK3 AS NOSEDISEASECD_REMARK3, \
     T1.SKINDISEASECD, \
     L6.DET_REMARK1 AS SKINDISEASECD_REMARK, \
     T1.HEART_MEDEXAM, \
     T1.HEART_MEDEXAM_REMARK, \
     T1.HEARTDISEASECD, \
     T1.HEARTDISEASECD_REMARK, \
     T1.MANAGEMENT_DIV, \
     T1.MANAGEMENT_REMARK, \
     T1.TB_DATE, \
     T1.TB_REACT, \
     T1.TB_RESULT, \
     T1.TB_BCGDATE, \
     T1.TB_FILMDATE, \
     T1.TB_FILMNO, \
     T1.TB_REMARKCD, \
     T1.TB_OTHERTESTCD, \
     L5.DET_REMARK1 AS TB_OTHERTEST_REMARK1, \
     T1.TB_NAMECD, \
     L5.DET_REMARK2 AS TB_NAME_REMARK1, \
     T1.TB_ADVISECD, \
     L5.DET_REMARK3 AS TB_ADVISE_REMARK1, \
     T1.TB_X_RAY, \
     L4.DET_REMARK4 AS TB_RE_EXAMINATION_DATE, \
     L4.DET_REMARK5 AS TB_RE_EXAMINATION_RESULT, \
     L4.DET_REMARK6 AS TB_RE_EXAMINATION_FILMNO, \
     T1.ANEMIA_REMARK, \
     T1.HEMOGLOBIN, \
     T1.PARASITE, \
     T1.OTHERDISEASECD, \
     T1.OTHER_ADVISECD, \
     T1.OTHER_REMARK, \
     L1.DET_REMARK2 AS OTHER_REMARK2, \
     L1.DET_REMARK3 AS OTHER_REMARK3, \
     T1.DOC_CD, \
     L013.DET_REMARK1 AS DOC_NAME, \
     T1.DOC_REMARK, \
     T1.DOC_DATE, \
     T1.TREATCD, \
     L011.DET_REMARK1 AS TREATCD2, \
     L4.DET_REMARK1 AS TREAT_REMARK1, \
     L4.DET_REMARK2 AS TREAT_REMARK2, \
     L4.DET_REMARK3 AS TREAT_REMARK3, \
     L013.DET_REMARK2 AS TREATCD2_REMARK1, \
     T1.REMARK, \
     T1.NUTRITION_RESULT, \
     T1.EYEDISEASE_RESULT, \
     T1.SKINDISEASE_RESULT, \
     T1.SPINERIB_RESULT, \
     T1.NOSEDISEASE_RESULT, \
     T1.OTHERDISEASE_RESULT, \
     T1.HEARTDISEASE_RESULT, \
     T1.GUIDE_DIV, \
     T1.JOINING_SPORTS_CLUB, \
     T1.MEDICAL_HISTORY1, \
     T1.MEDICAL_HISTORY2, \
     T1.MEDICAL_HISTORY3, \
     T1.DIAGNOSIS_NAME, \
     L8.DET_REMARK1 AS MESSAGE, \
     L9.DET_REMARK5 AS R_EAR_DB_1000, \
     L9.DET_REMARK6 AS L_EAR_DB_1000, \
     L9.DET_REMARK7 AS HEART_GRAPH_NO, \
     L7.DET_REMARK2 AS DETAILED_EXAMINATION, \
     T1.REGISTERCD, \
     T1.UPDATED \
FROM \
    MEDEXAM_DET_DAT T1 \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L1 ON T1.YEAR = L1.YEAR \
         AND T1.SCHREGNO = L1.SCHREGNO \
         AND L1.DET_SEQ = '001' \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L2 ON T1.YEAR = L2.YEAR \
         AND T1.SCHREGNO = L2.SCHREGNO \
         AND L2.DET_SEQ = '002' \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L3 ON T1.YEAR = L3.YEAR \
         AND T1.SCHREGNO = L3.SCHREGNO \
         AND L3.DET_SEQ = '003' \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L4 ON T1.YEAR = L4.YEAR \
         AND T1.SCHREGNO = L4.SCHREGNO \
         AND L4.DET_SEQ = '004' \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L5 ON T1.YEAR = L5.YEAR \
         AND T1.SCHREGNO = L5.SCHREGNO \
         AND L5.DET_SEQ = '005' \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L6 ON T1.YEAR = L6.YEAR \
         AND T1.SCHREGNO = L6.SCHREGNO \
         AND L6.DET_SEQ = '006' \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L7 ON T1.YEAR = L7.YEAR \
         AND T1.SCHREGNO = L7.SCHREGNO \
         AND L7.DET_SEQ = '007' \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L8 ON T1.YEAR = L8.YEAR \
         AND T1.SCHREGNO = L8.SCHREGNO \
         AND L8.DET_SEQ = '008' \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L9 ON T1.YEAR = L9.YEAR \
         AND T1.SCHREGNO = L9.SCHREGNO \
         AND L9.DET_SEQ = '009' \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L011 ON T1.YEAR = L011.YEAR \
         AND T1.SCHREGNO  = L011.SCHREGNO \
         AND L011.DET_SEQ = '011' \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L012 ON T1.YEAR = L012.YEAR \
         AND T1.SCHREGNO  = L012.SCHREGNO \
         AND L012.DET_SEQ = '012' \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L013 ON T1.YEAR = L013.YEAR \
         AND T1.SCHREGNO  = L013.SCHREGNO \
         AND L013.DET_SEQ = '013' \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L014 ON T1.YEAR = L014.YEAR \
         AND T1.SCHREGNO  = L014.SCHREGNO \
         AND L014.DET_SEQ = '014' \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L017 ON T1.YEAR = L017.YEAR \
         AND T1.SCHREGNO  = L017.SCHREGNO \
         AND L017.DET_SEQ = '017' \
    LEFT JOIN MEDEXAM_DET_DETAIL_DAT L018 ON T1.YEAR = L018.YEAR \
         AND T1.SCHREGNO  = L018.SCHREGNO \
         AND L018.DET_SEQ = '018'
