-- $Id: 1a21d863aa0692fe94be6c81536bdc324f8c09af $

DROP VIEW V_PRISCHOOL_MST

CREATE VIEW V_PRISCHOOL_MST \
  ( YEAR, \
    PRISCHOOLCD, \
    PRISCHOOL_NAME, \
    PRISCHOOL_KANA, \
    PRINCNAME, \
    PRINCNAME_SHOW, \
    PRINCKANA, \
    DISTRICTCD, \
    PRISCHOOL_ZIPCD, \
    PRISCHOOL_ADDR1, \
    PRISCHOOL_ADDR2, \
    PRISCHOOL_TELNO, \
    PRISCHOOL_FAXNO, \
    GRP_PRISCHOOLCD, \
    UPDATED ) \
AS SELECT \
    T1.YEAR, \
    T2.PRISCHOOLCD, \
    T2.PRISCHOOL_NAME, \
    T2.PRISCHOOL_KANA, \
    T2.PRINCNAME, \
    T2.PRINCNAME_SHOW, \
    T2.PRINCKANA, \
    T2.DISTRICTCD, \
    T2.PRISCHOOL_ZIPCD, \
    T2.PRISCHOOL_ADDR1, \
    T2.PRISCHOOL_ADDR2, \
    T2.PRISCHOOL_TELNO, \
    T2.PRISCHOOL_FAXNO, \
    T2.GRP_PRISCHOOLCD, \
    T2.UPDATED \
FROM     PRISCHOOL_YDAT T1, \
    PRISCHOOL_MST T2 \
WHERE    T1.PRISCHOOLCD = T2.PRISCHOOLCD

