-- kanji=漢字
-- $Id: 4404d419abedc008c21bfd34da1c6281b937a685 $

-- 注意:このファイルは EUC/LFのみ でなければならない。
-- 適用方法:
--    1.データベース接続
--    2.db2 +c -f <このファイル>
--    3.コミットするなら、db2 +c commit。やり直すなら、db2 +c rollback
--

DROP VIEW V_RECORD_SCORE_DAT

CREATE VIEW V_RECORD_SCORE_DAT \
    (YEAR, \
     CLASSCD, \
     SCHOOL_KIND, \
     CURRICULUM_CD, \
     SUBCLASSCD, \
     TAKESEMES, \
     SCHREGNO, \
     CHAIRCD, \
     SEM1_INTR_CHAIRCD, \
     SEM1_TERM_CHAIRCD, \
     SEM1_TERM2_CHAIRCD, \
     SEM2_INTR_CHAIRCD, \
     SEM2_TERM_CHAIRCD, \
     SEM2_TERM2_CHAIRCD, \
     SEM3_INTR_CHAIRCD, \
     SEM3_TERM_CHAIRCD, \
     SEM1_INTR_SCORE, \
     SEM1_TERM_SCORE, \
     SEM1_TERM2_SCORE, \
     SEM2_INTR_SCORE, \
     SEM2_TERM_SCORE, \
     SEM2_TERM2_SCORE, \
     SEM3_INTR_SCORE, \
     SEM3_TERM_SCORE, \
     SEM1_INTR_SCORE2, \
     SEM1_TERM_SCORE2, \
     SEM2_INTR_SCORE2, \
     SEM2_TERM_SCORE2, \
     SEM1_INTR_SCORE3, \
     SEM1_TERM_SCORE3, \
     SEM2_INTR_SCORE3, \
     SEM2_TERM_SCORE3, \
     SEM1_SCORE, \
     SEM2_SCORE, \
     GRAD_SCORE, \
     SEM1_INTR_VALUE, \
     SEM1_TERM_VALUE, \
     SEM1_TERM2_VALUE, \
     SEM1_VALUE, \
     SEM2_INTR_VALUE, \
     SEM2_TERM_VALUE, \
     SEM2_TERM2_VALUE, \
     SEM2_VALUE, \
     SEM3_INTR_VALUE, \
     SEM3_TERM_VALUE, \
     SEM3_VALUE, \
     GRAD_VALUE, \
     GRAD_VALUE2, \
     GET_CREDIT, \
     ADD_CREDIT, \
     COMP_TAKESEMES, \
     COMP_CREDIT, \
     SEM1_INTR_SCORE_DI, \
     SEM1_TERM_SCORE_DI, \
     SEM2_INTR_SCORE_DI, \
     SEM2_TERM_SCORE_DI, \
     SEM3_INTR_SCORE_DI, \
     SEM3_TERM_SCORE_DI, \
     SEM1_INTR_VALUE_DI, \
     SEM1_TERM_VALUE_DI, \
     SEM1_TERM2_VALUE_DI, \
     SEM1_VALUE_DI, \
     SEM2_INTR_VALUE_DI, \
     SEM2_TERM_VALUE_DI, \
     SEM2_TERM2_VALUE_DI, \
     SEM2_VALUE_DI, \
     SEM3_INTR_VALUE_DI, \
     SEM3_TERM_VALUE_DI, \
     SEM3_VALUE_DI, \
     GRAD_VALUE_DI) \
AS SELECT \
       YEAR \
      ,CLASSCD \
      ,SCHOOL_KIND \
      ,CURRICULUM_CD \
      ,SUBCLASSCD \
      ,'0' as TAKESEMES \
      ,SCHREGNO \
      ,cast(null as varchar(7)) as CHAIRCD \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1010101' THEN CHAIRCD END) as SEM1_INTR_CHAIRCD \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1020101' THEN CHAIRCD END) as SEM1_TERM_CHAIRCD \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1020201' THEN CHAIRCD END) as SEM1_TERM2_CHAIRCD \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2010101' THEN CHAIRCD END) as SEM2_INTR_CHAIRCD \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2020101' THEN CHAIRCD END) as SEM2_TERM_CHAIRCD \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2020201' THEN CHAIRCD END) as SEM2_TERM2_CHAIRCD \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '3010101' THEN CHAIRCD END) as SEM3_INTR_CHAIRCD \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '3020101' THEN CHAIRCD END) as SEM3_TERM_CHAIRCD \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1010101' THEN SCORE END) as SEM1_INTR_SCORE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1020101' THEN SCORE END) as SEM1_TERM_SCORE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1020201' THEN SCORE END) as SEM1_TERM2_SCORE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2010101' THEN SCORE END) as SEM2_INTR_SCORE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2020101' THEN SCORE END) as SEM2_TERM_SCORE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2020201' THEN SCORE END) as SEM2_TERM2_SCORE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '3010101' THEN SCORE END) as SEM3_INTR_SCORE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '3020101' THEN SCORE END) as SEM3_TERM_SCORE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1010102' THEN SCORE END) as SEM1_INTR_SCORE2 \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1020102' THEN SCORE END) as SEM1_TERM_SCORE2 \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2010102' THEN SCORE END) as SEM2_INTR_SCORE2 \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2020102' THEN SCORE END) as SEM2_TERM_SCORE2 \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1010103' THEN SCORE END) as SEM1_INTR_SCORE3 \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1020103' THEN SCORE END) as SEM1_TERM_SCORE3 \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2010103' THEN SCORE END) as SEM2_INTR_SCORE3 \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2020103' THEN SCORE END) as SEM2_TERM_SCORE3 \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1990000' THEN SCORE END) as SEM1_SCORE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2990000' THEN SCORE END) as SEM2_SCORE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '9990000' THEN SCORE END) as GRAD_SCORE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1010101' THEN VALUE END) as SEM1_INTR_VALUE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1020101' THEN VALUE END) as SEM1_TERM_VALUE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1020201' THEN VALUE END) as SEM1_TERM2_VALUE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1990000' THEN VALUE END) as SEM1_VALUE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2010101' THEN VALUE END) as SEM2_INTR_VALUE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2020101' THEN VALUE END) as SEM2_TERM_VALUE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2020201' THEN VALUE END) as SEM2_TERM2_VALUE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2990000' THEN VALUE END) as SEM2_VALUE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '3010101' THEN VALUE END) as SEM3_INTR_VALUE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '3020101' THEN VALUE END) as SEM3_TERM_VALUE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '3990000' THEN VALUE END) as SEM3_VALUE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '9990000' THEN VALUE END) as GRAD_VALUE \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '9990100' THEN VALUE END) as GRAD_VALUE2 \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '9990000' THEN GET_CREDIT END) as GET_CREDIT \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '9990000' THEN ADD_CREDIT END) as ADD_CREDIT \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '9990000' THEN COMP_TAKESEMES END) as COMP_TAKESEMES \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '9990000' THEN COMP_CREDIT END) as COMP_CREDIT \
      ,cast(null as varchar(2)) as SEM1_INTR_SCORE_DI \
      ,cast(null as varchar(2)) as SEM1_TERM_SCORE_DI \
      ,cast(null as varchar(2)) as SEM2_INTR_SCORE_DI \
      ,cast(null as varchar(2)) as SEM2_TERM_SCORE_DI \
      ,cast(null as varchar(2)) as SEM3_INTR_SCORE_DI \
      ,cast(null as varchar(2)) as SEM3_TERM_SCORE_DI \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1010101' THEN VALUE_DI END) as SEM1_INTR_VALUE_DI \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1020101' THEN VALUE_DI END) as SEM1_TERM_VALUE_DI \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1020201' THEN VALUE_DI END) as SEM1_TERM2_VALUE_DI \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '1990000' THEN VALUE_DI END) as SEM1_VALUE_DI \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2010101' THEN VALUE_DI END) as SEM2_INTR_VALUE_DI \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2020101' THEN VALUE_DI END) as SEM2_TERM_VALUE_DI \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2020201' THEN VALUE_DI END) as SEM2_TERM2_VALUE_DI \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '2990000' THEN VALUE_DI END) as SEM2_VALUE_DI \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '3010101' THEN VALUE_DI END) as SEM3_INTR_VALUE_DI \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '3020101' THEN VALUE_DI END) as SEM3_TERM_VALUE_DI \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '3990000' THEN VALUE_DI END) as SEM3_VALUE_DI \
      ,min(CASE WHEN SEMESTER||TESTKINDCD||TESTITEMCD||SCORE_DIV = '9990000' THEN VALUE_DI END) as GRAD_VALUE_DI \
FROM   RECORD_SCORE_DAT \
GROUP BY YEAR,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO
