
DROP VIEW V_RECORD_RANK_SDIV_DAT
CREATE VIEW V_RECORD_RANK_SDIV_DAT \
    ( \
       YEAR, \
       SEMESTER, \
       TESTKINDCD, \
       TESTITEMCD, \
       SCORE_DIV, \
       CLASSCD, \
       SCHOOL_KIND, \
       CURRICULUM_CD, \
       SUBCLASSCD, \
       SCHREGNO, \
       COURSE_GROUP_CL_RANK, \
       COURSE_GROUP_CL_AVG_RANK, \
       COURSE_GROUP_CL_DEVIATION, \
       COURSE_GROUP_CL_DEVIATION_RANK, \
       HRCLASS_COURSE_RANK, \
       HRCLASS_COURSE_AVG_RANK, \
       HRCLASS_COURSE_DEVIATION, \
       HRCLASS_COURSE_DEVIATION_RANK, \
       HRCLASS_COURSE_ENT_OUT_RANK, \
       HRCLASS_COURSE_ENT_OUT_AVG_RANK, \
       HRCLASS_COURSE_ENT_OUT_DEVIATION, \
       HRCLASS_COURSE_ENT_OUT_DEVIATION_RANK, \
       HRCLASS_COURSE_ENT_IN_RANK, \
       HRCLASS_COURSE_ENT_IN_AVG_RANK, \
       HRCLASS_COURSE_ENT_IN_DEVIATION, \
       HRCLASS_COURSE_ENT_IN_DEVIATION_RANK, \
       GRADE_COURSE_ENT_OUT_RANK, \
       GRADE_COURSE_ENT_OUT_AVG_RANK, \
       GRADE_COURSE_ENT_OUT_DEVIATION, \
       GRADE_COURSE_ENT_OUT_DEVIATION_RANK, \
       GRADE_COURSE_ENT_IN_RANK, \
       GRADE_COURSE_ENT_IN_AVG_RANK, \
       GRADE_COURSE_ENT_IN_DEVIATION, \
       GRADE_COURSE_ENT_IN_DEVIATION_RANK \
    ) AS \
SELECT \
   T1.YEAR, \
   T1.SEMESTER, \
   T1.TESTKINDCD, \
   T1.TESTITEMCD, \
   T1.SCORE_DIV, \
   T1.CLASSCD, \
   T1.SCHOOL_KIND, \
   T1.CURRICULUM_CD, \
   T1.SUBCLASSCD, \
   T1.SCHREGNO, \
   SUM(CASE T2.RANK_DIV WHEN 'A' THEN T2.RANK ELSE NULL END)           AS COURSE_GROUP_CL_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'A' THEN T2.AVG_RANK ELSE NULL END)       AS COURSE_GROUP_CL_AVG_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'A' THEN T2.DEVIATION ELSE NULL END)      AS COURSE_GROUP_CL_DEVIATION, \
   SUM(CASE T2.RANK_DIV WHEN 'A' THEN T2.DEVIATION_RANK ELSE NULL END) AS COURSE_GROUP_CL_DEVIATION_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'B' THEN T2.RANK ELSE NULL END)           AS HRCLASS_COURSE_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'B' THEN T2.AVG_RANK ELSE NULL END)       AS HRCLASS_COURSE_AVG_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'B' THEN T2.DEVIATION ELSE NULL END)      AS HRCLASS_COURSE_DEVIATION, \
   SUM(CASE T2.RANK_DIV WHEN 'B' THEN T2.DEVIATION_RANK ELSE NULL END) AS HRCLASS_COURSE_DEVIATION_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'C' THEN T2.RANK ELSE NULL END)           AS HRCLASS_COURSE_ENT_OUT_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'C' THEN T2.AVG_RANK ELSE NULL END)       AS HRCLASS_COURSE_ENT_OUT_AVG_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'C' THEN T2.DEVIATION ELSE NULL END)      AS HRCLASS_COURSE_ENT_OUT_DEVIATION, \
   SUM(CASE T2.RANK_DIV WHEN 'C' THEN T2.DEVIATION_RANK ELSE NULL END) AS HRCLASS_COURSE_ENT_OUT_DEVIATION_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'D' THEN T2.RANK ELSE NULL END)           AS HRCLASS_COURSE_ENT_IN_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'D' THEN T2.AVG_RANK ELSE NULL END)       AS HRCLASS_COURSE_ENT_IN_AVG_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'D' THEN T2.DEVIATION ELSE NULL END)      AS HRCLASS_COURSE_ENT_IN_DEVIATION, \
   SUM(CASE T2.RANK_DIV WHEN 'D' THEN T2.DEVIATION_RANK ELSE NULL END) AS HRCLASS_COURSE_ENT_IN_DEVIATION_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'E' THEN T2.RANK ELSE NULL END)           AS GRADE_COURSE_ENT_OUT_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'E' THEN T2.AVG_RANK ELSE NULL END)       AS GRADE_COURSE_ENT_OUT_AVG_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'E' THEN T2.DEVIATION ELSE NULL END)      AS GRADE_COURSE_ENT_OUT_DEVIATION, \
   SUM(CASE T2.RANK_DIV WHEN 'E' THEN T2.DEVIATION_RANK ELSE NULL END) AS GRADE_COURSE_ENT_OUT_DEVIATION_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'F' THEN T2.RANK ELSE NULL END)           AS GRADE_COURSE_ENT_IN_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'F' THEN T2.AVG_RANK ELSE NULL END)       AS GRADE_COURSE_ENT_IN_AVG_RANK, \
   SUM(CASE T2.RANK_DIV WHEN 'F' THEN T2.DEVIATION ELSE NULL END)      AS GRADE_COURSE_ENT_IN_DEVIATION, \
   SUM(CASE T2.RANK_DIV WHEN 'F' THEN T2.DEVIATION_RANK ELSE NULL END) AS GRADE_COURSE_ENT_IN_DEVIATION_RANK \
FROM \
  RECORD_RANK_SDIV_DAT T1 \
  LEFT JOIN RECORD_RANK_DETAIL_SDIV_DAT T2 \
    ON T2.YEAR = T1.YEAR \
    AND T2.SEMESTER = T1.SEMESTER \
    AND T2.TESTKINDCD = T1.TESTKINDCD \
    AND T2.TESTITEMCD = T1.TESTITEMCD \
    AND T2.SCORE_DIV = T1.SCORE_DIV \
    AND T2.CLASSCD = T1.CLASSCD \
    AND T2.SCHOOL_KIND = T1.SCHOOL_KIND \
    AND T2.CURRICULUM_CD = T1.CURRICULUM_CD \
    AND T2.SUBCLASSCD = T1.SUBCLASSCD \
    AND T2.SCHREGNO = T1.SCHREGNO \
GROUP BY \
  T1.YEAR, \
  T1.SEMESTER, \
  T1.TESTKINDCD, \
  T1.TESTITEMCD, \
  T1.SCORE_DIV, \
  T1.CLASSCD, \
  T1.SCHOOL_KIND, \
  T1.CURRICULUM_CD, \
  T1.SUBCLASSCD, \
  T1.SCHREGNO
