-- $Id: 780330f79f803f3f8b90e732c06ebe020fba7121 $

DROP VIEW V_SCHOOL_GCM_MST

CREATE VIEW V_SCHOOL_GCM_MST \
   (YEAR, \
    SCHOOLCD, \
    SCHOOL_KIND, \
    GRADE, \
    COURSECD, \
    MAJORCD, \
    FOUNDEDYEAR, \
    PRESENT_EST, \
    CLASSIFICATION, \
    SCHOOLNAME1, \
    SCHOOLNAME2, \
    SCHOOLNAME3, \
    SCHOOLNAME_ENG, \
    SCHOOLZIPCD, \
    SCHOOLADDR1, \
    SCHOOLADDR2, \
    SCHOOLADDR1_ENG, \
    SCHOOLADDR2_ENG, \
    SCHOOLTELNO, \
    SCHOOLFAXNO, \
    SCHOOLMAIL, \
    SCHOOLURL, \
    SCHOOLDIV, \
    SEMESTERDIV, \
    GRADE_HVAL, \
    ENTRANCE_DATE, \
    GRADUATE_DATE, \
    GRAD_CREDITS, \
    GRAD_COMP_CREDITS, \
    SEMES_ASSESSCD, \
    SEMES_FEARVAL, \
    GRADE_FEARVAL, \
    ABSENT_COV, \
    ABSENT_COV_LATE, \
    GVAL_CALC, \
    SUB_OFFDAYS, \
    SUB_ABSENT, \
    SUB_SUSPEND, \
    SUB_MOURNING, \
    SUB_VIRUS, \
    SEM_OFFDAYS, \
    JUGYOU_JISU_FLG, \
    RISYU_BUNSI, \
    RISYU_BUNBO, \
    SYUTOKU_BUNSI, \
    SYUTOKU_BUNBO, \
    RISYU_BUNSI_SPECIAL, \
    RISYU_BUNBO_SPECIAL, \
    SYUTOKU_BUNSI_SPECIAL, \
    SYUTOKU_BUNBO_SPECIAL, \
    JITU_JIFUN, \
    JITU_JIFUN_SPECIAL, \
    JITU_SYUSU, \
    JOUGENTI_SANSYUTU_HOU, \
    AMARI_KURIAGE, \
    KESSEKI_WARN_BUNSI, \
    KESSEKI_WARN_BUNBO, \
    KESSEKI_OUT_BUNSI, \
    KESSEKI_OUT_BUNBO, \
    TOKUBETU_KATUDO_KANSAN, \
    SYUKESSEKI_HANTEI_HOU, \
    SUB_KOUDOME, \
    PREF_CD, \
    KYOUIKU_IINKAI_SCHOOLCD, \
    HOUTEI_SYUSU_SEMESTER1, \
    HOUTEI_SYUSU_SEMESTER2, \
    HOUTEI_SYUSU_SEMESTER3, \
    HOUTEI_SYUSU_SEMESTER4, \
    HOUTEI_SYUSU_SEMESTER5, \
    HOUTEI_SYUSU_SEMESTER6, \
    HOUTEI_SYUSU_SEMESTER7, \
    HOUTEI_SYUSU_SEMESTER8, \
    HOUTEI_SYUSU_SEMESTER9, \
    HOUTEI_SYUSU_SEMESTER10, \
    PARTS_HYOUKA_HYOUTEI_KEISAN) \
AS \
SELECT \
    T1.YEAR, \
    T1.SCHOOLCD, \
    T1.SCHOOL_KIND, \
    '00' AS GRADE, \
    CM_M.COURSECD, \
    CM_M.MAJORCD, \
    T1.FOUNDEDYEAR, \
    T1.PRESENT_EST, \
    T1.CLASSIFICATION, \
    T1.SCHOOLNAME1, \
    T1.SCHOOLNAME2, \
    T1.SCHOOLNAME3, \
    T1.SCHOOLNAME_ENG, \
    T1.SCHOOLZIPCD, \
    T1.SCHOOLADDR1, \
    T1.SCHOOLADDR2, \
    T1.SCHOOLADDR1_ENG, \
    T1.SCHOOLADDR2_ENG, \
    T1.SCHOOLTELNO, \
    T1.SCHOOLFAXNO, \
    T1.SCHOOLMAIL, \
    T1.SCHOOLURL, \
    T1.SCHOOLDIV, \
    T1.SEMESTERDIV, \
    T1.GRADE_HVAL, \
    T1.ENTRANCE_DATE, \
    T1.GRADUATE_DATE, \
    T1.GRAD_CREDITS, \
    T1.GRAD_COMP_CREDITS, \
    T1.SEMES_ASSESSCD, \
    T1.SEMES_FEARVAL, \
    T1.GRADE_FEARVAL, \
    T1.ABSENT_COV, \
    T1.ABSENT_COV_LATE, \
    T1.GVAL_CALC, \
    T1.SUB_OFFDAYS, \
    T1.SUB_ABSENT, \
    T1.SUB_SUSPEND, \
    T1.SUB_MOURNING, \
    T1.SUB_VIRUS, \
    T1.SEM_OFFDAYS, \
    L1.REMARK1, \
    L1.REMARK2, \
    L1.REMARK3, \
    L1.REMARK4, \
    L1.REMARK5, \
    L3.REMARK2, \
    L3.REMARK3, \
    L3.REMARK4, \
    L3.REMARK5, \
    L1.REMARK6, \
    L3.REMARK7, \
    L1.REMARK7, \
    L1.REMARK8, \
    VALUE(L1.REMARK9, '99'), \
    L4.REMARK2, \
    L4.REMARK3, \
    L4.REMARK4, \
    L4.REMARK5, \
    L3.REMARK6, \
    L5.REMARK1, \
    L5.REMARK2, \
    L2.REMARK1, \
    L2.REMARK3, \
    L6.REMARK1, \
    L6.REMARK2, \
    L6.REMARK3, \
    L6.REMARK4, \
    L6.REMARK5, \
    L6.REMARK6, \
    L6.REMARK7, \
    L6.REMARK8, \
    L6.REMARK9, \
    L6.REMARK10, \
    L7.REMARK1 \
FROM \
    SCHOOL_MST T1 \
    INNER JOIN V_COURSE_MAJOR_MST CM_M ON T1.YEAR = CM_M.YEAR \
    LEFT JOIN SCHOOL_DETAIL_GCM_DAT L1 ON CM_M.YEAR = L1.YEAR \
         AND CM_M.COURSECD = L1.COURSECD \
         AND CM_M.MAJORCD = L1.MAJORCD \
         AND L1.SEQ = '001' \
    LEFT JOIN SCHOOL_DETAIL_GCM_DAT L2 ON CM_M.YEAR = L2.YEAR \
         AND CM_M.COURSECD = L2.COURSECD \
         AND CM_M.MAJORCD = L2.MAJORCD \
         AND L2.SEQ = '002' \
    LEFT JOIN SCHOOL_DETAIL_GCM_DAT L3 ON CM_M.YEAR = L3.YEAR \
         AND CM_M.COURSECD = L3.COURSECD \
         AND CM_M.MAJORCD = L3.MAJORCD \
         AND L3.SEQ = '003' \
    LEFT JOIN SCHOOL_DETAIL_GCM_DAT L4 ON CM_M.YEAR = L4.YEAR \
         AND CM_M.COURSECD = L4.COURSECD \
         AND CM_M.MAJORCD = L4.MAJORCD \
         AND L4.SEQ = '004' \
    LEFT JOIN SCHOOL_DETAIL_GCM_DAT L5 ON CM_M.YEAR = L5.YEAR \
         AND CM_M.COURSECD = L5.COURSECD \
         AND CM_M.MAJORCD = L5.MAJORCD \
         AND L5.SEQ = '005' \
    LEFT JOIN SCHOOL_DETAIL_GCM_DAT L6 ON CM_M.YEAR = L6.YEAR \
         AND CM_M.COURSECD = L6.COURSECD \
         AND CM_M.MAJORCD = L6.MAJORCD \
         AND L6.SEQ = '006' \
    LEFT JOIN SCHOOL_DETAIL_GCM_DAT L7 ON CM_M.YEAR = L7.YEAR \
         AND CM_M.COURSECD = L7.COURSECD \
         AND CM_M.MAJORCD = L7.MAJORCD \
         AND L7.SEQ = '007'
