-- kanji=Š¿Žš
-- $Id: 7569e7f6ec9172845a0ff8e919343e8d5301d95f $

DROP VIEW V_SEMESTER_GRADE_MST

CREATE VIEW V_SEMESTER_GRADE_MST \
    (YEAR, \
     SEMESTER, \
     GRADE, \
     SEMESTERNAME, \
     SDATE, \
     EDATE, \
     REGISTERCD, \
     UPDATED \
    ) \
AS SELECT \
     GDAT.YEAR, \
     SEME.SEMESTER, \
     GDAT.GRADE, \
     CASE WHEN SEMEG.SEMESTERNAME IS NOT NULL THEN SEMEG.SEMESTERNAME ELSE SEME.SEMESTERNAME END AS SEMESTERNAME, \
     CASE WHEN SEMEG.SDATE IS NOT NULL THEN SEMEG.SDATE ELSE SEME.SDATE END AS SDATE, \
     CASE WHEN SEMEG.EDATE IS NOT NULL THEN SEMEG.EDATE ELSE SEME.EDATE END AS EDATE, \
     GDAT.REGISTERCD, \
     GDAT.UPDATED \
FROM \
    SCHREG_REGD_GDAT GDAT \
    LEFT JOIN SEMESTER_MST SEME ON GDAT.YEAR = SEME.YEAR \
    LEFT JOIN SEMESTER_GRADE_MST SEMEG ON SEME.YEAR = SEMEG.YEAR \
         AND SEME.SEMESTER = SEMEG.SEMESTER \
         AND GDAT.GRADE = SEMEG.GRADE
