-- kanji=´Á»ú
-- $Id: collect_l_mst.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE COLLECT_L_MST

CREATE TABLE COLLECT_L_MST ( \
        "COLLECT_L_CD"    VARCHAR(2) NOT NULL, \
        "COLLECT_L_NAME"  VARCHAR(90), \
        "COLLECT_L_ABBV"  VARCHAR(90), \
        "LEVY_FLG"        VARCHAR(1), \
        "REGISTERCD"      VARCHAR(10), \
        "UPDATED"         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COLLECT_L_MST ADD CONSTRAINT PK_COLLECT_L_MST PRIMARY KEY (COLLECT_L_CD)
