-- $Id: menu_mst.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE MENU_MST
CREATE TABLE MENU_MST( \
    MENUID	        VARCHAR(11) NOT NULL, \
    SUBMENUID   	VARCHAR(1), \
    PARENTMENUID	VARCHAR(11), \
    MENUNAME	    VARCHAR(120), \
    PROGRAMID	    VARCHAR(20), \
    PROGRAMPATH	    VARCHAR(40), \
    PROCESSCD	    VARCHAR(1), \
    INVALID_FLG	    VARCHAR(1), \
    PROGRAMMEMO	    VARCHAR(3000), \
    SHOWORDER	    SMALLINT, \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE MENU_MST ADD CONSTRAINT PK_MENU_MST PRIMARY KEY (MENUID)
