-- kanji=漢字
-- $Id: cov-entexam_testdiv_mst.sql 56577 2017-10-22 11:35:50Z maeshiro $

DELETE FROM ENTEXAM_TESTDIV_MST

INSERT INTO ENTEXAM_TESTDIV_MST \
SELECT \
    T2.YEAR AS ENTEXAMYEAR, \
    T1.NAMECD2 AS TESTDIV, \
    T1.NAME1 AS NAME, \
    T1.ABBV1 AS ABBV, \
    T1.NAMESPARE3 AS CLASSDIV, \
    T1.NAMESPARE2 AS SHOWDIV, \
    SMALLINT(T1.ABBV2) AS CAPACITY, \
    REPLACE(T1.NAMESPARE1,'/','-') AS TESTDAY, \
    SMALLINT(T1.NAMECD2) AS SHOWORDER, \
    T1.REGISTERCD AS REGISTERCD, \
    T1.UPDATED AS UPDATED \
FROM \
    NAME_MST T1, \
    NAME_YDAT T2 \
WHERE \
    T1.NAMECD1='L004' \
    AND T2.NAMECD1=T1.NAMECD1 \
    AND T2.NAMECD2=T1.NAMECD2
