-- $Id: v_staff_mst.sql 56577 2017-10-22 11:35:50Z maeshiro $

drop view V_STAFF_MST

create view V_STAFF_MST \
    as  select \
            T1.YEAR, T2.STAFFCD, T2.STAFFNAME, T2.STAFFNAME_SHOW, T2.STAFFNAME_KANA, \
            T2.STAFFNAME_ENG, T2.BELONGING_DIV, T2.JOBCD, T2.SECTIONCD, T2.DUTYSHARECD, T2.CHARGECLASSCD, \
            T2.STAFFSEX, T2.STAFFBIRTHDAY, T2.STAFFZIPCD, T2.STAFFPREF_CD, T2.STAFFADDR1, T2.STAFFADDR2, T2.STAFFADDR3, \
            T2.STAFFTELNO, T2.STAFFTELNO_SEARCH, T2.STAFFFAXNO, T2.STAFFE_MAIL, T2.UPDATED \
        from \
            STAFF_YDAT T1, \
            STAFF_MST T2 \
        where T1.STAFFCD = T2.STAFFCD
