-- $Id: v_textbook_mst.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP VIEW V_TEXTBOOK_MST

CREATE VIEW V_TEXTBOOK_MST \
AS SELECT \
    T1.YEAR, \
    T2.TEXTBOOKCD, \
    T2.TEXT_GROUP_CD, \
    T2.TEXTBOOKDIV, \
    T2.TEXTBOOKNAME, \
    T2.TEXTBOOKABBV, \
    T2.TEXTBOOKMK, \
    T2.TEXTBOOKMS, \
    T2.TEXTBOOKWRITINGNAME, \
    T2.TEXTBOOKPRICE, \
    T2.TEXTBOOKUNITPRICE, \
    T2.TEXTBOOKAMOUNT, \
    T2.ISSUECOMPANYCD, \
    T2.ORDER_CD, \
    T2.REMARK, \
    T2.UPDATED \
FROM     TEXTBOOK_YDAT T1, \
    TEXTBOOK_MST T2 \
WHERE    T1.TEXTBOOKCD = T2.TEXTBOOKCD

