-- $Id: rep-kojin_rishi_furikomi_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE KOJIN_RISHI_FURIKOMI_DAT_OLD
RENAME TABLE KOJIN_RISHI_FURIKOMI_DAT TO KOJIN_RISHI_FURIKOMI_DAT_OLD
CREATE TABLE KOJIN_RISHI_FURIKOMI_DAT( \
    SHUUGAKU_NO             VARCHAR(7)    NOT NULL, \
    SHINSEI_YEAR            VARCHAR(4)    NOT NULL, \
    KOUFU_SEQ               VARCHAR(2)    NOT NULL, \
    SHIKIN_SHUBETSU         VARCHAR(1)    NOT NULL, \
    KOJIN_NO                VARCHAR(7)    NOT NULL, \
    FURIKOMI_DATE           DATE          NOT NULL, \
    FURIKOMI_GK             INT, \
    REGISTERCD              VARCHAR(8), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO KOJIN_RISHI_FURIKOMI_DAT \
    SELECT \
        SHUUGAKU_NO, \
        SHINSEI_YEAR, \
        right(rtrim('0'|| KOUFU_SEQ),2) AS KOUFU_SEQ, \
        SHIKIN_SHUBETSU, \
        KOJIN_NO, \
        FURIKOMI_DATE, \
        FURIKOMI_GK, \
        REGISTERCD, \
        UPDATED \
    FROM \
        KOJIN_RISHI_FURIKOMI_DAT_OLD

ALTER TABLE KOJIN_RISHI_FURIKOMI_DAT ADD CONSTRAINT PK_K_RISHI_FU_DAT PRIMARY KEY (SHUUGAKU_NO, SHINSEI_YEAR, KOUFU_SEQ)