-- $Id: rep-rishi_torikomi_wkdat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE RISHI_TORIKOMI_WKDAT_OLD
RENAME TABLE RISHI_TORIKOMI_WKDAT TO RISHI_TORIKOMI_WKDAT_OLD
CREATE TABLE RISHI_TORIKOMI_WKDAT( \
    SEQ                     INT         NOT NULL, \
    DIV                     VARCHAR(1), \
    DATA                    VARCHAR(711), \
    REGISTERCD              VARCHAR(8), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO RISHI_TORIKOMI_WKDAT \
    SELECT \
        SEQ        , \
        DIV       , \
        DATA      , \
        REGISTERCD, \
        UPDATED \
    FROM \
        RISHI_TORIKOMI_WKDAT_OLD

ALTER TABLE RISHI_TORIKOMI_WKDAT ADD CONSTRAINT PK_RISHI_T_WKDAT PRIMARY KEY (SEQ)
