-- kanji=漢字
-- $Id$

DROP TABLE ENTEXAM_MIRAI_MAPPING_MST

CREATE TABLE ENTEXAM_MIRAI_MAPPING_MST \
( \
    ENTEXAMYEAR         VARCHAR(4)    NOT NULL, \
    APPLICANTDIV        VARCHAR(1)    NOT NULL, \
    TESTDIV             VARCHAR(2)    NOT NULL, \
    MAPPING_NO          VARCHAR(2)    NOT NULL, \
    TESTDIV_NAME        VARCHAR(120)          , \
    REMARK1             VARCHAR(150)          , \
    REMARK2             VARCHAR(150)          , \
    REMARK3             VARCHAR(150)          , \
    REGISTERCD          VARCHAR(10)           , \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_MIRAI_MAPPING_MST ADD CONSTRAINT PK_ENTEXAM_MIRAI_MAPPING_M PRIMARY KEY (ENTEXAMYEAR, APPLICANTDIV, TESTDIV, MAPPING_NO)
