-- kanji=漢字
-- $Id: 80229fc7698a99d5835e96136386aee188f8c13e $

DROP TABLE ENTEXAM_TRANSFER_FORMS_WK_MST

CREATE TABLE ENTEXAM_TRANSFER_FORMS_WK_MST \
( \
    ENTEXAMYEAR                 VARCHAR(4)  NOT NULL, \
    APPLICANTDIV                VARCHAR(1)  NOT NULL, \
    PATTERN_CD                  VARCHAR(3)  NOT NULL, \
    TOKUTAI_SELECT              VARCHAR(1)  NOT NULL, \
    PATTERN_NAME                VARCHAR(30), \
    PREF_NAME                   VARCHAR(12), \
    ACCOUNT_NUMBER1             VARCHAR(5), \
    ACCOUNT_NUMBER2             VARCHAR(1), \
    ACCOUNT_NUMBER3             VARCHAR(7), \
    MEMBER                      VARCHAR(30), \
    SUBJECT                     VARCHAR(24), \
    COMMUNICATION               VARCHAR(360), \
    TRANSFER_MONEY              INTEGER, \
    REGISTERCD                  VARCHAR(10), \
    UPDATED                     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_TRANSFER_FORMS_WK_MST ADD CONSTRAINT PK_ENTEXAM_TRANSFER_FORMS_WK_MST PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,PATTERN_CD,TOKUTAI_SELECT)
