-- $Id: 2dc595db4b3e2bd507d583263d641184cf2a052c $

DROP TABLE ENTEXAM_HALL_YDAT
CREATE TABLE ENTEXAM_HALL_YDAT( \
    ENTEXAMYEAR   VARCHAR(4)    NOT NULL, \
    APPLICANTDIV  VARCHAR(1)    NOT NULL, \
    TESTDIV       VARCHAR(1)    NOT NULL, \
    EXAM_TYPE     VARCHAR(1)    NOT NULL, \
    EXAMHALLCD    VARCHAR(4)    NOT NULL, \
    EXAMHALL_NAME VARCHAR(30), \
    CAPA_CNT      SMALLINT, \
    S_RECEPTNO    VARCHAR(5), \
    E_RECEPTNO    VARCHAR(5), \
    REGISTERCD    VARCHAR(10), \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_HALL_YDAT ADD CONSTRAINT PK_ENTEXAM_HAL_Y PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,EXAM_TYPE,EXAMHALLCD)