-- $Id: a43e80bd25862c24d083d4f88a3e415fa3f2fee2 $

drop view V_AFT_SINRO_ADDITION_L350W_DAT

create view V_AFT_SINRO_ADDITION_L350W_DAT \
   (EDBOARD_SCHOOLCD, \
    YEAR, \
    APPLICANTDIV, \
    TESTDIV, \
    RUIKEI_DIV, \
    TESTDIV2, \
    COURSECD, \
    MAJORCD, \
    COURSECODE, \
    NYUUGAKU_TEIIN, \
    BOSYUU_TEIIN, \
    SIGAN_M, \
    SIGAN_W, \
    SIGAN_K, \
    SIGAN_T, \
    OBOEGAKI_M, \
    OBOEGAKI_W, \
    OBOEGAKI_K, \
    OBOEGAKI_T, \
    KAIGAI_M, \
    KAIGAI_W, \
    KAIGAI_K, \
    KAIGAI_T, \
    KISOTSU_M, \
    KISOTSU_W, \
    KISOTSU_K, \
    KISOTSU_T, \
    SEIJIN_M, \
    SEIJIN_W, \
    SEIJIN_K, \
    SEIJIN_T, \
    TSUUGAKUGAI_M, \
    TSUUGAKUGAI_W, \
    TSUUGAKUGAI_K, \
    TSUUGAKUGAI_T, \
    SPORTTOKU_M, \
    SPORTTOKU_W, \
    SPORTTOKU_K, \
    SPORTTOKU_T, \
    GOUKAKU_M, \
    GOUKAKU_W, \
    GOUKAKU_K, \
    GOUKAKU_T, \
    HOSHOUNIN_M, \
    HOSHOUNIN_W, \
    HOSHOUNIN_K, \
    HOSHOUNIN_T, \
    INNER_TO_OUT_J_M, \
    INNER_TO_OUT_J_W, \
    INNER_TO_OUT_J_K, \
    INNER_TO_OUT_J_T, \
    TOKUREI3_M, \
    TOKUREI3_W, \
    TOKUREI3_K, \
    TOKUREI3_T, \
    OUTER_M, \
    OUTER_W, \
    OUTER_K, \
    OUTER_T  \
    ) \
as  \
SELECT \
    T1.EDBOARD_SCHOOLCD, \
    T1.YEAR, \
    T1.APPLICANTDIV, \
    T1.TESTDIV, \
    T1.RUIKEI_DIV, \
    T1.TESTDIV2, \
    T1.COURSECD, \
    T1.MAJORCD, \
    T1.COURSECODE, \
    NYUUGAKU_TEIIN.COUNT, \
    BOSYUU_TEIIN.COUNT, \
    SIGAN_M.COUNT, \
    SIGAN_W.COUNT, \
    SIGAN_K.COUNT, \
    SIGAN_T.COUNT, \
    OBOEGAKI_M.COUNT, \
    OBOEGAKI_W.COUNT, \
    OBOEGAKI_K.COUNT, \
    OBOEGAKI_T.COUNT, \
    KAIGAI_M.COUNT, \
    KAIGAI_W.COUNT, \
    KAIGAI_K.COUNT, \
    KAIGAI_T.COUNT, \
    KISOTSU_M.COUNT, \
    KISOTSU_W.COUNT, \
    KISOTSU_K.COUNT, \
    KISOTSU_T.COUNT, \
    SEIJIN_M.COUNT, \
    SEIJIN_W.COUNT, \
    SEIJIN_K.COUNT, \
    SEIJIN_T.COUNT, \
    TSUUGAKUGAI_M.COUNT, \
    TSUUGAKUGAI_W.COUNT, \
    TSUUGAKUGAI_K.COUNT, \
    TSUUGAKUGAI_T.COUNT, \
    SPORTTOKU_M.COUNT, \
    SPORTTOKU_W.COUNT, \
    SPORTTOKU_K.COUNT, \
    SPORTTOKU_T.COUNT, \
    GOUKAKU_M.COUNT, \
    GOUKAKU_W.COUNT, \
    GOUKAKU_K.COUNT, \
    GOUKAKU_T.COUNT, \
    HOSHOUNIN_M.COUNT, \
    HOSHOUNIN_W.COUNT, \
    HOSHOUNIN_K.COUNT, \
    HOSHOUNIN_T.COUNT, \
    INNER_TO_OUT_J_M.COUNT, \
    INNER_TO_OUT_J_W.COUNT, \
    INNER_TO_OUT_J_K.COUNT, \
    INNER_TO_OUT_J_T.COUNT, \
    TOKUREI3_M.COUNT, \
    TOKUREI3_W.COUNT, \
    TOKUREI3_K.COUNT, \
    TOKUREI3_T.COUNT, \
    OUTER_M.COUNT, \
    OUTER_W.COUNT, \
    OUTER_K.COUNT, \
    OUTER_T.COUNT \
FROM \
    (SELECT DISTINCT \
        MAIN.EDBOARD_SCHOOLCD, \
        MAIN.YEAR, \
        MAIN.APPLICANTDIV, \
        MAIN.TESTDIV, \
        MAIN.RUIKEI_DIV, \
        MAIN.TESTDIV2, \
        MAIN.COURSECD, \
        MAIN.MAJORCD, \
        MAIN.COURSECODE \
     FROM \
        AFT_SINRO_ADDITION_L350W_DAT MAIN \
    ) T1 \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT NYUUGAKU_TEIIN ON T1.EDBOARD_SCHOOLCD = NYUUGAKU_TEIIN.EDBOARD_SCHOOLCD \
         AND T1.YEAR = NYUUGAKU_TEIIN.YEAR \
         AND T1.APPLICANTDIV = NYUUGAKU_TEIIN.APPLICANTDIV \
         AND T1.TESTDIV = NYUUGAKU_TEIIN.TESTDIV \
         AND T1.RUIKEI_DIV = NYUUGAKU_TEIIN.RUIKEI_DIV \
         AND T1.TESTDIV2 = NYUUGAKU_TEIIN.TESTDIV2 \
         AND T1.COURSECD = NYUUGAKU_TEIIN.COURSECD \
         AND T1.MAJORCD = NYUUGAKU_TEIIN.MAJORCD \
         AND T1.COURSECODE = NYUUGAKU_TEIIN.COURSECODE \
         AND NYUUGAKU_TEIIN.SEX = '9' \
         AND NYUUGAKU_TEIIN.LARGE_DIV = '98' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT BOSYUU_TEIIN ON T1.EDBOARD_SCHOOLCD = BOSYUU_TEIIN.EDBOARD_SCHOOLCD \
         AND T1.YEAR = BOSYUU_TEIIN.YEAR \
         AND T1.APPLICANTDIV = BOSYUU_TEIIN.APPLICANTDIV \
         AND T1.TESTDIV = BOSYUU_TEIIN.TESTDIV \
         AND T1.RUIKEI_DIV = BOSYUU_TEIIN.RUIKEI_DIV \
         AND T1.TESTDIV2 = BOSYUU_TEIIN.TESTDIV2 \
         AND T1.COURSECD = BOSYUU_TEIIN.COURSECD \
         AND T1.MAJORCD = BOSYUU_TEIIN.MAJORCD \
         AND T1.COURSECODE = BOSYUU_TEIIN.COURSECODE \
         AND BOSYUU_TEIIN.SEX = '9' \
         AND BOSYUU_TEIIN.LARGE_DIV = '99' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT SIGAN_M ON T1.EDBOARD_SCHOOLCD = SIGAN_M.EDBOARD_SCHOOLCD \
         AND T1.YEAR = SIGAN_M.YEAR \
         AND T1.APPLICANTDIV = SIGAN_M.APPLICANTDIV \
         AND T1.TESTDIV = SIGAN_M.TESTDIV \
         AND T1.RUIKEI_DIV = SIGAN_M.RUIKEI_DIV \
         AND T1.TESTDIV2 = SIGAN_M.TESTDIV2 \
         AND T1.COURSECD = SIGAN_M.COURSECD \
         AND T1.MAJORCD = SIGAN_M.MAJORCD \
         AND T1.COURSECODE = SIGAN_M.COURSECODE \
         AND SIGAN_M.LARGE_DIV = '01' \
         AND SIGAN_M.SEX = '1' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT SIGAN_W ON T1.EDBOARD_SCHOOLCD = SIGAN_W.EDBOARD_SCHOOLCD \
         AND T1.YEAR = SIGAN_W.YEAR \
         AND T1.APPLICANTDIV = SIGAN_W.APPLICANTDIV \
         AND T1.TESTDIV = SIGAN_W.TESTDIV \
         AND T1.RUIKEI_DIV = SIGAN_W.RUIKEI_DIV \
         AND T1.TESTDIV2 = SIGAN_W.TESTDIV2 \
         AND T1.COURSECD = SIGAN_W.COURSECD \
         AND T1.MAJORCD = SIGAN_W.MAJORCD \
         AND T1.COURSECODE = SIGAN_W.COURSECODE \
         AND SIGAN_W.LARGE_DIV = '01' \
         AND SIGAN_W.SEX = '2' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT SIGAN_K ON T1.EDBOARD_SCHOOLCD = SIGAN_K.EDBOARD_SCHOOLCD \
         AND T1.YEAR = SIGAN_K.YEAR \
         AND T1.APPLICANTDIV = SIGAN_K.APPLICANTDIV \
         AND T1.TESTDIV = SIGAN_K.TESTDIV \
         AND T1.RUIKEI_DIV = SIGAN_K.RUIKEI_DIV \
         AND T1.TESTDIV2 = SIGAN_K.TESTDIV2 \
         AND T1.COURSECD = SIGAN_K.COURSECD \
         AND T1.MAJORCD = SIGAN_K.MAJORCD \
         AND T1.COURSECODE = SIGAN_K.COURSECODE \
         AND SIGAN_K.LARGE_DIV = '01' \
         AND SIGAN_K.SEX = '0' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT SIGAN_T ON T1.EDBOARD_SCHOOLCD = SIGAN_T.EDBOARD_SCHOOLCD \
         AND T1.YEAR = SIGAN_T.YEAR \
         AND T1.APPLICANTDIV = SIGAN_T.APPLICANTDIV \
         AND T1.TESTDIV = SIGAN_T.TESTDIV \
         AND T1.RUIKEI_DIV = SIGAN_T.RUIKEI_DIV \
         AND T1.TESTDIV2 = SIGAN_T.TESTDIV2 \
         AND T1.COURSECD = SIGAN_T.COURSECD \
         AND T1.MAJORCD = SIGAN_T.MAJORCD \
         AND T1.COURSECODE = SIGAN_T.COURSECODE \
         AND SIGAN_T.LARGE_DIV = '01' \
         AND SIGAN_T.SEX = '9' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT OBOEGAKI_M ON T1.EDBOARD_SCHOOLCD = OBOEGAKI_M.EDBOARD_SCHOOLCD \
         AND T1.YEAR = OBOEGAKI_M.YEAR \
         AND T1.APPLICANTDIV = OBOEGAKI_M.APPLICANTDIV \
         AND T1.TESTDIV = OBOEGAKI_M.TESTDIV \
         AND T1.RUIKEI_DIV = OBOEGAKI_M.RUIKEI_DIV \
         AND T1.TESTDIV2 = OBOEGAKI_M.TESTDIV2 \
         AND T1.COURSECD = OBOEGAKI_M.COURSECD \
         AND T1.MAJORCD = OBOEGAKI_M.MAJORCD \
         AND T1.COURSECODE = OBOEGAKI_M.COURSECODE \
         AND OBOEGAKI_M.LARGE_DIV = '02' \
         AND OBOEGAKI_M.SEX = '1' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT OBOEGAKI_W ON T1.EDBOARD_SCHOOLCD = OBOEGAKI_W.EDBOARD_SCHOOLCD \
         AND T1.YEAR = OBOEGAKI_W.YEAR \
         AND T1.APPLICANTDIV = OBOEGAKI_W.APPLICANTDIV \
         AND T1.TESTDIV = OBOEGAKI_W.TESTDIV \
         AND T1.RUIKEI_DIV = OBOEGAKI_W.RUIKEI_DIV \
         AND T1.TESTDIV2 = OBOEGAKI_W.TESTDIV2 \
         AND T1.COURSECD = OBOEGAKI_W.COURSECD \
         AND T1.MAJORCD = OBOEGAKI_W.MAJORCD \
         AND T1.COURSECODE = OBOEGAKI_W.COURSECODE \
         AND OBOEGAKI_W.LARGE_DIV = '02' \
         AND OBOEGAKI_W.SEX = '2' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT OBOEGAKI_K ON T1.EDBOARD_SCHOOLCD = OBOEGAKI_K.EDBOARD_SCHOOLCD \
         AND T1.YEAR = OBOEGAKI_K.YEAR \
         AND T1.APPLICANTDIV = OBOEGAKI_K.APPLICANTDIV \
         AND T1.TESTDIV = OBOEGAKI_K.TESTDIV \
         AND T1.RUIKEI_DIV = OBOEGAKI_K.RUIKEI_DIV \
         AND T1.TESTDIV2 = OBOEGAKI_K.TESTDIV2 \
         AND T1.COURSECD = OBOEGAKI_K.COURSECD \
         AND T1.MAJORCD = OBOEGAKI_K.MAJORCD \
         AND T1.COURSECODE = OBOEGAKI_K.COURSECODE \
         AND OBOEGAKI_K.LARGE_DIV = '02' \
         AND OBOEGAKI_K.SEX = '0' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT OBOEGAKI_T ON T1.EDBOARD_SCHOOLCD = OBOEGAKI_T.EDBOARD_SCHOOLCD \
         AND T1.YEAR = OBOEGAKI_T.YEAR \
         AND T1.APPLICANTDIV = OBOEGAKI_T.APPLICANTDIV \
         AND T1.TESTDIV = OBOEGAKI_T.TESTDIV \
         AND T1.RUIKEI_DIV = OBOEGAKI_T.RUIKEI_DIV \
         AND T1.TESTDIV2 = OBOEGAKI_T.TESTDIV2 \
         AND T1.COURSECD = OBOEGAKI_T.COURSECD \
         AND T1.MAJORCD = OBOEGAKI_T.MAJORCD \
         AND T1.COURSECODE = OBOEGAKI_T.COURSECODE \
         AND OBOEGAKI_T.LARGE_DIV = '02' \
         AND OBOEGAKI_T.SEX = '9' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT KAIGAI_M ON T1.EDBOARD_SCHOOLCD = KAIGAI_M.EDBOARD_SCHOOLCD \
         AND T1.YEAR = KAIGAI_M.YEAR \
         AND T1.APPLICANTDIV = KAIGAI_M.APPLICANTDIV \
         AND T1.TESTDIV = KAIGAI_M.TESTDIV \
         AND T1.RUIKEI_DIV = KAIGAI_M.RUIKEI_DIV \
         AND T1.TESTDIV2 = KAIGAI_M.TESTDIV2 \
         AND T1.COURSECD = KAIGAI_M.COURSECD \
         AND T1.MAJORCD = KAIGAI_M.MAJORCD \
         AND T1.COURSECODE = KAIGAI_M.COURSECODE \
         AND KAIGAI_M.LARGE_DIV = '03' \
         AND KAIGAI_M.SEX = '1' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT KAIGAI_W ON T1.EDBOARD_SCHOOLCD = KAIGAI_W.EDBOARD_SCHOOLCD \
         AND T1.YEAR = KAIGAI_W.YEAR \
         AND T1.APPLICANTDIV = KAIGAI_W.APPLICANTDIV \
         AND T1.TESTDIV = KAIGAI_W.TESTDIV \
         AND T1.RUIKEI_DIV = KAIGAI_W.RUIKEI_DIV \
         AND T1.TESTDIV2 = KAIGAI_W.TESTDIV2 \
         AND T1.COURSECD = KAIGAI_W.COURSECD \
         AND T1.MAJORCD = KAIGAI_W.MAJORCD \
         AND T1.COURSECODE = KAIGAI_W.COURSECODE \
         AND KAIGAI_W.LARGE_DIV = '03' \
         AND KAIGAI_W.SEX = '2' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT KAIGAI_K ON T1.EDBOARD_SCHOOLCD = KAIGAI_K.EDBOARD_SCHOOLCD \
         AND T1.YEAR = KAIGAI_K.YEAR \
         AND T1.APPLICANTDIV = KAIGAI_K.APPLICANTDIV \
         AND T1.TESTDIV = KAIGAI_K.TESTDIV \
         AND T1.RUIKEI_DIV = KAIGAI_K.RUIKEI_DIV \
         AND T1.TESTDIV2 = KAIGAI_K.TESTDIV2 \
         AND T1.COURSECD = KAIGAI_K.COURSECD \
         AND T1.MAJORCD = KAIGAI_K.MAJORCD \
         AND T1.COURSECODE = KAIGAI_K.COURSECODE \
         AND KAIGAI_K.LARGE_DIV = '03' \
         AND KAIGAI_K.SEX = '0' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT KAIGAI_T ON T1.EDBOARD_SCHOOLCD = KAIGAI_T.EDBOARD_SCHOOLCD \
         AND T1.YEAR = KAIGAI_T.YEAR \
         AND T1.APPLICANTDIV = KAIGAI_T.APPLICANTDIV \
         AND T1.TESTDIV = KAIGAI_T.TESTDIV \
         AND T1.RUIKEI_DIV = KAIGAI_T.RUIKEI_DIV \
         AND T1.TESTDIV2 = KAIGAI_T.TESTDIV2 \
         AND T1.COURSECD = KAIGAI_T.COURSECD \
         AND T1.MAJORCD = KAIGAI_T.MAJORCD \
         AND T1.COURSECODE = KAIGAI_T.COURSECODE \
         AND KAIGAI_T.LARGE_DIV = '03' \
         AND KAIGAI_T.SEX = '9' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT KISOTSU_M ON T1.EDBOARD_SCHOOLCD = KISOTSU_M.EDBOARD_SCHOOLCD \
         AND T1.YEAR = KISOTSU_M.YEAR \
         AND T1.APPLICANTDIV = KISOTSU_M.APPLICANTDIV \
         AND T1.TESTDIV = KISOTSU_M.TESTDIV \
         AND T1.RUIKEI_DIV = KISOTSU_M.RUIKEI_DIV \
         AND T1.TESTDIV2 = KISOTSU_M.TESTDIV2 \
         AND T1.COURSECD = KISOTSU_M.COURSECD \
         AND T1.MAJORCD = KISOTSU_M.MAJORCD \
         AND T1.COURSECODE = KISOTSU_M.COURSECODE \
         AND KISOTSU_M.LARGE_DIV = '04' \
         AND KISOTSU_M.SEX = '1' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT KISOTSU_W ON T1.EDBOARD_SCHOOLCD = KISOTSU_W.EDBOARD_SCHOOLCD \
         AND T1.YEAR = KISOTSU_W.YEAR \
         AND T1.APPLICANTDIV = KISOTSU_W.APPLICANTDIV \
         AND T1.TESTDIV = KISOTSU_W.TESTDIV \
         AND T1.RUIKEI_DIV = KISOTSU_W.RUIKEI_DIV \
         AND T1.TESTDIV2 = KISOTSU_W.TESTDIV2 \
         AND T1.COURSECD = KISOTSU_W.COURSECD \
         AND T1.MAJORCD = KISOTSU_W.MAJORCD \
         AND T1.COURSECODE = KISOTSU_W.COURSECODE \
         AND KISOTSU_W.LARGE_DIV = '04' \
         AND KISOTSU_W.SEX = '2' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT KISOTSU_K ON T1.EDBOARD_SCHOOLCD = KISOTSU_K.EDBOARD_SCHOOLCD \
         AND T1.YEAR = KISOTSU_K.YEAR \
         AND T1.APPLICANTDIV = KISOTSU_K.APPLICANTDIV \
         AND T1.TESTDIV = KISOTSU_K.TESTDIV \
         AND T1.RUIKEI_DIV = KISOTSU_K.RUIKEI_DIV \
         AND T1.TESTDIV2 = KISOTSU_K.TESTDIV2 \
         AND T1.COURSECD = KISOTSU_K.COURSECD \
         AND T1.MAJORCD = KISOTSU_K.MAJORCD \
         AND T1.COURSECODE = KISOTSU_K.COURSECODE \
         AND KISOTSU_K.LARGE_DIV = '04' \
         AND KISOTSU_K.SEX = '0' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT KISOTSU_T ON T1.EDBOARD_SCHOOLCD = KISOTSU_T.EDBOARD_SCHOOLCD \
         AND T1.YEAR = KISOTSU_T.YEAR \
         AND T1.APPLICANTDIV = KISOTSU_T.APPLICANTDIV \
         AND T1.TESTDIV = KISOTSU_T.TESTDIV \
         AND T1.RUIKEI_DIV = KISOTSU_T.RUIKEI_DIV \
         AND T1.TESTDIV2 = KISOTSU_T.TESTDIV2 \
         AND T1.COURSECD = KISOTSU_T.COURSECD \
         AND T1.MAJORCD = KISOTSU_T.MAJORCD \
         AND T1.COURSECODE = KISOTSU_T.COURSECODE \
         AND KISOTSU_T.LARGE_DIV = '04' \
         AND KISOTSU_T.SEX = '9' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT SEIJIN_M ON T1.EDBOARD_SCHOOLCD = SEIJIN_M.EDBOARD_SCHOOLCD \
         AND T1.YEAR = SEIJIN_M.YEAR \
         AND T1.APPLICANTDIV = SEIJIN_M.APPLICANTDIV \
         AND T1.TESTDIV = SEIJIN_M.TESTDIV \
         AND T1.RUIKEI_DIV = SEIJIN_M.RUIKEI_DIV \
         AND T1.TESTDIV2 = SEIJIN_M.TESTDIV2 \
         AND T1.COURSECD = SEIJIN_M.COURSECD \
         AND T1.MAJORCD = SEIJIN_M.MAJORCD \
         AND T1.COURSECODE = SEIJIN_M.COURSECODE \
         AND SEIJIN_M.LARGE_DIV = '05' \
         AND SEIJIN_M.SEX = '1' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT SEIJIN_W ON T1.EDBOARD_SCHOOLCD = SEIJIN_W.EDBOARD_SCHOOLCD \
         AND T1.YEAR = SEIJIN_W.YEAR \
         AND T1.APPLICANTDIV = SEIJIN_W.APPLICANTDIV \
         AND T1.TESTDIV = SEIJIN_W.TESTDIV \
         AND T1.RUIKEI_DIV = SEIJIN_W.RUIKEI_DIV \
         AND T1.TESTDIV2 = SEIJIN_W.TESTDIV2 \
         AND T1.COURSECD = SEIJIN_W.COURSECD \
         AND T1.MAJORCD = SEIJIN_W.MAJORCD \
         AND T1.COURSECODE = SEIJIN_W.COURSECODE \
         AND SEIJIN_W.LARGE_DIV = '05' \
         AND SEIJIN_W.SEX = '2' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT SEIJIN_K ON T1.EDBOARD_SCHOOLCD = SEIJIN_K.EDBOARD_SCHOOLCD \
         AND T1.YEAR = SEIJIN_K.YEAR \
         AND T1.APPLICANTDIV = SEIJIN_K.APPLICANTDIV \
         AND T1.TESTDIV = SEIJIN_K.TESTDIV \
         AND T1.RUIKEI_DIV = SEIJIN_K.RUIKEI_DIV \
         AND T1.TESTDIV2 = SEIJIN_K.TESTDIV2 \
         AND T1.COURSECD = SEIJIN_K.COURSECD \
         AND T1.MAJORCD = SEIJIN_K.MAJORCD \
         AND T1.COURSECODE = SEIJIN_K.COURSECODE \
         AND SEIJIN_K.LARGE_DIV = '05' \
         AND SEIJIN_K.SEX = '0' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT SEIJIN_T ON T1.EDBOARD_SCHOOLCD = SEIJIN_T.EDBOARD_SCHOOLCD \
         AND T1.YEAR = SEIJIN_T.YEAR \
         AND T1.APPLICANTDIV = SEIJIN_T.APPLICANTDIV \
         AND T1.TESTDIV = SEIJIN_T.TESTDIV \
         AND T1.RUIKEI_DIV = SEIJIN_T.RUIKEI_DIV \
         AND T1.TESTDIV2 = SEIJIN_T.TESTDIV2 \
         AND T1.COURSECD = SEIJIN_T.COURSECD \
         AND T1.MAJORCD = SEIJIN_T.MAJORCD \
         AND T1.COURSECODE = SEIJIN_T.COURSECODE \
         AND SEIJIN_T.LARGE_DIV = '05' \
         AND SEIJIN_T.SEX = '9' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT TSUUGAKUGAI_M ON T1.EDBOARD_SCHOOLCD = TSUUGAKUGAI_M.EDBOARD_SCHOOLCD \
         AND T1.YEAR = TSUUGAKUGAI_M.YEAR \
         AND T1.APPLICANTDIV = TSUUGAKUGAI_M.APPLICANTDIV \
         AND T1.TESTDIV = TSUUGAKUGAI_M.TESTDIV \
         AND T1.RUIKEI_DIV = TSUUGAKUGAI_M.RUIKEI_DIV \
         AND T1.TESTDIV2 = TSUUGAKUGAI_M.TESTDIV2 \
         AND T1.COURSECD = TSUUGAKUGAI_M.COURSECD \
         AND T1.MAJORCD = TSUUGAKUGAI_M.MAJORCD \
         AND T1.COURSECODE = TSUUGAKUGAI_M.COURSECODE \
         AND TSUUGAKUGAI_M.LARGE_DIV = '06' \
         AND TSUUGAKUGAI_M.SEX = '1' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT TSUUGAKUGAI_W ON T1.EDBOARD_SCHOOLCD = TSUUGAKUGAI_W.EDBOARD_SCHOOLCD \
         AND T1.YEAR = TSUUGAKUGAI_W.YEAR \
         AND T1.APPLICANTDIV = TSUUGAKUGAI_W.APPLICANTDIV \
         AND T1.TESTDIV = TSUUGAKUGAI_W.TESTDIV \
         AND T1.RUIKEI_DIV = TSUUGAKUGAI_W.RUIKEI_DIV \
         AND T1.TESTDIV2 = TSUUGAKUGAI_W.TESTDIV2 \
         AND T1.COURSECD = TSUUGAKUGAI_W.COURSECD \
         AND T1.MAJORCD = TSUUGAKUGAI_W.MAJORCD \
         AND T1.COURSECODE = TSUUGAKUGAI_W.COURSECODE \
         AND TSUUGAKUGAI_W.LARGE_DIV = '06' \
         AND TSUUGAKUGAI_W.SEX = '2' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT TSUUGAKUGAI_K ON T1.EDBOARD_SCHOOLCD = TSUUGAKUGAI_K.EDBOARD_SCHOOLCD \
         AND T1.YEAR = TSUUGAKUGAI_K.YEAR \
         AND T1.APPLICANTDIV = TSUUGAKUGAI_K.APPLICANTDIV \
         AND T1.TESTDIV = TSUUGAKUGAI_K.TESTDIV \
         AND T1.RUIKEI_DIV = TSUUGAKUGAI_K.RUIKEI_DIV \
         AND T1.TESTDIV2 = TSUUGAKUGAI_K.TESTDIV2 \
         AND T1.COURSECD = TSUUGAKUGAI_K.COURSECD \
         AND T1.MAJORCD = TSUUGAKUGAI_K.MAJORCD \
         AND T1.COURSECODE = TSUUGAKUGAI_K.COURSECODE \
         AND TSUUGAKUGAI_K.LARGE_DIV = '06' \
         AND TSUUGAKUGAI_K.SEX = '0' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT TSUUGAKUGAI_T ON T1.EDBOARD_SCHOOLCD = TSUUGAKUGAI_T.EDBOARD_SCHOOLCD \
         AND T1.YEAR = TSUUGAKUGAI_T.YEAR \
         AND T1.APPLICANTDIV = TSUUGAKUGAI_T.APPLICANTDIV \
         AND T1.TESTDIV = TSUUGAKUGAI_T.TESTDIV \
         AND T1.RUIKEI_DIV = TSUUGAKUGAI_T.RUIKEI_DIV \
         AND T1.TESTDIV2 = TSUUGAKUGAI_T.TESTDIV2 \
         AND T1.COURSECD = TSUUGAKUGAI_T.COURSECD \
         AND T1.MAJORCD = TSUUGAKUGAI_T.MAJORCD \
         AND T1.COURSECODE = TSUUGAKUGAI_T.COURSECODE \
         AND TSUUGAKUGAI_T.LARGE_DIV = '06' \
         AND TSUUGAKUGAI_T.SEX = '9' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT SPORTTOKU_M ON T1.EDBOARD_SCHOOLCD = SPORTTOKU_M.EDBOARD_SCHOOLCD \
         AND T1.YEAR = SPORTTOKU_M.YEAR \
         AND T1.APPLICANTDIV = SPORTTOKU_M.APPLICANTDIV \
         AND T1.TESTDIV = SPORTTOKU_M.TESTDIV \
         AND T1.RUIKEI_DIV = SPORTTOKU_M.RUIKEI_DIV \
         AND T1.TESTDIV2 = SPORTTOKU_M.TESTDIV2 \
         AND T1.COURSECD = SPORTTOKU_M.COURSECD \
         AND T1.MAJORCD = SPORTTOKU_M.MAJORCD \
         AND T1.COURSECODE = SPORTTOKU_M.COURSECODE \
         AND SPORTTOKU_M.LARGE_DIV = '07' \
         AND SPORTTOKU_M.SEX = '1' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT SPORTTOKU_W ON T1.EDBOARD_SCHOOLCD = SPORTTOKU_W.EDBOARD_SCHOOLCD \
         AND T1.YEAR = SPORTTOKU_W.YEAR \
         AND T1.APPLICANTDIV = SPORTTOKU_W.APPLICANTDIV \
         AND T1.TESTDIV = SPORTTOKU_W.TESTDIV \
         AND T1.RUIKEI_DIV = SPORTTOKU_W.RUIKEI_DIV \
         AND T1.TESTDIV2 = SPORTTOKU_W.TESTDIV2 \
         AND T1.COURSECD = SPORTTOKU_W.COURSECD \
         AND T1.MAJORCD = SPORTTOKU_W.MAJORCD \
         AND T1.COURSECODE = SPORTTOKU_W.COURSECODE \
         AND SPORTTOKU_W.LARGE_DIV = '07' \
         AND SPORTTOKU_W.SEX = '2' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT SPORTTOKU_K ON T1.EDBOARD_SCHOOLCD = SPORTTOKU_K.EDBOARD_SCHOOLCD \
         AND T1.YEAR = SPORTTOKU_K.YEAR \
         AND T1.APPLICANTDIV = SPORTTOKU_K.APPLICANTDIV \
         AND T1.TESTDIV = SPORTTOKU_K.TESTDIV \
         AND T1.RUIKEI_DIV = SPORTTOKU_K.RUIKEI_DIV \
         AND T1.TESTDIV2 = SPORTTOKU_K.TESTDIV2 \
         AND T1.COURSECD = SPORTTOKU_K.COURSECD \
         AND T1.MAJORCD = SPORTTOKU_K.MAJORCD \
         AND T1.COURSECODE = SPORTTOKU_K.COURSECODE \
         AND SPORTTOKU_K.LARGE_DIV = '07' \
         AND SPORTTOKU_K.SEX = '0' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT SPORTTOKU_T ON T1.EDBOARD_SCHOOLCD = SPORTTOKU_T.EDBOARD_SCHOOLCD \
         AND T1.YEAR = SPORTTOKU_T.YEAR \
         AND T1.APPLICANTDIV = SPORTTOKU_T.APPLICANTDIV \
         AND T1.TESTDIV = SPORTTOKU_T.TESTDIV \
         AND T1.RUIKEI_DIV = SPORTTOKU_T.RUIKEI_DIV \
         AND T1.TESTDIV2 = SPORTTOKU_T.TESTDIV2 \
         AND T1.COURSECD = SPORTTOKU_T.COURSECD \
         AND T1.MAJORCD = SPORTTOKU_T.MAJORCD \
         AND T1.COURSECODE = SPORTTOKU_T.COURSECODE \
         AND SPORTTOKU_T.LARGE_DIV = '07' \
         AND SPORTTOKU_T.SEX = '9' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT GOUKAKU_M ON T1.EDBOARD_SCHOOLCD = GOUKAKU_M.EDBOARD_SCHOOLCD \
         AND T1.YEAR = GOUKAKU_M.YEAR \
         AND T1.APPLICANTDIV = GOUKAKU_M.APPLICANTDIV \
         AND T1.TESTDIV = GOUKAKU_M.TESTDIV \
         AND T1.RUIKEI_DIV = GOUKAKU_M.RUIKEI_DIV \
         AND T1.TESTDIV2 = GOUKAKU_M.TESTDIV2 \
         AND T1.COURSECD = GOUKAKU_M.COURSECD \
         AND T1.MAJORCD = GOUKAKU_M.MAJORCD \
         AND T1.COURSECODE = GOUKAKU_M.COURSECODE \
         AND GOUKAKU_M.LARGE_DIV = '08' \
         AND GOUKAKU_M.SEX = '1' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT GOUKAKU_W ON T1.EDBOARD_SCHOOLCD = GOUKAKU_W.EDBOARD_SCHOOLCD \
         AND T1.YEAR = GOUKAKU_W.YEAR \
         AND T1.APPLICANTDIV = GOUKAKU_W.APPLICANTDIV \
         AND T1.TESTDIV = GOUKAKU_W.TESTDIV \
         AND T1.RUIKEI_DIV = GOUKAKU_W.RUIKEI_DIV \
         AND T1.TESTDIV2 = GOUKAKU_W.TESTDIV2 \
         AND T1.COURSECD = GOUKAKU_W.COURSECD \
         AND T1.MAJORCD = GOUKAKU_W.MAJORCD \
         AND T1.COURSECODE = GOUKAKU_W.COURSECODE \
         AND GOUKAKU_W.LARGE_DIV = '08' \
         AND GOUKAKU_W.SEX = '2' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT GOUKAKU_K ON T1.EDBOARD_SCHOOLCD = GOUKAKU_K.EDBOARD_SCHOOLCD \
         AND T1.YEAR = GOUKAKU_K.YEAR \
         AND T1.APPLICANTDIV = GOUKAKU_K.APPLICANTDIV \
         AND T1.TESTDIV = GOUKAKU_K.TESTDIV \
         AND T1.RUIKEI_DIV = GOUKAKU_K.RUIKEI_DIV \
         AND T1.TESTDIV2 = GOUKAKU_K.TESTDIV2 \
         AND T1.COURSECD = GOUKAKU_K.COURSECD \
         AND T1.MAJORCD = GOUKAKU_K.MAJORCD \
         AND T1.COURSECODE = GOUKAKU_K.COURSECODE \
         AND GOUKAKU_K.LARGE_DIV = '08' \
         AND GOUKAKU_K.SEX = '0' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT GOUKAKU_T ON T1.EDBOARD_SCHOOLCD = GOUKAKU_T.EDBOARD_SCHOOLCD \
         AND T1.YEAR = GOUKAKU_T.YEAR \
         AND T1.APPLICANTDIV = GOUKAKU_T.APPLICANTDIV \
         AND T1.TESTDIV = GOUKAKU_T.TESTDIV \
         AND T1.RUIKEI_DIV = GOUKAKU_T.RUIKEI_DIV \
         AND T1.TESTDIV2 = GOUKAKU_T.TESTDIV2 \
         AND T1.COURSECD = GOUKAKU_T.COURSECD \
         AND T1.MAJORCD = GOUKAKU_T.MAJORCD \
         AND T1.COURSECODE = GOUKAKU_T.COURSECODE \
         AND GOUKAKU_T.LARGE_DIV = '08' \
         AND GOUKAKU_T.SEX = '9' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT HOSHOUNIN_M ON T1.EDBOARD_SCHOOLCD = HOSHOUNIN_M.EDBOARD_SCHOOLCD \
         AND T1.YEAR = HOSHOUNIN_M.YEAR \
         AND T1.APPLICANTDIV = HOSHOUNIN_M.APPLICANTDIV \
         AND T1.TESTDIV = HOSHOUNIN_M.TESTDIV \
         AND T1.RUIKEI_DIV = HOSHOUNIN_M.RUIKEI_DIV \
         AND T1.TESTDIV2 = HOSHOUNIN_M.TESTDIV2 \
         AND T1.COURSECD = HOSHOUNIN_M.COURSECD \
         AND T1.MAJORCD = HOSHOUNIN_M.MAJORCD \
         AND T1.COURSECODE = HOSHOUNIN_M.COURSECODE \
         AND HOSHOUNIN_M.LARGE_DIV = '09' \
         AND HOSHOUNIN_M.SEX = '1' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT HOSHOUNIN_W ON T1.EDBOARD_SCHOOLCD = HOSHOUNIN_W.EDBOARD_SCHOOLCD \
         AND T1.YEAR = HOSHOUNIN_W.YEAR \
         AND T1.APPLICANTDIV = HOSHOUNIN_W.APPLICANTDIV \
         AND T1.TESTDIV = HOSHOUNIN_W.TESTDIV \
         AND T1.RUIKEI_DIV = HOSHOUNIN_W.RUIKEI_DIV \
         AND T1.TESTDIV2 = HOSHOUNIN_W.TESTDIV2 \
         AND T1.COURSECD = HOSHOUNIN_W.COURSECD \
         AND T1.MAJORCD = HOSHOUNIN_W.MAJORCD \
         AND T1.COURSECODE = HOSHOUNIN_W.COURSECODE \
         AND HOSHOUNIN_W.LARGE_DIV = '09' \
         AND HOSHOUNIN_W.SEX = '2' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT HOSHOUNIN_K ON T1.EDBOARD_SCHOOLCD = HOSHOUNIN_K.EDBOARD_SCHOOLCD \
         AND T1.YEAR = HOSHOUNIN_K.YEAR \
         AND T1.APPLICANTDIV = HOSHOUNIN_K.APPLICANTDIV \
         AND T1.TESTDIV = HOSHOUNIN_K.TESTDIV \
         AND T1.RUIKEI_DIV = HOSHOUNIN_K.RUIKEI_DIV \
         AND T1.TESTDIV2 = HOSHOUNIN_K.TESTDIV2 \
         AND T1.COURSECD = HOSHOUNIN_K.COURSECD \
         AND T1.MAJORCD = HOSHOUNIN_K.MAJORCD \
         AND T1.COURSECODE = HOSHOUNIN_K.COURSECODE \
         AND HOSHOUNIN_K.LARGE_DIV = '09' \
         AND HOSHOUNIN_K.SEX = '0' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT HOSHOUNIN_T ON T1.EDBOARD_SCHOOLCD = HOSHOUNIN_T.EDBOARD_SCHOOLCD \
         AND T1.YEAR = HOSHOUNIN_T.YEAR \
         AND T1.APPLICANTDIV = HOSHOUNIN_T.APPLICANTDIV \
         AND T1.TESTDIV = HOSHOUNIN_T.TESTDIV \
         AND T1.RUIKEI_DIV = HOSHOUNIN_T.RUIKEI_DIV \
         AND T1.TESTDIV2 = HOSHOUNIN_T.TESTDIV2 \
         AND T1.COURSECD = HOSHOUNIN_T.COURSECD \
         AND T1.MAJORCD = HOSHOUNIN_T.MAJORCD \
         AND T1.COURSECODE = HOSHOUNIN_T.COURSECODE \
         AND HOSHOUNIN_T.LARGE_DIV = '09' \
         AND HOSHOUNIN_T.SEX = '9' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT INNER_TO_OUT_J_M ON T1.EDBOARD_SCHOOLCD = INNER_TO_OUT_J_M.EDBOARD_SCHOOLCD \
         AND T1.YEAR = INNER_TO_OUT_J_M.YEAR \
         AND T1.APPLICANTDIV = INNER_TO_OUT_J_M.APPLICANTDIV \
         AND T1.TESTDIV = INNER_TO_OUT_J_M.TESTDIV \
         AND T1.RUIKEI_DIV = INNER_TO_OUT_J_M.RUIKEI_DIV \
         AND T1.TESTDIV2 = INNER_TO_OUT_J_M.TESTDIV2 \
         AND T1.COURSECD = INNER_TO_OUT_J_M.COURSECD \
         AND T1.MAJORCD = INNER_TO_OUT_J_M.MAJORCD \
         AND T1.COURSECODE = INNER_TO_OUT_J_M.COURSECODE \
         AND INNER_TO_OUT_J_M.LARGE_DIV = '10' \
         AND INNER_TO_OUT_J_M.SEX = '1' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT INNER_TO_OUT_J_W ON T1.EDBOARD_SCHOOLCD = INNER_TO_OUT_J_W.EDBOARD_SCHOOLCD \
         AND T1.YEAR = INNER_TO_OUT_J_W.YEAR \
         AND T1.APPLICANTDIV = INNER_TO_OUT_J_W.APPLICANTDIV \
         AND T1.TESTDIV = INNER_TO_OUT_J_W.TESTDIV \
         AND T1.RUIKEI_DIV = INNER_TO_OUT_J_W.RUIKEI_DIV \
         AND T1.TESTDIV2 = INNER_TO_OUT_J_W.TESTDIV2 \
         AND T1.COURSECD = INNER_TO_OUT_J_W.COURSECD \
         AND T1.MAJORCD = INNER_TO_OUT_J_W.MAJORCD \
         AND T1.COURSECODE = INNER_TO_OUT_J_W.COURSECODE \
         AND INNER_TO_OUT_J_W.LARGE_DIV = '10' \
         AND INNER_TO_OUT_J_W.SEX = '2' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT INNER_TO_OUT_J_K ON T1.EDBOARD_SCHOOLCD = INNER_TO_OUT_J_K.EDBOARD_SCHOOLCD \
         AND T1.YEAR = INNER_TO_OUT_J_K.YEAR \
         AND T1.APPLICANTDIV = INNER_TO_OUT_J_K.APPLICANTDIV \
         AND T1.TESTDIV = INNER_TO_OUT_J_K.TESTDIV \
         AND T1.RUIKEI_DIV = INNER_TO_OUT_J_K.RUIKEI_DIV \
         AND T1.TESTDIV2 = INNER_TO_OUT_J_K.TESTDIV2 \
         AND T1.COURSECD = INNER_TO_OUT_J_K.COURSECD \
         AND T1.MAJORCD = INNER_TO_OUT_J_K.MAJORCD \
         AND T1.COURSECODE = INNER_TO_OUT_J_K.COURSECODE \
         AND INNER_TO_OUT_J_K.LARGE_DIV = '10' \
         AND INNER_TO_OUT_J_K.SEX = '0' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT INNER_TO_OUT_J_T ON T1.EDBOARD_SCHOOLCD = INNER_TO_OUT_J_T.EDBOARD_SCHOOLCD \
         AND T1.YEAR = INNER_TO_OUT_J_T.YEAR \
         AND T1.APPLICANTDIV = INNER_TO_OUT_J_T.APPLICANTDIV \
         AND T1.TESTDIV = INNER_TO_OUT_J_T.TESTDIV \
         AND T1.RUIKEI_DIV = INNER_TO_OUT_J_T.RUIKEI_DIV \
         AND T1.TESTDIV2 = INNER_TO_OUT_J_T.TESTDIV2 \
         AND T1.COURSECD = INNER_TO_OUT_J_T.COURSECD \
         AND T1.MAJORCD = INNER_TO_OUT_J_T.MAJORCD \
         AND T1.COURSECODE = INNER_TO_OUT_J_T.COURSECODE \
         AND INNER_TO_OUT_J_T.LARGE_DIV = '10' \
         AND INNER_TO_OUT_J_T.SEX = '9' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT TOKUREI3_M ON T1.EDBOARD_SCHOOLCD = TOKUREI3_M.EDBOARD_SCHOOLCD \
         AND T1.YEAR = TOKUREI3_M.YEAR \
         AND T1.APPLICANTDIV = TOKUREI3_M.APPLICANTDIV \
         AND T1.TESTDIV = TOKUREI3_M.TESTDIV \
         AND T1.RUIKEI_DIV = TOKUREI3_M.RUIKEI_DIV \
         AND T1.TESTDIV2 = TOKUREI3_M.TESTDIV2 \
         AND T1.COURSECD = TOKUREI3_M.COURSECD \
         AND T1.MAJORCD = TOKUREI3_M.MAJORCD \
         AND T1.COURSECODE = TOKUREI3_M.COURSECODE \
         AND TOKUREI3_M.LARGE_DIV = '11' \
         AND TOKUREI3_M.SEX = '1' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT TOKUREI3_W ON T1.EDBOARD_SCHOOLCD = TOKUREI3_W.EDBOARD_SCHOOLCD \
         AND T1.YEAR = TOKUREI3_W.YEAR \
         AND T1.APPLICANTDIV = TOKUREI3_W.APPLICANTDIV \
         AND T1.TESTDIV = TOKUREI3_W.TESTDIV \
         AND T1.RUIKEI_DIV = TOKUREI3_W.RUIKEI_DIV \
         AND T1.TESTDIV2 = TOKUREI3_W.TESTDIV2 \
         AND T1.COURSECD = TOKUREI3_W.COURSECD \
         AND T1.MAJORCD = TOKUREI3_W.MAJORCD \
         AND T1.COURSECODE = TOKUREI3_W.COURSECODE \
         AND TOKUREI3_W.LARGE_DIV = '11' \
         AND TOKUREI3_W.SEX = '2' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT TOKUREI3_K ON T1.EDBOARD_SCHOOLCD = TOKUREI3_K.EDBOARD_SCHOOLCD \
         AND T1.YEAR = TOKUREI3_K.YEAR \
         AND T1.APPLICANTDIV = TOKUREI3_K.APPLICANTDIV \
         AND T1.TESTDIV = TOKUREI3_K.TESTDIV \
         AND T1.RUIKEI_DIV = TOKUREI3_K.RUIKEI_DIV \
         AND T1.TESTDIV2 = TOKUREI3_K.TESTDIV2 \
         AND T1.COURSECD = TOKUREI3_K.COURSECD \
         AND T1.MAJORCD = TOKUREI3_K.MAJORCD \
         AND T1.COURSECODE = TOKUREI3_K.COURSECODE \
         AND TOKUREI3_K.LARGE_DIV = '11' \
         AND TOKUREI3_K.SEX = '0' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT TOKUREI3_T ON T1.EDBOARD_SCHOOLCD = TOKUREI3_T.EDBOARD_SCHOOLCD \
         AND T1.YEAR = TOKUREI3_T.YEAR \
         AND T1.APPLICANTDIV = TOKUREI3_T.APPLICANTDIV \
         AND T1.TESTDIV = TOKUREI3_T.TESTDIV \
         AND T1.RUIKEI_DIV = TOKUREI3_T.RUIKEI_DIV \
         AND T1.TESTDIV2 = TOKUREI3_T.TESTDIV2 \
         AND T1.COURSECD = TOKUREI3_T.COURSECD \
         AND T1.MAJORCD = TOKUREI3_T.MAJORCD \
         AND T1.COURSECODE = TOKUREI3_T.COURSECODE \
         AND TOKUREI3_T.LARGE_DIV = '11' \
         AND TOKUREI3_T.SEX = '9' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT OUTER_M ON T1.EDBOARD_SCHOOLCD = OUTER_M.EDBOARD_SCHOOLCD \
         AND T1.YEAR = OUTER_M.YEAR \
         AND T1.APPLICANTDIV = OUTER_M.APPLICANTDIV \
         AND T1.TESTDIV = OUTER_M.TESTDIV \
         AND T1.RUIKEI_DIV = OUTER_M.RUIKEI_DIV \
         AND T1.TESTDIV2 = OUTER_M.TESTDIV2 \
         AND T1.COURSECD = OUTER_M.COURSECD \
         AND T1.MAJORCD = OUTER_M.MAJORCD \
         AND T1.COURSECODE = OUTER_M.COURSECODE \
         AND OUTER_M.LARGE_DIV = '12' \
         AND OUTER_M.SEX = '1' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT OUTER_W ON T1.EDBOARD_SCHOOLCD = OUTER_W.EDBOARD_SCHOOLCD \
         AND T1.YEAR = OUTER_W.YEAR \
         AND T1.APPLICANTDIV = OUTER_W.APPLICANTDIV \
         AND T1.TESTDIV = OUTER_W.TESTDIV \
         AND T1.RUIKEI_DIV = OUTER_W.RUIKEI_DIV \
         AND T1.TESTDIV2 = OUTER_W.TESTDIV2 \
         AND T1.COURSECD = OUTER_W.COURSECD \
         AND T1.MAJORCD = OUTER_W.MAJORCD \
         AND T1.COURSECODE = OUTER_W.COURSECODE \
         AND OUTER_W.LARGE_DIV = '12' \
         AND OUTER_W.SEX = '2' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT OUTER_K ON T1.EDBOARD_SCHOOLCD = OUTER_K.EDBOARD_SCHOOLCD \
         AND T1.YEAR = OUTER_K.YEAR \
         AND T1.APPLICANTDIV = OUTER_K.APPLICANTDIV \
         AND T1.TESTDIV = OUTER_K.TESTDIV \
         AND T1.RUIKEI_DIV = OUTER_K.RUIKEI_DIV \
         AND T1.TESTDIV2 = OUTER_K.TESTDIV2 \
         AND T1.COURSECD = OUTER_K.COURSECD \
         AND T1.MAJORCD = OUTER_K.MAJORCD \
         AND T1.COURSECODE = OUTER_K.COURSECODE \
         AND OUTER_K.LARGE_DIV = '12' \
         AND OUTER_K.SEX = '0' \
    LEFT JOIN AFT_SINRO_ADDITION_L350W_DAT OUTER_T ON T1.EDBOARD_SCHOOLCD = OUTER_T.EDBOARD_SCHOOLCD \
         AND T1.YEAR = OUTER_T.YEAR \
         AND T1.APPLICANTDIV = OUTER_T.APPLICANTDIV \
         AND T1.TESTDIV = OUTER_T.TESTDIV \
         AND T1.RUIKEI_DIV = OUTER_T.RUIKEI_DIV \
         AND T1.TESTDIV2 = OUTER_T.TESTDIV2 \
         AND T1.COURSECD = OUTER_T.COURSECD \
         AND T1.MAJORCD = OUTER_T.MAJORCD \
         AND T1.COURSECODE = OUTER_T.COURSECODE \
         AND OUTER_T.LARGE_DIV = '12' \
         AND OUTER_T.SEX = '9'
