drop table applicant_mst


create table applicant_mst \
        (enteryear                  varchar(4)     not null, \
         examineeno                 varchar(4)     not null, \
         acceptcd                   varchar(1), \
         attendcd                   varchar(1), \
         testp_no                   smallint,   \
         testp_cd1                  varchar(1), \ 
         testp_cd2                  varchar(2), \
         d1_coursecd                 varchar(1), \
         d1_majorcd                  varchar(3), \
         d2_coursecd                 varchar(1), \
         d2_majorcd                  varchar(3), \
         j_cd                       varchar(6), \
         cur_pastcd                 varchar(1), \
         sexcd                      varchar(1), \
         applic_name                varchar(40), \
         applic_name_show           varchar(20), \
         applic_kana                varchar(20), \
         applic_birthday            date, \
         applic_j_graduatedate      date, \
         applic_guard_name          varchar(40), \
         applic_guard_kana          varchar(20), \
         applic_telno               varchar(13), \
         applic_zipcd               varchar(8), \
         applic_address1            varchar(50), \
         applic_address2            varchar(50), \
         view_japanesea             smallint, \
         view_societya              smallint, \
         view_matha                 smallint, \
         view_sciencea              smallint, \
         view_musica                smallint, \
         view_arta                  smallint, \
         view_healtha               smallint, \
         view_techa                 smallint, \
         view_englisha              smallint, \
         view_japaneseb             smallint, \
         view_societyb              smallint, \
         view_mathb                 smallint, \
         view_scienceb              smallint, \
         view_musicb                smallint, \
         view_artb                  smallint, \
         view_healthb               smallint, \
         view_techb                 smallint, \
         view_englishb              smallint, \
         view_japanesec             smallint, \
         view_societyc              smallint, \
         view_mathc                 smallint, \
         view_sciencec              smallint, \
         view_musicc                smallint, \
         view_artc                  smallint, \
         view_healthc               smallint, \
         view_techc                 smallint, \
         view_englishc              smallint, \
         view_scoresuma             dec(4,1), \
         view_scoresumb             dec(4,1), \
         view_scoresumc             dec(4,1), \
         assess_1_japanese          smallint, \
         assess_1_society           smallint, \
         assess_1_math              smallint, \
         assess_1_science           smallint, \
         assess_1_music             smallint, \
         assess_1_art               smallint, \
         assess_1_health            smallint, \
         assess_1_tech              smallint, \
         assess_1_english           smallint, \
         assess_2_japanese          smallint, \
         assess_2_society           smallint, \
         assess_2_math              smallint, \
         assess_2_science           smallint, \
         assess_2_music             smallint, \
         assess_2_art               smallint, \
         assess_2_health            smallint, \
         assess_2_tech              smallint, \
         assess_2_english           smallint, \
         assess_3_japanese          smallint, \
         assess_3_society           smallint, \
         assess_3_math              smallint, \
         assess_3_science           smallint, \
         assess_3_music             smallint, \
         assess_3_art               smallint, \
         assess_3_health            smallint, \
         assess_3_tech              smallint, \
         assess_3_english           smallint, \
         d1_report_dv                dec(5,2), \
         d2_report_dv                dec(5,2), \
         dayoff_1                   smallint, \
         dayoff_2                   smallint, \
         dayoff_3                   smallint, \
         late_1                     smallint, \
         late_2                     smallint, \
         late_3                     smallint, \
         absent_1                   smallint, \
         absent_2                   smallint, \
         absent_3                   smallint, \
         actrecord                  varchar(24), \
         specialactrecord           varchar(24), \
         recom_kind                 varchar(1), \
         recom_item                 varchar(1), \
         experience                 varchar(48), \
         qualification              varchar(40), \
         remark                     varchar(10), \
         interview                  varchar(4), \
         abilitytestjapanese        smallint, \
         abilitytestsociety         smallint, \
         abilitytestmath            smallint, \
         abilitytestscience         smallint, \
         abilitytestenglish         smallint, \
         appendquiza                smallint, \
         appendquizb                smallint, \
         appendquizc                smallint, \
         appendquizd                smallint, \
         appendquize                smallint, \
         d1_ability_dv               dec(5,2), \
         d2_ability_dv               dec(5,2), \
         pass_failcd                varchar(1), \
         entercd                    varchar(1), \
         consideration              varchar(4), \
         irateview_japanesea        dec(3,2), \
         irateview_japaneseb        dec(3,2), \
         irateview_japanesec        dec(3,2), \
         irateview_societya         dec(3,2), \
         irateview_societyb         dec(3,2), \
         irateview_societyc         dec(3,2), \
         irateview_matha            dec(3,2), \
         irateview_mathb            dec(3,2), \
         irateview_mathc            dec(3,2), \
         irateview_sciencea         dec(3,2), \
         irateview_scienceb         dec(3,2), \
         irateview_sciencec         dec(3,2), \
         irateview_musica           dec(3,2), \
         irateview_musicb           dec(3,2), \
         irateview_musicc           dec(3,2), \
         irateview_arta             dec(3,2), \
         irateview_artb             dec(3,2), \
         irateview_artc             dec(3,2), \
         irateview_healtha          dec(3,2), \
         irateview_healthb          dec(3,2), \
         irateview_healthc          dec(3,2), \
         irateview_techa            dec(3,2), \
         irateview_techb            dec(3,2), \
         irateview_techc            dec(3,2), \
         irateview_englisha         dec(3,2), \
         irateview_englishb         dec(3,2), \
         irateview_englishc         dec(3,2), \
         irateview_suma             dec(3,2), \
         irateview_sumb             dec(3,2), \
         irateview_sumc             dec(3,2), \
         irateassess_japanese       dec(3,2), \
         irateassess_society        dec(3,2), \
         irateassess_math           dec(3,2), \
         irateassess_science        dec(3,2), \
         irateassess_music          dec(3,2), \
         irateassess_art            dec(3,2), \
         irateassess_health         dec(3,2), \
         irateassess_tech           dec(3,2), \
         irateassess_english        dec(3,2), \
         irateability_japanese      dec(3,2), \
         irateability_society       dec(3,2), \
         irateability_math          dec(3,2), \
         irateability_science       dec(3,2), \
         irateability_english       dec(3,2), \
         irateappendquiza           dec(3,2), \
         irateappendquizb           dec(3,2), \
         irateappendquizc           dec(3,2), \
         irateappendquizd           dec(3,2), \
         irateappendquize           dec(3,2), \
         firstattendh_sch           varchar(20), \
         updated                  timestamp default current timestamp \
        ) in usr1dms index in idx1dms

alter table applicant_mst add constraint pk_aplcnt_mst primary key \
         (enteryear, examineeno)
