-- $Id: test_attend_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE TEST_ATTEND_DAT
CREATE TABLE TEST_ATTEND_DAT ( \
     YEAR                   VARCHAR(4)  NOT NULL, \
     SEMESTER               VARCHAR(1)  NOT NULL, \
     CLASSCD                VARCHAR(2)  NOT NULL, \
     SCHOOL_KIND            VARCHAR(2)  NOT NULL, \
     CURRICULUM_CD          VARCHAR(2)  NOT NULL, \
     SUBCLASSCD             VARCHAR(6)  NOT NULL, \
     SCHREGNO               VARCHAR(8)  NOT NULL, \
     TEST_KIND              VARCHAR(1), \
     INPUT_DATE             DATE, \
     REGISTERCD             VARCHAR(8), \
     UPDATED                TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS
ALTER TABLE TEST_ATTEND_DAT ADD CONSTRAINT PK_TEST_ATTEND_DAT PRIMARY KEY(YEAR,SEMESTER,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO)
