-- $Id: entexam_perfect_pre_mst.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE ENTEXAM_PERFECT_PRE_MST
CREATE TABLE ENTEXAM_PERFECT_PRE_MST( \
    ENTEXAMYEAR    VARCHAR(4)    NOT NULL, \
    APPLICANTDIV   VARCHAR(1)    NOT NULL, \
    PRE_EXAM_TYPE  VARCHAR(1)    NOT NULL, \
    TESTSUBCLASSCD VARCHAR(1)    NOT NULL, \
    PERFECT        SMALLINT, \
    REGISTERCD     VARCHAR(8), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_PERFECT_PRE_MST ADD CONSTRAINT PK_ENTEXAM_PER_PRE PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,PRE_EXAM_TYPE,TESTSUBCLASSCD)