-- $Id: entexam_score_pre_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE ENTEXAM_SCORE_PRE_DAT
CREATE TABLE ENTEXAM_SCORE_PRE_DAT( \
    ENTEXAMYEAR    VARCHAR(4)    NOT NULL, \
    APPLICANTDIV   VARCHAR(1)    NOT NULL, \
    PRE_RECEPTNO   VARCHAR(5)    NOT NULL, \
    TESTSUBCLASSCD VARCHAR(1)    NOT NULL, \
    ATTEND_FLG     VARCHAR(1), \
    SCORE          SMALLINT, \
    RANK           SMALLINT, \
    DIV_RANK       SMALLINT, \
    REGISTERCD     VARCHAR(8), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_SCORE_PRE_DAT ADD CONSTRAINT PK_ENTEXAM_SCO_PRE PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,PRE_RECEPTNO,TESTSUBCLASSCD)