-- $Id: entexam_sch_ptrn_hdat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE ENTEXAM_SCH_PTRN_HDAT
CREATE TABLE ENTEXAM_SCH_PTRN_HDAT( \
    ENTEXAMYEAR    VARCHAR(4)    NOT NULL, \
    APPLICANTDIV   VARCHAR(1)    NOT NULL, \
    TESTDIV        VARCHAR(1)    NOT NULL, \
    PATTERN_NO     VARCHAR(1)    NOT NULL, \
    PATTERN_NAME   VARCHAR(60), \
    REGISTERCD     VARCHAR(8), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_SCH_PTRN_HDAT ADD CONSTRAINT PK_ENT_SCH_PTN_HDT PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,PATTERN_NO)