-- $Id: entexam_hall_list_ydat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE ENTEXAM_HALL_LIST_YDAT
CREATE TABLE ENTEXAM_HALL_LIST_YDAT( \
    ENTEXAMYEAR   VARCHAR(4)    NOT NULL, \
    APPLICANTDIV  VARCHAR(1)    NOT NULL, \
    TESTDIV       VARCHAR(1)    NOT NULL, \
    EXAM_TYPE     VARCHAR(1)    NOT NULL, \
    EXAMHALLCD    VARCHAR(4)    NOT NULL, \
    RECEPTNO      VARCHAR(5)    NOT NULL, \
    REGISTERCD    VARCHAR(8), \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_HALL_LIST_YDAT ADD CONSTRAINT PK_ENTEXAM_HAL_L_Y PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,EXAM_TYPE,EXAMHALLCD,RECEPTNO)