-- $Id: bank_mst.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE BANK_MST
CREATE TABLE BANK_MST( \
	BANKCD          	VARCHAR(4)      NOT NULL, \
    BRANCHCD        	VARCHAR(3)      NOT NULL, \
    BANKNAME        	VARCHAR(90), \
    BANKNAME_KANA   	VARCHAR(90), \
    BANKNAME_ROMAJI 	VARCHAR(180), \
    BRANCHNAME      	VARCHAR(90), \
    BRANCHNAME_KANA 	VARCHAR(90), \
    BRANCHNAME_ROMAJI 	VARCHAR(180), \
    BANKZIPCD       	VARCHAR(8), \
    BANKADDR1       	VARCHAR(150), \
    BANKADDR2       	VARCHAR(150), \
    BANKTELNO       	VARCHAR(14), \
    BANKFAXNO       	VARCHAR(14), \
    SHUUGAKU_ITAKU_CD	VARCHAR(10), \
    SHITAKU_ITAKU_CD	VARCHAR(10), \
    SAIFURIKAE_DIV		VARCHAR(1), \
    GROUPING_DIV		VARCHAR(1), \
    MANAGE_BRANCHCD		VARCHAR(3), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE BANK_MST ADD CONSTRAINT PK_BANK_MST PRIMARY KEY (BANKCD,BRANCHCD)
