-- $Id: chiji_mst.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE CHIJI_MST
CREATE TABLE CHIJI_MST( \
    S_DATE			 		 	DATE    	   NOT NULL, \
    CHIJI_YAKUSHOKU_NAME	 	VARCHAR(45)    NOT NULL, \
    CHIJI_NAME		 		 	VARCHAR(120)   NOT NULL, \
    SUITOUCHOU_YAKUSHOKU_NAME	VARCHAR(45)    NOT NULL, \
    SUITOUCHOU_NAME		 		VARCHAR(120)   NOT NULL, \
    REGISTERCD           	 	VARCHAR(8), \
    UPDATED              	 	TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE CHIJI_MST ADD CONSTRAINT PK_CHIJI_MST PRIMARY KEY (S_DATE)