-- $Id: edboard_mst.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE EDBOARD_MST
CREATE TABLE EDBOARD_MST( \
    EDBOARDCD				VARCHAR(6) 	NOT NULL, \
	EDBOARDNAME				VARCHAR(60), \
	EDBOARDABBV				VARCHAR(60), \
    REGISTERCD           	VARCHAR(8), \
    UPDATED              	TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_MST ADD CONSTRAINT PK_EDBOARD_MST PRIMARY KEY (EDBOARDCD)