-- $Id: furikomi_kyuhu_bunmeisai_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE FURIKOMI_KYUHU_BUNMEISAI_DAT

CREATE TABLE FURIKOMI_KYUHU_BUNMEISAI_DAT( \
    S_KETTEI_DATE           DATE          NOT NULL, \
    E_KETTEI_DATE           DATE          NOT NULL, \
    SHIKIN_SHUBETSU         VARCHAR(1)    NOT NULL, \
    S_SHITEI_YM             VARCHAR(7)    NOT NULL, \
    E_SHITEI_YM             VARCHAR(7)    NOT NULL, \
    FURIKOMI_DATE           DATE          NOT NULL, \
    KOJIN_NO                VARCHAR(7)    NOT NULL, \
    SHINSEI_YEAR            VARCHAR(4)    NOT NULL, \
    SHUUGAKU_NO             VARCHAR(7)    NOT NULL, \
    BUN_FURIKOMI_GK         INT, \
    BUN_DAIRI_FURIKOMI_GK   INT, \
    REGISTERCD              VARCHAR(8), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE FURIKOMI_KYUHU_BUNMEISAI_DAT ADD CONSTRAINT PK_FURI_KYU_BUN PRIMARY KEY (S_KETTEI_DATE, E_KETTEI_DATE, SHIKIN_SHUBETSU, S_SHITEI_YM, E_SHITEI_YM, FURIKOMI_DATE, KOJIN_NO, SHINSEI_YEAR)
