drop table HENNOU_SESSYO

create table HENNOU_SESSYO \
( \
    SHUUGAKU_NO     VARCHAR(7) NOT NULL, \
    SESSYO_CODE     VARCHAR(2) NOT NULL, \
    INPUT_DATE      DATE, \
    JISSI_DATE      DATE NOT NULL, \
    SESSYO_BIKOU    VARCHAR(120), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) in USR1DMS INDEX IN IDX1DMS 

alter table HENNOU_SESSYO add constraint PK_HENNOU_SESSYO \
    primary key (SHUUGAKU_NO, JISSI_DATE, SESSYO_CODE)
