-- $Id: kojin_shuugaku_no_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE KOJIN_SHUUGAKU_NO_DAT
CREATE TABLE KOJIN_SHUUGAKU_NO_DAT( \
    YEAR          		 	 VARCHAR(4)    NOT NULL, \
    KOJIN_NO          		 VARCHAR(7)    NOT NULL, \
    UKE_NO         		     VARCHAR(4)    NOT NULL, \
    UKE_EDABAN               VARCHAR(3)    NOT NULL, \
    SHUUGAKU_NO              VARCHAR(7), \
    SHIKIN_DIV          	 VARCHAR(1)    NOT NULL, \
    REGISTERCD           	 VARCHAR(8), \
    UPDATED              	 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE KOJIN_SHUUGAKU_NO_DAT ADD CONSTRAINT PK_K_SHU_NO_DAT PRIMARY KEY (YEAR, KOJIN_NO, UKE_NO)