-- $Id: kojin_shinkensha_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE KOJIN_SHINKENSHA_DAT
CREATE TABLE KOJIN_SHINKENSHA_DAT( \
    KOJIN_NO                    VARCHAR(7)  NOT NULL, \
    SHINKEN_CD                  VARCHAR(7)  NOT NULL, \
    REMARK                      VARCHAR(60), \
    REGISTERCD                  VARCHAR(8), \
    UPDATED                     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE KOJIN_SHINKENSHA_DAT ADD CONSTRAINT PK_K_SHINKEN_DAT PRIMARY KEY (KOJIN_NO, SHINKEN_CD)