-- $Id: kojin_taiyo_shinsa_huyou_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE KOJIN_TAIYO_SHINSA_HUYOU_DAT
CREATE TABLE KOJIN_TAIYO_SHINSA_HUYOU_DAT( \
    KOJIN_NO                 VARCHAR(7)     NOT NULL, \
    SHINSEI_YEAR             VARCHAR(4)     NOT NULL, \
    HUYOU_DIV                VARCHAR(1)     NOT NULL, \
    SEQ                      SMALLINT       NOT NULL, \
    TARGET_YEAR_DIV          VARCHAR(1)     NOT NULL, \
    BIRTHDAY                 DATE, \
    NENREI                   SMALLINT, \
    REGISTERCD               VARCHAR(8), \
    UPDATED                  TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE KOJIN_TAIYO_SHINSA_HUYOU_DAT ADD CONSTRAINT PK_K_T_SHI_HUYOU_D PRIMARY KEY (KOJIN_NO, SHINSEI_YEAR, HUYOU_DIV, SEQ)