-- $Id: kojin_henkou_kyuhu_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE KOJIN_HENKOU_KYUHU_DAT
CREATE TABLE KOJIN_HENKOU_KYUHU_DAT( \
    KOJIN_NO                 VARCHAR(7)    NOT NULL, \
    SHINSEI_YEAR             VARCHAR(4)    NOT NULL, \
    HENKOU_DATE              DATE          NOT NULL, \
    HENKOU_UKE_YEAR          VARCHAR(4), \
    HENKOU_UKE_NO            VARCHAR(4), \
    HENKOU_UKE_EDABAN        VARCHAR(3), \
    HENKOUGO_KYUHU_GK        INT, \
    HENKOUMAE_KYUHU_GK       INT, \
    REGISTERCD               VARCHAR(8), \
    UPDATED                  TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE KOJIN_HENKOU_KYUHU_DAT ADD CONSTRAINT PK_K_HENK_K_DAT PRIMARY KEY (KOJIN_NO, SHINSEI_YEAR, HENKOU_DATE)

