-- $Id: kojin_rishi_hokyuu_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE KOJIN_RISHI_HOKYUU_DAT
CREATE TABLE KOJIN_RISHI_HOKYUU_DAT( \
    SHUUGAKU_NO                 VARCHAR(7)  NOT NULL, \
    SHIKIN_SHUBETSU             VARCHAR(1)  NOT NULL, \
    KOJIN_NO                    VARCHAR(7)  NOT NULL, \
    SHUTARU_CD                  VARCHAR(7)  NOT NULL, \
    S_SHINSEI_YEAR              VARCHAR(4), \
    KARIIRE_TOTAL_GK            INT         NOT NULL, \
    RISHI_TOTAL_GK              INT         NOT NULL, \
    KOUFU_SHINSEI_TOTAL_GK      INT         NOT NULL, \
    RISHI_HOKYUUSHORI_TOTAL_GK  INT         NOT NULL, \
    REGISTERCD                  VARCHAR(8), \
    UPDATED                     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE KOJIN_RISHI_HOKYUU_DAT ADD CONSTRAINT PK_K_RISHI_HO_DAT PRIMARY KEY (SHUUGAKU_NO)