-- $Id: kyuhu_gk_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE KYUHU_GK_DAT
CREATE TABLE KYUHU_GK_DAT( \
    YEAR                     VARCHAR(4)    NOT NULL, \
    SHOTOKUWARI_DIV          VARCHAR(1)    NOT NULL, \
    KOUSHI_DIV               VARCHAR(1)    NOT NULL, \
    KATEI_DIV                VARCHAR(1)    NOT NULL, \
    KYUHU_GK                 INT           NOT NULL, \
    REGISTERCD               VARCHAR(8), \
    UPDATED                  TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE KYUHU_GK_DAT ADD CONSTRAINT PK_KYUHU_GK_DAT PRIMARY KEY (YEAR, SHOTOKUWARI_DIV, KOUSHI_DIV, KATEI_DIV)