-- $Id: kyuuchi_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE KYUUCHI_DAT
CREATE TABLE KYUUCHI_DAT( \
    YEAR          		 	 VARCHAR(4)    NOT NULL, \
    CITYCD      			 VARCHAR(5)    NOT NULL, \
    KYUUCHI_CD           	 VARCHAR(1)    NOT NULL, \
    REGISTERCD           	 VARCHAR(8), \
    UPDATED              	 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE KYUUCHI_DAT ADD CONSTRAINT PK_KYUUCHI_DAT PRIMARY KEY (YEAR, CITYCD)