-- $Id: kyuuchi_mst.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE KYUUCHI_MST
CREATE TABLE KYUUCHI_MST( \
    KYUUCHI_CD      		 VARCHAR(1)    NOT NULL, \
    KYUUCHI_NAME1            VARCHAR(30), \
    KYUUCHI_NAME2            VARCHAR(30), \
    KYUUCHI_NAME3            VARCHAR(30), \
    REGISTERCD           	 VARCHAR(8), \
    UPDATED              	 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE KYUUCHI_MST ADD CONSTRAINT PK_KYUUCHI_MST PRIMARY KEY (KYUUCHI_CD)