-- $Id: ninteigk2_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE NINTEIGK2_DAT
CREATE TABLE NINTEIGK2_DAT( \
    YEAR          		 	 VARCHAR(4)    NOT NULL, \
	KHANTEI1_GK					INT, \
	KHANTEI2_GK					INT, \
	KHANTEI2_JYOZAN				INT, \
	KHANTEI2_KASAN_GK			INT, \
	KHANTEI3_GK					INT, \
	KHANTEI3_JYOZAN				INT, \
	KHANTEI3_KASAN_GK			INT, \
	KHANTEI4_KOUJYO_GK			INT, \
    TBOSHI_GK					INT, \
	TSYOUGAKU_GK				INT, \
	TCHUUGAKU_GK				INT, \
	TKOUKOU_JI_GK			 	INT, \
	TKOUKOU_JIGAI_GK		 	INT, \
	TKOUKOU_SHI_JI_GK			INT, \
	TKOUKOU_SHI_JIGAI_GK		INT, \
	TSENMON_KO_JI_GK			INT, \
	TSENMON_KO_JIGAI_GK		    INT, \
	TSENMON_SHI_JI_GK		    INT, \
	TSENMON_SHI_JIGAI_GK		INT, \
	TDAIGAKU_KO_JI_GK		    INT, \
	TDAIGAKU_KO_JIGAI_GK		INT, \
	TDAIGAKU_SHI_JI_GK		    INT, \
	TDAIGAKU_SHI_JIGAI_GK		INT, \
	TSENSYU_KO_KO_JI_GK			INT, \
	TSENSYU_KO_KO_JIGAI_GK		INT, \
	TSENSYU_KO_SHI_JI_GK		INT, \
	TSENSYU_KO_SHI_JIGAI_GK		INT, \
	TSENSYU_SEN_KO_JI_GK		INT, \
	TSENSYU_SEN_KO_JIGAI_GK		INT, \
	TSENSYU_SEN_SHI_JI_GK		INT, \
	TSENSYU_SEN_SHI_JIGAI_GK	INT, \
	TSHOUGAI_GK		     		INT, \
    REGISTERCD           	 VARCHAR(8), \
    UPDATED              	 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE NINTEIGK2_DAT ADD CONSTRAINT PK_NINTEIGK2_DAT PRIMARY KEY (YEAR)