-- $Id: ninteigk1_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE NINTEIGK1_DAT
CREATE TABLE NINTEIGK1_DAT( \
    YEAR          		VARCHAR(4)  NOT NULL, \
    SETAI_COUNT			SMALLINT    NOT NULL, \
	SHOTOKU_KIJYUN_GK	INT    		NOT NULL, \
    REGISTERCD          VARCHAR(8), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE NINTEIGK1_DAT ADD CONSTRAINT PK_NINTEIGK1_DAT PRIMARY KEY (YEAR, SETAI_COUNT)