-- $Id: school_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE SCHOOL_DAT
CREATE TABLE SCHOOL_DAT( \
    SCHOOLCD         VARCHAR(7)    NOT NULL, \
    SCHOOL_TYPE      VARCHAR(1), \
    SCHOOL_DISTCD    VARCHAR(4), \
    SCHOOL_DIV       VARCHAR(2), \
    NAME      		 VARCHAR(75), \
    KANA      		 VARCHAR(75), \
    NAME_ABBV 		 VARCHAR(75), \
    KANA_ABBV 		 VARCHAR(75), \
    DISTRICTCD       VARCHAR(2), \
    PREF_CD   		 VARCHAR(2), \
    CITYCD     		 VARCHAR(5), \
    ZIPCD     		 VARCHAR(8), \
    ADDR1     		 VARCHAR(150), \
    ADDR2     		 VARCHAR(150), \
    TELNO     		 VARCHAR(20), \
    FAXNO     		 VARCHAR(14), \
    EDBOARDCD        VARCHAR(6), \
    FU_NAIGAI_DIV	 VARCHAR(1), \
    FURITSU_DIV		 VARCHAR(1), \
    HAISHI_FLG		 VARCHAR(1), \
    ATENA_INSATSU_FLG VARCHAR(1), \
    REMARK			 VARCHAR(2400), \
    REGISTERCD       VARCHAR(8), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHOOL_DAT ADD CONSTRAINT PK_SCHOOL_DAT PRIMARY KEY (SCHOOLCD)
