-- $Id: school_katei_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE SCHOOL_KATEI_DAT
CREATE TABLE SCHOOL_KATEI_DAT( \
    SCHOOLCD         		VARCHAR(7)    NOT NULL, \
    KATEI      	 			VARCHAR(2)    NOT NULL, \
    REGISTERCD       		VARCHAR(8), \
    UPDATED          		TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHOOL_KATEI_DAT ADD CONSTRAINT PK_SCHOOL_K_DAT PRIMARY KEY (SCHOOLCD, KATEI)