-- $Id: shotoku_wari_gk_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE SHOTOKU_WARI_GK_DAT
CREATE TABLE SHOTOKU_WARI_GK_DAT( \
    YEAR                        VARCHAR(4)    NOT NULL, \
    HUYOU_COUNT                 SMALLINT      NOT NULL, \
    HUYOU_16_UNDER              SMALLINT      NOT NULL, \
    HUYOU_16_ANDOVER_19_UNDER   SMALLINT      NOT NULL, \
    SHOTOKU_WARI_GK             INT, \
    REGISTERCD                  VARCHAR(8), \
    UPDATED                     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SHOTOKU_WARI_GK_DAT ADD CONSTRAINT PK_SH_WARI_GK_D PRIMARY KEY (YEAR, HUYOU_COUNT, HUYOU_16_UNDER, HUYOU_16_ANDOVER_19_UNDER)