-- $Id: shuugaku_no_mst.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE SHUUGAKU_NO_MST
CREATE TABLE SHUUGAKU_NO_MST( \
    YEAR                     VARCHAR(4)    NOT NULL, \
    SHUUGAKU_DIV             VARCHAR(1)    NOT NULL, \
    SHUUGAKU_NO              VARCHAR(7)    NOT NULL, \
    REGISTERCD               VARCHAR(8), \
    UPDATED                  TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SHUUGAKU_NO_MST ADD CONSTRAINT PK_SHU_NO_MST PRIMARY KEY (YEAR, SHUUGAKU_DIV)