
DROP TABLE SOUFU_ADDRESS_DAT

CREATE TABLE SOUFU_ADDRESS_DAT ( \
    KOJIN_NO      VARCHAR(7) NOT NULL, \
    SHUUGAKU_NO   VARCHAR(7) NOT NULL, \
    ZIP_CD        VARCHAR(8), \
    CITY_CD    VARCHAR(5), \
    ADDR1    VARCHAR(150), \
    ADDR2    VARCHAR(150), \
    FAMILY_NAME    VARCHAR(60),  \
    FIRST_NAME    VARCHAR(60), \
    FAMILY_NAME_KANA    VARCHAR(60), \
    FIRST_NAME_KANA    VARCHAR(60), \
    REGISTERCD    VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SOUFU_ADDRESS_DAT ADD CONSTRAINT PK_SOUFU_ADDRESS_DAT \
 PRIMARY KEY (KOJIN_NO, SHUUGAKU_NO)
