-- $Id: taiyo_kasan1_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE TAIYO_KASAN1_DAT
CREATE TABLE TAIYO_KASAN1_DAT( \
    YEAR          		 	 VARCHAR(4)    NOT NULL, \
    SETAI_COUNT          	 SMALLINT      NOT NULL, \
    KYUUCHI_CD		 		 VARCHAR(1)	   NOT NULL, \
    KYUUCHI_KASAN_GK		 INT, \
    REGISTERCD           	 VARCHAR(8), \
    UPDATED              	 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE TAIYO_KASAN1_DAT ADD CONSTRAINT PK_T_KASAN1_DAT PRIMARY KEY (YEAR, SETAI_COUNT, KYUUCHI_CD)