-- $Id: taiyo_gendo_gk_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE TAIYO_GENDO_GK_DAT
CREATE TABLE TAIYO_GENDO_GK_DAT( \
    YEAR                     VARCHAR(4)    NOT NULL, \
    SHIKIN_SHUBETSU          VARCHAR(1)    NOT NULL, \
    SHOTOKUWARI_DIV          VARCHAR(1)    NOT NULL, \
    KOUSHI_DIV               VARCHAR(1)    NOT NULL, \
    KATEI_DIV                VARCHAR(1)    NOT NULL, \
    TSUUGAKU_DIV             VARCHAR(1)    NOT NULL, \
    GENDO_GK                 INT           NOT NULL, \
    REGISTERCD               VARCHAR(8), \
    UPDATED                  TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE TAIYO_GENDO_GK_DAT ADD CONSTRAINT PK_T_GENDO_GK_DAT PRIMARY KEY (YEAR, SHIKIN_SHUBETSU, SHOTOKUWARI_DIV, KOUSHI_DIV, KATEI_DIV, TSUUGAKU_DIV)