-- $Id: taiyo_kasan2_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE TAIYO_KASAN2_DAT
CREATE TABLE TAIYO_KASAN2_DAT( \
    YEAR          		 	 VARCHAR(4)    NOT NULL, \
    BOSHI_FUSHI_SETAI_GK     INT, \
    JUNIOR_UNDER_GK          INT, \
    SHOUGAISHA_GK		 	 INT, \
    ROUNENSHA_GK		 	 INT, \
    REGISTERCD           	 VARCHAR(8), \
    UPDATED              	 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE TAIYO_KASAN2_DAT ADD CONSTRAINT PK_T_KASAN2_DAT PRIMARY KEY (YEAR)