-- $Id: taiyo_setai_kijyun_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE TAIYO_SETAI_KIJYUN_DAT
CREATE TABLE TAIYO_SETAI_KIJYUN_DAT( \
    YEAR          		 	 VARCHAR(4)    NOT NULL, \
    SETAI_COUNT          	 SMALLINT      NOT NULL, \
    SETAI_KIJYUN_GK          INT, \
    REGISTERCD           	 VARCHAR(8), \
    UPDATED              	 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE TAIYO_SETAI_KIJYUN_DAT ADD CONSTRAINT PK_T_S_KIJYUN_DAT PRIMARY KEY (YEAR, SETAI_COUNT)