-- $Id: zipcd_mst.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP TABLE ZIPCD_MST
CREATE TABLE ZIPCD_MST( \
	ZIPNO			 VARCHAR(10) NOT NULL, \
	CITYCD			 VARCHAR(5), \
	OLD_ZIPCD		 VARCHAR(6), \
	NEW_ZIPCD		 VARCHAR(8), \
	PREF_KANA	     VARCHAR(75), \
	CITY_KANA		 VARCHAR(120), \
	TOWN_KANA		 VARCHAR(150), \
	PREF	     	 VARCHAR(75), \
	CITY			 VARCHAR(120), \
	TOWN			 VARCHAR(150), \
    REGISTERCD       VARCHAR(8), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ZIPCD_MST ADD CONSTRAINT PK_ZIPCD_MST PRIMARY KEY (ZIPNO)