-- kanji=Š¿Žš
-- $Id: 276048ac34b519af6e7bc9cbea4e9f7d0e3197b7 $

DROP VIEW V_ENTEXAM_APPLICANTBASE_TESTDIV_DAT

CREATE VIEW V_ENTEXAM_APPLICANTBASE_TESTDIV_DAT \
   (ENTEXAMYEAR, \
    APPLICANTDIV, \
    EXAMNO, \
    TESTDIV, \
    RECEPTNO, \
    EXAM_TYPE, \
    TESTSUBCLASSCD \
    ) \
AS \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK1 AS TESTDIV, \
        L2.REMARK1 AS RECEPTNO, \
        L1.REMARK1 AS EXAM_TYPE, \
        L3.REMARK1 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK1 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK2 AS TESTDIV, \
        L2.REMARK2 AS RECEPTNO, \
        L1.REMARK2 AS EXAM_TYPE, \
        L3.REMARK2 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK2 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK3 AS TESTDIV, \
        L2.REMARK3 AS RECEPTNO, \
        L1.REMARK3 AS EXAM_TYPE, \
        L3.REMARK3 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK3 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK4 AS TESTDIV, \
        L2.REMARK4 AS RECEPTNO, \
        L1.REMARK4 AS EXAM_TYPE, \
        L3.REMARK4 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK4 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK5 AS TESTDIV, \
        L2.REMARK5 AS RECEPTNO, \
        L1.REMARK5 AS EXAM_TYPE, \
        L3.REMARK5 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK5 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK6 AS TESTDIV, \
        L2.REMARK6 AS RECEPTNO, \
        L1.REMARK6 AS EXAM_TYPE, \
        L3.REMARK6 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK6 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK7 AS TESTDIV, \
        L2.REMARK7 AS RECEPTNO, \
        L1.REMARK7 AS EXAM_TYPE, \
        L3.REMARK7 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK7 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK8 AS TESTDIV, \
        L2.REMARK8 AS RECEPTNO, \
        L1.REMARK8 AS EXAM_TYPE, \
        L3.REMARK8 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK8 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK9 AS TESTDIV, \
        L2.REMARK9 AS RECEPTNO, \
        L1.REMARK9 AS EXAM_TYPE, \
        L3.REMARK9 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK9 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK10 AS TESTDIV, \
        L2.REMARK10 AS RECEPTNO, \
        L1.REMARK10 AS EXAM_TYPE, \
        L3.REMARK10 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK10 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK11 AS TESTDIV, \
        L2.REMARK11 AS RECEPTNO, \
        L1.REMARK11 AS EXAM_TYPE, \
        L3.REMARK11 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK11 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK12 AS TESTDIV, \
        L2.REMARK12 AS RECEPTNO, \
        L1.REMARK12 AS EXAM_TYPE, \
        L3.REMARK12 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK12 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK13 AS TESTDIV, \
        L2.REMARK13 AS RECEPTNO, \
        L1.REMARK13 AS EXAM_TYPE, \
        L3.REMARK13 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK13 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK14 AS TESTDIV, \
        L2.REMARK14 AS RECEPTNO, \
        L1.REMARK14 AS EXAM_TYPE, \
        L3.REMARK14 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK14 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK15 AS TESTDIV, \
        L2.REMARK15 AS RECEPTNO, \
        L1.REMARK15 AS EXAM_TYPE, \
        L3.REMARK15 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK15 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK16 AS TESTDIV, \
        L2.REMARK16 AS RECEPTNO, \
        L1.REMARK16 AS EXAM_TYPE, \
        L3.REMARK16 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK16 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK17 AS TESTDIV, \
        L2.REMARK17 AS RECEPTNO, \
        L1.REMARK17 AS EXAM_TYPE, \
        L3.REMARK17 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK17 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK18 AS TESTDIV, \
        L2.REMARK18 AS RECEPTNO, \
        L1.REMARK18 AS EXAM_TYPE, \
        L3.REMARK18 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK18 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK19 AS TESTDIV, \
        L2.REMARK19 AS RECEPTNO, \
        L1.REMARK19 AS EXAM_TYPE, \
        L3.REMARK19 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK19 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK20 AS TESTDIV, \
        L2.REMARK20 AS RECEPTNO, \
        L1.REMARK20 AS EXAM_TYPE, \
        L3.REMARK20 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK20 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK90 AS TESTDIV, \
        L2.REMARK90 AS RECEPTNO, \
        L1.REMARK90 AS EXAM_TYPE, \
        L3.REMARK90 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK90 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK91 AS TESTDIV, \
        L2.REMARK91 AS RECEPTNO, \
        L1.REMARK91 AS EXAM_TYPE, \
        L3.REMARK91 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK91 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK92 AS TESTDIV, \
        L2.REMARK92 AS RECEPTNO, \
        L1.REMARK92 AS EXAM_TYPE, \
        L3.REMARK92 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK92 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK93 AS TESTDIV, \
        L2.REMARK93 AS RECEPTNO, \
        L1.REMARK93 AS EXAM_TYPE, \
        L3.REMARK93 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK93 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK94 AS TESTDIV, \
        L2.REMARK94 AS RECEPTNO, \
        L1.REMARK94 AS EXAM_TYPE, \
        L3.REMARK94 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK94 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK95 AS TESTDIV, \
        L2.REMARK95 AS RECEPTNO, \
        L1.REMARK95 AS EXAM_TYPE, \
        L3.REMARK95 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK95 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK96 AS TESTDIV, \
        L2.REMARK96 AS RECEPTNO, \
        L1.REMARK96 AS EXAM_TYPE, \
        L3.REMARK96 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK96 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK97 AS TESTDIV, \
        L2.REMARK97 AS RECEPTNO, \
        L1.REMARK97 AS EXAM_TYPE, \
        L3.REMARK97 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK97 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK98 AS TESTDIV, \
        L2.REMARK98 AS RECEPTNO, \
        L1.REMARK98 AS EXAM_TYPE, \
        L3.REMARK98 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK98 IS NOT NULL \
    UNION ALL \
    SELECT \
        T1.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        T1.EXAMNO, \
        T1.REMARK99 AS TESTDIV, \
        L2.REMARK99 AS RECEPTNO, \
        L1.REMARK99 AS EXAM_TYPE, \
        L3.REMARK99 AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT T1 \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L1 \
                 ON L1.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L1.EXAMNO = T1.EXAMNO \
                AND L1.SEQ = '011' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L2 \
                 ON L2.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L2.EXAMNO = T1.EXAMNO \
                AND L2.SEQ = '012' \
        LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_BUN_DAT L3 \
                 ON L3.ENTEXAMYEAR = T1.ENTEXAMYEAR \
                AND L3.EXAMNO = T1.EXAMNO \
                AND L3.SEQ = '013' \
        INNER JOIN ENTEXAM_APPLICANTBASE_DAT BASE ON T1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
              AND T1.EXAMNO = BASE.EXAMNO \
              AND BASE.APPLICANTDIV = '1' \
    WHERE \
        T1.SEQ = '010' \
        AND T1.REMARK99 IS NOT NULL \
    UNION ALL \
    SELECT \
        BASE.ENTEXAMYEAR, \
        BASE.APPLICANTDIV, \
        BASE.EXAMNO, \
        L1.TESTDIV, \
        L1.RECEPTNO, \
        L1.EXAM_TYPE, \
        '' AS TESTSUBCLASSCD \
    FROM \
        ENTEXAM_APPLICANTBASE_DAT BASE \
        LEFT JOIN ENTEXAM_RECEPT_DAT L1 \
              ON L1.ENTEXAMYEAR = BASE.ENTEXAMYEAR \
             AND L1.APPLICANTDIV = BASE.APPLICANTDIV \
             AND L1.EXAM_TYPE = '1' \
             AND L1.EXAMNO = BASE.EXAMNO \
    WHERE \
        BASE.APPLICANTDIV = '2'
