-- $Id: 9c52a5903a50025a30f4897ae936d2b758c90bb5 $

DROP VIEW V_ENTEXAM_APPLICANTBASE_DAT

CREATE VIEW V_ENTEXAM_APPLICANTBASE_DAT ( \
    ENTEXAMYEAR, \
    APPLICANTDIV, \
    EXAMNO, \
    TESTDIV, \
    SHDIV, \
    DESIREDIV, \
    TESTDIV0, \
    TESTDIV1, \
    TESTDIV2, \
    TESTDIV3, \
    TESTDIV4, \
    TESTDIV5, \
    SPECIAL_REASON_DIV, \
    RECEPTDATE, \
    NAME, \
    NAME_KANA, \
    SEX, \
    ERACD, \
    BIRTH_Y, \
    BIRTH_M, \
    BIRTH_D, \
    BIRTHDAY, \
    FS_CD, \
    FS_NAME, \
    FS_AREA_CD, \
    FS_AREA_DIV, \
    FS_NATPUBPRIDIV, \
    FS_GRDYEAR, \
    FS_ERACD, \
    FS_Y, \
    FS_M, \
    FS_DAY, \
    FS_GRDDIV, \
    PRISCHOOLCD, \
    INTERVIEW_ATTEND_FLG, \
    SUC_COURSECD, \
    SUC_MAJORCD, \
    SUC_COURSECODE, \
    JUDGEMENT, \
    JUDGE_KIND, \
    SUB_ORDER, \
    SPECIAL_MEASURES, \
    PROCEDUREDIV, \
    PROCEDUREDATE, \
    PAY_MONEY, \
    ENTDIV, \
    HONORDIV, \
    SUCCESS_NOTICENO, \
    FAILURE_NOTICENO, \
    REMARK1, \
    REMARK2, \
    RECOM_EXAMNO, \
    PICTURE_ERACD, \
    PICTURE_Y, \
    PICTURE_M, \
    PICTURE_DAY, \
    SELECT_SUBCLASS_DIV, \
    SHIFT_DESIRE_FLG, \
    SH_SCHOOLCD, \
    SLIDE_FLG, \
    GENERAL_FLG, \
    SPORTS_FLG, \
    DORMITORY_FLG, \
    RECOM_ITEM1, \
    RECOM_ITEM2, \
    RECOM_ITEM3, \
    RECOM_ITEM4, \
    TOKUSIN, \
    SINGAKU1, \
    SINGAKU2, \
    SOUGOUGAKKA, \
    DAI1_COURSECD, \
    DAI1_MAJORCD, \
    DAI1_COURSECODE, \
    GANHEN_DAI1_COURSECD, \
    GANHEN_DAI1_MAJORCD, \
    GANHEN_DAI1_COURSECODE, \
    LAST_DAI1_COURSECD, \
    LAST_DAI1_MAJORCD, \
    LAST_DAI1_COURSECODE, \
    PAGE, \
    RENBAN, \
    JIZEN_BANGOU, \
    SAT_GROUPCD, \
    SENBATU1_GOUKAKU, \
    PUBLIC_TEST_NO, \
    CLUB_NAME, \
    SUISEN_RIYUU, \
    JITSURYOKU1, \
    JITSURYOKU2, \
    KAKUYAKU_KUBUN, \
    JIZEN_SOUDAN_CD, \
    JIZEN_SOUDAN_TEXT, \
    DAI1_SIBOU_CHK, \
    ZAIKOU_HOGOSYA_NAME, \
    ZAISEKI_CLASS, \
    HEIGAN_YOTEI, \
    SH_SCHOOLCD1, \
    SH_SCHOOLCD2, \
    SH_SCHOOLCD3, \
    SH_SCHOOLCD4, \
    SH_GAKKAMEI1, \
    SH_GAKKAMEI2, \
    SH_GAKKAMEI3, \
    SH_GAKKAMEI4, \
    YONENSEI_DAIGAKU, \
    TANKI_DAIGAKU, \
    SENMON_GAKKOU, \
    SYUUSYOKU, \
    SONOTA, \
    ONGAKU1, \
    BIJUTSU1, \
    SYODOU1, \
    ENT_COURSECD, \
    ENT_MAJORCD, \
    ENT_COURSECODE, \
    JUKUCD, \
    KYOUSHITSU_NAME, \
    KYOUSHITSU_CD, \
    KYOUIKU_SYOUGAKUSEI, \
    FUTOUKOU, \
    SYOZAITI_MAWASI, \
    SIKAKU_HYOUSYOU, \
    JUKU_NADO, \
    KETTEI_SYOUGAKUSEI, \
    KYOUIKU_SYOUGAKUSEI_CD, \
    KETTEI_SYOUGAKUSEI_CD, \
    KYOUIKU_JADGE, \
    DAI1_TESTDIV, \
    DAI2_TESTDIV, \
    DAI3_TESTDIV, \
    DAI4_TESTDIV, \
    DAI5_TESTDIV, \
    DAI1_KIKOKU_TESTDIV, \
    DAI2_KIKOKU_TESTDIV, \
    DAI1_EXAM_TYPE, \
    DAI2_EXAM_TYPE, \
    DAI3_EXAM_TYPE, \
    DAI4_EXAM_TYPE, \
    DAI5_EXAM_TYPE, \
    DAI1_KIKOKU_EXAM_TYPE, \
    DAI2_KIKOKU_EXAM_TYPE, \
    DAI1_RECEPTNO, \
    DAI2_RECEPTNO, \
    DAI3_RECEPTNO, \
    DAI4_RECEPTNO, \
    DAI5_RECEPTNO, \
    DAI1_KIKOKU_RECEPTNO, \
    DAI2_KIKOKU_RECEPTNO, \
    DAI1_KIKOKU_SENTAKU, \
    DAI2_KIKOKU_SENTAKU, \
    SIMAI_SCHOOL_KIND1, \
    SIMAI_NAME1, \
    SIMAI_SCHOOL_KIND2, \
    SIMAI_NAME2, \
    SIMAI_DIV, \
    SIMAI_NAME, \
    SIMAI_KOUSYU, \
    SIMAI_GRADE, \
    SIMAI_HR_CLASS, \
    HAHA_KYUSEI, \
    HAHA_GRDYEAR, \
    HAHA_HR_CLASS, \
    HAHA_BIRTHDAY, \
    HEIGANKOU, \
    HEIGANKOU_GOUKAKU_HAPPYOUBI, \
    DAI2_COURSECD, \
    DAI2_MAJORCD, \
    DAI2_COURSECODE, \
    DAI2_SENPEIDIV, \
    GANHEN_DAI2_COURSECD, \
    GANHEN_DAI2_MAJORCD, \
    GANHEN_DAI2_COURSECODE, \
    LAST_DAI2_COURSECD, \
    LAST_DAI2_MAJORCD, \
    LAST_DAI2_COURSECODE, \
    SINZOKU_NAME, \
    SINZOKU_KYUSEI, \
    SINZOKU_ZOKUGARA, \
    SINZOKU_GAKKOUMEI, \
    SINZOKU_GAKKA, \
    SINZOKU_ZAI_GRD_YEAR, \
    SINZOKU_ZAI_GRD_FLG, \
    SINZOKU_FUTAGO_NAME, \
    SINZOKU_FUTAGO_ZOKUGARA, \
    CLUB_CD, \
    CLUB_RANK, \
    HOPE_CLUB_CD, \
    JITURYOKU_KOKUGO, \
    JITURYOKU_EIGO, \
    JITURYOKU_SUUGAKU, \
    JITURYOKU_TOTAL, \
    MOGI_HENSATI, \
    OBOEGAKI_SIGANSYA, \
    KAIGAI_KIKOKUSEI_NADO, \
    TUUGAKU_KUIKIGAI_KYOKA, \
    BOSHUU_KYOUGI, \
    HOSHOUNIN_TODOKE, \
    KENGAI_ZAIJUU, \
    KENGAI_HOSHOUNIN_ZAIJUU, \
    KENGAI_CHUUGAKKOU_SHUSSHIN, \
    NYUUGAKU_SIGAN_KYOKA, \
    KENGAI_CHUUGAKKOU_SHUSSHIN2, \
    NYUUGAKU_JITAIBI, \
    SCHOLAR_KIBOU, \
    SCHOLAR_SAIYOU, \
    SCHOLAR_TOUKYU_SENGAN, \
    SCHOLAR_TOUKYU_HEIGAN, \
    SIKEN_KAIJOU_CD1, \
    SIKEN_KAIJOU_CD2 \
) AS \
SELECT \
    BASE.ENTEXAMYEAR, \
    BASE.APPLICANTDIV, \
    BASE.EXAMNO, \
    BASE.TESTDIV, \
    BASE.SHDIV, \
    BASE.DESIREDIV, \
    BASE.TESTDIV0, \
    BASE.TESTDIV1, \
    BASE.TESTDIV2, \
    BASE.TESTDIV3, \
    BASE.TESTDIV4, \
    BASE.TESTDIV5, \
    BASE.SPECIAL_REASON_DIV, \
    BASE.RECEPTDATE, \
    BASE.NAME, \
    BASE.NAME_KANA, \
    BASE.SEX, \
    BASE.ERACD, \
    BASE.BIRTH_Y, \
    BASE.BIRTH_M, \
    BASE.BIRTH_D, \
    BASE.BIRTHDAY, \
    BASE.FS_CD, \
    BASE.FS_NAME, \
    BASE.FS_AREA_CD, \
    BASE.FS_AREA_DIV, \
    BASE.FS_NATPUBPRIDIV, \
    BASE.FS_GRDYEAR, \
    BASE.FS_ERACD, \
    BASE.FS_Y, \
    BASE.FS_M, \
    BASE.FS_DAY, \
    BASE.FS_GRDDIV, \
    BASE.PRISCHOOLCD, \
    BASE.INTERVIEW_ATTEND_FLG, \
    BASE.SUC_COURSECD, \
    BASE.SUC_MAJORCD, \
    BASE.SUC_COURSECODE, \
    BASE.JUDGEMENT, \
    BASE.JUDGE_KIND, \
    BASE.SUB_ORDER, \
    BASE.SPECIAL_MEASURES, \
    BASE.PROCEDUREDIV, \
    BASE.PROCEDUREDATE, \
    BASE.PAY_MONEY, \
    BASE.ENTDIV, \
    BASE.HONORDIV, \
    BASE.SUCCESS_NOTICENO, \
    BASE.FAILURE_NOTICENO, \
    BASE.REMARK1, \
    BASE.REMARK2, \
    BASE.RECOM_EXAMNO, \
    BASE.PICTURE_ERACD, \
    BASE.PICTURE_Y, \
    BASE.PICTURE_M, \
    BASE.PICTURE_DAY, \
    BASE.SELECT_SUBCLASS_DIV, \
    BASE.SHIFT_DESIRE_FLG, \
    BASE.SH_SCHOOLCD, \
    BASE.SLIDE_FLG, \
    BASE.GENERAL_FLG, \
    BASE.SPORTS_FLG, \
    BASE.DORMITORY_FLG, \
    BASE.RECOM_ITEM1, \
    BASE.RECOM_ITEM2, \
    BASE.RECOM_ITEM3, \
    BASE.RECOM_ITEM4, \
    SEQ001.REMARK1  AS TOKUSIN, \
    SEQ001.REMARK2  AS SINGAKU1, \
    SEQ001.REMARK3  AS SINGAKU2, \
    SEQ001.REMARK4  AS SOUGOUGAKKA, \
    SEQ001.REMARK8  AS DAI1_COURSECD, \
    SEQ001.REMARK9  AS DAI1_MAJORCD, \
    SEQ001.REMARK10 AS DAI1_COURSECODE, \
    SEQ001.REMARK5  AS GANHEN_DAI1_COURSECD, \
    SEQ001.REMARK6  AS GANHEN_DAI1_MAJORCD, \
    SEQ001.REMARK7  AS GANHEN_DAI1_COURSECODE, \
    SEQ001.REMARK8  AS LAST_DAI1_COURSECD, \
    SEQ001.REMARK9  AS LAST_DAI1_MAJORCD, \
    SEQ001.REMARK10 AS LAST_DAI1_COURSECODE, \
    SEQ002.REMARK1  AS PAGE, \
    SEQ002.REMARK2  AS RENBAN, \
    SEQ002.REMARK1  AS JIZEN_BANGOU, \
    SEQ002.REMARK3  AS SAT_GROUPCD, \
    SEQ003.REMARK1  AS SENBATU1_GOUKAKU, \
    SEQ003.REMARK1  AS PUBLIC_TEST_NO, \
    SEQ004.REMARK1  AS CLUB_NAME, \
    SEQ004.REMARK2  AS SUISEN_RIYUU, \
    SEQ004.REMARK3  AS JITSURYOKU1, \
    SEQ004.REMARK4  AS JITSURYOKU2, \
    SEQ004.REMARK8  AS KAKUYAKU_KUBUN, \
    SEQ004.REMARK9  AS JIZEN_SOUDAN_CD, \
    SEQ004.REMARK10 AS JIZEN_SOUDAN_TEXT, \
    SEQ005.REMARK1  AS DAI1_SIBOU_CHK, \
    SEQ005.REMARK2  AS ZAIKOU_HOGOSYA_NAME, \
    SEQ005.REMARK3  AS ZAISEKI_CLASS, \
    SEQ005.REMARK4  AS HEIGAN_YOTEI, \
    SEQ005.REMARK1  AS SH_SCHOOLCD1, \
    SEQ005.REMARK2  AS SH_SCHOOLCD2, \
    SEQ005.REMARK3  AS SH_SCHOOLCD3, \
    SEQ005.REMARK4  AS SH_SCHOOLCD4, \
    SEQ005.REMARK5  AS SH_GAKKAMEI1, \
    SEQ005.REMARK6  AS SH_GAKKAMEI2, \
    SEQ005.REMARK7  AS SH_GAKKAMEI3, \
    SEQ005.REMARK8  AS SH_GAKKAMEI4, \
    SEQ006.REMARK1  AS YONENSEI_DAIGAKU, \
    SEQ006.REMARK2  AS TANKI_DAIGAKU, \
    SEQ006.REMARK3  AS SENMON_GAKKOU, \
    SEQ006.REMARK4  AS SYUUSYOKU, \
    SEQ006.REMARK5  AS SONOTA, \
    SEQ006.REMARK6  AS ONGAKU1, \
    SEQ006.REMARK7  AS BIJUTSU1, \
    SEQ006.REMARK8  AS SYODOU1, \
    SEQ007.REMARK1  AS ENT_COURSECD, \
    SEQ007.REMARK2  AS ENT_MAJORCD, \
    SEQ007.REMARK3  AS ENT_COURSECODE, \
    SEQ008.REMARK1  AS JUKUCD, \
    SEQ008.REMARK2  AS KYOUSHITSU_NAME, \
    SEQ008.REMARK3  AS KYOUSHITSU_CD, \
    SEQ009.REMARK1  AS KYOUIKU_SYOUGAKUSEI, \
    SEQ009.REMARK2  AS FUTOUKOU, \
    SEQ009.REMARK3  AS SYOZAITI_MAWASI, \
    SEQ009.REMARK4  AS SIKAKU_HYOUSYOU, \
    SEQ009.REMARK5  AS JUKU_NADO, \
    SEQ009.REMARK6  AS KETTEI_SYOUGAKUSEI, \
    SEQ009.REMARK7  AS KYOUIKU_SYOUGAKUSEI_CD, \
    SEQ009.REMARK8  AS KETTEI_SYOUGAKUSEI_CD, \
    SEQ009.REMARK9  AS KYOUIKU_JADGE, \
    SEQ010.REMARK1  AS DAI1_TESTDIV, \
    SEQ010.REMARK2  AS DAI2_TESTDIV, \
    SEQ010.REMARK3  AS DAI3_TESTDIV, \
    SEQ010.REMARK4  AS DAI4_TESTDIV, \
    SEQ010.REMARK5  AS DAI5_TESTDIV, \
    SEQ010.REMARK6  AS DAI1_KIKOKU_TESTDIV, \
    SEQ010.REMARK7  AS DAI2_KIKOKU_TESTDIV, \
    SEQ011.REMARK1  AS DAI1_EXAM_TYPE, \
    SEQ011.REMARK2  AS DAI2_EXAM_TYPE, \
    SEQ011.REMARK3  AS DAI3_EXAM_TYPE, \
    SEQ011.REMARK4  AS DAI4_EXAM_TYPE, \
    SEQ011.REMARK5  AS DAI5_EXAM_TYPE, \
    SEQ011.REMARK6  AS DAI1_KIKOKU_EXAM_TYPE, \
    SEQ011.REMARK7  AS DAI2_KIKOKU_EXAM_TYPE, \
    SEQ012.REMARK1  AS DAI1_RECEPTNO, \
    SEQ012.REMARK2  AS DAI2_RECEPTNO, \
    SEQ012.REMARK3  AS DAI3_RECEPTNO, \
    SEQ012.REMARK4  AS DAI4_RECEPTNO, \
    SEQ012.REMARK5  AS DAI5_RECEPTNO, \
    SEQ012.REMARK6  AS DAI1_KIKOKU_RECEPTNO, \
    SEQ012.REMARK7  AS DAI2_KIKOKU_RECEPTNO, \
    SEQ013.REMARK6  AS DAI1_KIKOKU_SENTAKU, \
    SEQ013.REMARK7  AS DAI2_KIKOKU_SENTAKU, \
    SEQ014.REMARK1  AS SIMAI_SCHOOL_KIND1, \
    SEQ014.REMARK2  AS SIMAI_NAME1, \
    SEQ014.REMARK3  AS SIMAI_SCHOOL_KIND2, \
    SEQ014.REMARK4  AS SIMAI_NAME2, \
    SEQ014.REMARK1  AS SIMAI_DIV, \
    SEQ014.REMARK2  AS SIMAI_NAME, \
    SEQ014.REMARK3  AS SIMAI_KOUSYU, \
    SEQ014.REMARK4  AS SIMAI_GRADE, \
    SEQ014.REMARK5  AS SIMAI_HR_CLASS, \
    SEQ015.REMARK1  AS HAHA_KYUSEI, \
    SEQ015.REMARK2  AS HAHA_GRDYEAR, \
    SEQ015.REMARK3  AS HAHA_HR_CLASS, \
    SEQ015.REMARK4  AS HAHA_BIRTHDAY, \
    SEQ016.REMARK1  AS HEIGANKOU, \
    SEQ016.REMARK2  AS HEIGANKOU_GOUKAKU_HAPPYOUBI, \
    SEQ017.REMARK1  AS DAI2_COURSECD, \
    SEQ017.REMARK2  AS DAI2_MAJORCD, \
    SEQ017.REMARK3  AS DAI2_COURSECODE, \
    SEQ017.REMARK4  AS DAI2_SENPEIDIV, \
    SEQ017.REMARK5  AS GANHEN_DAI2_COURSECD, \
    SEQ017.REMARK6  AS GANHEN_DAI2_MAJORCD, \
    SEQ017.REMARK7  AS GANHEN_DAI2_COURSECODE, \
    SEQ017.REMARK1  AS LAST_DAI2_COURSECD, \
    SEQ017.REMARK2  AS LAST_DAI2_MAJORCD, \
    SEQ017.REMARK3  AS LAST_DAI2_COURSECODE, \
    SEQ018.REMARK1  AS SINZOKU_NAME, \
    SEQ018.REMARK2  AS SINZOKU_KYUSEI, \
    SEQ018.REMARK3  AS SINZOKU_ZOKUGARA, \
    SEQ018.REMARK4  AS SINZOKU_GAKKOUMEI, \
    SEQ018.REMARK5  AS SINZOKU_GAKKA, \
    SEQ018.REMARK6  AS SINZOKU_ZAI_GRD_YEAR, \
    SEQ018.REMARK7  AS SINZOKU_ZAI_GRD_FLG, \
    SEQ018.REMARK8  AS SINZOKU_FUTAGO_NAME, \
    SEQ018.REMARK9  AS SINZOKU_FUTAGO_ZOKUGARA, \
    SEQ019.REMARK1  AS CLUB_CD, \
    SEQ019.REMARK2  AS CLUB_RANK, \
    SEQ019.REMARK3  AS HOPE_CLUB_CD, \
    SEQ020.REMARK1  AS JITURYOKU_KOKUGO, \
    SEQ020.REMARK2  AS JITURYOKU_EIGO, \
    SEQ020.REMARK3  AS JITURYOKU_SUUGAKU, \
    SEQ020.REMARK4  AS JITURYOKU_TOTAL, \
    SEQ020.REMARK5  AS MOGI_HENSATI, \
    SEQ021.REMARK1  AS OBOEGAKI_SIGANSYA, \
    SEQ021.REMARK2  AS KAIGAI_KIKOKUSEI_NADO, \
    SEQ021.REMARK3  AS TUUGAKU_KUIKIGAI_KYOKA, \
    SEQ021.REMARK4  AS BOSHUU_KYOUGI, \
    SEQ021.REMARK5  AS HOSHOUNIN_TODOKE, \
    SEQ021.REMARK6  AS KENGAI_ZAIJUU, \
    SEQ021.REMARK7  AS KENGAI_HOSHOUNIN_ZAIJUU, \
    SEQ021.REMARK8  AS KENGAI_CHUUGAKKOU_SHUSSHIN, \
    SEQ021.REMARK9  AS NYUUGAKU_SIGAN_KYOKA, \
    SEQ021.REMARK10 AS KENGAI_CHUUGAKKOU_SHUSSHIN2, \
    SEQ022.REMARK1  AS NYUUGAKU_JITAIBI, \
    SEQ023.REMARK1  AS SCHOLAR_KIBOU, \
    SEQ023.REMARK2  AS SCHOLAR_SAIYOU, \
    SEQ023.REMARK3  AS SCHOLAR_TOUKYU_SENGAN, \
    SEQ023.REMARK4  AS SCHOLAR_TOUKYU_HEIGAN, \
    SEQ024.REMARK1  AS SIKEN_KAIJOU_CD1, \
    SEQ024.REMARK2  AS SIKEN_KAIJOU_CD2 \
FROM \
    ENTEXAM_APPLICANTBASE_DAT BASE \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ001 ON BASE.ENTEXAMYEAR = SEQ001.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ001.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ001.EXAMNO \
         AND SEQ001.SEQ = '001' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ002 ON BASE.ENTEXAMYEAR = SEQ002.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ002.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ002.EXAMNO \
         AND SEQ002.SEQ = '002' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ003 ON BASE.ENTEXAMYEAR = SEQ003.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ003.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ003.EXAMNO \
         AND SEQ003.SEQ = '003' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ004 ON BASE.ENTEXAMYEAR = SEQ004.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ004.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ004.EXAMNO \
         AND SEQ004.SEQ = '004' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ005 ON BASE.ENTEXAMYEAR = SEQ005.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ005.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ005.EXAMNO \
         AND SEQ005.SEQ = '005' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ006 ON BASE.ENTEXAMYEAR = SEQ006.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ006.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ006.EXAMNO \
         AND SEQ006.SEQ = '006' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ007 ON BASE.ENTEXAMYEAR = SEQ007.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ007.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ007.EXAMNO \
         AND SEQ007.SEQ = '007' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ008 ON BASE.ENTEXAMYEAR = SEQ008.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ008.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ008.EXAMNO \
         AND SEQ008.SEQ = '008' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ009 ON BASE.ENTEXAMYEAR = SEQ009.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ009.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ009.EXAMNO \
         AND SEQ009.SEQ = '009' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ010 ON BASE.ENTEXAMYEAR = SEQ010.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ010.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ010.EXAMNO \
         AND SEQ010.SEQ = '010' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ011 ON BASE.ENTEXAMYEAR = SEQ011.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ011.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ011.EXAMNO \
         AND SEQ011.SEQ = '011' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ012 ON BASE.ENTEXAMYEAR = SEQ012.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ012.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ012.EXAMNO \
         AND SEQ012.SEQ = '012' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ013 ON BASE.ENTEXAMYEAR = SEQ013.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ013.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ013.EXAMNO \
         AND SEQ013.SEQ = '013' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ014 ON BASE.ENTEXAMYEAR = SEQ014.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ014.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ014.EXAMNO \
         AND SEQ014.SEQ = '014' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ015 ON BASE.ENTEXAMYEAR = SEQ015.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ015.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ015.EXAMNO \
         AND SEQ015.SEQ = '015' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ016 ON BASE.ENTEXAMYEAR = SEQ016.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ016.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ016.EXAMNO \
         AND SEQ016.SEQ = '016' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ017 ON BASE.ENTEXAMYEAR = SEQ017.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ017.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ017.EXAMNO \
         AND SEQ017.SEQ = '017' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ018 ON BASE.ENTEXAMYEAR = SEQ018.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ018.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ018.EXAMNO \
         AND SEQ018.SEQ = '018' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ019 ON BASE.ENTEXAMYEAR = SEQ019.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ019.APPLICANTDIV \
         AND BASE.APPLICANTDIV = SEQ019.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ019.EXAMNO \
         AND SEQ019.SEQ = '019' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ020 ON BASE.ENTEXAMYEAR = SEQ020.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ020.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ020.EXAMNO \
         AND SEQ020.SEQ = '020' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ021 ON BASE.ENTEXAMYEAR = SEQ021.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ021.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ021.EXAMNO \
         AND SEQ021.SEQ = '021' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ022 ON BASE.ENTEXAMYEAR = SEQ022.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ022.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ022.EXAMNO \
         AND SEQ022.SEQ = '022' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ023 ON BASE.ENTEXAMYEAR = SEQ023.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ023.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ023.EXAMNO \
         AND SEQ023.SEQ = '023' \
    LEFT JOIN ENTEXAM_APPLICANTBASE_DETAIL_DAT SEQ024 ON BASE.ENTEXAMYEAR = SEQ024.ENTEXAMYEAR \
         AND BASE.APPLICANTDIV = SEQ024.APPLICANTDIV \
         AND BASE.EXAMNO = SEQ024.EXAMNO \
         AND SEQ024.SEQ = '024'
