DROP TABLE SCHREG_RECOMMENDATION_WISH_DAT_OLD
RENAME TABLE SCHREG_RECOMMENDATION_WISH_DAT TO SCHREG_RECOMMENDATION_WISH_DAT_OLD
CREATE TABLE SCHREG_RECOMMENDATION_WISH_DAT( \
    YEAR               VARCHAR(4)    NOT NULL, \
    SCHREGNO           VARCHAR(8)    NOT NULL, \
    WISH_RANK          VARCHAR(2)    NOT NULL, \
    SCHOOL_CD          VARCHAR(8)    NOT NULL, \
    BU_CD              VARCHAR(2), \
    KA_CD              VARCHAR(1), \
    RECOMMENDATION_FLG VARCHAR(1), \
    REGISTERCD         VARCHAR(8), \
    UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SCHREG_RECOMMENDATION_WISH_DAT \
    SELECT \
        YEAR, \
        SCHREGNO, \
        WISH_RANK, \
        SCHOOL_CD, \
        BU_CD, \
        KA_CD, \
        RECOMMENDATION_FLG, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SCHREG_RECOMMENDATION_WISH_DAT_OLD

ALTER TABLE SCHREG_RECOMMENDATION_WISH_DAT ADD CONSTRAINT PK_SCHREG_REC_WISH PRIMARY KEY (YEAR,SCHREGNO,WISH_RANK)