-- $Id: $

ALTER TABLE ENTEXAM_STD_APPLICANTBASE_DAT ALTER COLUMN NAME SET DATA TYPE VARCHAR(120)
ALTER TABLE ENTEXAM_STD_APPLICANTBASE_DAT ALTER COLUMN NAME_KANA SET DATA TYPE VARCHAR(240)
REORG TABLE ENTEXAM_STD_APPLICANTBASE_DAT
