-- $Id: rep-schreg_studyrec_replace_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE SCHREG_STUDYREC_REPLACE_DAT_OLD
CREATE TABLE SCHREG_STUDYREC_REPLACE_DAT_OLD LIKE SCHREG_STUDYREC_REPLACE_DAT
INSERT INTO SCHREG_STUDYREC_REPLACE_DAT_OLD SELECT * FROM SCHREG_STUDYREC_REPLACE_DAT

DROP TABLE SCHREG_STUDYREC_REPLACE_DAT

CREATE TABLE SCHREG_STUDYREC_REPLACE_DAT ( \
    SCHOOLCD            VARCHAR(1)    NOT NULL, \
    YEAR                VARCHAR(4)    NOT NULL, \
    SCHREGNO            VARCHAR(8)    NOT NULL, \
    ANNUAL              VARCHAR(2)    NOT NULL, \
    CLASSCD             VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND         VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD       VARCHAR(2)    NOT NULL, \
    SUBCLASSCD          VARCHAR(6)    NOT NULL, \
    CLASSCD_SAKI        VARCHAR(2), \
    SCHOOL_KIND_SAKI    VARCHAR(2), \
    CURRICULUM_CD_SAKI  VARCHAR(2), \
    SUBCLASSCD_SAKI     VARCHAR(6), \
    FORMER_REG_SCHOOLCD VARCHAR(12), \
    VALUATION           SMALLINT, \
    GET_CREDIT          SMALLINT, \
    ADD_CREDIT          SMALLINT, \
    COMP_CREDIT         SMALLINT, \
    PRINT_FLG           VARCHAR(1), \
    GET_DATE            DATE, \
    REMARK              VARCHAR(90), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_STUDYREC_REPLACE_DAT ADD CONSTRAINT PK_SCHRG_STUDY_REP PRIMARY KEY (SCHOOLCD,YEAR,SCHREGNO,ANNUAL,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)

INSERT INTO SCHREG_STUDYREC_REPLACE_DAT \
SELECT \
    * \
FROM SCHREG_STUDYREC_REPLACE_DAT_OLD
