-- $Id: 68934c12c02e23376708d4c7a18852ce55208f08 $

DROP TABLE ENTEXAM_INTERVIEW_DAT

CREATE TABLE ENTEXAM_INTERVIEW_DAT( \
    ENTEXAMYEAR               VARCHAR(4)    NOT NULL, \
    APPLICANTDIV              VARCHAR(1)    NOT NULL, \
    TESTDIV                   VARCHAR(1)    NOT NULL, \
    EXAMNO                    VARCHAR(10)   NOT NULL, \
    INTERVIEW_REMARK          VARCHAR(210), \
    INTERVIEW_VALUE           VARCHAR(1), \
    COMPOSITION_VALUE         VARCHAR(1), \
    INTERVIEW_A               VARCHAR(1), \
    INTERVIEW_B               VARCHAR(1), \
    INTERVIEW_C               VARCHAR(1), \
    INTERVIEW_REMARK2         VARCHAR(210), \
    INTERVIEW_VALUE2          VARCHAR(1), \
    INTERVIEW_REMARK3         VARCHAR(210), \
    ATTEND_FLG                VARCHAR(1), \
    SCORE                     SMALLINT, \
    STD_SCORE                 DECIMAL(4,1), \
    SCORE1                    SMALLINT, \
    SCORE2                    SMALLINT, \
    REGISTERCD                VARCHAR(10), \
    UPDATED                   TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_INTERVIEW_DAT ADD CONSTRAINT PK_ENTEXAM_INTERVI PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,EXAMNO)