-- $Id: 3b5dbb56214b0f0390df25ddccd41db9e1c90d7c $

DROP TABLE ENTEXAM_JISSEKI_DAT

CREATE TABLE ENTEXAM_JISSEKI_DAT( \
    ENTEXAMYEAR         VARCHAR(4)    NOT NULL, \
    APPLICANTDIV        VARCHAR(1)    NOT NULL, \
    TESTDIV             VARCHAR(1)    NOT NULL, \
    EXAMNO              VARCHAR(10)   NOT NULL, \
    SCORE               SMALLINT, \
    REMARK1             VARCHAR(750), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_JISSEKI_DAT ADD CONSTRAINT PK_ENTEXAM_JISSEKI PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,EXAMNO)
