-- $Id: rep-entexam_applicantaddr_dat.sql 63855 2018-12-10 06:31:23Z tawada $

DROP TABLE ENTEXAM_APPLICANTADDR_DAT_OLD

create table ENTEXAM_APPLICANTADDR_DAT_OLD like ENTEXAM_APPLICANTADDR_DAT

insert into ENTEXAM_APPLICANTADDR_DAT_OLD select * from ENTEXAM_APPLICANTADDR_DAT

drop table ENTEXAM_APPLICANTADDR_DAT

CREATE TABLE ENTEXAM_APPLICANTADDR_DAT( \
    ENTEXAMYEAR         VARCHAR(4)  NOT NULL, \
    APPLICANTDIV        VARCHAR(1)  NOT NULL, \
    EXAMNO              VARCHAR(5)  NOT NULL, \
    FAMILY_REGISTER     VARCHAR(2), \
    ZIPCD               VARCHAR(8), \
    PREF_CD             VARCHAR(2), \
    ADDRESS1            VARCHAR(150), \
    ADDRESS2            VARCHAR(150), \
    TELNO               VARCHAR(14), \
    GNAME               VARCHAR(60), \
    GKANA               VARCHAR(120), \
    GZIPCD              VARCHAR(8), \
    GPREF_CD            VARCHAR(2), \
    GADDRESS1           VARCHAR(150), \
    GADDRESS2           VARCHAR(150), \
    GTELNO              VARCHAR(14), \
    GFAXNO              VARCHAR(14), \
    RELATIONSHIP        VARCHAR(2), \
    EMERGENCYCALL       VARCHAR(30), \
    EMERGENCYTELNO      VARCHAR(14), \
    REGISTERCD          VARCHAR(10),  \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_APPLICANTADDR_DAT ADD CONSTRAINT PK_ENTEXAM_ADDR PRIMARY KEY (ENTEXAMYEAR, APPLICANTDIV, EXAMNO)

INSERT INTO ENTEXAM_APPLICANTADDR_DAT \
 SELECT \
    ENTEXAMYEAR, \
    '1' as APPLICANTDIV, \
    EXAMNO, \
    FAMILY_REGISTER, \
    ZIPCD, \
    PREF_CD, \
    ADDRESS1, \
    ADDRESS2, \
    TELNO, \
    GNAME, \
    GKANA, \
    GZIPCD, \
    GPREF_CD, \
    GADDRESS1, \
    GADDRESS2, \
    GTELNO, \
    GFAXNO, \
    RELATIONSHIP, \
    EMERGENCYCALL, \
    EMERGENCYTELNO, \
    REGISTERCD, \
    UPDATED \
 FROM \
    ENTEXAM_APPLICANTADDR_DAT_OLD
