-- $Id: rep-entexam_applicantconfrpt_dat.sql 63855 2018-12-10 06:31:23Z tawada $

DROP TABLE ENTEXAM_APPLICANTCONFRPT_DAT_OLD

create table ENTEXAM_APPLICANTCONFRPT_DAT_OLD like ENTEXAM_APPLICANTCONFRPT_DAT

insert into ENTEXAM_APPLICANTCONFRPT_DAT_OLD select * from ENTEXAM_APPLICANTCONFRPT_DAT

drop table ENTEXAM_APPLICANTCONFRPT_DAT

CREATE TABLE ENTEXAM_APPLICANTCONFRPT_DAT( \
    ENTEXAMYEAR        VARCHAR(4)    NOT NULL, \
    APPLICANTDIV       VARCHAR(1)    NOT NULL, \
    EXAMNO             VARCHAR(5)    NOT NULL, \
    CONFIDENTIAL_RPT01 SMALLINT, \
    CONFIDENTIAL_RPT02 SMALLINT, \
    CONFIDENTIAL_RPT03 SMALLINT, \
    CONFIDENTIAL_RPT04 SMALLINT, \
    CONFIDENTIAL_RPT05 SMALLINT, \
    CONFIDENTIAL_RPT06 SMALLINT, \
    CONFIDENTIAL_RPT07 SMALLINT, \
    CONFIDENTIAL_RPT08 SMALLINT, \
    CONFIDENTIAL_RPT09 SMALLINT, \
    CONFIDENTIAL_RPT10 SMALLINT, \
    CONFIDENTIAL_RPT11 SMALLINT, \
    CONFIDENTIAL_RPT12 SMALLINT, \
    ABSENCE_DAYS       SMALLINT, \
    ABSENCE_DAYS2      SMALLINT, \
    ABSENCE_DAYS3      SMALLINT, \
    AVERAGE3           DECIMAL(4,1), \
    AVERAGE5           DECIMAL(4,1), \
    AVERAGE_ALL        DECIMAL(4,1), \
    TOTAL3             SMALLINT, \
    TOTAL5             SMALLINT, \
    TOTAL_ALL          SMALLINT, \
    KASANTEN_ALL       SMALLINT, \
    REGISTERCD         VARCHAR(10), \
    UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO ENTEXAM_APPLICANTCONFRPT_DAT \
    SELECT \
        ENTEXAMYEAR, \
        '1' as APPLICANTDIV, \
        EXAMNO, \
        CONFIDENTIAL_RPT01, \
        CONFIDENTIAL_RPT02, \
        CONFIDENTIAL_RPT03, \
        CONFIDENTIAL_RPT04, \
        CONFIDENTIAL_RPT05, \
        CONFIDENTIAL_RPT06, \
        CONFIDENTIAL_RPT07, \
        CONFIDENTIAL_RPT08, \
        CONFIDENTIAL_RPT09, \
        CONFIDENTIAL_RPT10, \
        CONFIDENTIAL_RPT11, \
        CONFIDENTIAL_RPT12, \
        ABSENCE_DAYS, \
        ABSENCE_DAYS2, \
        ABSENCE_DAYS3, \
        AVERAGE3, \
        AVERAGE5, \
        AVERAGE_ALL, \
        TOTAL3, \
        TOTAL5, \
        TOTAL_ALL, \
        KASANTEN_ALL, \
        REGISTERCD, \
        UPDATED \
    FROM \
        ENTEXAM_APPLICANTCONFRPT_DAT_OLD

ALTER TABLE ENTEXAM_APPLICANTCONFRPT_DAT ADD CONSTRAINT PK_ENTEXAM_APCNRPT PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,EXAMNO)