-- $Id: rep-entexam_applicant_before_dat.sql 71461 2019-12-26 01:30:32Z nakamoto $

DROP TABLE ENTEXAM_APPLICANT_BEFORE_DAT_OLD

CREATE TABLE ENTEXAM_APPLICANT_BEFORE_DAT_OLD LIKE ENTEXAM_APPLICANT_BEFORE_DAT

INSERT INTO ENTEXAM_APPLICANT_BEFORE_DAT_OLD SELECT * FROM ENTEXAM_APPLICANT_BEFORE_DAT

DROP TABLE ENTEXAM_APPLICANT_BEFORE_DAT

CREATE TABLE ENTEXAM_APPLICANT_BEFORE_DAT( \
    ENTEXAMYEAR          VARCHAR(4)    NOT NULL, \
    APPLICANTDIV         VARCHAR(1)    NOT NULL, \
    TESTDIV              VARCHAR(1)    NOT NULL, \
    BEFORE_PAGE          VARCHAR(3)    NOT NULL, \
    BEFORE_SEQ           VARCHAR(3)    NOT NULL, \
    BEFORE_COURSECD      VARCHAR(1), \
    BEFORE_MAJORCD       VARCHAR(3), \
    BEFORE_EXAMCOURSECD  VARCHAR(4), \
    FS_CD                VARCHAR(7), \
    NAME                 VARCHAR(60), \
    NAME_KANA            VARCHAR(120), \
    SEX                  VARCHAR(1), \
    NAISIN1              SMALLINT, \
    NAISIN2              SMALLINT, \
    NAISIN3              SMALLINT, \
    ATTEND1              SMALLINT, \
    ATTEND2              SMALLINT, \
    ATTEND3              SMALLINT, \
    ATTEND_TOTAL         SMALLINT, \
    SENBATU1_SCHOOL      VARCHAR(90), \
    SENBATU1_MAJOR       VARCHAR(90), \
    SENBATU2_SCHOOL      VARCHAR(90), \
    SENBATU2_MAJOR       VARCHAR(90), \
    SCHOLARSHIP          VARCHAR(1), \
    RECOM_FLG            VARCHAR(1), \
    RECOM_REMARK         VARCHAR(150), \
    REMARK               VARCHAR(150), \
    NANKAN_FLG           VARCHAR(1), \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_APPLICANT_BEFORE_DAT ADD CONSTRAINT PK_ENTEXAM_BEF PRIMARY KEY (ENTEXAMYEAR, APPLICANTDIV, TESTDIV, BEFORE_PAGE, BEFORE_SEQ)

INSERT INTO ENTEXAM_APPLICANT_BEFORE_DAT \
SELECT \
    ENTEXAMYEAR, \
    APPLICANTDIV, \
    TESTDIV, \
    BEFORE_PAGE, \
    BEFORE_SEQ, \
    BEFORE_COURSECD, \
    BEFORE_MAJORCD, \
    BEFORE_EXAMCOURSECD, \
    FS_CD, \
    NAME, \
    NAME_KANA, \
    SEX, \
    NAISIN1, \
    NAISIN2, \
    NAISIN3, \
    ATTEND1, \
    ATTEND2, \
    ATTEND3, \
    ATTEND_TOTAL, \
    SENBATU1_SCHOOL, \
    SENBATU1_MAJOR, \
    SENBATU2_SCHOOL, \
    SENBATU2_MAJOR, \
    SCHOLARSHIP, \
    RECOM_FLG, \
    RECOM_REMARK, \
    REMARK, \
    CAST(NULL AS VARCHAR(1)) AS NANKAN_FLG, \
    REGISTERCD, \
    UPDATED \
FROM \
    ENTEXAM_APPLICANT_BEFORE_DAT_OLD
