#!/bin/sh
##############################################################################
# Svf Java Connect Server startup script  Copyright(C) by FIT.
##############################################################################

SCRIPT_NAME="SvfJavaConnectServer"

if [ "$FIT_PRODUCTS_BASE" = "" ]; then
    echo "FIT_PRODUCTS_BASE not found!"
    echo "please set 'FIT_PRODUCTS_BASE' environment variable and try again."
    exit 1
fi

PRODUCT_NAME="Svf Java Connect Server"
PRODUCT_PID="$FIT_PRODUCTS_BASE/var/run/SvfJavaConnectServer.pid"

##############################################################################
# subroutines
##############################################################################

# --- Set SvfJavaConnectServer CLASSPATH ---
set_simple_httpd_classpath() {
# start classpath section
    CLASSPATH="$CLASSPATH:$FIT_PRODUCTS_BASE/svfjpd/lib/forme.jar"
    CLASSPATH="$CLASSPATH:$FIT_PRODUCTS_BASE/svfjpd/lib/svfpdfparser.jar"
    CLASSPATH="$CLASSPATH:$FIT_PRODUCTS_BASE/svfjpd/lib/svf.jar"
    CLASSPATH="$CLASSPATH:$FIT_PRODUCTS_BASE/svfjpd/lib/svfgrph.jar"
    CLASSPATH="$CLASSPATH:$FIT_PRODUCTS_BASE/svfjpd/lib/BSPro.jar"
    CLASSPATH="$CLASSPATH:$FIT_PRODUCTS_BASE/svfjpd/lib/jai_codec.jar"
    CLASSPATH="$CLASSPATH:$FIT_PRODUCTS_BASE/svfjpd/lib/jai_core.jar"
# end classpath section
    export CLASSPATH
}

# --- Stop if running SvfJavaConnectServer  ---
stop_if_running_simple_httpd() {
    if [ -f $PRODUCT_PID ]; then
        echo "$PRODUCT_NAME is running. Shutting down $PRODUCT_NAME services"
        kill `cat $PRODUCT_PID` > /dev/null 2>&1
        while [ 1 ]; do
            ps -p `cat $PRODUCT_PID` > /dev/null
            RETVAL=$?
            if [ $RETVAL = 1 ]; then
                break;
            fi
            sleep 1
        done
        rm -f $PRODUCT_PID
        sleep 1
    fi
}

##############################################################################
# main
##############################################################################

RETVAL=0

case "$1" in
  start | restart)
    # Check servers are running
    stop_if_running_simple_httpd

    # Start daemon.
    echo "Starting $PRODUCT_NAME services"
    set_simple_httpd_classpath
    java -Xrs -Xms512m -Xmx512m -Djp.co.fit.vfreport.home="$FIT_PRODUCTS_BASE/SimpleHttpd" jp.co.fit.vfreport.SvfrServer &
    RETVAL=$?
    if [ $RETVAL = 0 ]; then
        echo $! > $PRODUCT_PID
    fi
    ;;

  stop)
    # Stop daemon.
    if [ -f $PRODUCT_PID ]; then
        echo "Shutting down $PRODUCT_NAME services"
        kill `cat $PRODUCT_PID` > /dev/null 2>&1
        rm -f $PRODUCT_PID
    else
        echo "$PRODUCT_NAME is not running."
    fi
    ;;

  status)
    # Check running daemon.
    if [ -f $PRODUCT_PID ]; then
        LANG=C ps -aef | grep `cat $PRODUCT_PID` | grep "java" > /dev/null 2>&1
        if [ $? = 0 ];then
            echo "$PRODUCT_NAME (`cat $PRODUCT_PID`) is running."
            RETVAL=2
        else
            echo "uum... $PRODUCT_NAME (`cat $PRODUCT_PID`) was started."
            echo "But $PRODUCT_NAME was DONE."
            RETVAL=3
        fi
    fi
    ;;

  *)
    echo "Usage: $SCRIPT_NAME {start|restart|stop|status}"
    RETVAL=1
esac

exit $RETVAL
##############################################################################
# end of script
##############################################################################
