-- $Id: 5aef733cf12228a902db4ffefe12240104839c2d $

DROP TABLE ADMIN_CONTROL_SDIV_DAT
CREATE TABLE ADMIN_CONTROL_SDIV_DAT ( \
    YEAR            VARCHAR(4) NOT NULL, \
    SEMESTER        VARCHAR(1) NOT NULL, \
    TESTKINDCD      VARCHAR(2) NOT NULL, \
    TESTITEMCD      VARCHAR(2) NOT NULL, \
    SCORE_DIV       VARCHAR(2) NOT NULL, \
    CLASSCD         VARCHAR(2) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    CURRICULUM_CD   VARCHAR(2) NOT NULL, \
    SUBCLASSCD      VARCHAR(6) NOT NULL, \
    CONTROL_FLG     VARCHAR(1), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ADMIN_CONTROL_SDIV_DAT ADD CONSTRAINT PK_AD_CONL_SD_DAT PRIMARY KEY (YEAR,SEMESTER,TESTKINDCD,TESTITEMCD,SCORE_DIV, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)
