-- $Id: 2772aa80a8278d08ed23efc2e0de4aa94cfa5992 $

DROP TABLE ADMIN_CONTROL_KANSAN_SDIV_DAT
CREATE TABLE ADMIN_CONTROL_KANSAN_SDIV_DAT ( \
    YEAR            VARCHAR(4) NOT NULL, \
    SEMESTER        VARCHAR(1) NOT NULL, \
    TESTKINDCD      VARCHAR(2) NOT NULL, \
    TESTITEMCD      VARCHAR(2) NOT NULL, \
    SCORE_DIV       VARCHAR(2) NOT NULL, \
    CLASSCD         VARCHAR(2) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    CURRICULUM_CD   VARCHAR(2) NOT NULL, \
    SUBCLASSCD      VARCHAR(6) NOT NULL, \
    NOT_AUTO_KANSAN_FLG         VARCHAR(1), \
    KANSAN_AFTER_UPDATE_FLG     VARCHAR(1), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ADMIN_CONTROL_KANSAN_SDIV_DAT ADD CONSTRAINT PK_AD_CN_CL_GK_DAT PRIMARY KEY (YEAR, SEMESTER, TESTKINDCD, TESTITEMCD, SCORE_DIV, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)
