-- $Id: dc3c3a7a32bdbbc75fd8d2aec7d1f3b91fb6ab15 $

DROP TABLE ADMIN_CONTROL_GCM_SDIV_DAT

CREATE TABLE ADMIN_CONTROL_GCM_SDIV_DAT ( \
    YEAR           VARCHAR(4)   NOT NULL, \
    SCHOOLCD       VARCHAR(12)  NOT NULL, \
    SEMESTER       VARCHAR(1)   NOT NULL, \
    TESTKINDCD     VARCHAR(2)   NOT NULL, \
    TESTITEMCD     VARCHAR(2)   NOT NULL, \
    SCORE_DIV      VARCHAR(2)   NOT NULL, \
    CLASSCD        VARCHAR(2)   NOT NULL, \
    SCHOOL_KIND    VARCHAR(2)   NOT NULL, \
    CURRICULUM_CD  VARCHAR(2)   NOT NULL, \
    SUBCLASSCD     VARCHAR(6)   NOT NULL, \
    GRADE          VARCHAR(2)   NOT NULL, \
    COURSECD       VARCHAR(1)   NOT NULL, \
    MAJORCD        VARCHAR(3)   NOT NULL, \
    CONTROL_FLG    VARCHAR(1)  , \
    REGISTERCD     VARCHAR(10) , \
    UPDATED        TIMESTAMP    DEFAULT CURRENT TIMESTAMP \
 ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ADMIN_CONTROL_GCM_SDIV_DAT ADD CONSTRAINT PK_AD_CTL_GCM_SD_D PRIMARY KEY (YEAR,SCHOOLCD,SEMESTER,TESTKINDCD,TESTITEMCD,SCORE_DIV,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,GRADE,COURSECD,MAJORCD)
