-- $Id: 940a5507f91f992080fd7c8f885485c6d511dcaf $

DROP TABLE ADMIN_CONTROL_DAT
CREATE TABLE ADMIN_CONTROL_DAT  \
(  \
        "YEAR"          VARCHAR(4)      NOT NULL, \
        "SCHOOL_KIND"   VARCHAR(2)      NOT NULL, \
        "CONTROL_FLG"   VARCHAR(1)      NOT NULL, \
        "CONTROL_CODE"  VARCHAR(4)      NOT NULL, \
        "REGISTERCD"    VARCHAR(10),  \
        "UPDATED"       TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS


ALTER TABLE ADMIN_CONTROL_DAT  \
ADD CONSTRAINT PK_ADMIN_CONL_DAT  \
PRIMARY KEY  \
( \
YEAR, \
SCHOOL_KIND, \
CONTROL_FLG, \
CONTROL_CODE \
)

