-- $Id: 8d4e5ec8f89cc527f32ced523a439558c522e2a9 $

DROP TABLE ADMIN_CONTROL_CALC_SDIV_DAT
CREATE TABLE ADMIN_CONTROL_CALC_SDIV_DAT ( \
    YEAR            VARCHAR(4) NOT NULL, \
    SEMESTER        VARCHAR(1) NOT NULL, \
    TESTKINDCD      VARCHAR(2) NOT NULL, \
    TESTITEMCD      VARCHAR(2) NOT NULL, \
    SCORE_DIV       VARCHAR(2) NOT NULL, \
    CLASSCD         VARCHAR(2) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    CURRICULUM_CD   VARCHAR(2) NOT NULL, \
    SUBCLASSCD      VARCHAR(6) NOT NULL, \
    MOTO_SEMESTER   VARCHAR(1) NOT NULL, \
    MOTO_TESTKINDCD VARCHAR(2) NOT NULL, \
    MOTO_TESTITEMCD VARCHAR(2) NOT NULL, \
    MOTO_SCORE_DIV  VARCHAR(2) NOT NULL, \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ADMIN_CONTROL_CALC_SDIV_DAT ADD CONSTRAINT PK_AD_CN_CL_SD_DAT PRIMARY KEY (YEAR, SEMESTER, TESTKINDCD, TESTITEMCD, SCORE_DIV, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, MOTO_SEMESTER, MOTO_TESTKINDCD, MOTO_TESTITEMCD, MOTO_SCORE_DIV)
