-- $Id: 4f1b92a6158d9cfd0820e150ae1e7e1ba3a1ee8c $

DROP TABLE ADMIN_CONTROL_CALC_GCM_SDIV_DAT
CREATE TABLE ADMIN_CONTROL_CALC_GCM_SDIV_DAT ( \
    YEAR            VARCHAR(4) NOT NULL, \
    SCHOOLCD        VARCHAR(12) NOT NULL, \
    SEMESTER        VARCHAR(1) NOT NULL, \
    TESTKINDCD      VARCHAR(2) NOT NULL, \
    TESTITEMCD      VARCHAR(2) NOT NULL, \
    SCORE_DIV       VARCHAR(2) NOT NULL, \
    CLASSCD         VARCHAR(2) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    CURRICULUM_CD   VARCHAR(2) NOT NULL, \
    SUBCLASSCD      VARCHAR(6) NOT NULL, \
    MOTO_SEMESTER   VARCHAR(1) NOT NULL, \
    MOTO_TESTKINDCD VARCHAR(2) NOT NULL, \
    MOTO_TESTITEMCD VARCHAR(2) NOT NULL, \
    MOTO_SCORE_DIV  VARCHAR(2) NOT NULL, \
    GRADE           VARCHAR(2) NOT NULL, \
    COURSECD        VARCHAR(1) NOT NULL, \
    MAJORCD         VARCHAR(3) NOT NULL, \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ADMIN_CONTROL_CALC_GCM_SDIV_DAT ADD CONSTRAINT PK_AD_CN_CL_GCM_SD PRIMARY KEY (YEAR, SCHOOLCD, SEMESTER, TESTKINDCD, TESTITEMCD, SCORE_DIV, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, MOTO_SEMESTER, MOTO_TESTKINDCD, MOTO_TESTITEMCD, MOTO_SCORE_DIV, GRADE, COURSECD, MAJORCD)
