-- kanji=´Á»ú
-- $Id: 93c61d2f69209001ff90d7b8a836f46860742f7d $

DROP TABLE AFT_DISEASE_ADDITION434_FIXED_HDAT

CREATE TABLE AFT_DISEASE_ADDITION434_FIXED_HDAT \
      (EDBOARD_SCHOOLCD     VARCHAR(12) NOT NULL, \
       YEAR                 VARCHAR(4)  NOT NULL, \
       DATA_DIV             VARCHAR(3)  NOT NULL, \
       FIXED_DATE           DATE        NOT NULL, \
       IDOU_DATE            DATE, \
       REGISTERCD           VARCHAR(10), \
       UPDATED      TIMESTAMP DEFAULT CURRENT TIMESTAMP \
      ) in usr1dms index in idx1dms

alter table AFT_DISEASE_ADDITION434_FIXED_HDAT add constraint PK_AFT_D_ADD434_FH \
primary key (EDBOARD_SCHOOLCD, YEAR, DATA_DIV, FIXED_DATE)
