-- kanji=漢字
-- $Id: 9a7f7cdfed029201f3da42d4de4db06c3cf19440 $

DROP TABLE AFT_SEARCH_REPORT_SCHOOL_DAT
CREATE TABLE AFT_SEARCH_REPORT_SCHOOL_DAT( \
    YEAR                VARCHAR(4)    NOT NULL, \
    DOC_NUMBER          INTEGER       NOT NULL, \
    EDBOARD_SCHOOLCD    VARCHAR(6)    NOT NULL, \
    RECEIVE_FLG         VARCHAR(1), \
    RECEIVE_DATE        TIMESTAMP, \
    ANSWER_FLG          VARCHAR(1), \
    ANSWER_DATE         TIMESTAMP, \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE AFT_SEARCH_REPORT_SCHOOL_DAT ADD CONSTRAINT PK_AFT_SCH_REP_S_D PRIMARY KEY (YEAR, DOC_NUMBER, EDBOARD_SCHOOLCD)