-- kanji=漢字
-- $Id: 461923f9d0a97ef440a79081b8786c2c87645e19 $

DROP TABLE AFT_GRAD_COURSE_EXEC_DAT

CREATE TABLE AFT_GRAD_COURSE_EXEC_DAT( \
    CALC_DATE           DATE            NOT NULL, \
    CALC_TIME           TIME            NOT NULL, \
    SCHOOL_KIND         VARCHAR(2)      NOT NULL, \
    COURSE_KIND         VARCHAR(1), \
    QUESTIONNAIRECD     VARCHAR(2), \
    ENTRYDATE           DATE, \
    YEAR                VARCHAR(4), \
    SEMESTER            VARCHAR(1), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE AFT_GRAD_COURSE_EXEC_DAT ADD CONSTRAINT PK_AFT_GRAD_EXEC PRIMARY KEY (CALC_DATE, CALC_TIME, SCHOOL_KIND)