-- kanji=漢字
-- $Id: e4c2a5f021fc83482c6565f30a5a087134c99ad4 $

DROP TABLE AFT_GRAD_STAT_EXEC_DAT

CREATE TABLE AFT_GRAD_STAT_EXEC_DAT( \
    CALC_DATE       DATE NOT NULL, \
    CALC_TIME       TIME NOT NULL, \
    COURSECD        VARCHAR(1) NOT NULL, \
    MAJORCD         VARCHAR(3) NOT NULL, \
    YEAR            VARCHAR(4) NOT NULL, \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE AFT_GRAD_STAT_EXEC_DAT ADD CONSTRAINT PK_AFT_GRAD_STAT_EXEC_DAT PRIMARY KEY (CALC_DATE, CALC_TIME, COURSECD, MAJORCD, YEAR)