-- kanji=?{?
-- $Id: 2df273e4598116ccb211b4ea7ceca0c18b96e7fa $

CREATE TABLE ANOTHER_SCHOOL_HIST_DAT( \
 SCHREGNO             VARCHAR(8)    NOT NULL, \
 SEQ                  SMALLINT      NOT NULL, \
 STUDENT_DIV          VARCHAR(1)   , \
 FORMER_REG_SCHOOLCD  VARCHAR(12)  , \
 MAJOR_NAME           VARCHAR(120) , \
 REGD_S_DATE          DATE         , \
 REGD_E_DATE          DATE         , \
 PERIOD_MONTH_CNT     VARCHAR(2)   , \
 ABSENCE_CNT          VARCHAR(2)   , \
 MONTH_CNT            VARCHAR(2)   , \
 ENT_FORM             VARCHAR(1)   , \
 REASON               VARCHAR(150) , \
 ANOTHER_SPORT        VARCHAR(1)   , \
 REGISTERCD           VARCHAR(10)  , \
 UPDATED              TIMESTAMP     DEFAULT CURRENT TIMESTAMP \
 ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ANOTHER_SCHOOL_HIST_DAT ADD CONSTRAINT PK_ANO_SCH_HIST PRIMARY KEY (SCHREGNO,SEQ)

