-- kanji=漢字
-- $Id: a0839946c5b1b11e1aac83b87ed315fc71c03262 $

DROP TABLE ASSESS_AVG_CALC_MST

CREATE TABLE ASSESS_AVG_CALC_MST \
(  \
    YEAR            VARCHAR(4) NOT NULL, \
    GRADE           VARCHAR(2) NOT NULL, \
    SEMESTER        VARCHAR(1) NOT NULL, \
    TESTKINDCD      VARCHAR(2) NOT NULL, \
    TESTITEMCD      VARCHAR(2) NOT NULL, \
    SCORE_DIV       VARCHAR(2) NOT NULL, \
    CLASSCD         VARCHAR(2) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    CURRICULUM_CD   VARCHAR(2) NOT NULL, \
    SUBCLASSCD      VARCHAR(6) NOT NULL, \
    ASSESS_TBL_DIV  VARCHAR(1), \
    CALC_UNIT_DIV   VARCHAR(1), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ASSESS_AVG_CALC_MST ADD CONSTRAINT PK_ASSESS_AVG_CALC_MST \
PRIMARY KEY (YEAR, GRADE, SEMESTER, TESTKINDCD, TESTITEMCD, SCORE_DIV, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)
