-- kanji=漢字
-- $Id: cb5766538d6b2005c4271e3b7c201a25693216c7 $

DROP TABLE ASSESS_SUBCLASS_MST

CREATE TABLE ASSESS_SUBCLASS_MST \
(  \
    YEAR            VARCHAR (4) NOT NULL, \
    GRADE           VARCHAR (2) NOT NULL, \
    COURSECD        VARCHAR (1) NOT NULL, \
    MAJORCD         VARCHAR (3) NOT NULL, \
    COURSECODE      VARCHAR (4) NOT NULL, \
    CLASSCD         VARCHAR (2) NOT NULL, \
    SCHOOL_KIND     VARCHAR (2) NOT NULL, \
    CURRICULUM_CD   VARCHAR (2) NOT NULL, \
    SUBCLASSCD      VARCHAR (6) NOT NULL, \
    ASSESSLEVEL     SMALLINT NOT NULL, \
    ASSESSMARK      VARCHAR (6), \
    ASSESSLOW       DECIMAL (4,1), \
    ASSESSHIGH      DECIMAL (4,1), \
    REGISTERCD      VARCHAR (10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ASSESS_SUBCLASS_MST ADD CONSTRAINT PK_ASSESS_SUB_MST \
PRIMARY KEY (YEAR,GRADE,COURSECD,MAJORCD,COURSECODE,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,ASSESSLEVEL)
