-- kanji=´Á»ú
-- $Id: 307c8e51980abfe4cdad008133872150b65992ba $

DROP   TABLE ASSESS_LEVEL_SDIV_MST

CREATE TABLE ASSESS_LEVEL_SDIV_MST ( \
    YEAR            VARCHAR(4)  NOT NULL, \
    SEMESTER        VARCHAR(1)  NOT NULL, \
    TESTKINDCD      VARCHAR(2)  NOT NULL, \
    TESTITEMCD      VARCHAR(2)  NOT NULL, \
    SCORE_DIV       VARCHAR(2)  NOT NULL, \
    CLASSCD         VARCHAR(2)  NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)  NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)  NOT NULL, \
    SUBCLASSCD      VARCHAR(6)  NOT NULL, \
    RUISEKI_DIV     VARCHAR(1)  NOT NULL, \
    DIV             VARCHAR(1)  NOT NULL, \
    GRADE           VARCHAR(2)  NOT NULL, \
    HR_CLASS        VARCHAR(3)  NOT NULL, \
    COURSECD        VARCHAR(1)  NOT NULL, \
    MAJORCD         VARCHAR(3)  NOT NULL, \
    COURSECODE      VARCHAR(4)  NOT NULL, \
    ASSESSLEVEL     SMALLINT NOT NULL, \
    ASSESSMARK      VARCHAR(6), \
    ASSESSLOW       DECIMAL, \
    ASSESSHIGH      DECIMAL, \
    PERCENT         DECIMAL(4,1), \
    PERCENT_ALLCNT  SMALLINT, \
    PERCENT_CNT     SMALLINT, \
    STANDARD_ASSESSLOW       DECIMAL, \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ASSESS_LEVEL_SDIV_MST ADD CONSTRAINT PK_ASS_LVL_S_MST \
      PRIMARY KEY (YEAR, SEMESTER, TESTKINDCD, TESTITEMCD, SCORE_DIV, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, RUISEKI_DIV, DIV, GRADE, HR_CLASS, COURSECD, MAJORCD, COURSECODE, ASSESSLEVEL)
