-- kanji=´Á»ú
-- $Id: 7cb9c01e966bbd65dea538d3e5135c9396dc9896 $

DROP   TABLE ASSESS_RANK_SDIV_MST

CREATE TABLE ASSESS_RANK_SDIV_MST ( \
    YEAR            VARCHAR(4)  NOT NULL, \
    SEMESTER        VARCHAR(1)  NOT NULL, \
    TESTKINDCD      VARCHAR(2)  NOT NULL, \
    TESTITEMCD      VARCHAR(2)  NOT NULL, \
    SCORE_DIV       VARCHAR(2)  NOT NULL, \
    DIV             VARCHAR(1)  NOT NULL, \
    GRADE           VARCHAR(2)  NOT NULL, \
    HR_CLASS        VARCHAR(3)  NOT NULL, \
    COURSECD        VARCHAR(1)  NOT NULL, \
    MAJORCD         VARCHAR(3)  NOT NULL, \
    COURSECODE      VARCHAR(4)  NOT NULL, \
    RANK_LEVEL      SMALLINT    NOT NULL, \
    RANK_MARK       VARCHAR(6), \
    RANK_LOW        DECIMAL, \
    RANK_HIGH       DECIMAL, \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ASSESS_RANK_SDIV_MST ADD CONSTRAINT PK_ASS_RNK_S_MST \
      PRIMARY KEY (YEAR, SEMESTER, TESTKINDCD, TESTITEMCD, SCORE_DIV, DIV, GRADE, HR_CLASS, COURSECD, MAJORCD, COURSECODE, RANK_LEVEL)
