-- $Id: 97abec2d44c49dff668132ff2a8bfcf85a26ca7b $

DROP TABLE ATTEND_SEMES_DETAIL_DEL_DAT
CREATE TABLE ATTEND_SEMES_DETAIL_DEL_DAT( \
    EXECUTEDATE     DATE            NOT NULL, \
    SEQ             VARCHAR(3)      NOT NULL, \
    COPYCD          VARCHAR(1)      NOT NULL, \
    YEAR            VARCHAR(4)      NOT NULL, \
    MONTH           VARCHAR(2)      NOT NULL, \
    SEMESTER        VARCHAR(1)      NOT NULL, \
    SCHREGNO        VARCHAR(8)      NOT NULL, \
    DEL_SEQ         VARCHAR(3)      NOT NULL, \
    CNT             SMALLINT, \
    VAL             VARCHAR(2), \
    CNT_DECIMAL     DECIMAL(5, 1), \
    DEL_REGISTERCD  VARCHAR(10), \
    DEL_UPDATED     TIMESTAMP, \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ATTEND_SEMES_DETAIL_DEL_DAT ADD CONSTRAINT PK_ATTSEM_DTL_DEL \
      PRIMARY KEY (EXECUTEDATE, SEQ, COPYCD, YEAR, MONTH, SEMESTER, SCHREGNO, DEL_SEQ)