-- $Id: f1f422eeda6d8db33d943905af30480af298f37b $

DROP TABLE BEHAVIOR_SUB_MST

CREATE TABLE BEHAVIOR_SUB_MST \
    (SCHOOL_KIND        VARCHAR(2) NOT NULL, \
     STUDYREC_CODE      VARCHAR(2) NOT NULL, \
     STUDYREC_CODENAME  VARCHAR(45), \
     REGISTERCD         VARCHAR(10), \
     UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE BEHAVIOR_SUB_MST \
ADD CONSTRAINT PK_BEHAVIOR_SUB_M \
PRIMARY KEY (SCHOOL_KIND, STUDYREC_CODE)
