-- $Id$

DROP TABLE CERTIF_DETAIL_EACHTYPE_DAT
CREATE TABLE CERTIF_DETAIL_EACHTYPE_DAT( \
    YEAR         VARCHAR(4)    NOT NULL, \
    CERTIF_INDEX VARCHAR(5)    NOT NULL, \
    SCHREGNO     VARCHAR(8), \
    TYPE         VARCHAR(1), \
    REMARK1      VARCHAR(60), \
    REMARK2      VARCHAR(60), \
    REMARK3      VARCHAR(60), \
    REMARK4      VARCHAR(60), \
    REMARK5      VARCHAR(60), \
    REMARK6      VARCHAR(60), \
    REMARK7      VARCHAR(60), \
    REMARK8      VARCHAR(60), \
    REMARK9      VARCHAR(60), \
    REMARK10     VARCHAR(60), \
    REMARK11     VARCHAR(60), \
    REMARK12     VARCHAR(60), \
    REMARK13     VARCHAR(60), \
    REMARK14     VARCHAR(60), \
    REMARK15     VARCHAR(60), \
    REMARK16     VARCHAR(60), \
    REMARK17     VARCHAR(60), \
    REMARK18     VARCHAR(60), \
    REMARK19     VARCHAR(60), \
    REMARK20     VARCHAR(60), \
    REMARK21     VARCHAR(60), \
    REMARK22     VARCHAR(60), \
    REMARK23     VARCHAR(60), \
    REMARK24     VARCHAR(60), \
    REMARK25     VARCHAR(60), \
    REMARK26     VARCHAR(60), \
    REMARK27     VARCHAR(60), \
    REMARK28     VARCHAR(60), \
    REMARK29     VARCHAR(60), \
    REMARK30     VARCHAR(60), \
    REMARK31     VARCHAR(60), \
    REMARK32     VARCHAR(60), \
    REMARK33     VARCHAR(60), \
    REMARK34     VARCHAR(60), \
    REMARK35     VARCHAR(60), \
    REMARK36     VARCHAR(60), \
    REMARK37     VARCHAR(60), \
    REMARK38     VARCHAR(60), \
    REMARK39     VARCHAR(60), \
    REMARK40     VARCHAR(60), \
    REGISTERCD   VARCHAR(10), \
    UPDATED      TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE CERTIF_DETAIL_EACHTYPE_DAT ADD CONSTRAINT PK_CERTIF_D_E_DAT PRIMARY KEY (YEAR,CERTIF_INDEX)