-- $Id: 08f9821a2c065b9cacb87a9668373fa1dce2d2a6 $

DROP TABLE CHALLENGED_NAME_MST
CREATE TABLE CHALLENGED_NAME_MST( \
    CHALLENGECD              VARCHAR(5)    NOT NULL, \
    NAME                     VARCHAR(150), \
    ABBV                     VARCHAR(90), \
    POPULAR_NAME             VARCHAR(150), \
    REMARK                   VARCHAR(300), \
    REGISTERCD               VARCHAR(8), \
    UPDATED                  TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE CHALLENGED_NAME_MST ADD CONSTRAINT PK_CHA_NAME_MST PRIMARY KEY (CHALLENGECD)