-- kanji=漢字
-- $Id: dc9c722fac10790a5ba217b4bd4859c77daaf2cf $

DROP TABLE CLASS_DETAIL_DAT
CREATE TABLE CLASS_DETAIL_DAT \
(  \
    YEAR           VARCHAR(4)  NOT NULL, \
    CLASSCD        VARCHAR(2)  NOT NULL, \
    SCHOOL_KIND    VARCHAR(2)  NOT NULL, \
    CLASS_SEQ      VARCHAR(3)  NOT NULL, \
    CLASS_REMARK1  VARCHAR(15), \
    CLASS_REMARK2  VARCHAR(15), \
    CLASS_REMARK3  VARCHAR(15), \
    CLASS_REMARK4  VARCHAR(15), \
    CLASS_REMARK5  VARCHAR(15), \
    CLASS_REMARK6  VARCHAR(15), \
    CLASS_REMARK7  VARCHAR(15), \
    CLASS_REMARK8  VARCHAR(15), \
    CLASS_REMARK9  VARCHAR(15), \
    CLASS_REMARK10 VARCHAR(15), \
    ORIGINAL_CD    VARCHAR(4), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE CLASS_DETAIL_DAT ADD CONSTRAINT PK_CLASS_DTL_DAT \
PRIMARY KEY (YEAR,CLASSCD,SCHOOL_KIND,CLASS_SEQ)


