-- $Id: a9d022ec275b7f66b62d500a1e260c2e2c44ba22 $

DROP TABLE COLLECT_MONTH_GRP_DAT
CREATE TABLE COLLECT_MONTH_GRP_DAT( \
    SCHOOLCD            VARCHAR(12)     NOT NULL, \
    SCHOOL_KIND         VARCHAR(2)      NOT NULL, \
    YEAR                VARCHAR(4)      NOT NULL, \
    COLLECT_GRP_CD      VARCHAR(4)      NOT NULL, \
    COLLECT_L_CD        VARCHAR(2)      NOT NULL, \
    COLLECT_M_CD        VARCHAR(2)      NOT NULL, \
    MONTH_CNT           SMALLINT, \
    COLLECT_MONTH_4     VARCHAR(1), \
    COLLECT_MONTH_5     VARCHAR(1), \
    COLLECT_MONTH_6     VARCHAR(1), \
    COLLECT_MONTH_7     VARCHAR(1), \
    COLLECT_MONTH_8     VARCHAR(1), \
    COLLECT_MONTH_9     VARCHAR(1), \
    COLLECT_MONTH_10    VARCHAR(1), \
    COLLECT_MONTH_11    VARCHAR(1), \
    COLLECT_MONTH_12    VARCHAR(1), \
    COLLECT_MONTH_1     VARCHAR(1), \
    COLLECT_MONTH_2     VARCHAR(1), \
    COLLECT_MONTH_3     VARCHAR(1), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COLLECT_MONTH_GRP_DAT ADD CONSTRAINT PK_COL_MONTH_GRP PRIMARY KEY (SCHOOLCD,SCHOOL_KIND,YEAR,COLLECT_GRP_CD,COLLECT_L_CD,COLLECT_M_CD)