-- kanji=´Á»ú
-- $Id: 39a7841c906ce86118543c376033343d061603ee $

DROP TABLE COLLECT_L_MST

CREATE TABLE COLLECT_L_MST ( \
        "SCHOOLCD"        VARCHAR(12) NOT NULL, \
        "SCHOOL_KIND"     VARCHAR(2)  NOT NULL, \
        "YEAR"            VARCHAR(4)  NOT NULL, \
        "COLLECT_L_CD"    VARCHAR(2)  NOT NULL, \
        "COLLECT_L_NAME"  VARCHAR(90), \
        "COLLECT_L_ABBV"  VARCHAR(90), \
        "LEVY_FLG"        VARCHAR(1), \
        "REGISTERCD"      VARCHAR(10), \
        "UPDATED"         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COLLECT_L_MST ADD CONSTRAINT PK_COLLECT_L_MST PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, YEAR, COLLECT_L_CD)
