-- $Id: c3b7acaaa0a2d71b1bb7623f5f419dd14af3dc0c $

DROP TABLE COLLEGE_CAMPUS_ADDR_DAT
CREATE TABLE COLLEGE_CAMPUS_ADDR_DAT( \
    SCHOOL_CD      VARCHAR(8)    NOT NULL, \
    CAMPUS_ADDR_CD VARCHAR(2)    NOT NULL, \
    PREF_CD        VARCHAR(2), \
    ZIPCD          VARCHAR(8), \
    ADDR1          VARCHAR(90), \
    ADDR2          VARCHAR(90), \
    TELNO          VARCHAR(16), \
    REGISTERCD     VARCHAR(8), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COLLEGE_CAMPUS_ADDR_DAT ADD CONSTRAINT PK_COLLEGE_C_A_DAT PRIMARY KEY (SCHOOL_CD,CAMPUS_ADDR_CD)