-- $Id$

DROP TABLE COLLEGE_DEPARTMENT_MST
CREATE TABLE COLLEGE_DEPARTMENT_MST( \
    SCHOOL_CD            VARCHAR(8)    NOT NULL, \
    FACULTYCD            VARCHAR(3)    NOT NULL, \
    DEPARTMENTCD         VARCHAR(3)    NOT NULL, \
    DEPARTMENTNAME       VARCHAR(90), \
    DEPARTMENTNAME_SHOW1 VARCHAR(90), \
    DEPARTMENTNAME_SHOW2 VARCHAR(90), \
    DEPARTMENT_GROUP     VARCHAR(3), \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    CAMPUS_DEPARTMENTCD  VARCHAR(3) \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COLLEGE_DEPARTMENT_MST ADD CONSTRAINT PK_COLLEGE_DEP_MST PRIMARY KEY (SCHOOL_CD,FACULTYCD,DEPARTMENTCD)