-- $Id: 6a527352ff91fc0d963a299658ed920a530513b7 $

drop table COLLECT_SGL_SCHREGNO_MAPPING_DAT

create table COLLECT_SGL_SCHREGNO_MAPPING_DAT \
( \
    SCHREGNO       varchar(8) not null, \
    SCHREGNO_J     varchar(8), \
    SCHREGNO_H     varchar(9), \
    SIGEL_NO_J     varchar(20), \
    SIGEL_NO_H     varchar(20), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COLLECT_SGL_SCHREGNO_MAPPING_DAT ADD CONSTRAINT PK_COL_SGL_SCH_MAP PRIMARY KEY (SCHREGNO)
