-- kanji=Š¿Žš
-- $Id: d6108563278b35b40577ae633d34011f131cef7e $

DROP TABLE COLLEGE_MST
CREATE TABLE COLLEGE_MST( \
    SCHOOL_CD         CHAR(8)       NOT NULL, \
    SCHOOL_NAME       VARCHAR(120), \
    SCHOOL_NAME_SHOW1 VARCHAR(120), \
    SCHOOL_NAME_SHOW2 VARCHAR(120), \
    SCHOOL_GROUP      VARCHAR(2), \
    BUNAME            VARCHAR(120), \
    KANAME            VARCHAR(120), \
    SCHOOL_SORT       CHAR(2), \
    BUNYA             CHAR(2), \
    AREA_NAME         VARCHAR(30), \
    CAMPUS_ADDR_CD    VARCHAR(2), \
    ZIPCD             VARCHAR(8), \
    ADDR1             VARCHAR(90), \
    ADDR2             VARCHAR(90), \
    TELNO             VARCHAR(16), \
    GREDES            VARCHAR(120), \
    BASE_SCORE        VARCHAR(20), \
    NECESSARY_SCORE   VARCHAR(20), \
    REGISTERCD        VARCHAR(10), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COLLEGE_MST ADD CONSTRAINT PK_COLLEGE_MST PRIMARY KEY (SCHOOL_CD)