-- $Id$

DROP TABLE COLLEGE_FACULTY_MST
CREATE TABLE COLLEGE_FACULTY_MST( \
    SCHOOL_CD            VARCHAR(8)    NOT NULL, \
    FACULTYCD            VARCHAR(3)    NOT NULL, \
    FACULTYNAME          VARCHAR(90), \
    FACULTYNAME_SHOW1    VARCHAR(90), \
    FACULTYNAME_SHOW2    VARCHAR(90), \
    CAMPUS_ADDR_CD       VARCHAR(2), \
    FACULTY_GROUP        VARCHAR(3), \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    CAMPUS_FACULTYCD     VARCHAR(3) \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COLLEGE_FACULTY_MST ADD CONSTRAINT PK_COLLEGE_FAC_MST PRIMARY KEY (SCHOOL_CD,FACULTYCD)