-- $Id$

DROP TABLE COLLECT_CONTACT_HISTORY_DAT
CREATE TABLE COLLECT_CONTACT_HISTORY_DAT( \
    SCHREGNO          VARCHAR(8)     NOT NULL, \
    CONTACT_SDATE     DATE           NOT NULL, \
    SEQ               VARCHAR(3)     NOT NULL, \
    CONTACT_DIV       VARCHAR(2)     NOT NULL, \
    STAFFCD           VARCHAR(10)    NOT NULL, \
    YEAR              VARCHAR(4)     NOT NULL, \
    SEMESTER          VARCHAR(1)     NOT NULL, \
    CONTACT_REMARK    VARCHAR(400)   , \
    CONTACT_EDATE     DATE           , \
    REGISTERCD        VARCHAR(10)    , \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COLLECT_CONTACT_HISTORY_DAT ADD CONSTRAINT PK_COLLECT_CONTACT_HISTORY_DAT PRIMARY KEY (SCHREGNO, CONTACT_SDATE, SEQ)
