-- $Id: 8f4a221acfc725fd66c8f8cfa113ebed6bc733f0 $

DROP TABLE COMMITTEE_YDAT

CREATE TABLE COMMITTEE_YDAT \
(  \
        "SCHOOLCD"              VARCHAR(12)     NOT NULL, \
        "SCHOOL_KIND"           VARCHAR(2)      NOT NULL, \
        "YEAR"                  VARCHAR(4)      NOT NULL, \
        "COMMITTEE_FLG"         VARCHAR(1)      NOT NULL, \
        "COMMITTEECD"           VARCHAR(4)      NOT NULL, \
        "REGISTERCD"            VARCHAR(10), \
        "UPDATED"               TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COMMITTEE_YDAT  \
ADD CONSTRAINT PK_COMMITTEE_YDAT  \
PRIMARY KEY  \
(SCHOOLCD, SCHOOL_KIND, YEAR,COMMITTEE_FLG,COMMITTEECD)
