-- $Id: c8d6f701aa7190f4cfcf47923550b5456969bf22 $

DROP TABLE COMMITTEE_MST

CREATE TABLE COMMITTEE_MST \
(  \
        "SCHOOLCD"              VARCHAR(12)      NOT NULL, \
        "SCHOOL_KIND"           VARCHAR(2)       NOT NULL, \
        "COMMITTEE_FLG"         VARCHAR(1)       NOT NULL, \
        "COMMITTEECD"           VARCHAR(4)       NOT NULL, \
        "COMMITTEENAME"         VARCHAR(45), \
        "REGISTERCD"            VARCHAR(10), \
        "UPDATED"               TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COMMITTEE_MST  \
ADD CONSTRAINT PK_COMMITTEE_MST  \
PRIMARY KEY  \
(SCHOOLCD, SCHOOL_KIND, COMMITTEE_FLG,COMMITTEECD)
