-- $Id: 0f2c9920dd144776752fccdfc73ef78f2d5ec246 $

DROP TABLE COMP_CREDITS_PATTERN_STD_COURSE_DAT_OLD

RENAME TABLE COMP_CREDITS_PATTERN_STD_COURSE_DAT TO COMP_CREDITS_PATTERN_STD_COURSE_DAT_OLD

CREATE TABLE COMP_CREDITS_PATTERN_STD_COURSE_DAT (       \
   YEAR           VARCHAR(4)    NOT NULL,                \
   RIREKI_CODE    VARCHAR(2)    NOT NULL,                \
   PATTERN_CD     VARCHAR(2)    NOT NULL,                \
   GRADE          VARCHAR(2)    NOT NULL,                \
   COURSECD       VARCHAR(1)    NOT NULL,                \
   MAJORCD        VARCHAR(3)    NOT NULL,                \
   COURSECODE     VARCHAR(4)    NOT NULL,                \
   SCHREGNO       VARCHAR(8)    NOT NULL,                \
   REGISTERCD     VARCHAR(10), \
   UPDATED        TIMESTAMP    DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COMP_CREDITS_PATTERN_STD_COURSE_DAT ADD CONSTRAINT PK_CMP_CR_P_ST_C_D PRIMARY KEY (YEAR,RIREKI_CODE,PATTERN_CD,GRADE,COURSECD,MAJORCD,COURSECODE,SCHREGNO)

