-- $Id: f1485e223c94598a9f1cd051314f87d0ce529582 $

DROP TABLE COMP_GROUP_DAT

CREATE TABLE COMP_GROUP_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    GAKUBU_SCHOOL_KIND  VARCHAR(2) NOT NULL, \
    CONDITION           VARCHAR(1) NOT NULL, \
    GROUPCD             VARCHAR(4) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    CURRICULUM_CD       VARCHAR(2) NOT NULL, \
    SUBCLASSCD          VARCHAR(6) NOT NULL, \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COMP_GROUP_DAT ADD CONSTRAINT PK_COMP_GROUP_DAT PRIMARY KEY (YEAR, GAKUBU_SCHOOL_KIND, CONDITION, GROUPCD, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)
