-- $Id: c12e76e64e1a2a073a1e2b83e4a8f8f07615ee02 $

DROP TABLE COURSE_MST
CREATE TABLE COURSE_MST( \
    COURSECD   VARCHAR(1)    NOT NULL, \
    COURSENAME VARCHAR(60), \
    COURSEABBV VARCHAR(60), \
    COURSEENG  VARCHAR(10), \
    S_PERIODCD VARCHAR(1), \
    E_PERIODCD VARCHAR(1), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COURSE_MST ADD CONSTRAINT PK_COURSE_MST PRIMARY KEY (COURSECD)