-- kanji=漢字
-- $Id: 2420147b0a5774c32800bf1ddca6c4c820644b31 $

DROP TABLE COURSE_HOPE_EXEC_DAT

CREATE TABLE COURSE_HOPE_EXEC_DAT( \
    CALC_DATE               DATE            NOT NULL, \
    CALC_TIME               TIME            NOT NULL, \
    SCHOOL_KIND             VARCHAR(2)      NOT NULL, \
    COURSE_KIND             VARCHAR(1), \
    FROM_QUESTIONNAIRECD    VARCHAR(2), \
    TO_QUESTIONNAIRECD      VARCHAR(2), \
    TO_ENTRYDATE            DATE, \
    YEAR                    VARCHAR(4), \
    SEMESTER                VARCHAR(1), \
    REGISTERCD              VARCHAR(10), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COURSE_HOPE_EXEC_DAT ADD CONSTRAINT PK_COURSE_HOPE_EXEC PRIMARY KEY (CALC_DATE, CALC_TIME, SCHOOL_KIND)