-- kanji=Š¿Žš
-- $Id: 494f479bfb4ef5ed8cde3e2d339d9bffb57c9230 $

DROP TABLE COURSE_GROUP_HDAT
CREATE TABLE COURSE_GROUP_HDAT( \
    YEAR       VARCHAR(4)    NOT NULL, \
    GRADE      VARCHAR(2)    NOT NULL, \
    GROUP_CD   VARCHAR(3)    NOT NULL, \
    GROUP_NAME VARCHAR(60), \
    GROUP_ABBV VARCHAR(60), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COURSE_GROUP_HDAT ADD CONSTRAINT PK_COURSE_GRP_HDAT PRIMARY KEY (YEAR,GRADE,GROUP_CD)