-- kanji=Š¿Žš
-- $Id: 78c6fe5144d7f6da85c1cc10fe241ac07e3f92fe $

DROP TABLE COURSE_GROUP_CD_HDAT
CREATE TABLE COURSE_GROUP_CD_HDAT( \
    YEAR       VARCHAR(4)    NOT NULL, \
    GRADE      VARCHAR(2)    NOT NULL, \
    GROUP_CD   VARCHAR(3)    NOT NULL, \
    GROUP_NAME VARCHAR(60), \
    GROUP_ABBV VARCHAR(60), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COURSE_GROUP_CD_HDAT ADD CONSTRAINT PK_CSE_GRP_CD_HDAT PRIMARY KEY (YEAR,GRADE,GROUP_CD)