-- kanji=Š¿Žš
-- $Id: 7d97325b8713294055116f15d5ec1e6557f03410 $

DROP TABLE COURSE_GROUP_CD_DAT
CREATE TABLE COURSE_GROUP_CD_DAT( \
    YEAR       VARCHAR(4)    NOT NULL, \
    GRADE      VARCHAR(2)    NOT NULL, \
    GROUP_CD   VARCHAR(3)    NOT NULL, \
    COURSECD   VARCHAR(1)    NOT NULL, \
    MAJORCD    VARCHAR(3)    NOT NULL, \
    COURSECODE VARCHAR(4)    NOT NULL, \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COURSE_GROUP_CD_DAT ADD CONSTRAINT PK_CSE_GRP_CD_DAT PRIMARY KEY (YEAR,GRADE,GROUP_CD,COURSECD,MAJORCD,COURSECODE)