-- kanji=漢字
-- $Id: a6b324259735cc2b872d82947839987659bc3ece $

-- 注意:このファイルは EUC/LFのみ でなければならない。
-- 適用方法:
--    1.データベース接続
--    2.db2 +c -f <このファイル>
--    3.コミットするなら、db2 +c commit。やり直すなら、db2 +c rollback
--

DROP TABLE COURSECODE_MST

CREATE TABLE COURSECODE_MST( \
    COURSECODE      VARCHAR(4)    NOT NULL, \
    COURSECODENAME  VARCHAR(60), \
    COURSECODEABBV1 VARCHAR(60), \
    COURSECODEABBV2 VARCHAR(60), \
    COURSECODEABBV3 VARCHAR(60), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COURSECODE_MST ADD CONSTRAINT PK_COURSECODE_MST PRIMARY KEY (COURSECODE)