-- kanji=漢字
-- $Id: c304db0d8f846ad9585e11e2f9668b1ebb839f71 $

DROP TABLE COURSE_HOPE_DETAIL_DAT
CREATE TABLE COURSE_HOPE_DETAIL_DAT( \
    ENTRYDATE         DATE          NOT NULL, \
    SEQ               INTEGER       NOT NULL, \
    SCHREGNO          VARCHAR(8)    NOT NULL, \
    HOPE_NUM          INTEGER       NOT NULL, \
    SCHOOL_GROUP      VARCHAR(2), \
    FACULTY_GROUP     VARCHAR(3), \
    DEPARTMENT_GROUP  VARCHAR(3), \
    SCHOOL_CD         VARCHAR(12), \
    FACULTYCD         VARCHAR(3), \
    DEPARTMENTCD      VARCHAR(3), \
    HOWTOEXAM         INTEGER, \
    JOBTYPE_LCD       VARCHAR(2), \
    JOBTYPE_MCD       VARCHAR(2), \
    JOBTYPE_SCD       VARCHAR(3), \
    WORK_AREA         VARCHAR(1), \
    INTRODUCTION_DIV  VARCHAR(1), \
    REGISTERCD        VARCHAR(10), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COURSE_HOPE_DETAIL_DAT ADD CONSTRAINT PK_COURSE_HOPE_DET PRIMARY KEY (ENTRYDATE, SEQ, SCHREGNO, HOPE_NUM)