-- $Id: 8567ac159c07570d48f0224816a915ca5c541c99 $

DROP TABLE COURSE_INTERVIEW_DAT_OLD

RENAME TABLE COURSE_INTERVIEW_DAT TO COURSE_INTERVIEW_DAT_OLD

CREATE TABLE COURSE_INTERVIEW_DAT (                         \
   YEAR              VARCHAR(4)    NOT NULL,                \
   SCHREGNO          VARCHAR(8)    NOT NULL,                \
   INTERVIEW_DIV     VARCHAR(3)    NOT NULL,                \
   INTERVIEW_REMARK  VARCHAR(500),                          \
   REGISTERCD        VARCHAR(10),                           \
   UPDATED           TIMESTAMP    DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COURSE_INTERVIEW_DAT ADD CONSTRAINT PK_CORS_INTV_DAT PRIMARY KEY (YEAR, SCHREGNO, INTERVIEW_DIV)

