-- $Id: e7e4ddf11506ba7bc266c848d1dd751d47461f4a $

DROP TABLE DELBK_CERTIF_ISSUE_DAT
CREATE TABLE DELBK_CERTIF_ISSUE_DAT ( \
     DEL_SEQ        SMALLINT   NOT NULL, \
     YEAR           VARCHAR(4)  NOT NULL, \
     CERTIF_INDEX   VARCHAR(5)  NOT NULL, \
     SCHREGNO       VARCHAR(8), \
     CERTIF_KINDCD  VARCHAR(3), \
     GRADUATE_FLG   VARCHAR(1), \
     APPLYDATE      DATE, \
     ISSUERNAME     VARCHAR(40), \
     ISSUECD        VARCHAR(1), \
     CERTIF_NO      SMALLINT, \
     ISSUEDATE      DATE, \
     CHARGE         VARCHAR(1), \
     PRINTCD        VARCHAR(1), \
     REGISTERCD     VARCHAR(8), \
     UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
     DEL_REGISTERCD     VARCHAR(8), \
     DEL_UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_CERTIF_ISSUE_DAT ADD CONSTRAINT PK_DLBK_CERTISSUE PRIMARY KEY \
    (DEL_SEQ, YEAR, CERTIF_INDEX)


