-- $Id: 6075e8ec036bd6985a3ee88cb70871e74525edfa $

DROP TABLE DELBK_CHAIR_STD_DAT
CREATE TABLE DELBK_CHAIR_STD_DAT ( \
       DEL_SEQ             SMALLINT      NOT NULL, \
       YEAR                VARCHAR(4)    NOT NULL, \
       SEMESTER            VARCHAR(1)    NOT NULL, \
       CHAIRCD             VARCHAR(7)    NOT NULL, \
       APPDATE             DATE          NOT NULL, \
       SCHREGNO            VARCHAR(8)    NOT NULL, \
       ROW                 VARCHAR(2), \
       COLUMN              VARCHAR(2), \
       REGISTERCD          VARCHAR(8), \
       UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
       DEL_REGISTERCD      VARCHAR(8), \
       DEL_UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
      ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_CHAIR_STD_DAT ADD CONSTRAINT PK_DLBK_CHAIR_STD PRIMARY KEY \
      (DEL_SEQ,YEAR,SEMESTER,CHAIRCD,APPDATE,SCHREGNO)
