-- $Id: 0db3bbf29f9111ace680bcdfcb001c71b46cf9cd $

DROP TABLE DELBK_SCHREG_REGD_DAT
CREATE TABLE DELBK_SCHREG_REGD_DAT ( \
    DEL_SEQ           SMALLINT        NOT NULL, \
    SCHREGNO          VARCHAR(8)      NOT NULL, \
    YEAR              VARCHAR(4)      NOT NULL, \
    SEMESTER          VARCHAR(1)      NOT NULL, \
    GRADE             VARCHAR(2), \
    HR_CLASS          VARCHAR(3), \
    ATTENDNO          VARCHAR(3), \
    ANNUAL            VARCHAR(2), \
    SEAT_ROW          VARCHAR(2), \
    SEAT_COL          VARCHAR(2), \
    COURSECD          VARCHAR(1), \
    MAJORCD           VARCHAR(3), \
    COURSECODE        VARCHAR(4), \
    REGISTERCD        VARCHAR(8), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    DEL_REGISTERCD    VARCHAR(8), \
    DEL_UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_SCHREG_REGD_DAT ADD CONSTRAINT PK_DLBK_SHG_REGD PRIMARY KEY (DEL_SEQ, SCHREGNO, YEAR, SEMESTER)
