-- $Id: c2ebb78d35233fdf176a975530ce35c2eede072f $

DROP TABLE DELBK_SCHREG_DETAILHIST_DAT
CREATE TABLE DELBK_SCHREG_DETAILHIST_DAT ( \
    DEL_SEQ            SMALLINT      NOT NULL, \
    YEAR               VARCHAR(4) NOT NULL, \
    SCHREGNO           VARCHAR(8) NOT NULL, \
    DETAIL_DIV         VARCHAR(1) NOT NULL, \
    DETAIL_SDATE       DATE       NOT NULL, \
    DETAIL_EDATE       DATE, \
    DETAILCD           VARCHAR(2), \
    CONTENT            VARCHAR(120), \
    REMARK             VARCHAR(60), \
    BICYCLE_CD         VARCHAR(8), \
    BICYCLE_NO         VARCHAR(4), \
    REGISTERCD         VARCHAR(8), \
    UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    DEL_REGISTERCD     VARCHAR(8), \
    DEL_UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_SCHREG_DETAILHIST_DAT ADD CONSTRAINT PK_DLBK_SHG_DTLHST PRIMARY KEY (DEL_SEQ, YEAR,SCHREGNO,DETAIL_DIV,DETAIL_SDATE )
