-- $Id: af8731fda7c5cfdd248a03671caa9631a077d4a6 $

DROP TABLE DELBK_SCHREG_TRAIN_DAT
CREATE TABLE DELBK_SCHREG_TRAIN_DAT( \
    DEL_SEQ              SMALLINT NOT NULL, \
    YEAR                 VARCHAR(4)    NOT NULL, \
    SEMESTER             VARCHAR(1)    NOT NULL, \
    SCHREGNO             VARCHAR(8)    NOT NULL, \
    CAUTION_GUIDANCE     VARCHAR(1), \
    ADMONITION_GUIDANCE  VARCHAR(1), \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    DEL_REGISTERCD       VARCHAR(8), \
    DEL_UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_SCHREG_TRAIN_DAT ADD CONSTRAINT PK_DLBK_SCH_TRAIN PRIMARY KEY (DEL_SEQ, YEAR,SEMESTER,SCHREGNO)


