-- $Id: ea7c0b3c83aeb6625b7aa155f8ef6222588bb301 $

DROP TABLE DELBK_SCHREG_STUDYREC_DAT
CREATE TABLE DELBK_SCHREG_STUDYREC_DAT( \
    DEL_SEQ          SMALLINT      NOT NULL, \
    SCHOOLCD         VARCHAR(1)    NOT NULL, \
    YEAR             VARCHAR(4)    NOT NULL, \
    SCHREGNO         VARCHAR(8)    NOT NULL, \
    ANNUAL           VARCHAR(2)    NOT NULL, \
    CLASSCD          VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND      VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD    VARCHAR(2)    NOT NULL, \
    SUBCLASSCD       VARCHAR(6)    NOT NULL, \
    CLASSNAME        VARCHAR(30), \
    CLASSABBV        VARCHAR(15), \
    CLASSNAME_ENG    VARCHAR(40), \
    CLASSABBV_ENG    VARCHAR(30), \
    SUBCLASSES       SMALLINT, \
    SUBCLASSNAME     VARCHAR(90), \
    SUBCLASSABBV     VARCHAR(90), \
    SUBCLASSNAME_ENG VARCHAR(40), \
    SUBCLASSABBV_ENG VARCHAR(20), \
    VALUATION        SMALLINT, \
    GET_CREDIT       SMALLINT, \
    ADD_CREDIT       SMALLINT, \
    COMP_CREDIT      SMALLINT, \
    PRINT_FLG        VARCHAR(1), \
    REGISTERCD       VARCHAR(8), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    DEL_REGISTERCD   VARCHAR(8), \
    DEL_UPDATED      TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_SCHREG_STUDYREC_DAT ADD CONSTRAINT PK_DLBK_SHG_STDYRC PRIMARY KEY (DEL_SEQ, SCHOOLCD,YEAR,SCHREGNO,ANNUAL,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)