-- $Id: a900d40f1fc02247fe7542a080ef739eec777930 $

DROP   TABLE DELBK_SCHREG_QUALIFIED_DAT
CREATE TABLE DELBK_SCHREG_QUALIFIED_DAT( \
     DEL_SEQ            SMALLINT   NOT NULL, \
     YEAR               VARCHAR(4) NOT NULL, \
     SCHREGNO           VARCHAR(8) NOT NULL, \
     SEQ                SMALLINT   NOT NULL, \
     REGDDATE           DATE       NOT NULL, \
     CLASSCD            VARCHAR(2) NOT NULL, \
     SCHOOL_KIND        VARCHAR(2) NOT NULL, \
     CURRICULUM_CD      VARCHAR(2) NOT NULL, \
     SUBCLASSCD         VARCHAR(6) NOT NULL, \
     CONDITION_DIV      VARCHAR(1), \
     CONTENTS           VARCHAR(90), \
     REMARK             VARCHAR(90), \
     CREDITS            SMALLINT, \
     REGISTERCD         VARCHAR(8), \
     UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
     DEL_REGISTERCD     VARCHAR(8), \
     DEL_UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_SCHREG_QUALIFIED_DAT ADD CONSTRAINT PK_SCH_QUAL_DAT PRIMARY KEY (DEL_SEQ, YEAR,SCHREGNO,SEQ)

