-- $Id: 912c61778710ee9ea734829ab0ae7bfdebcc5a24 $

DROP TABLE DELBK_ATTEND_SUBCLASS_DAT
CREATE TABLE DELBK_ATTEND_SUBCLASS_DAT( \
    DEL_SEQ        SMALLINT   NOT NULL, \
    COPYCD         VARCHAR(1) NOT NULL, \
    YEAR           VARCHAR(4) NOT NULL, \
    MONTH          VARCHAR(2) NOT NULL, \
    SEMESTER       VARCHAR(1) NOT NULL, \
    SCHREGNO       VARCHAR(8) NOT NULL, \
    CLASSCD        VARCHAR(2) NOT NULL, \
    SCHOOL_KIND    VARCHAR(2) NOT NULL, \
    CURRICULUM_CD  VARCHAR(2) NOT NULL, \
    SUBCLASSCD     VARCHAR(6) NOT NULL, \
    APPOINTED_DAY  VARCHAR(2), \
    LESSON         SMALLINT, \
    OFFDAYS        SMALLINT, \
    ABSENT         SMALLINT, \
    SUSPEND        SMALLINT, \
    MOURNING       SMALLINT, \
    ABROAD         SMALLINT, \
    SICK           SMALLINT, \
    NOTICE         SMALLINT, \
    NONOTICE       SMALLINT, \
    NURSEOFF       SMALLINT, \
    LATE           SMALLINT, \
    EARLY          SMALLINT, \
    VIRUS          SMALLINT, \
    KOUDOME        SMALLINT, \
    REGISTERCD     VARCHAR(8), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    DEL_REGISTERCD     VARCHAR(8), \
    DEL_UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_ATTEND_SUBCLASS_DAT ADD CONSTRAINT PK_DLBK_AT_SUBCL PRIMARY KEY (DEL_SEQ, COPYCD,YEAR,MONTH,SCHREGNO,SEMESTER,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)

