-- $Id: 353c7029c5d832912056be22ae31b4fcee288ff2 $

DROP TABLE DELBK_SCHREG_RELA_DAT
CREATE TABLE DELBK_SCHREG_RELA_DAT ( \
     DEL_SEQ              SMALLINT NOT NULL, \
     SCHREGNO             VARCHAR(8) NOT NULL, \
     RELANO               VARCHAR(2) NOT NULL, \
     RELANAME             VARCHAR(60), \
     RELAKANA             VARCHAR(120), \
     RELASEX              VARCHAR(1), \
     RELABIRTHDAY         DATE, \
     OCCUPATION           VARCHAR(60), \
     REGIDENTIALCD        VARCHAR(2), \
     RELATIONSHIP         VARCHAR(2), \
     RELA_SCHREGNO        VARCHAR(2), \
     REMARK               VARCHAR(45), \
     REGISTERCD           VARCHAR(8), \
     UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
     DEL_REGISTERCD       VARCHAR(8), \
     DEL_UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_SCHREG_RELA_DAT ADD CONSTRAINT PK_DLBK_SCH_RELA PRIMARY KEY (DEL_SEQ, SCHREGNO, RELANO)