-- $Id: c3da6e10605de7cdbdb2b1ae3316a854c78cce2e $

DROP TABLE DELBK_SCHREG_TRAINHIST_DAT
CREATE TABLE DELBK_SCHREG_TRAINHIST_DAT( \
    DEL_SEQ             SMALLINT      NOT NULL, \
    YEAR                VARCHAR(4)    NOT NULL, \
    TRAINDATE           DATE          NOT NULL, \
    SCHREGNO            VARCHAR(8)    NOT NULL, \
    PATIENTCD           VARCHAR(2), \
    STAFFCD             VARCHAR(8), \
    HOWTOTRAINCD        VARCHAR(2), \
    CONTENT             VARCHAR(458), \
    REGISTERCD          VARCHAR(8), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    DEL_REGISTERCD      VARCHAR(8), \
    DEL_UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_SCHREG_TRAINHIST_DAT ADD CONSTRAINT PK_DLBK_SCH_THIST PRIMARY KEY (DEL_SEQ, YEAR,TRAINDATE,SCHREGNO)