-- $Id: 0d7d986b4ec20434c8684315e317d6e999d19fae $

DROP TABLE DELBK_HEXAM_ENTREMARK_HDAT

CREATE TABLE DELBK_HEXAM_ENTREMARK_HDAT ( \
     DEL_SEQ             SMALLINT      NOT NULL, \
     SCHREGNO       VARCHAR(8) NOT NULL, \
     COMMENTEX_A_CD VARCHAR(1), \
     DISEASE        VARCHAR(259), \
     DOC_REMARK     VARCHAR(90), \
     TR_REMARK      VARCHAR(159), \
     TOTALSTUDYACT  VARCHAR(746), \
     TOTALSTUDYVAL  VARCHAR(845), \
     BEHAVEREC_REMARK   VARCHAR(845), \
     HEALTHREC          VARCHAR(845), \
     SPECIALACTREC      VARCHAR(845), \
     TRIN_REF           VARCHAR(1248), \
     REMARK             VARCHAR(1500), \
     REGISTERCD         VARCHAR(8), \
     UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
     DEL_REGISTERCD     VARCHAR(8), \
     DEL_UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_HEXAM_ENTREMARK_HDAT ADD CONSTRAINT PK_DLBK_HXM_ETRK_H PRIMARY KEY (DEL_SEQ, SCHREGNO)
