-- $Id: 91257dd8776e86bd0cd252ca55b1c196d7e98e7d $

DROP TABLE DELBK_HREPORTREMARK_DAT
CREATE TABLE DELBK_HREPORTREMARK_DAT( \
    DEL_SEQ          SMALLINT      NOT NULL, \
    YEAR             VARCHAR(4)    NOT NULL, \
    SEMESTER         VARCHAR(1)    NOT NULL, \
    SCHREGNO         VARCHAR(8)    NOT NULL, \
    TOTALSTUDYTIME   VARCHAR(500), \
    SPECIALACTREMARK VARCHAR(323), \
    COMMUNICATION    VARCHAR(500), \
    REMARK1          VARCHAR(323), \
    REMARK2          VARCHAR(323), \
    REMARK3          VARCHAR(780), \
    FOREIGNLANGACT   VARCHAR(450), \
    ATTENDREC_REMARK VARCHAR(242), \
    REGISTERCD       VARCHAR(8), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    DEL_REGISTERCD   VARCHAR(8), \
    DEL_UPDATED      TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_HREPORTREMARK_DAT ADD CONSTRAINT PK_DLBK_HRPRTRK PRIMARY KEY (DEL_SEQ,YEAR,SEMESTER,SCHREGNO)