-- $Id: efc93aea219fa6d6acac91392388e3e36fd3cc93 $

DROP TABLE DELBK_SCHREG_ATTENDREC_DAT
CREATE TABLE DELBK_SCHREG_ATTENDREC_DAT ( \
     DEL_SEQ              SMALLINT   NOT NULL, \
     SCHOOLCD             VARCHAR(1) NOT NULL, \
     YEAR                 VARCHAR(4) NOT NULL, \
     SCHREGNO             VARCHAR(8) NOT NULL, \
     ANNUAL               VARCHAR(2) NOT NULL, \
     SUMDATE              DATE, \
     CLASSDAYS            SMALLINT, \
     OFFDAYS              SMALLINT, \
     ABSENT               SMALLINT, \
     SUSPEND              SMALLINT, \
     MOURNING             SMALLINT, \
     ABROAD               SMALLINT, \
     REQUIREPRESENT       SMALLINT, \
     SICK                 SMALLINT, \
     ACCIDENTNOTICE       SMALLINT, \
     NOACCIDENTNOTICE     SMALLINT, \
     PRESENT              SMALLINT, \
     REGISTERCD           VARCHAR(8), \
     UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
     DEL_REGISTERCD       VARCHAR(8), \
     DEL_UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_SCHREG_ATTENDREC_DAT ADD CONSTRAINT PK_DLBK_SHG_ATNDRC PRIMARY KEY (DEL_SEQ, SCHOOLCD, YEAR, SCHREGNO)

