-- $Id: 4f50da66a08531f7f812d7f664f415421d7c4514 $

DROP TABLE DELBK_STUDYRECREMARK_DAT
CREATE TABLE DELBK_STUDYRECREMARK_DAT( \
    DEL_SEQ         SMALLINT      NOT NULL, \
    YEAR            VARCHAR(4)    NOT NULL, \
    SCHREGNO        VARCHAR(8)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    REMARK          VARCHAR(150), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    DEL_REGISTERCD  VARCHAR(8), \
    DEL_UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_STUDYRECREMARK_DAT ADD CONSTRAINT PK_STUDYCLASS_DAT PRIMARY KEY (DEL_SEQ,YEAR,SCHREGNO,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)