-- $Id: ce136b8ae83acf2f5f4f2179969642f17bb61320 $

DROP TABLE DELBK_SCHREG_TRANSFER_DAT
CREATE TABLE DELBK_SCHREG_TRANSFER_DAT ( \
     DEL_SEQ          SMALLINT      NOT NULL, \
     SCHREGNO         VARCHAR(8)    NOT NULL, \
     TRANSFERCD       VARCHAR(2)    NOT NULL, \
     TRANSFER_SDATE   DATE          NOT NULL, \
     TRANSFER_EDATE   DATE, \
     TRANSFERREASON   VARCHAR(75), \
     TRANSFERPLACE    VARCHAR(60), \
     TRANSFERADDR     VARCHAR(150), \
     TRANSFERADDR2    VARCHAR(150), \
     ABROAD_CLASSDAYS SMALLINT, \
     ABROAD_CREDITS   SMALLINT, \
     REGISTERCD       VARCHAR(8), \
     UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
     DEL_REGISTERCD   VARCHAR(8), \
     DEL_UPDATED      TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    )IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_SCHREG_TRANSFER_DAT ADD CONSTRAINT PK_DLBK_SHG_TRANS PRIMARY KEY \
    (SCHREGNO, TRANSFERCD, TRANSFER_SDATE)
