-- $Id: d34b20f6a3381d8a0a962ce51088eab406c4abab $

DROP TABLE DELBK_STUDYCLASSREMARK_DAT
CREATE TABLE DELBK_STUDYCLASSREMARK_DAT( \
     DEL_SEQ        SMALLINT    NOT NULL, \
     YEAR           VARCHAR(4)  NOT NULL, \
     SCHREGNO       VARCHAR(8)  NOT NULL, \
     CLASSCD        VARCHAR(2)  NOT NULL, \
     SCHOOL_KIND    VARCHAR(2)  NOT NULL, \
     CURRICULUM_CD  VARCHAR(2)  NOT NULL, \
     SUBCLASSCD     VARCHAR(6)  NOT NULL, \
     REMARK         VARCHAR(60), \
     REGISTERCD     VARCHAR(8), \
     UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
     DEL_REGISTERCD         VARCHAR(8), \
     DEL_UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
 ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_STUDYCLASSREMARK_DAT ADD CONSTRAINT PK_STUDYCLASSREMAR PRIMARY KEY \
  (DEL_SEQ, YEAR, SCHREGNO, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)


