-- $Id: d2ee9d0ed28718d9f85c9347accc842abe36fb64 $

DROP TABLE DELBK_CLASS_FORMATION_DAT
CREATE TABLE DELBK_CLASS_FORMATION_DAT ( \
     DEL_SEQ             SMALLINT   NOT NULL, \
     SCHREGNO            VARCHAR(8) NOT NULL, \
     YEAR                VARCHAR(4) NOT NULL, \
     SEMESTER            VARCHAR(1) NOT NULL, \
     GRADE               VARCHAR(2), \
     HR_CLASS            VARCHAR(2), \
     ATTENDNO            VARCHAR(3), \
     COURSECD            VARCHAR(1), \
     MAJORCD             VARCHAR(3), \
     COURSECODE          VARCHAR(4), \
     REMAINGRADE_FLG     VARCHAR(1), \
     OLD_GRADE           VARCHAR(2), \
     OLD_HR_CLASS        VARCHAR(2), \
     OLD_ATTENDNO        VARCHAR(3), \
     REGISTERCD          VARCHAR(8), \
     UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
     DEL_REGISTERCD      VARCHAR(8), \
     DEL_UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_CLASS_FORMATION_DAT ADD CONSTRAINT PK_DLBK_CLS_FRMTON PRIMARY KEY (DEL_SEQ,SCHREGNO,YEAR,SEMESTER)
