-- $Id: 6e3138769181f560c587e4e5d81810a237e6fba1 $

DROP TABLE DELBK_SCHREG_ADDRESS_DAT
CREATE TABLE DELBK_SCHREG_ADDRESS_DAT( \
    DEL_SEQ    SMALLINT      NOT NULL, \
    SCHREGNO   VARCHAR(8)    NOT NULL, \
    ISSUEDATE  DATE          NOT NULL, \
    EXPIREDATE DATE, \
    ZIPCD      VARCHAR(8), \
    AREACD     VARCHAR(2), \
    ADDR1      VARCHAR(150), \
    ADDR2      VARCHAR(150), \
    ADDR_FLG   VARCHAR(1), \
    ADDR1_ENG  VARCHAR(150), \
    ADDR2_ENG  VARCHAR(150), \
    TELNO      VARCHAR(14), \
    FAXNO      VARCHAR(14), \
    EMAIL      VARCHAR(20), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    DEL_REGISTERCD      VARCHAR(8), \
    DEL_UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_SCHREG_ADDRESS_DAT ADD CONSTRAINT PK_DLBK_SHG_ADRS PRIMARY KEY (DEL_SEQ, SCHREGNO,ISSUEDATE)