-- $Id: 3ea4b1e3b1cc6b5435aa85d754d4cd3da60a6bd6 $

DROP TABLE DELBK_FRESHMAN_DAT
CREATE TABLE DELBK_FRESHMAN_DAT( \
    DEL_SEQ           SMALLINT      NOT NULL, \
    ENTERYEAR         VARCHAR(4)    NOT NULL, \
    SCHREGNO          VARCHAR(8)    NOT NULL, \
    ENT_DIV           VARCHAR(1), \
    HR_CLASS          VARCHAR(3), \
    ATTENDNO          VARCHAR(3), \
    INOUTCD           VARCHAR(1), \
    COURSECD          VARCHAR(1), \
    MAJORCD           VARCHAR(3), \
    COURSECODE        VARCHAR(4), \
    NAME              VARCHAR(120), \
    NAME_KANA         VARCHAR(240), \
    BIRTHDAY          DATE, \
    SEX               VARCHAR(1), \
    FINSCHOOLCD       VARCHAR(7), \
    FINSCHOOLGRADDATE DATE, \
    ZIPCD             VARCHAR(8), \
    ADDR1             VARCHAR(150), \
    ADDR2             VARCHAR(150), \
    TELNO             VARCHAR(14), \
    FAXNO             VARCHAR(14), \
    EMAIL             VARCHAR(20), \
    EMERGENCYCALL     VARCHAR(60), \
    EMERGENCYTELNO    VARCHAR(14), \
    SCALASHIPDIV      VARCHAR(2), \
    CURRICULUM_YEAR   VARCHAR(4), \
    EXAMNO            VARCHAR(10), \
    AREACD            VARCHAR(2), \
    REGISTERCD        VARCHAR(8), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    DEL_REGISTERCD    VARCHAR(8), \
    DEL_UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_FRESHMAN_DAT ADD CONSTRAINT PK_DLBK_FRESHMAN PRIMARY KEY (DEL_SEQ, ENTERYEAR,SCHREGNO)