-- $Id: 7f697adbf17ca25b523fb6e9b075616709d01091 $

DROP TABLE DELBK_SCHREG_BASE_DETAIL_MST
CREATE TABLE DELBK_SCHREG_BASE_DETAIL_MST ( \
     DEL_SEQ             SMALLINT      NOT NULL, \
     SCHREGNO            VARCHAR(8)    NOT NULL, \
     BASE_SEQ            VARCHAR(3)    NOT NULL, \
     BASE_REMARK1        VARCHAR(768), \
     BASE_REMARK2        VARCHAR(768), \
     BASE_REMARK3        VARCHAR(768), \
     BASE_REMARK4        VARCHAR(768), \
     BASE_REMARK5        VARCHAR(768), \
     BASE_REMARK6        VARCHAR(768), \
     REGISTERCD          VARCHAR(8), \
     UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
     DEL_REGISTERCD      VARCHAR(8), \
     DEL_UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_SCHREG_BASE_DETAIL_MST ADD CONSTRAINT PK_DLBK_SHG_BASE PRIMARY KEY (DEL_SEQ, SCHREGNO, BASE_SEQ)
