-- $Id: 8b41ee06dc04fc465aae9b0458d29af0f14bc59d $

DROP TABLE DELBK_HTRAINREMARK_DAT
CREATE TABLE DELBK_HTRAINREMARK_DAT( \
    DEL_SEQ          SMALLINT      NOT NULL, \
    YEAR             VARCHAR(4)    NOT NULL, \
    SCHREGNO         VARCHAR(8)    NOT NULL, \
    ANNUAL           VARCHAR(2)    NOT NULL, \
    TOTALSTUDYACT    VARCHAR(678), \
    TOTALSTUDYVAL    VARCHAR(678), \
    SPECIALACTREMARK VARCHAR(678), \
    TOTALREMARK      VARCHAR(1740), \
    ATTENDREC_REMARK VARCHAR(242), \
    VIEWREMARK       VARCHAR(300), \
    BEHAVEREC_REMARK VARCHAR(122), \
    CLASSACT         VARCHAR(300), \
    STUDENTACT       VARCHAR(218), \
    CLUBACT          VARCHAR(225), \
    SCHOOLEVENT      VARCHAR(218), \
    REGISTERCD       VARCHAR(8), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    DEL_REGISTERCD   VARCHAR(8), \
    DEL_UPDATED      TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_HTRAINREMARK_DAT ADD CONSTRAINT PK_DLBK_HTRAINRK PRIMARY KEY (DEL_SEQ, YEAR,SCHREGNO)