-- $Id: 2d80419249acd1ad88f98a1475bc01fa902711d1 $

DROP TABLE DELBK_HEXAM_ENTREMARK_DAT
CREATE TABLE DELBK_HEXAM_ENTREMARK_DAT( \
    DEL_SEQ          SMALLINT      NOT NULL, \
    YEAR             VARCHAR(4)    NOT NULL, \
    SCHREGNO         VARCHAR(8)    NOT NULL, \
    ANNUAL           VARCHAR(2)    NOT NULL, \
    ATTENDREC_REMARK VARCHAR(238), \
    SPECIALACTREC    VARCHAR(468), \
    TRAIN_REF        VARCHAR(1248), \
    TRAIN_REF1       VARCHAR(453), \
    TRAIN_REF2       VARCHAR(520), \
    TRAIN_REF3       VARCHAR(800), \
    TOTALSTUDYACT    VARCHAR(746), \
    TOTALSTUDYVAL    VARCHAR(746), \
    CALSSACT         VARCHAR(300), \
    STUDENTACT       VARCHAR(218), \
    CLUBACT          VARCHAR(225), \
    SCHOOLEVENT      VARCHAR(218), \
    REGISTERCD       VARCHAR(8), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    DEL_REGISTERCD      VARCHAR(8), \
    DEL_UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DELBK_HEXAM_ENTREMARK_DAT ADD CONSTRAINT PK_DLBK_HEXAM_ENT PRIMARY KEY (DEL_SEQ, YEAR,SCHREGNO)