-- $Id: e5ff5cff05ae9123a132f5ba91a4e4e4ec78c5ae $

DROP TABLE DUTYSHARE_MST
CREATE TABLE DUTYSHARE_MST( \
    DUTYSHARECD      VARCHAR(4)    NOT NULL, \
    SHARENAME       VARCHAR(24), \
    BASE_SHARENAME  VARCHAR(60), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DUTYSHARE_MST ADD CONSTRAINT PK_DUTYSHARE_MST PRIMARY KEY (DUTYSHARECD)
