-- $Id: e0bb04e66baba7c60cd915384978d40d455f62c1 $

DROP TABLE DUTYSHARE_YDAT
CREATE TABLE DUTYSHARE_YDAT( \
    YEAR            VARCHAR(4)    NOT NULL, \
    DUTYSHARECD     VARCHAR(4)    NOT NULL, \
    REGISTERCD      VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DUTYSHARE_YDAT ADD CONSTRAINT PK_DUTYSHARE_YDAT PRIMARY KEY (YEAR, DUTYSHARECD)
