-- $Id: 5ae6303f4c2afe3ac155262ae887280f93896a9d $

DROP TABLE EDBOARD_COURSECODE_YDAT
CREATE TABLE EDBOARD_COURSECODE_YDAT( \
    EDBOARD_SCHOOLCD    VARCHAR(12)     NOT NULL, \
    YEAR                VARCHAR(4)      NOT NULL, \
    COURSECODE          VARCHAR(4)      NOT NULL, \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_COURSECODE_YDAT ADD CONSTRAINT \
PK_ED_COURSECODE_Y PRIMARY KEY (EDBOARD_SCHOOLCD, YEAR, COURSECODE)
