-- $Id: 156ad73235f77742f90f33fbc133a4eedf6f04dc $

drop table EDBOARD_STAFF_DAT

CREATE TABLE EDBOARD_STAFF_DAT( \
    EDBOARD_SCHOOLCD      VARCHAR(12) NOT NULL, \
    STAFFCD               VARCHAR(10)  NOT NULL, \
    STAFF_DIV             VARCHAR(1)  NOT NULL, \
    REMARK                VARCHAR(120), \
    REGISTERCD            VARCHAR(10), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_STAFF_DAT ADD CONSTRAINT PK_ED_STAFF_DAT PRIMARY KEY (EDBOARD_SCHOOLCD, STAFFCD)
