-- $Id: 389a73525c07a9c22c7cd857fac9867ddac7f02c $

DROP TABLE EDBOARD_FINSCHOOL_DAT
CREATE TABLE EDBOARD_FINSCHOOL_DAT( \
    EDBOARD_SCHOOLCD    VARCHAR(12)  NOT NULL, \
    FINSCHOOLCD         VARCHAR(12)  NOT NULL, \
    EDBOARD_FLG         VARCHAR(1), \
    REGISTERCD          VARCHAR(8), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_FINSCHOOL_DAT ADD CONSTRAINT PK_ED_FINSCHL_DAT PRIMARY KEY (EDBOARD_SCHOOLCD, FINSCHOOLCD)