-- $Id: f59b015b14452a2f40066dae1a4ee07be8c8cd10 $

drop table EDBOARD_STAFF_COPY_ERR_DAT

CREATE TABLE EDBOARD_STAFF_COPY_ERR_DAT( \
    EDBOARD_SCHOOLCD      VARCHAR(12) NOT NULL, \
    STAFFCD               VARCHAR(10) NOT NULL, \
    ERR_MSG               VARCHAR(60), \
    REGISTERCD            VARCHAR(10), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

