-- $Id: c69451d21fa4c38db805ab75814172017cf0f0b7 $

DROP TABLE EDBOARD_JOB_DAT
CREATE TABLE EDBOARD_JOB_DAT( \
    EDBOARD_SCHOOLCD   VARCHAR(12)   NOT NULL, \
    JOBCD              VARCHAR(4)    NOT NULL, \
    EDBOARD_FLG        VARCHAR(1), \
    REGISTERCD         VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_JOB_DAT ADD CONSTRAINT PK_ED_JOB_DAT PRIMARY KEY (EDBOARD_SCHOOLCD, JOBCD)