-- $Id: ab1cdf1c61acd911a7fd06e546eeb686f9063b17 $

DROP TABLE EDBOARD_COURSE_MST
CREATE TABLE EDBOARD_COURSE_MST( \
    EDBOARD_SCHOOLCD    VARCHAR(12)     NOT NULL, \
    COURSECD            VARCHAR(1)      NOT NULL, \
    COURSENAME          VARCHAR(60), \
    COURSEABBV          VARCHAR(60), \
    COURSEENG           VARCHAR(10), \
    S_PERIODCD          VARCHAR(1), \
    E_PERIODCD          VARCHAR(1), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_COURSE_MST ADD CONSTRAINT \
PK_ED_COURSE_MST PRIMARY KEY (EDBOARD_SCHOOLCD, COURSECD)
