-- $Id: 4ecaa7429126e27051a9df115a9eb5ca4a772129 $

drop table EDBOARD_STAFF_WORK_HIST_DAT

CREATE TABLE EDBOARD_STAFF_WORK_HIST_DAT( \
    STAFFCD             VARCHAR(10) NOT NULL, \
    FROM_DATE           DATE        NOT NULL, \
    WORK_DIV            VARCHAR(1)  NOT NULL, \
    FROM_DIV            VARCHAR(2)  NOT NULL, \
    FROM_SCHOOLCD       VARCHAR(12), \
    FROM_COURSECD       VARCHAR(1), \
    TO_DATE             DATE, \
    TO_DIV              VARCHAR(2), \
    TO_SCHOOLCD         VARCHAR(12), \
    TO_COURSECD         VARCHAR(1), \
    REMARK              VARCHAR(150), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_STAFF_WORK_HIST_DAT ADD CONSTRAINT PK_EDB_WORK_HIST PRIMARY KEY (STAFFCD, FROM_DATE, WORK_DIV)
