-- $Id: 34712275a9af30eba81217a36220cc94741fdd6f $

drop table EDBOARD_SCHOOL_DB_DAT

CREATE TABLE EDBOARD_SCHOOL_DB_DAT( \
    EDBOARD_SCHOOLCD      VARCHAR(12) NOT NULL, \
    SRV_ADDR              VARCHAR(60), \
    SRV_PORT              VARCHAR(10), \
    DBNAME                VARCHAR(10), \
    USER                  VARCHAR(30), \
    USERPASS              VARCHAR(30), \
    REGISTERCD            VARCHAR(10), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_SCHOOL_DB_DAT ADD CONSTRAINT PK_EDBOARD_DB PRIMARY KEY (EDBOARD_SCHOOLCD)
