-- $Id: 34c3da8a7cb16e6c37063e7a42cdfa492e4e2b8f $

DROP TABLE EDBOARD_SUBCLASS_DAT
CREATE TABLE EDBOARD_SUBCLASS_DAT( \
    EDBOARD_SCHOOLCD   VARCHAR(12)   NOT NULL, \
    CLASSCD            VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND        VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD      VARCHAR(2)    NOT NULL, \
    SUBCLASSCD         VARCHAR(6)    NOT NULL, \
    EDBOARD_FLG        VARCHAR(1), \
    REGISTERCD         VARCHAR(8), \
    UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_SUBCLASS_DAT ADD CONSTRAINT PK_ED_SUBCLASS_DAT PRIMARY KEY (EDBOARD_SCHOOLCD, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)