-- $Id: 305dfb0bfee7436a586b6ab00c0de39d5108e315 $

DROP TABLE EDBOARD_MAJOR_MST
CREATE TABLE EDBOARD_MAJOR_MST( \
    EDBOARD_SCHOOLCD    VARCHAR(12)     NOT NULL, \
    COURSECD            VARCHAR(1)      NOT NULL, \
    MAJORCD             VARCHAR(3)      NOT NULL, \
    MAJORNAME           VARCHAR(60), \
    MAJORNAME2          VARCHAR(60), \
    MAJORNAME3          VARCHAR(60), \
    MAJORABBV           VARCHAR(6), \
    MAJORENG            VARCHAR(45), \
    MAJORBANKCD         VARCHAR(2), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_MAJOR_MST ADD CONSTRAINT \
PK_ED_MAJOR_MST PRIMARY KEY (EDBOARD_SCHOOLCD, COURSECD, MAJORCD)
