-- $Id: 89edafbe9ba46ca453a2eb7839270d1f89485ceb $

drop table EDBOARD_STAFF_CHANGE_SCHOOL_DAT

CREATE TABLE EDBOARD_STAFF_CHANGE_SCHOOL_DAT( \
    STAFFCD               VARCHAR(8)  NOT NULL, \
    EDBOARD_SCHOOLCD      VARCHAR(12) NOT NULL, \
    REGISTERCD            VARCHAR(8), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_STAFF_CHANGE_SCHOOL_DAT ADD CONSTRAINT PK_CHANGE_SCHOOL PRIMARY KEY (STAFFCD, EDBOARD_SCHOOLCD)
