-- kanji=漢字
-- $Id: cb3fa1fabe4debf41565135b483b6feb51b734b7 $

DROP TABLE EDBOARD_MAJOR_DAT
CREATE TABLE EDBOARD_MAJOR_DAT( \
    EDBOARD_SCHOOLCD   VARCHAR(12)   NOT NULL, \
    COURSECD           VARCHAR(1)    NOT NULL, \
    MAJORCD            VARCHAR(3)    NOT NULL, \
    EDBOARD_FLG        VARCHAR(1), \
    REGISTERCD         VARCHAR(8), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS
ALTER TABLE EDBOARD_MAJOR_DAT ADD CONSTRAINT PK_ED_MAJOR_DAT PRIMARY KEY (EDBOARD_SCHOOLCD,COURSECD,MAJORCD)