-- $Id: 20443e4af48a64e386646bfa29aaf998092b5d7b $

DROP TABLE EDBOARD_COURSE_DAT
CREATE TABLE EDBOARD_COURSE_DAT( \
    EDBOARD_SCHOOLCD   VARCHAR(12)   NOT NULL, \
    COURSECD           VARCHAR(1)    NOT NULL, \
    EDBOARD_FLG        VARCHAR(1), \
    REGISTERCD         VARCHAR(8), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_COURSE_DAT ADD CONSTRAINT PK_ED_COURSE_DAT PRIMARY KEY (EDBOARD_SCHOOLCD, COURSECD)