-- $Id: 6b5e700a2f4a3f40bdb30fe65418179939751ead $

drop table EDBOARD_SCHOOL_MST

CREATE TABLE EDBOARD_SCHOOL_MST( \
    EDBOARD_SCHOOLCD      VARCHAR(12)    NOT NULL, \
    EDBOARD_SCHOOLNAME    VARCHAR(60)    NOT NULL, \
    LINK_ADDR             VARCHAR(60), \
    DBNAME                VARCHAR(10), \
    REMARK                VARCHAR(60), \
    GROUPWARE_SCHOOLCD    VARCHAR(12)    NOT NULL, \
    REGISTERCD            VARCHAR(8), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_SCHOOL_MST ADD CONSTRAINT PK_EDBOARD_SCHOOL PRIMARY KEY (EDBOARD_SCHOOLCD)
