-- $Id: 1f75e579776c16297c3c3d94f76780d1821c7b1c $

DROP TABLE EDUCATION_GUIDANCE_SCHREG_REMARK_DAT

CREATE TABLE EDUCATION_GUIDANCE_SCHREG_REMARK_DAT( \
    SCHREGNO                VARCHAR(8)  NOT NULL, \
    YEAR                    VARCHAR(4)  NOT NULL, \
    SEMESTER                VARCHAR(1)  NOT NULL, \
    WRITING_DATE            DATE        NOT NULL, \
    CLASSCD                 VARCHAR(2)  NOT NULL, \
    SCHOOL_KIND             VARCHAR(2)  NOT NULL, \
    CURRICULUM_CD           VARCHAR(2)  NOT NULL, \
    SUBCLASSCD              VARCHAR(6)  NOT NULL, \
    DIV                     VARCHAR(1)  NOT NULL, \
    REMARK1                 VARCHAR(1500), \
    REMARK2                 VARCHAR(1500), \
    REMARK3                 VARCHAR(1500), \
    REMARK4                 VARCHAR(1500), \
    REGISTERCD              VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDUCATION_GUIDANCE_SCHREG_REMARK_DAT ADD CONSTRAINT PK_EDU_GUID_S_REM PRIMARY KEY (SCHREGNO, YEAR, SEMESTER, WRITING_DATE, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, DIV)
