-- $Id: a64fe740cae94712cf51dd566545d9fb56294a35 $

DROP TABLE EDUCATION_GUIDANCE_SCHREG_SUBCLASS_DAT

CREATE TABLE EDUCATION_GUIDANCE_SCHREG_SUBCLASS_DAT( \
    SCHREGNO            VARCHAR(8)  NOT NULL, \
    YEAR                VARCHAR(4)  NOT NULL, \
    SEMESTER            VARCHAR(1)  NOT NULL, \
    CLASSCD             VARCHAR(2)  NOT NULL, \
    SCHOOL_KIND         VARCHAR(2)  NOT NULL, \
    CURRICULUM_CD       VARCHAR(2)  NOT NULL, \
    SUBCLASSCD          VARCHAR(6)  NOT NULL, \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDUCATION_GUIDANCE_SCHREG_SUBCLASS_DAT ADD CONSTRAINT PK_EDU_GUID_S_SUB PRIMARY KEY (SCHREGNO, YEAR, SEMESTER, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)
