-- $Id: 6a81d4bfc7ca7105b343a3c217463cbee03aa08a $

DROP TABLE EDUCATION_GUIDANCE_SCHREG_DAT

CREATE TABLE EDUCATION_GUIDANCE_SCHREG_DAT( \
    SCHREGNO            VARCHAR(8) NOT NULL, \
    YEAR                VARCHAR(4) NOT NULL, \
    SEMESTER            VARCHAR(1) NOT NULL, \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDUCATION_GUIDANCE_SCHREG_DAT ADD CONSTRAINT PK_EDU_GUID_SCH PRIMARY KEY (SCHREGNO, YEAR, SEMESTER)
