-- $Id: 538a5745e83cc0eacab7547137e4103e66273af7 $

DROP TABLE EVENT_SCHREG_DAT

CREATE TABLE EVENT_SCHREG_DAT( \
     SCHREGNO            VARCHAR(8)  NOT NULL, \
     EXECUTEDATE         DATE        NOT NULL, \
     HOLIDAY_FLG         VARCHAR(1), \
     EVENT_ABBV          VARCHAR(9), \
     EVENT_FLG           VARCHAR(1), \
     REMARK1             VARCHAR(150), \
     REMARK2             VARCHAR(150), \
     REGISTERCD          VARCHAR(10), \
     UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EVENT_SCHREG_DAT ADD CONSTRAINT PK_EVENT_SCH_DAT PRIMARY KEY (SCHREGNO, EXECUTEDATE)
