-- kanji=漢字
-- $Id: a513a1027207487103693d0b0859de0970ae8c70 $

DROP TABLE FACULTY_GROUP_MST
CREATE TABLE FACULTY_GROUP_MST( \
    FACULTY_GROUP     VARCHAR(3)    NOT NULL, \
    FACULTY_GROUPNAME VARCHAR(90), \
    REGISTERCD        VARCHAR(8), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE FACULTY_GROUP_MST ADD CONSTRAINT PK_FACULTY_GRP_MST PRIMARY KEY (FACULTY_GROUP)