-- $Id: 619371e9d6adf833e4d376549d7fd076172cae94 $

DROP TABLE GRADE_KIND_SCHREG_UNIT_DAT

CREATE TABLE GRADE_KIND_SCHREG_UNIT_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    SEMESTER            VARCHAR(1) NOT NULL, \
    SCHREGNO            VARCHAR(8) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    CURRICULUM_CD       VARCHAR(2) NOT NULL, \
    SUBCLASSCD          VARCHAR(6) NOT NULL, \
    UNITCD              VARCHAR(2) NOT NULL, \
    UNITNAME            VARCHAR(90), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRADE_KIND_SCHREG_UNIT_DAT ADD CONSTRAINT PK_GK_SCH_UNIT_DAT PRIMARY KEY (YEAR, SEMESTER, SCHREGNO, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, UNITCD)
