-- $Id: 80cc3f2dbce1718da106da247a0c70372e137235 $

DROP TABLE GRADE_KIND_COMP_SUBCLASS_DAT

CREATE TABLE GRADE_KIND_COMP_SUBCLASS_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    CONDITION           VARCHAR(1) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    CURRICULUM_CD       VARCHAR(2) NOT NULL, \
    SUBCLASSCD          VARCHAR(6) NOT NULL, \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRADE_KIND_COMP_SUBCLASS_DAT ADD CONSTRAINT PK_GK_COMP_SUB_D PRIMARY KEY (YEAR, CONDITION, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)
