-- $Id: 27ead8f3fe29f5ff8b8bb93d12308895752a4242 $

DROP TABLE GRADE_KIND_UNIT_GROUP_YMST

CREATE TABLE GRADE_KIND_UNIT_GROUP_YMST( \
    YEAR                VARCHAR(4) NOT NULL, \
    SEMESTER            VARCHAR(1) NOT NULL, \
    GAKUBU_SCHOOL_KIND  VARCHAR(2) NOT NULL, \
    GHR_CD              VARCHAR(2) NOT NULL, \
    GRADE               VARCHAR(2) NOT NULL, \
    HR_CLASS            VARCHAR(3) NOT NULL, \
    CONDITION           VARCHAR(1) NOT NULL, \
    GROUPCD             VARCHAR(4) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    CURRICULUM_CD       VARCHAR(2) NOT NULL, \
    SUBCLASSCD          VARCHAR(6) NOT NULL, \
    UNITCD              VARCHAR(2) NOT NULL, \
    UNITNAME            VARCHAR(180), \
    UNITABBV            VARCHAR(90), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRADE_KIND_UNIT_GROUP_YMST ADD CONSTRAINT PK_GK_UNIT_GP_YMST PRIMARY KEY (YEAR, SEMESTER, GAKUBU_SCHOOL_KIND, GHR_CD, GRADE, HR_CLASS, CONDITION, GROUPCD, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, UNITCD)
