-- $Id: 8c9f9f785b2dd81ae23a9dbc50b95c4032a6e05d $

DROP TABLE GRADE_KIND_COMP_GROUP_YMST

CREATE TABLE GRADE_KIND_COMP_GROUP_YMST( \
    YEAR                VARCHAR(4) NOT NULL, \
    SEMESTER            VARCHAR(1) NOT NULL, \
    GAKUBU_SCHOOL_KIND  VARCHAR(2) NOT NULL, \
    GHR_CD              VARCHAR(2) NOT NULL, \
    GRADE               VARCHAR(2) NOT NULL, \
    HR_CLASS            VARCHAR(3) NOT NULL, \
    CONDITION           VARCHAR(1) NOT NULL, \
    GROUPCD             VARCHAR(4) NOT NULL, \
    GROUPNAME           VARCHAR(90), \
    GROUPABBV           VARCHAR(90), \
    GUIDANCE_PATTERN    VARCHAR(1), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRADE_KIND_COMP_GROUP_YMST ADD CONSTRAINT PK_GK_COMP_GP_MST PRIMARY KEY (YEAR, SEMESTER, GAKUBU_SCHOOL_KIND, GHR_CD, GRADE, HR_CLASS, CONDITION, GROUPCD)
