-- $Id: d8df8660955229b7fd2e86e7592139b3fd8b90b3 $

DROP TABLE GRADE_KIND_SCHREG_GROUP_DAT

CREATE TABLE GRADE_KIND_SCHREG_GROUP_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    SEMESTER            VARCHAR(1) NOT NULL, \
    GAKUBU_SCHOOL_KIND  VARCHAR(2) NOT NULL, \
    GHR_CD              VARCHAR(2) NOT NULL, \
    GRADE               VARCHAR(2) NOT NULL, \
    HR_CLASS            VARCHAR(3) NOT NULL, \
    CONDITION           VARCHAR(1) NOT NULL, \
    GROUPCD             VARCHAR(4) NOT NULL, \
    SCHREGNO            VARCHAR(8) NOT NULL, \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRADE_KIND_SCHREG_GROUP_DAT ADD CONSTRAINT PK_GK_SCH_GP_DAT PRIMARY KEY (YEAR, SEMESTER, GAKUBU_SCHOOL_KIND, GHR_CD, GRADE, HR_CLASS, CONDITION, GROUPCD, SCHREGNO)
