-- $Id: 3423f625ec2d06979800ab9cdcb585426135160a $

DROP TABLE GRADE_KIND_ASSESS_DAT

CREATE TABLE GRADE_KIND_ASSESS_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    GRADE               VARCHAR(2) NOT NULL, \
    CONDITION           VARCHAR(1) NOT NULL, \
    ASSESSLEVEL         SMALLINT NOT NULL, \
    ASSESSMARK          VARCHAR(9), \
    ASSESSLOW           decimal(4,1), \
    ASSESSHIGH          decimal(4,1), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRADE_KIND_ASSESS_DAT ADD CONSTRAINT PK_GK_ASSESS PRIMARY KEY (YEAR, SCHOOL_KIND, GRADE, CONDITION, ASSESSLEVEL)
