-- $Id: grd_hexam_empremark_seq_dat.sql 77570 2020-11-24 00:53:45Z ishii $

DROP TABLE GRD_HEXAM_EMPREMARK_SEQ_DAT
CREATE TABLE GRD_HEXAM_EMPREMARK_SEQ_DAT( \
    SCHREGNO             VARCHAR(8)    NOT NULL, \
    PATTERN_SEQ          VARCHAR(1)    NOT NULL, \
    JOBHUNT_REC          VARCHAR(618), \
    JOBHUNT_RECOMMEND    VARCHAR(1506), \
    JOBHUNT_ABSENCE      VARCHAR(190), \
    JOBHUNT_HEALTHREMARK VARCHAR(130), \
    REGISTERCD           VARCHAR(10), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRD_HEXAM_EMPREMARK_SEQ_DAT ADD CONSTRAINT PK_GRD_HEXAMEMP_SEQ PRIMARY KEY (SCHREGNO,PATTERN_SEQ)