-- $Id: e5242cbb953948bfbd11f14d904ac32a3ee517ac $

DROP TABLE GRD_GUARDIAN_ADDRESS_COMEBACK_DAT
CREATE TABLE GRD_GUARDIAN_ADDRESS_COMEBACK_DAT( \
    SCHREGNO       VARCHAR(8)    NOT NULL, \
    ISSUEDATE      DATE          NOT NULL, \
    COMEBACK_DATE  date          NOT NULL, \
    EXPIREDATE     DATE, \
    GUARD_ZIPCD    VARCHAR(8), \
    GUARD_ADDR1    VARCHAR(150), \
    GUARD_ADDR2    VARCHAR(150), \
    GUARD_ADDR_FLG VARCHAR(1), \
    GUARD_TELNO    VARCHAR(14), \
    GUARD_TELNO2   VARCHAR(14), \
    GUARD_FAXNO    VARCHAR(14), \
    GUARD_E_MAIL   VARCHAR(50), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRD_GUARDIAN_ADDRESS_COMEBACK_DAT ADD CONSTRAINT PK_GRD_GUARD_COM_A PRIMARY KEY (SCHREGNO, ISSUEDATE, COMEBACK_DATE)