-- $Id: 8434af64c7437811c0f38eb58912d43ea74689e8 $

DROP TABLE GRD_GUARANTOR_ADDRESS_COMEBACK_DAT
CREATE TABLE GRD_GUARANTOR_ADDRESS_COMEBACK_DAT( \
    SCHREGNO               VARCHAR(8)    NOT NULL, \
    ISSUEDATE              DATE          NOT NULL, \
    COMEBACK_DATE          date          NOT NULL, \
    EXPIREDATE             DATE, \
    GUARANTOR_ZIPCD        VARCHAR(8), \
    GUARANTOR_ADDR1        VARCHAR(150), \
    GUARANTOR_ADDR2        VARCHAR(150), \
    GUARANTOR_ADDR_FLG     VARCHAR(1), \
    GUARANTOR_TELNO        VARCHAR(14), \
    REGISTERCD             VARCHAR(8), \
    UPDATED                TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRD_GUARANTOR_ADDRESS_COMEBACK_DAT ADD CONSTRAINT PK_G_GUARAN_COME_A PRIMARY KEY (SCHREGNO, ISSUEDATE, COMEBACK_DATE)