-- $Id: db80e51101f675fb20f7f54caf1298ed89b0dc53 $

DROP TABLE GRD_GUARANTOR_ADDRESS_DAT
CREATE TABLE GRD_GUARANTOR_ADDRESS_DAT( \
    SCHREGNO               VARCHAR(8)    NOT NULL, \
    ISSUEDATE              DATE          NOT NULL, \
    EXPIREDATE             DATE, \
    GUARANTOR_ZIPCD        VARCHAR(8), \
    GUARANTOR_ADDR1        VARCHAR(150), \
    GUARANTOR_ADDR2        VARCHAR(150), \
    GUARANTOR_TELNO        VARCHAR(14), \
    REGISTERCD             VARCHAR(8), \
    UPDATED                TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRD_GUARANTOR_ADDRESS_DAT ADD CONSTRAINT PK_GRD_GUARANTOR_A PRIMARY KEY (SCHREGNO, ISSUEDATE)