-- $Id: 0f7b6b9fa1fb2f37f8b59e75f2ce90d749fb9b12 $

DROP TABLE GRD_HEXAM_EMPREMARK_DAT
CREATE TABLE GRD_HEXAM_EMPREMARK_DAT( \
    SCHREGNO             VARCHAR(8)    NOT NULL, \
    JOBHUNT_REC          VARCHAR(618), \
    JOBHUNT_RECOMMEND    VARCHAR(1506), \
    JOBHUNT_ABSENCE      VARCHAR(190), \
    JOBHUNT_HEALTHREMARK VARCHAR(130), \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRD_HEXAM_EMPREMARK_DAT ADD CONSTRAINT PK_GRD_HEXAMEMP PRIMARY KEY (SCHREGNO)