-- KANJI=´Á»ú
-- $ID$

DROP TABLE GRD_ATTENDREC_EXEC_HIST_DAT

CREATE TABLE GRD_ATTENDREC_EXEC_HIST_DAT( \
    CALC_DATE           DATE NOT NULL, \
    CALC_TIME           TIME NOT NULL, \
    BEF_AFT_DIV         VARCHAR(1) NOT NULL, \
    SCHOOLCD            VARCHAR(1) NOT NULL, \
    YEAR                VARCHAR(4) NOT NULL, \
    SCHREGNO            VARCHAR(8) NOT NULL, \
    ANNUAL              VARCHAR(2) NOT NULL, \
    SUMDATE             DATE, \
    CLASSDAYS           SMALLINT, \
    OFFDAYS             SMALLINT, \
    ABSENT              SMALLINT, \
    SUSPEND             SMALLINT, \
    MOURNING            SMALLINT, \
    ABROAD              SMALLINT, \
    REQUIREPRESENT      SMALLINT, \
    SICK                SMALLINT, \
    ACCIDENTNOTICE      SMALLINT, \
    NOACCIDENTNOTICE    SMALLINT, \
    PRESENT             SMALLINT, \
    CMD_DIV             VARCHAR(1), \
    UPD_PRGID           VARCHAR(20), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRD_ATTENDREC_EXEC_HIST_DAT ADD CONSTRAINT PK_GRD_ATTENDREC_EXEC_HIST_DAT PRIMARY KEY (CALC_DATE, CALC_TIME, BEF_AFT_DIV, SCHOOLCD, YEAR, SCHREGNO)
