-- $Id: f0c0180d39c8ad27fe844a5a4dff4eaaeae8202c $

DROP TABLE GRD_STUDYRECREMARK_DAT
CREATE TABLE GRD_STUDYRECREMARK_DAT( \
    YEAR            VARCHAR(4)    NOT NULL, \
    SCHREGNO        VARCHAR(8)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    REMARK          VARCHAR(150), \
    REGISTERCD      VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRD_STUDYRECREMARK_DAT ADD CONSTRAINT PK_GRD_STDRECREM PRIMARY KEY (YEAR,SCHREGNO,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)