-- kanji=漢字
-- 実行前にDROP FUNCTION SECURITY_CHK_MNU、SECURITY_CHK_PRG実行し、再度FUNCTIONのSCRIPTを実行する必要あり

DROP TABLE GROUPAUTH_DAT_OLD
RENAME TABLE GROUPAUTH_DAT TO GROUPAUTH_DAT_OLD
CREATE TABLE GROUPAUTH_DAT( \
    SCHOOLCD        VARCHAR(12) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    GROUPCD         VARCHAR(4) NOT NULL, \
    MENUID          VARCHAR(11) NOT NULL, \
    GROUPAUTH       VARCHAR(1), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GROUPAUTH_DAT ADD CONSTRAINT PK_GROUPAUTH_DAT PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, GROUPCD, MENUID)