-- $Id: e4c7f80f3c98d21e404965441eda510715410f26 $

DROP TABLE GUARANTOR_HIST_DAT
CREATE TABLE GUARANTOR_HIST_DAT( \
    SCHREGNO                    VARCHAR(8)    NOT NULL, \
    ISSUEDATE                   DATE          NOT NULL, \
    EXPIREDATE                  DATE, \
    GUARANTOR_RELATIONSHIP      VARCHAR(2), \
    GUARANTOR_NAME              VARCHAR(120), \
    GUARANTOR_KANA              VARCHAR(240), \
    GUARANTOR_REAL_NAME         VARCHAR(120), \
    GUARANTOR_REAL_KANA         VARCHAR(240), \
    GUARANTOR_SEX               VARCHAR(1), \
    GUARANTOR_RELATIONSHIP_FLG  VARCHAR(1), \
    GUARANTOR_NAME_FLG          VARCHAR(1), \
    GUARANTOR_KANA_FLG          VARCHAR(1), \
    GUARANTOR_REAL_NAME_FLG     VARCHAR(120), \
    GUARANTOR_REAL_KANA_FLG     VARCHAR(240), \
    GUARANTOR_SEX_FLG           VARCHAR(1), \
    REGISTERCD                  VARCHAR(8), \
    UPDATED                     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GUARANTOR_HIST_DAT ADD CONSTRAINT PK_GUARANTOR_HIST PRIMARY KEY (SCHREGNO, ISSUEDATE)