-- $Id: 80ce5057470a1e5337b80807f934d33677a3ad75 $

DROP TABLE GUARANTOR_ADDRESS_DAT
CREATE TABLE GUARANTOR_ADDRESS_DAT( \
    SCHREGNO               VARCHAR(8)    NOT NULL, \
    ISSUEDATE              DATE          NOT NULL, \
    EXPIREDATE             DATE, \
    GUARANTOR_ZIPCD        VARCHAR(8), \
    GUARANTOR_ADDR1        VARCHAR(150), \
    GUARANTOR_ADDR2        VARCHAR(150), \
    GUARANTOR_ADDR_FLG     VARCHAR(1), \
    GUARANTOR_TELNO        VARCHAR(14), \
    REGISTERCD             VARCHAR(8), \
    UPDATED                TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GUARANTOR_ADDRESS_DAT ADD CONSTRAINT PK_GUARANTOR_ADD PRIMARY KEY (SCHREGNO, ISSUEDATE)