-- $Id: 7089c3d4d504fc00b4937136baf40bcfe340860c $

DROP TABLE GUARDIAN_NAME_SETUP_DAT
CREATE TABLE GUARDIAN_NAME_SETUP_DAT( \
    SCHREGNO              VARCHAR(8)    NOT NULL, \
    DIV                   VARCHAR(2)    NOT NULL, \
    GUARD_NAME_OUTPUT_FLG VARCHAR(1), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GUARDIAN_NAME_SETUP_DAT ADD CONSTRAINT PK_GUARD_N_S_DAT PRIMARY KEY (SCHREGNO,DIV)