-- $Id: 140b3b60e71de5cc8329b900a8ede70f538fa668 $

DROP TABLE GUARDIAN2_HIST_DAT
CREATE TABLE GUARDIAN2_HIST_DAT( \
    SCHREGNO            VARCHAR(8)    NOT NULL, \
    ISSUEDATE           DATE          NOT NULL, \
    EXPIREDATE          DATE, \
    RELATIONSHIP        VARCHAR(2)    NOT NULL, \
    GUARD_NAME          VARCHAR(120), \
    GUARD_KANA          VARCHAR(240), \
    GUARD_REAL_NAME     VARCHAR(120), \
    GUARD_REAL_KANA     VARCHAR(240), \
    GUARD_SEX           VARCHAR(1), \
    GUARD_BIRTHDAY      DATE, \
    RELATIONSHIP_FLG    VARCHAR(1), \
    GUARD_NAME_FLG      VARCHAR(1), \
    GUARD_KANA_FLG      VARCHAR(1), \
    GUARD_REAL_NAME_FLG VARCHAR(120), \
    GUARD_REAL_KANA_FLG VARCHAR(240), \
    GUARD_SEX_FLG       VARCHAR(1), \
    GUARD_BIRTHDAY_FLG  VARCHAR(1), \
    REGISTERCD          VARCHAR(8), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GUARDIAN2_HIST_DAT ADD CONSTRAINT PK_GUARDIAN2_HIST PRIMARY KEY (SCHREGNO,ISSUEDATE)