-- $Id: c8916b38b012936a323ec79d9d9bcd95a6b89a6f $

DROP TABLE HEXAM_EMPREMARK_DAT
CREATE TABLE HEXAM_EMPREMARK_DAT( \
    SCHREGNO             VARCHAR(8)    NOT NULL, \
    JOBHUNT_REC          VARCHAR(900), \
    JOBHUNT_RECOMMEND    VARCHAR(1506), \
    JOBHUNT_ABSENCE      VARCHAR(190), \
    JOBHUNT_HEALTHREMARK VARCHAR(130), \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HEXAM_EMPREMARK_DAT ADD CONSTRAINT PK_HEXAM_EMP_DAT PRIMARY KEY (SCHREGNO)