-- $Id: 8277b7ba24a3947c15190a9c74e449073612cfb9 $

DROP TABLE HEXAM_ENTREMARK_TRAINREF_DAT
CREATE TABLE HEXAM_ENTREMARK_TRAINREF_DAT( \
    YEAR                    VARCHAR(4)    NOT NULL, \
    SCHREGNO                VARCHAR(8)    NOT NULL, \
    TRAIN_SEQ               VARCHAR(3)    NOT NULL, \
    REMARK                  VARCHAR(3110), \
    REGISTERCD              VARCHAR(10), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HEXAM_ENTREMARK_TRAINREF_DAT ADD CONSTRAINT PK_HEX_ENT_TRAIN PRIMARY KEY(YEAR, SCHREGNO, TRAIN_SEQ)
