-- $Id: 24324a3d860514fd06fdeed5fb800452c8aeff54 $

DROP TABLE HEXAM_PHYSICAL_AVG_DAT
CREATE TABLE HEXAM_PHYSICAL_AVG_DAT( \
    YEAR                 VARCHAR(4)    NOT NULL, \
    SEX                  VARCHAR(1)    NOT NULL, \
    NENREI_YEAR          SMALLINT      NOT NULL, \
    NENREI_MONTH         SMALLINT      NOT NULL, \
    HEIGHT_AVG           DECIMAL(4, 1), \
    HEIGHT_SD            DECIMAL(4, 1), \
    WEIGHT_AVG           DECIMAL(4, 1), \
    WEIGHT_SD            DECIMAL(4, 1), \
    STD_WEIGHT_KEISU_A   DECIMAL(6, 3), \
    STD_WEIGHT_KEISU_B   DECIMAL(6, 3), \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HEXAM_PHYSICAL_AVG_DAT ADD CONSTRAINT PK_HEXAM_P_AVG_DAT PRIMARY KEY (YEAR, SEX, NENREI_YEAR, NENREI_MONTH)