-- $Id$

DROP TABLE HEXAM_EMPREMARK_SEQ_DAT
CREATE TABLE HEXAM_EMPREMARK_SEQ_DAT( \
    SCHREGNO             VARCHAR(8)    NOT NULL, \
    PATTERN_SEQ          VARCHAR(1)    NOT NULL, \
    JOBHUNT_REC          VARCHAR(1300), \
    JOBHUNT_RECOMMEND    VARCHAR(3100), \
    JOBHUNT_ABSENCE      VARCHAR(550), \
    JOBHUNT_HEALTHREMARK VARCHAR(130), \
    REGISTERCD           VARCHAR(10), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HEXAM_EMPREMARK_SEQ_DAT ADD CONSTRAINT PK_HEXAM_EMP_SEQ_DAT PRIMARY KEY (SCHREGNO, PATTERN_SEQ)
