-- $Id: d8430bc07949955c1074a54d448c7948ef638501 $

DROP TABLE HREPORT_GUIDANCE_SCHREG_UNIT_DAT

CREATE TABLE HREPORT_GUIDANCE_SCHREG_UNIT_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    SEMESTER            VARCHAR(1) NOT NULL, \
    SCHREGNO            VARCHAR(8) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    CURRICULUM_CD       VARCHAR(2) NOT NULL, \
    SUBCLASSCD          VARCHAR(6) NOT NULL, \
    UNITCD              VARCHAR(2) NOT NULL, \
    GUIDANCE_PATTERN    VARCHAR(1) NOT NULL, \
    REMARK1             VARCHAR(708), \
    REMARK_VALUE1       VARCHAR(6), \
    REMARK2             VARCHAR(708), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HREPORT_GUIDANCE_SCHREG_UNIT_DAT ADD CONSTRAINT PK_HRE_GUID_SCHUNI PRIMARY KEY (YEAR, SEMESTER, SCHREGNO, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, UNITCD)
