-- $Id: 0126484a015ad1e5ed26b982915a1beb83586259 $

DROP TABLE HREPORTREMARK_DAT
CREATE TABLE HREPORTREMARK_DAT( \
    YEAR             VARCHAR(4)    NOT NULL, \
    SEMESTER         VARCHAR(1)    NOT NULL, \
    SCHREGNO         VARCHAR(8)    NOT NULL, \
    TOTALSTUDYTIME   VARCHAR(780)  , \
    SPECIALACTREMARK VARCHAR(780)  , \
    COMMUNICATION    VARCHAR(1000) , \
    REMARK1          VARCHAR(780)  , \
    REMARK2          VARCHAR(780)  , \
    REMARK3          VARCHAR(780)  , \
    FOREIGNLANGACT   VARCHAR(450)  , \
    ATTENDREC_REMARK VARCHAR(780)  , \
    REGISTERCD       VARCHAR(10)   , \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HREPORTREMARK_DAT ADD CONSTRAINT PK_HREPORTREMARK PRIMARY KEY (YEAR,SEMESTER,SCHREGNO)