-- $Id: c6a03f6e5f1517eac9dc6645047cd29b1cb01720 $

DROP TABLE HREPORT_GUIDANCE_SCHREG_DETAIL_DAT

CREATE TABLE HREPORT_GUIDANCE_SCHREG_DETAIL_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    SEMESTER            VARCHAR(1) NOT NULL, \
    SCHREGNO            VARCHAR(8) NOT NULL, \
    SEQ                 VARCHAR(3) NOT NULL, \
    REMARK1             VARCHAR(300), \
    REMARK2             VARCHAR(300), \
    REMARK3             VARCHAR(300), \
    REMARK4             VARCHAR(300), \
    REMARK5             VARCHAR(300), \
    REMARK6             VARCHAR(300), \
    REMARK7             VARCHAR(300), \
    REMARK8             VARCHAR(300), \
    REMARK9             VARCHAR(300), \
    REMARK10            VARCHAR(300), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HREPORT_GUIDANCE_SCHREG_DETAIL_DAT ADD CONSTRAINT PK_HREP_GUID_SCH_DETAIL PRIMARY KEY (YEAR, SEMESTER, SCHREGNO, SEQ)
