-- $Id: 8a7782c50f4ad6a9c361e1d3c21cc0e4166b737e $

DROP TABLE HREPORT_GUIDANCE_SCHREG_UNIT_SEQ_DAT

CREATE TABLE HREPORT_GUIDANCE_SCHREG_UNIT_SEQ_DAT( \
    YEAR           VARCHAR(4)     NOT NULL, \
    SEMESTER       VARCHAR(1)     NOT NULL, \
    SCHREGNO       VARCHAR(8)     NOT NULL, \
    CLASSCD        VARCHAR(2)     NOT NULL, \
    SCHOOL_KIND    VARCHAR(2)     NOT NULL, \
    CURRICULUM_CD  VARCHAR(2)     NOT NULL, \
    SUBCLASSCD     VARCHAR(6)     NOT NULL, \
    UNITCD         VARCHAR(2)     NOT NULL, \
    SEQ            SMALLINT       NOT NULL, \
    REMARK         VARCHAR(6100) , \
    REGISTERCD     VARCHAR(10)   , \
    UPDATED        TIMESTAMP      DEFAULT CURRENT TIMESTAMP \
 ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HREPORT_GUIDANCE_SCHREG_UNIT_SEQ_DAT ADD CONSTRAINT PK_HR_G_SU_SQ PRIMARY KEY (YEAR,SEMESTER,SCHREGNO,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,UNITCD,SEQ)

