-- $Id: e35b5f4958808f300c8d5b2297770086acf93915 $

DROP TABLE HREPORT_GUIDANCE_ITEM_NAME_DAT

CREATE TABLE HREPORT_GUIDANCE_ITEM_NAME_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    SEMESTER            VARCHAR(1) NOT NULL, \
    GAKUBU_SCHOOL_KIND  VARCHAR(2) NOT NULL, \
    CONDITION           VARCHAR(1) NOT NULL, \
    GUIDANCE_PATTERN    VARCHAR(1) NOT NULL, \
    ITEM_REMARK1        VARCHAR(120), \
    ITEM_REMARK2        VARCHAR(120), \
    ITEM_REMARK3        VARCHAR(120), \
    ITEM_REMARK4        VARCHAR(120), \
    ITEM_REMARK5        VARCHAR(120), \
    ITEM_REMARK6        VARCHAR(120), \
    ITEM_REMARK7        VARCHAR(120), \
    ITEM_REMARK8        VARCHAR(120), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HREPORT_GUIDANCE_ITEM_NAME_DAT ADD CONSTRAINT PK_HREP_GUID_ITEM PRIMARY KEY (YEAR, SEMESTER, GAKUBU_SCHOOL_KIND, CONDITION, GUIDANCE_PATTERN)
