-- $Id: 4c408cb1b5685bcc9a4006c67496722e69c693ce $

DROP TABLE HREPORT_GUIDANCE_GROUP_HDAT

CREATE TABLE HREPORT_GUIDANCE_GROUP_HDAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    SEMESTER            VARCHAR(1) NOT NULL, \
    GAKUBU_SCHOOL_KIND  VARCHAR(2) NOT NULL, \
    GHR_CD              VARCHAR(2) NOT NULL, \
    GRADE               VARCHAR(2) NOT NULL, \
    HR_CLASS            VARCHAR(3) NOT NULL, \
    CONDITION           VARCHAR(1) NOT NULL, \
    GROUPCD             VARCHAR(4) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    CURRICULUM_CD       VARCHAR(2) NOT NULL, \
    SUBCLASSCD          VARCHAR(6) NOT NULL, \
    GROUP_REMARK_CNT    VARCHAR(2), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HREPORT_GUIDANCE_GROUP_HDAT ADD CONSTRAINT PK_HREP_GUID_GRPH PRIMARY KEY (YEAR, SEMESTER, GAKUBU_SCHOOL_KIND, GHR_CD, GRADE, HR_CLASS, CONDITION, GROUPCD, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)
