-- $Id: d6168f9e445d6c226441cc3222667350f4ea5f2e $

DROP TABLE HREPORT_GUIDANCE_SCHREG_DAT

CREATE TABLE HREPORT_GUIDANCE_SCHREG_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    SEMESTER            VARCHAR(1) NOT NULL, \
    SCHREGNO            VARCHAR(8) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    CURRICULUM_CD       VARCHAR(2) NOT NULL, \
    SUBCLASSCD          VARCHAR(6) NOT NULL, \
    SEQ                 SMALLINT   NOT NULL, \
    REMARK              VARCHAR(6100), \
    REMARK_VALUE        VARCHAR(6), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HREPORT_GUIDANCE_SCHREG_DAT ADD CONSTRAINT PK_HREP_GUID_SCH PRIMARY KEY (YEAR, SEMESTER, SCHREGNO, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, SEQ)
