-- $Id: 8198728664deb5f8e77c2c79d4dee2151bde8951 $

DROP TABLE HTESTREMARK_DAT
CREATE TABLE HTESTREMARK_DAT( \
    YEAR            VARCHAR(4)    NOT NULL, \
    SEMESTER        VARCHAR(1)    NOT NULL, \
    SCHREGNO        VARCHAR(8)    NOT NULL, \
    TESTKINDCD      VARCHAR(2)    NOT NULL, \
    TESTITEMCD      VARCHAR(2)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    DIV             VARCHAR(1)    NOT NULL, \
    REMARK     VARCHAR(150), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HTESTREMARK_DAT ADD CONSTRAINT PK_HTESTREMARK_DAT PRIMARY KEY (YEAR,SEMESTER,SCHREGNO,TESTKINDCD,TESTITEMCD,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,DIV)