-- $Id: 344d9f2272be09c9c98669c44148ec15ae5da6bb $

DROP TABLE HTRAINREMARK_K_DAT
CREATE TABLE HTRAINREMARK_K_DAT( \
    YEAR             VARCHAR(4)    NOT NULL, \
    SCHREGNO         VARCHAR(8)    NOT NULL, \
    TOTALSTUDYACT    VARCHAR(678), \
    TOTALSTUDYVAL    VARCHAR(678), \
    SPECIALACTREMARK VARCHAR(678), \
    TOTALREMARK      VARCHAR(3300), \
    ATTENDREC_REMARK VARCHAR(242), \
    VIEWREMARK       VARCHAR(226), \
    BEHAVEREC_REMARK VARCHAR(122), \
    REGISTERCD       VARCHAR(10), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HTRAINREMARK_K_DAT ADD CONSTRAINT PK_HTRAINREMARKK PRIMARY KEY (YEAR, SCHREGNO)