-- kanji=´Á»ú
-- $Id: 580e3761cff2ae7ee6b4fc57fb2c79ba18b76161 $

DROP TABLE HTRAINREMARK_DETAIL2_HDAT
CREATE TABLE HTRAINREMARK_DETAIL2_HDAT( \
    SCHREGNO            VARCHAR(8)    NOT NULL, \
    HTRAIN_SEQ          VARCHAR(3)    NOT NULL, \
    REMARK1             VARCHAR(1500), \
    REMARK2             VARCHAR(780), \
    REMARK3             VARCHAR(780), \
    REMARK4             VARCHAR(780), \
    REMARK5             VARCHAR(780), \
    REGISTERCD          VARCHAR(8), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HTRAINREMARK_DETAIL2_HDAT ADD CONSTRAINT PK_HTRAINRMK_D2_H PRIMARY KEY (SCHREGNO,HTRAIN_SEQ)