-- $Id: f37814f71328821576f9e1e2c710fe1b73a7dc77 $

DROP TABLE HTRAINREMARK_DETAIL_DAT
CREATE TABLE HTRAINREMARK_DETAIL_DAT( \
    YEAR             VARCHAR(4)    NOT NULL, \
    SCHREGNO         VARCHAR(8)    NOT NULL, \
    TRAIN_REF1       VARCHAR(1740), \
    TRAIN_REF2       VARCHAR(453), \
    TRAIN_REF3       VARCHAR(453), \
    REGISTERCD       VARCHAR(10), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HTRAINREMARK_DETAIL_DAT ADD CONSTRAINT PK_HTRAINREMARK_DE PRIMARY KEY (YEAR,SCHREGNO)