-- $Id: 9a85ea740be3abe07d5a954d1a0dae458de8e964 $

DROP TABLE HTRAINREMARK_TEMP_DAT
CREATE TABLE HTRAINREMARK_TEMP_DAT( \
    YEAR             VARCHAR(4)    NOT NULL, \
    GRADE            VARCHAR(2)    NOT NULL, \
    DATA_DIV         VARCHAR(2)    NOT NULL, \
    PATTERN_CD       VARCHAR(1)    NOT NULL, \
    REMARK           VARCHAR(1500), \
    REGISTERCD       VARCHAR(8), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HTRAINREMARK_TEMP_DAT ADD CONSTRAINT PK_HTRAINREMARK_T PRIMARY KEY (YEAR,GRADE,DATA_DIV,PATTERN_CD)