-- $Id: a0ca6dbfa96d9710b3e13324682b800bf4783444 $

DROP TABLE HTRAINREMARK_TRAINREF_DAT

CREATE TABLE HTRAINREMARK_TRAINREF_DAT( \
    YEAR        VARCHAR(4)     NOT NULL, \
    SCHREGNO    VARCHAR(8)     NOT NULL, \
    TRAIN_SEQ   VARCHAR(3)     NOT NULL, \
    REMARK      VARCHAR(3110) , \
    REGISTERCD  VARCHAR(10)   , \
    UPDATED     TIMESTAMP      DEFAULT CURRENT TIMESTAMP \
 ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HTRAINREMARK_TRAINREF_DAT ADD CONSTRAINT PK_HTRAIN_TRAIN PRIMARY KEY (YEAR,SCHREGNO,TRAIN_SEQ)

