-- $Id: c21e0fbb18465c42831896bb2755117aeee6a02d $

drop   table IBCLASS_MST
create table IBCLASS_MST ( \
    IBCLASSCD         VARCHAR(2) NOT NULL, \
    IBPRG_COURSE      VARCHAR(2) NOT NULL, \
    IBCLASSNAME       VARCHAR(90), \
    IBCLASSABBV       VARCHAR(90), \
    IBCLASSNAME_ENG   VARCHAR(90), \
    IBCLASSABBV_ENG   VARCHAR(90), \
    IBCLASSORDERNAME1 VARCHAR(60), \
    IBCLASSORDERNAME2 VARCHAR(60), \
    IBCLASSORDERNAME3 VARCHAR(60), \
    IBSUBCLASSES      SMALLINT, \
    IBSHOWORDER       SMALLINT, \
    IBSHOWORDER2      SMALLINT, \
    IBSHOWORDER3      SMALLINT, \
    IBSHOWORDER4      SMALLINT, \
    IBELECTDIV        VARCHAR(1), \
    IBSPECIALDIV      VARCHAR(1), \
    REGISTERCD        VARCHAR(8), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) in usr1dms index in idx1dms

alter table IBCLASS_MST add constraint PK_IBCLASS_MST primary key (IBCLASSCD, IBPRG_COURSE)

