-- $Id: e80bc9f3dde1deea46174cbfa2bfccab973ed388 $

DROP TABLE IBCREDIT_MST
CREATE TABLE IBCREDIT_MST( \
    YEAR                 VARCHAR(4)    NOT NULL, \
    GRADE                VARCHAR(2)    NOT NULL, \
    IBCLASSCD            VARCHAR(2)    NOT NULL, \
    IBPRG_COURSE         VARCHAR(2)    NOT NULL, \
    IBCURRICULUM_CD      VARCHAR(2)    NOT NULL, \
    IBSUBCLASSCD         VARCHAR(6)    NOT NULL, \
    NEED_TIME            DECIMAL(4,1), \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE IBCREDIT_MST ADD CONSTRAINT PK_IBCREDIT_MST PRIMARY KEY (YEAR,GRADE,IBCLASSCD,IBPRG_COURSE,IBCURRICULUM_CD,IBSUBCLASSCD)