-- $Id: 4bf89f72b15905171a227c8528c13183369a32aa $

DROP TABLE IBSUBCLASS_VIEW_PERFECT_DAT
CREATE TABLE IBSUBCLASS_VIEW_PERFECT_DAT( \
    IBYEAR               VARCHAR(4)    NOT NULL, \
    IBGRADE              VARCHAR(2)    NOT NULL, \
    IBCLASSCD            VARCHAR(2)    NOT NULL, \
    IBPRG_COURSE         VARCHAR(2)    NOT NULL, \
    IBCURRICULUM_CD      VARCHAR(2)    NOT NULL, \
    IBSUBCLASSCD         VARCHAR(6)    NOT NULL, \
    VIEWCD               VARCHAR(4)    NOT NULL, \
    PERFECT              SMALLINT, \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE IBSUBCLASS_VIEW_PERFECT_DAT ADD CONSTRAINT PK_IBSUB_VIEW_PER PRIMARY KEY (IBYEAR, IBGRADE, IBCLASSCD, IBPRG_COURSE, IBCURRICULUM_CD, IBSUBCLASSCD, VIEWCD)