-- $Id: 44e8ab65b4e86289fb2f9c00a34b960d9e368cf1 $

DROP TABLE IBSUBCLASS_GRADE_PHASE_DAT

CREATE TABLE IBSUBCLASS_GRADE_PHASE_DAT( \
    IBYEAR        VARCHAR(4)   NOT NULL, \
    IBGRADE       VARCHAR(2)   NOT NULL, \
    SCHREGNO      VARCHAR(8)   NOT NULL, \
    IBCLASSCD     VARCHAR(2)   NOT NULL, \
    IBPRG_COURSE  VARCHAR(2)   NOT NULL, \
    SEMESTER      VARCHAR(1)   NOT NULL, \
    SCORE         SMALLINT    , \
    REGISTERCD    VARCHAR(10) , \
    UPDATED       TIMESTAMP    DEFAULT CURRENT TIMESTAMP \
 ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE IBSUBCLASS_GRADE_PHASE_DAT ADD CONSTRAINT PK_IBSUB_GPHASE PRIMARY KEY (IBYEAR,IBGRADE,SCHREGNO,IBCLASSCD,IBPRG_COURSE,SEMESTER)

