-- $Id: a79905b8982f12ca3362e23de39e73bddc9d4867 $

DROP TABLE IBSUBCLASS_GRADE_ASSESS_YMST
CREATE TABLE IBSUBCLASS_GRADE_ASSESS_YMST( \
    IBYEAR               VARCHAR(4)    NOT NULL, \
    IBGRADE              VARCHAR(2)    NOT NULL, \
    IBCLASSCD            VARCHAR(2)    NOT NULL, \
    IBPRG_COURSE         VARCHAR(2)    NOT NULL, \
    IBCURRICULUM_CD      VARCHAR(2)    NOT NULL, \
    IBSUBCLASSCD         VARCHAR(6)    NOT NULL, \
    GRADE_LEVEL          SMALLINT      NOT NULL, \
    GRADE_MARK           VARCHAR (30), \
    GRADE_LOW            DECIMAL (4,1), \
    GRADE_HIGH           DECIMAL (4,1), \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE IBSUBCLASS_GRADE_ASSESS_YMST ADD CONSTRAINT PK_IBSUB_GRADE PRIMARY KEY (IBYEAR, IBGRADE, IBCLASSCD, IBPRG_COURSE, IBCURRICULUM_CD, IBSUBCLASSCD, GRADE_LEVEL)