-- $Id: 06e692dc259a9d3c61ce50d3ff7bfa8ea0cce3a8 $

DROP TABLE IBSUBCLASS_SCORE_DAT
CREATE TABLE IBSUBCLASS_SCORE_DAT( \
    IBYEAR               VARCHAR(4)    NOT NULL, \
    IBGRADE              VARCHAR(2)    NOT NULL, \
    SCHREGNO             VARCHAR(8)    NOT NULL, \
    IBCLASSCD            VARCHAR(2)    NOT NULL, \
    IBPRG_COURSE         VARCHAR(2)    NOT NULL, \
    IBCURRICULUM_CD      VARCHAR(2)    NOT NULL, \
    IBSUBCLASSCD         VARCHAR(6)    NOT NULL, \
    IBSEQ                SMALLINT      NOT NULL, \
    IBEVAL_DIV1          VARCHAR(1)    NOT NULL, \
    IBEVAL_DIV2          VARCHAR(1)    NOT NULL, \
    IBEVAL_MARK          VARCHAR(2)    NOT NULL, \
    VIEWCD               VARCHAR(4)    NOT NULL, \
    SCORE                SMALLINT, \
    GRADE                SMALLINT, \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE IBSUBCLASS_SCORE_DAT ADD CONSTRAINT PK_IB_SCORE PRIMARY KEY (IBYEAR, IBGRADE, SCHREGNO, IBCLASSCD, IBPRG_COURSE, IBCURRICULUM_CD, IBSUBCLASSCD, IBSEQ, IBEVAL_DIV1, IBEVAL_DIV2, IBEVAL_MARK, VIEWCD)