-- $Id: aa3811931e71ce549f05afc26aeeeca152ee0b81 $

DROP TABLE IBSUBCLASS_SELECT_DAT
CREATE TABLE IBSUBCLASS_SELECT_DAT( \
    IBYEAR               VARCHAR(4)    NOT NULL, \
    IBGRADE              VARCHAR(2)    NOT NULL, \
    IBCLASSCD            VARCHAR(2)    NOT NULL, \
    IBPRG_COURSE         VARCHAR(2)    NOT NULL, \
    IBCURRICULUM_CD      VARCHAR(2)    NOT NULL, \
    IBSUBCLASSCD         VARCHAR(6)    NOT NULL, \
    IBNOT_CALC           VARCHAR(1), \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE IBSUBCLASS_SELECT_DAT ADD CONSTRAINT PK_IBSUB_SELECT PRIMARY KEY (IBYEAR, IBGRADE, IBCLASSCD, IBPRG_COURSE, IBCURRICULUM_CD, IBSUBCLASSCD)