-- $Id: ff32781aca34b1613d2c2014a5ce4b3f731fdedb $

DROP TABLE IBSUBCLASS_MST
CREATE TABLE IBSUBCLASS_MST( \
    IBCLASSCD            VARCHAR(2)    NOT NULL, \
    IBPRG_COURSE         VARCHAR(2)    NOT NULL, \
    IBCURRICULUM_CD      VARCHAR(2)    NOT NULL, \
    IBSUBCLASSCD         VARCHAR(6)    NOT NULL, \
    IBSUBCLASSNAME       VARCHAR(90), \
    IBSUBCLASSABBV       VARCHAR(90), \
    IBSUBCLASSNAME_ENG   VARCHAR(90), \
    IBSUBCLASSABBV_ENG   VARCHAR(90), \
    IBSUBCLASSORDERNAME1 VARCHAR(90), \
    IBSUBCLASSORDERNAME2 VARCHAR(90), \
    IBSUBCLASSORDERNAME3 VARCHAR(90), \
    IBSHOWORDER          SMALLINT, \
    IBSHOWORDER2         SMALLINT, \
    IBSHOWORDER3         SMALLINT, \
    IBSUBCLASSCD2        VARCHAR(6), \
    IBSUBCLASSCD3        VARCHAR(6), \
    IBELECTDIV           VARCHAR(1), \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE IBSUBCLASS_MST ADD CONSTRAINT PK_IBSUBCLASS_M PRIMARY KEY (IBCLASSCD, IBPRG_COURSE, IBCURRICULUM_CD, IBSUBCLASSCD)