-- $Id: c6cdb036a142b8ca4bd77c3278c388c207dd37bb $

DROP TABLE IBSUBCLASS_REPLACE_DAT
CREATE TABLE IBSUBCLASS_REPLACE_DAT( \
    IBYEAR               VARCHAR(4)    NOT NULL, \
    IBGRADE              VARCHAR(2)    NOT NULL, \
    IBCLASSCD            VARCHAR(2)    NOT NULL, \
    IBPRG_COURSE         VARCHAR(2)    NOT NULL, \
    IBCURRICULUM_CD      VARCHAR(2)    NOT NULL, \
    IBSUBCLASSCD         VARCHAR(6)    NOT NULL, \
    CLASSCD              VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND          VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD        VARCHAR(2)    NOT NULL, \
    SUBCLASSCD           VARCHAR(6)    NOT NULL, \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE IBSUBCLASS_REPLACE_DAT ADD CONSTRAINT PK_IBSUB_REPLACE PRIMARY KEY (IBYEAR, IBGRADE, IBCLASSCD, IBPRG_COURSE, IBCURRICULUM_CD, IBSUBCLASSCD, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)