-- $Id: da52f1e26e5a3ebc6f8239245f78f0317fd13529 $

DROP TABLE IBSUBCLASS_GRADE_DAT
CREATE TABLE IBSUBCLASS_GRADE_DAT( \
    IBYEAR               VARCHAR(4)    NOT NULL, \
    IBGRADE              VARCHAR(2)    NOT NULL, \
    SCHREGNO             VARCHAR(8)    NOT NULL, \
    IBCLASSCD            VARCHAR(2)    NOT NULL, \
    IBPRG_COURSE         VARCHAR(2)    NOT NULL, \
    IBCURRICULUM_CD      VARCHAR(2)    NOT NULL, \
    IBSUBCLASSCD         VARCHAR(6)    NOT NULL, \
    SEMESTER             VARCHAR(1)    NOT NULL, \
    IBEVAL_DIV1          VARCHAR(1)    NOT NULL, \
    IBEVAL_DIV2          VARCHAR(1)    NOT NULL, \
    IBEVAL_MARK          VARCHAR(2)    NOT NULL, \
    VIEWCD               VARCHAR(4)    NOT NULL, \
    SCORE                SMALLINT, \
    GRADE                SMALLINT, \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE IBSUBCLASS_GRADE_DAT ADD CONSTRAINT PK_IB_GRADE PRIMARY KEY (IBYEAR, IBGRADE, SCHREGNO, IBCLASSCD, IBPRG_COURSE, IBCURRICULUM_CD, IBSUBCLASSCD, SEMESTER, IBEVAL_DIV1, IBEVAL_DIV2, IBEVAL_MARK, VIEWCD)