-- $Id: 5e55eecfe7c95f629a1792898e55dd3d2526f61c $

DROP TABLE IBVIEW_NAME_YMST
CREATE TABLE IBVIEW_NAME_YMST( \
    IBYEAR               VARCHAR(4)    NOT NULL, \
    IBGRADE              VARCHAR(2)    NOT NULL, \
    IBCLASSCD            VARCHAR(2)    NOT NULL, \
    IBPRG_COURSE         VARCHAR(2)    NOT NULL, \
    IBCURRICULUM_CD      VARCHAR(2)    NOT NULL, \
    IBSUBCLASSCD         VARCHAR(6)    NOT NULL, \
    IBEVAL_DIV1          VARCHAR(1)    NOT NULL, \
    IBEVAL_DIV2          VARCHAR(1)    NOT NULL, \
    IBEVAL_MARK          VARCHAR(2)    NOT NULL, \
    IBEVAL_NAME          VARCHAR(90), \
    IBEVAL_ABBV          VARCHAR(90), \
    IBEVAL_NAME_ENG      VARCHAR(90), \
    IBEVAL_ABBV_ENG      VARCHAR(90), \
    IBSORT               SMALLINT, \
    IBPERFECT            SMALLINT, \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE IBVIEW_NAME_YMST ADD CONSTRAINT PK_IBVIEW_NAME_YM PRIMARY KEY (IBYEAR, IBGRADE, IBCLASSCD, IBPRG_COURSE, IBCURRICULUM_CD, IBSUBCLASSCD, IBEVAL_DIV1, IBEVAL_DIV2, IBEVAL_MARK)