-- kanji=漢字
-- $Id: 2b851d68443257a6009c71119429fc062338af38 $

DROP TABLE INDUSTRY_M_MST
CREATE TABLE INDUSTRY_M_MST( \
    INDUSTRY_LCD   VARCHAR(1)    NOT NULL, \
    INDUSTRY_MCD   VARCHAR(2)    NOT NULL, \
    INDUSTRY_MNAME VARCHAR(90), \
    M_GROUPCD      VARCHAR(2), \
    NO_OUTPUT      VARCHAR(1), \
    REGISTERCD     VARCHAR(8), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE INDUSTRY_M_MST ADD CONSTRAINT PK_INDUSTRY_M_MST PRIMARY KEY (INDUSTRY_LCD,INDUSTRY_MCD)