-- kanji=漢字
-- $Id: b92a0f762f6c4df75f5558dee6aec2a8841c14ce $

DROP TABLE INDUSTRY_MGROUP_MST
CREATE TABLE INDUSTRY_MGROUP_MST( \
    M_GROUPCD   VARCHAR(2)    NOT NULL, \
    M_GROUPNAME VARCHAR(90), \
    REGISTERCD  VARCHAR(8), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE INDUSTRY_MGROUP_MST ADD CONSTRAINT PK_INDUST_MGRP_MST PRIMARY KEY (M_GROUPCD)