-- kanji=漢字
-- $Id: a8bc7fa0871bce1f651d2ddb1e5a2ed8c2bacb25 $

DROP TABLE INDUSTRY_S_MST
CREATE TABLE INDUSTRY_S_MST( \
    INDUSTRY_LCD   VARCHAR(1)    NOT NULL, \
    INDUSTRY_MCD   VARCHAR(2)    NOT NULL, \
    INDUSTRY_SCD   VARCHAR(3)    NOT NULL, \
    INDUSTRY_SNAME VARCHAR(90), \
    NO_OUTPUT      VARCHAR(1), \
    REGISTERCD     VARCHAR(8), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE INDUSTRY_S_MST ADD CONSTRAINT PK_INDUSTRY_S_MST PRIMARY KEY (INDUSTRY_LCD,INDUSTRY_MCD,INDUSTRY_SCD)