-- kanji=漢字
-- $Id: 6f7573cecaaadf0833d712f14bffa78944331f81 $

DROP TABLE INDUSTRY_LGROUP_MST
CREATE TABLE INDUSTRY_LGROUP_MST( \
    L_GROUPCD   VARCHAR(2)    NOT NULL, \
    L_GROUPNAME VARCHAR(90), \
    REGISTERCD  VARCHAR(8), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE INDUSTRY_LGROUP_MST ADD CONSTRAINT PK_INDUST_LGRP_MST PRIMARY KEY (L_GROUPCD)