-- $Id: 3a3bf08ff871f900956e08a1dc5713e0895ea60f $

drop table ISSUECOMPANY_MST

CREATE TABLE ISSUECOMPANY_MST  \
(  \
        "ISSUECOMPANYCD"       VARCHAR(4)      NOT NULL, \
        "ISSUECOMPANYNAME"     VARCHAR(60),  \
        "ISSUECOMPANYABBV"     VARCHAR(15),  \
        "REGISTERCD"           VARCHAR(8),  \
        "UPDATED"              TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS


ALTER TABLE ISSUECOMPANY_MST  \
ADD CONSTRAINT PK_ISSUE_MST  \
PRIMARY KEY  \
( \
ISSUECOMPANYCD \
)

