-- $Id: 6524b561582a05fd958c4e4f5683c66a5715d2f1 $

CREATE TABLE ISSUECOMPANY_YDAT  \
(  \
        "YEAR"               VARCHAR(4)      NOT NULL, \
        "ISSUECOMPANYCD"     VARCHAR(4)      NOT NULL, \
        "REGISTERCD"         VARCHAR(8),  \
        "UPDATED"            TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS


ALTER TABLE ISSUECOMPANY_YDAT  \
ADD CONSTRAINT PK_ISSUE_YDAT  \
PRIMARY KEY  \
( \
YEAR, \
ISSUECOMPANYCD \
)

