-- kanji=漢字
-- $Id: 10cd23bcf8cc048e93ca8a803ffcaff90e4f0623 $

DROP TABLE JOBTYPE_MGROUP_MST
CREATE TABLE JOBTYPE_MGROUP_MST( \
    M_GROUPCD   VARCHAR(2)    NOT NULL, \
    M_GROUPNAME VARCHAR(90), \
    REGISTERCD  VARCHAR(8), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE JOBTYPE_MGROUP_MST ADD CONSTRAINT PK_JOBT_MGRP_MST PRIMARY KEY (M_GROUPCD)