-- kanji=漢字
-- $Id: c8481609aaecf49e9f8a608b5bd6beb662249779 $

-- 注意:このファイルは EUC/LFのみ でなければならない。
-- 適用方法:
--    1.データベース接続
--    2.db2 +c -f <このファイル>
--    3.コミットするなら、db2 +c commit。やり直すなら、db2 +c rollback
--

DROP TABLE JOBTYPE_S_MST
CREATE TABLE JOBTYPE_S_MST( \
    JOBTYPE_LCD        VARCHAR(2)    NOT NULL, \
    JOBTYPE_MCD        VARCHAR(2)    NOT NULL, \
    JOBTYPE_SCD        VARCHAR(3)    NOT NULL, \
    JOBTYPE_SNAME      VARCHAR(150), \
    JOBTYPE_SNAME_KANA VARCHAR(300), \
    REGISTERCD         VARCHAR(10), \
    UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE JOBTYPE_S_MST ADD CONSTRAINT PK_JOBTYPE_S_MST PRIMARY KEY (JOBTYPE_LCD,JOBTYPE_MCD,JOBTYPE_SCD)