-- kanji=漢字
-- $Id: 858aea142ecc349f3d617ecb3ea178dede75f911 $

DROP TABLE JOBTYPE_LGROUP_MST
CREATE TABLE JOBTYPE_LGROUP_MST( \
    L_GROUPCD   VARCHAR(2)    NOT NULL, \
    L_GROUPNAME VARCHAR(90), \
    REGISTERCD  VARCHAR(8), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE JOBTYPE_LGROUP_MST ADD CONSTRAINT PK_JOBT_LGRP_MST PRIMARY KEY (L_GROUPCD)