-- $Id: ecaed83563f1e47b47de91ebbb3057a598703e52 $

DROP TABLE JVIEWNAME_GRADE_YDAT
CREATE TABLE JVIEWNAME_GRADE_YDAT ( \
    YEAR                  VARCHAR(4)    NOT NULL, \
    GRADE                 VARCHAR(2)    NOT NULL, \
    CLASSCD               VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND           VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD         VARCHAR(2)    NOT NULL, \
    SUBCLASSCD            VARCHAR(6)    NOT NULL, \
    VIEWCD                VARCHAR(4)    NOT NULL, \
    REGISTERCD            VARCHAR(8), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE JVIEWNAME_GRADE_YDAT ADD CONSTRAINT PK_JVN_GRADE_YDAT PRIMARY KEY (YEAR, GRADE, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, VIEWCD)
