-- $Id: 894bc367f4e427fc2139d9aa32bfa3437a94c680 $

DROP TABLE JVIEWNAME_GRADE_DETAIL_MST
CREATE TABLE JVIEWNAME_GRADE_DETAIL_MST ( \
    GRADE                 VARCHAR(2)    NOT NULL, \
    CLASSCD               VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND           VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD         VARCHAR(2)    NOT NULL, \
    SUBCLASSCD            VARCHAR(6)    NOT NULL, \
    VIEWCD                VARCHAR(4)    NOT NULL, \
    VIEW_SEQ              VARCHAR(3)    NOT NULL, \
    REMARK1               VARCHAR(120), \
    REMARK2               VARCHAR(120), \
    REMARK3               VARCHAR(120), \
    REMARK4               VARCHAR(120), \
    REMARK5               VARCHAR(120), \
    REMARK6               VARCHAR(120), \
    REMARK7               VARCHAR(120), \
    REMARK8               VARCHAR(120), \
    REMARK9               VARCHAR(120), \
    REMARK10              VARCHAR(120), \
    REGISTERCD            VARCHAR(8), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE JVIEWNAME_GRADE_DETAIL_MST ADD CONSTRAINT PK_JVN_GRD_D_MST PRIMARY KEY (GRADE, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, VIEWCD, VIEW_SEQ)
