-- $Id: 0455c11980eecd69363ec533af8a2c11ad6283e8 $

DROP TABLE JVIEWNAME_ASSESS_MST

CREATE TABLE JVIEWNAME_ASSESS_MST( \
    YEAR           VARCHAR(4)   NOT NULL, \
    GRADE          VARCHAR(2)   NOT NULL, \
    CLASSCD        VARCHAR(2)   NOT NULL, \
    CURRICULUM_CD  VARCHAR(2)   NOT NULL, \
    SCHOOL_KIND    VARCHAR(2)   NOT NULL, \
    SUBCLASSCD     VARCHAR(6)   NOT NULL, \
    JVIEW_DIV      VARCHAR(1)   NOT NULL, \
    ASSESSLEVEL    SMALLINT     NOT NULL, \
    JVIEW_CNT      SMALLINT     NOT NULL, \
    STATUS         VARCHAR(2)   , \
    REGISTERCD     VARCHAR(10)  , \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE JVIEWNAME_ASSESS_MST ADD CONSTRAINT PK_JV_NM_AS_M PRIMARY KEY (YEAR, GRADE, CLASSCD, CURRICULUM_CD, SCHOOL_KIND, SUBCLASSCD, JVIEW_DIV, ASSESSLEVEL, JVIEW_CNT)
