-- kanji=´Á»ú
-- $Id: 5f4f293036418b46cf585257b0b8bc5d7544ffd2 $

DROP TABLE JVIEWSTAT_RECORD_DETAIL_DAT

CREATE TABLE JVIEWSTAT_RECORD_DETAIL_DAT(  \
    YEAR          VARCHAR(4)  NOT NULL, \
    SEMESTER      VARCHAR(1)  NOT NULL, \
    SCHREGNO      VARCHAR(8)  NOT NULL, \
    CLASSCD       VARCHAR(2)  NOT NULL, \
    SCHOOL_KIND   VARCHAR(2)  NOT NULL, \
    CURRICULUM_CD VARCHAR(2)  NOT NULL, \
    SUBCLASSCD    VARCHAR(6)  NOT NULL, \
    VIEWCD        VARCHAR(4)  NOT NULL, \
    REMARK1       SMALLINT,  \
    REMARK2       SMALLINT,  \
    REMARK3       DECIMAL(4, 1),  \
    REMARK4       DECIMAL(5, 2),  \
    REMARK5       DECIMAL(5, 2),  \
    REGISTERCD    VARCHAR(10),  \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS

alter table JVIEWSTAT_RECORD_DETAIL_DAT ADD CONSTRAINT PK_JVIEWSTAT_REC_D PRIMARY KEY (YEAR, SEMESTER, SCHREGNO, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, VIEWCD)
