-- $Id: 205d0c5501753e6cbaf319eaf5cb25efb9813e4e $

DROP TABLE JVIEWNAME_SUB_MST
CREATE TABLE JVIEWNAME_SUB_MST ( \
    CLASSCD               VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND           VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD         VARCHAR(2)    NOT NULL, \
    SUBCLASSCD            VARCHAR(6)    NOT NULL, \
    VIEWCD                VARCHAR(4)    NOT NULL, \
    VIEWNAME              VARCHAR(75), \
    VIEWABBV              VARCHAR(60), \
    SHOWORDER             SMALLINT, \
    WEIGHT                SMALLINT, \
    REGISTERCD            VARCHAR(8), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE JVIEWNAME_SUB_MST ADD CONSTRAINT PK_JVN_SUB_MST PRIMARY KEY (CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, VIEWCD)
