-- $Id: 3c5bf3b52c9c7433e68d90c040e9960269fdf6b3 $

DROP TABLE JVIEWNAME_GRADE_MST
CREATE TABLE JVIEWNAME_GRADE_MST ( \
    GRADE                 VARCHAR(2)    NOT NULL, \
    CLASSCD               VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND           VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD         VARCHAR(2)    NOT NULL, \
    SUBCLASSCD            VARCHAR(6)    NOT NULL, \
    VIEWCD                VARCHAR(4)    NOT NULL, \
    VIEWNAME              VARCHAR(300), \
    VIEWABBV              VARCHAR(60), \
    SHOWORDER             SMALLINT, \
    STUDYREC_CLASSCD       VARCHAR(2), \
    STUDYREC_SCHOOL_KIND   VARCHAR(2), \
    STUDYREC_CURRICULUM_CD VARCHAR(2), \
    STUDYREC_SUBCLASSCD   VARCHAR(6), \
    STUDYREC_VIEWCD       VARCHAR(4), \
    REGISTERCD            VARCHAR(8), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE JVIEWNAME_GRADE_MST ADD CONSTRAINT PK_JVN_GRADE_MST PRIMARY KEY (GRADE, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, VIEWCD)
