-- $Id: 22a226ca0f961205dc5a9da6044cd7bf06a22f6c $

DROP TABLE JVIEWNAME_SUB_YDAT
CREATE TABLE JVIEWNAME_SUB_YDAT ( \
    YEAR                  VARCHAR(4)    NOT NULL, \
    CLASSCD               VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND           VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD         VARCHAR(2)    NOT NULL, \
    SUBCLASSCD            VARCHAR(6)    NOT NULL, \
    VIEWCD                VARCHAR(4)    NOT NULL, \
    REGISTERCD            VARCHAR(8), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE JVIEWNAME_SUB_YDAT ADD CONSTRAINT PK_JVN_SUB_YDAT PRIMARY KEY (YEAR, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, VIEWCD)
