-- kanji=´Á»ú
-- $Id: 9c3a443d5f83545e2aa1af368f2b93308b9196d5 $

DROP TABLE LICENSE_GROUP_PRGID_MST
CREATE TABLE LICENSE_GROUP_PRGID_MST \
(  \
        "PRGID"             VARCHAR(8) NOT NULL, \
        "PRGNAME"           VARCHAR(120) , \
        "REGISTERCD"        VARCHAR(10), \
        "UPDATED"           TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE LICENSE_GROUP_PRGID_MST ADD CONSTRAINT PK_LI_GP_PRG_MST PRIMARY KEY (PRGID)
