-- kanji=´Á»ú
-- $Id: c59e7b991f7ff45a47467a7b08fbb6388b46f778 $

DROP TABLE LICENSE_GROUP_PRGID_DAT
CREATE TABLE LICENSE_GROUP_PRGID_DAT \
(  \
        "GROUP_DIV"         VARCHAR(2) NOT NULL, \
        "PRGID"             VARCHAR(8) NOT NULL, \
        "REGISTERCD"        VARCHAR(10), \
        "UPDATED"           TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE LICENSE_GROUP_PRGID_DAT ADD CONSTRAINT PK_LI_GP_PRG_DAT PRIMARY KEY (GROUP_DIV, PRGID)
