-- kanji=漢字
-- $Id: c88fe0176490057217a3d1c1276504c04883ac09 $

DROP TABLE MAJOR_MST
CREATE TABLE MAJOR_MST( \
    COURSECD    VARCHAR(1)    NOT NULL, \
    MAJORCD     VARCHAR(3)    NOT NULL, \
    MAJORNAME   VARCHAR(60), \
    MAJORNAME2  VARCHAR(60), \
    MAJORNAME3  VARCHAR(60), \
    MAJORABBV   VARCHAR(6), \
    MAJORENG    VARCHAR(45), \
    MAJORBANKCD VARCHAR(2), \
    REGISTERCD  VARCHAR(10), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS
ALTER TABLE MAJOR_MST ADD CONSTRAINT PK_MAJOR_MST PRIMARY KEY (COURSECD,MAJORCD)
