-- kanji=漢字
-- $Id: c8983879d3a0e370583fce649dab4aa4db1ba780 $

DROP TABLE MAJOR_YDAT
CREATE TABLE MAJOR_YDAT( \
    YEAR        VARCHAR(4)    NOT NULL, \
    COURSECD    VARCHAR(1)    NOT NULL, \
    MAJORCD     VARCHAR(3)    NOT NULL, \
    SCHOOLDIV   VARCHAR(1), \
    REGISTERCD  VARCHAR(8), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS
ALTER TABLE MAJOR_YDAT ADD CONSTRAINT PK_MAJOR_YDAT PRIMARY KEY (YEAR,COURSECD,MAJORCD)