-- kanji=´Á»ú
-- $Id:

DROP TABLE MEDEXAM_DISEASE_HOKENSITU_GAITOUNASI_DAT

CREATE TABLE MEDEXAM_DISEASE_HOKENSITU_GAITOUNASI_DAT \
      (EDBOARD_SCHOOLCD     VARCHAR(12) NOT NULL, \
       YEAR                 VARCHAR(4) NOT NULL, \
       INT_VAL              INT, \
       CHAR_VAL             VARCHAR(150), \
       REGISTERCD           VARCHAR(10), \
       UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
      ) in usr1dms index in idx1dms

alter table MEDEXAM_DISEASE_HOKENSITU_GAITOUNASI_DAT add constraint PK_MEDEXAM_HS_GN primary key (EDBOARD_SCHOOLCD, YEAR)
