-- kanji=´Á»ú
-- $Id: 78198d833c7a139e8d1b742b01b9a69fa05063e3 $

drop table MEDEXAM_DET_NOT_EXAMINED_DAT

create table MEDEXAM_DET_NOT_EXAMINED_DAT ( \
    YEAR                    varchar(4)  not null, \
    GRADE                   varchar(2)  not null, \
    HEIGHT                  varchar(1), \
    WEIGHT                  varchar(1), \
    SITHEIGHT               varchar(1), \
    CHEST                   varchar(1), \
    R_BAREVISION            varchar(1), \
    R_BAREVISION_MARK       varchar(1), \
    L_BAREVISION            varchar(1), \
    L_BAREVISION_MARK       varchar(1), \
    R_VISION                varchar(1), \
    R_VISION_MARK           varchar(1), \
    L_VISION                varchar(1), \
    L_VISION_MARK           varchar(1), \
    VISION_CANTMEASURE      varchar(1), \
    R_VISION_CANTMEASURE    varchar(1), \
    L_VISION_CANTMEASURE    varchar(1), \
    R_EAR                   varchar(1), \
    R_EAR_DB                varchar(1), \
    R_EAR_DB_4000           varchar(1), \
    R_EAR_CANTMEASURE       varchar(1), \
    L_EAR                   varchar(1), \
    L_EAR_DB                varchar(1), \
    L_EAR_DB_4000           varchar(1), \
    L_EAR_CANTMEASURE       varchar(1), \
    ALBUMINURIA1CD          varchar(1), \
    URICSUGAR1CD            varchar(1), \
    URICBLEED1CD            varchar(1), \
    ALBUMINURIA2CD          varchar(1), \
    URICSUGAR2CD            varchar(1), \
    URICBLEED2CD            varchar(1), \
    URICOTHERTESTCD         varchar(1), \
    URICOTHERTEST           varchar(1), \
    URI_ADVISECD            varchar(1), \
    NUTRITIONCD             varchar(1), \
    NUTRITIONCD_REMARK      varchar(1), \
    SPINERIBCD              varchar(1), \
    SPINERIBCD_REMARK       varchar(1), \
    EYEDISEASECD            varchar(1), \
    EYEDISEASECD2           varchar(1), \
    EYEDISEASECD3           varchar(1), \
    EYEDISEASECD4           varchar(1), \
    EYEDISEASECD5           varchar(1), \
    EYE_TEST_RESULT         varchar(1), \
    EYE_TEST_RESULT2        varchar(1), \
    EYE_TEST_RESULT3        varchar(1), \
    NOSEDISEASECD           varchar(1), \
    NOSEDISEASECD2          varchar(1), \
    NOSEDISEASECD3          varchar(1), \
    NOSEDISEASECD4          varchar(1), \
    NOSEDISEASECD5          varchar(1), \
    NOSEDISEASECD6          varchar(1), \
    NOSEDISEASECD7          varchar(1), \
    NOSEDISEASECD_REMARK    varchar(1), \
    NOSEDISEASECD_REMARK1   varchar(1), \
    NOSEDISEASECD_REMARK2   varchar(1), \
    NOSEDISEASECD_REMARK3   varchar(1), \
    SKINDISEASECD           varchar(1), \
    SKINDISEASECD_REMARK    varchar(1), \
    HEART_MEDEXAM           varchar(1), \
    HEART_MEDEXAM_REMARK    varchar(1), \
    HEARTDISEASECD          varchar(1), \
    HEARTDISEASECD_REMARK   varchar(1), \
    MANAGEMENT_DIV          varchar(1), \
    MANAGEMENT_REMARK       varchar(1), \
    TB_DATE                 varchar(1), \
    TB_REACT                varchar(1), \
    TB_RESULT               varchar(1), \
    TB_BCGDATE              varchar(1), \
    TB_FILMDATE             varchar(1), \
    TB_FILMNO               varchar(1), \
    TB_REMARKCD             varchar(1), \
    TB_OTHERTESTCD          varchar(1), \
    TB_OTHERTEST_REMARK1    varchar(1), \
    TB_NAMECD               varchar(1), \
    TB_NAME_REMARK1         varchar(1), \
    TB_ADVISECD             varchar(1), \
    TB_ADVISE_REMARK1       varchar(1), \
    TB_X_RAY                varchar(1), \
    ANEMIA_REMARK           varchar(1), \
    HEMOGLOBIN              varchar(1), \
    PARASITE                varchar(1), \
    OTHERDISEASECD          varchar(1), \
    OTHER_ADVISECD          varchar(1), \
    OTHER_REMARK            varchar(1), \
    OTHER_REMARK2           varchar(1), \
    OTHER_REMARK3           varchar(1), \
    DOC_CD                  varchar(1), \
    DOC_REMARK              varchar(1), \
    DOC_DATE                varchar(1), \
    TREATCD                 varchar(1), \
    TREATCD2                varchar(1), \
    TREAT_REMARK1           varchar(1), \
    TREAT_REMARK2           varchar(1), \
    TREAT_REMARK3           varchar(1), \
    REMARK                  varchar(1), \
    NUTRITION_RESULT        varchar(1), \
    EYEDISEASE_RESULT       varchar(1), \
    SKINDISEASE_RESULT      varchar(1), \
    SPINERIB_RESULT         varchar(1), \
    NOSEDISEASE_RESULT      varchar(1), \
    OTHERDISEASE_RESULT     varchar(1), \
    HEARTDISEASE_RESULT     varchar(1), \
    GUIDE_DIV               varchar(1), \
    JOINING_SPORTS_CLUB     varchar(1), \
    MEDICAL_HISTORY1        varchar(1), \
    MEDICAL_HISTORY2        varchar(1), \
    MEDICAL_HISTORY3        varchar(1), \
    DIAGNOSIS_NAME          varchar(1), \
    MESSAGE                 varchar(1), \
    REGISTERCD              varchar(10), \
    UPDATED                 timestamp default current timestamp \
    ) in usr1dms index in idx1dms

alter table MEDEXAM_DET_NOT_EXAMINED_DAT add constraint PK_MED_DET_NO_E_D primary key (YEAR, GRADE)
