-- $Id: c48e585d66d7005a865b13717557ec47dddf1fdc $

DROP TABLE MEDEXAM_DET_NO_DAT

CREATE TABLE MEDEXAM_DET_NO_DAT( \
    YEAR              VARCHAR(4) NOT NULL , \
    SCHREGNO          VARCHAR(8) NOT NULL , \
    NO                VARCHAR(2) NOT NULL , \
    DATE              DATE , \
    HEIGHT            DECIMAL(4,1) , \
    WEIGHT            DECIMAL(4,1) , \
    SITHEIGHT         DECIMAL(4,1) , \
    R_BAREVISION      VARCHAR(5) , \
    R_BAREVISION_MARK VARCHAR(3) , \
    L_BAREVISION      VARCHAR(5) , \
    L_BAREVISION_MARK VARCHAR(3) , \
    R_VISION          VARCHAR(5) , \
    R_VISION_MARK     VARCHAR(3) , \
    L_VISION          VARCHAR(5) , \
    L_VISION_MARK     VARCHAR(3) , \
    REGISTERCD        VARCHAR(10) , \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE MEDEXAM_DET_NO_DAT ADD CONSTRAINT PK_MEDEX_D_NO_DAT PRIMARY KEY (YEAR, SCHREGNO, NO)
