-- $Id: 297150a9c4d4ec0ba6486c1993f74e7b03f6ea6f $

DROP TABLE MEDICAL_WORK_RECORD_DAT
CREATE TABLE MEDICAL_WORK_RECORD_DAT( \
    WORK_DATE               DATE          NOT NULL, \
    STAFFCD                 VARCHAR(8)    NOT NULL, \
    WORK_DIV                VARCHAR(1)    NOT NULL, \
    NEWS_STORY              VARCHAR(770), \
    SPECIAL_REPORT          VARCHAR(770), \
    REGISTERCD              VARCHAR(8), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE MEDICAL_WORK_RECORD_DAT ADD CONSTRAINT PK_MED_WORK_REC PRIMARY KEY (WORK_DATE, STAFFCD, WORK_DIV)