-- $Id: 1d5ad019f6d64b88359dc02d5b6a48b0b6f5bd8d $

DROP TABLE MEDICAL_CARE_NAME_MST
CREATE TABLE MEDICAL_CARE_NAME_MST( \
    NAMECD                  VARCHAR(3)    NOT NULL, \
    NAME                    VARCHAR(90), \
    REGISTERCD              VARCHAR(8), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE MEDICAL_CARE_NAME_MST ADD CONSTRAINT PK_MED_CA_NAME_MST PRIMARY KEY (NAMECD)