-- $Id: 27e5d09cb78e1169346ce0b0b7bfa6ed07a9c6fb $

DROP TABLE MEDICAL_DEPARTMENTS_MST
CREATE TABLE MEDICAL_DEPARTMENTS_MST( \
    NAMECD                  VARCHAR(3)    NOT NULL, \
    NAME                    VARCHAR(90), \
    ABBV                    VARCHAR(30), \
    REGISTERCD              VARCHAR(8), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE MEDICAL_DEPARTMENTS_MST ADD CONSTRAINT PK_MED_DEPART_MST PRIMARY KEY (NAMECD)