DROP TABLE MENU_SUB_MST

CREATE TABLE MENU_SUB_MST
    (SCHOOLCD        VARCHAR(12) NOT NULL, \
     SCHOOL_KIND     VARCHAR(2)  NOT NULL, \
     SUBID           VARCHAR(11) NOT NULL, \
     SUBSUBID        VARCHAR(2), \
     PARENTSUBID     VARCHAR(11), \
     SUBNAME         VARCHAR(120), \
     SUBNAME_ENG     VARCHAR(120), \
     MAINID          VARCHAR(11), \
     SYORI_MONTH     INT, \
     HIDE_FLG        varchar(1), \
     REGISTERCD      VARCHAR(10), \
     UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) in usr1dms index in idx1dms

ALTER TABLE MENU_SUB_MST ADD CONSTRAINT PK_MENU_SUB_MST PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, SUBID)
