-- kanji=漢字
-- 実行前にDROP FUNCTION SECURITY_CHK_MNU、SECURITY_CHK_PRG実行し、再度FUNCTIONのSCRIPTを実行する必要あり
-- $Id: eb1e03e3901aade3b0e64a507711ddc30361ac81 $

DROP TABLE MENU_STAFF_MST

CREATE TABLE MENU_STAFF_MST( \
    SCHOOLCD        VARCHAR(12) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)  NOT NULL, \
    STAFFCD         VARCHAR(10) NOT NULL, \
    MENUID          VARCHAR(11) NOT NULL, \
    SUBMENUID       VARCHAR(1), \
    PARENTMENUID    VARCHAR(11), \
    MENUNAME        VARCHAR(120), \
    PROGRAMID       VARCHAR(20), \
    PROGRAMPATH     VARCHAR(40), \
    PROCESSCD       VARCHAR(1), \
    INVALID_FLG     VARCHAR(1), \
    PROGRAMMEMO     VARCHAR(3000), \
    SHOWORDER       SMALLINT, \
    SSL             VARCHAR(1), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE MENU_STAFF_MST ADD CONSTRAINT PK_MENU_STAFF PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, STAFFCD, MENUID)
