-- $Id: dd7c32f0de164a6194de8496db59cb35843323e8 $

DROP TABLE MOCK2_DAT
CREATE TABLE MOCK2_DAT( \
    YEAR             VARCHAR(4)    NOT NULL, \
    MOCKCD           VARCHAR(9)    NOT NULL, \
    SCHREGNO         VARCHAR(8)    NOT NULL, \
    MOCK_SUBCLASS_CD VARCHAR(6)    NOT NULL, \
    MOCKDIV          VARCHAR(1)    NOT NULL, \
    SCORE            SMALLINT, \
    AVG              DECIMAL(9,5), \
    DEVIATION        DECIMAL(4,1), \
    RANK             SMALLINT, \
    COUNT            SMALLINT, \
    REGISTERCD       VARCHAR(8), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE MOCK2_DAT ADD CONSTRAINT PK_MOCK2_DAT PRIMARY KEY (YEAR,MOCKCD,SCHREGNO,MOCK_SUBCLASS_CD,MOCKDIV)