-- $Id: e2fbc20b6c3c519fbf4389cb6f34ceefd7709796 $

DROP TABLE MOCK_DOCUMENT_GDAT
CREATE TABLE MOCK_DOCUMENT_GDAT( \
    YEAR             VARCHAR(4)    NOT NULL, \
    GROUP_DIV        VARCHAR(1)    NOT NULL, \
    STF_AUTH_CD      VARCHAR(8)    NOT NULL, \
    GROUPCD          VARCHAR(4)    NOT NULL, \
    GRADE            VARCHAR(2)    NOT NULL, \
    MOCK_SUBCLASS_CD VARCHAR(6)    NOT NULL, \
    REMARK1          VARCHAR(300), \
    REMARK2          VARCHAR(300), \
    REGISTERCD       VARCHAR(8), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE MOCK_DOCUMENT_GDAT ADD CONSTRAINT PK_MOCK_DOCU_GDAT PRIMARY KEY (YEAR,GROUP_DIV,STF_AUTH_CD,GROUPCD,GRADE,MOCK_SUBCLASS_CD)