-- $Id: 159e5f4a2b27267f39460bc0529ece5263e9eeaf $

DROP TABLE MOCK_DOCUMENT_SDAT
CREATE TABLE MOCK_DOCUMENT_SDAT( \
    YEAR             VARCHAR(4)    NOT NULL, \
    GROUP_DIV        VARCHAR(1)    NOT NULL, \
    STF_AUTH_CD      VARCHAR(8)    NOT NULL, \
    GROUPCD          VARCHAR(4)    NOT NULL, \
    SCHREGNO         VARCHAR(8)    NOT NULL, \
    MOCK_SUBCLASS_CD VARCHAR(6)    NOT NULL, \
    REMARK1          VARCHAR(30), \
    REMARK2          VARCHAR(30), \
    REMARK3          VARCHAR(30), \
    REMARK4          VARCHAR(300), \
    REGISTERCD       VARCHAR(8), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE MOCK_DOCUMENT_SDAT ADD CONSTRAINT PK_MOCK_DOCU_SDAT PRIMARY KEY (YEAR,GROUP_DIV,STF_AUTH_CD,GROUPCD,SCHREGNO,MOCK_SUBCLASS_CD)