create table NURSEOFF_VISIT_TEXT_DAT( \
    SCHREGNO      VARCHAR(8)   NOT NULL, \
    VISIT_DATE    DATE         NOT NULL, \
    VISIT_HOUR    VARCHAR(2)   NOT NULL, \
    VISIT_MINUTE  VARCHAR(2)   NOT NULL, \
    OCCUR_CAUSE   VARCHAR(60) , \
    OCCUR_PLACE   VARCHAR(60) , \
    TREATMENT     VARCHAR(60) , \
    REGISTERCD    VARCHAR(10) , \
    UPDATED       TIMESTAMP    DEFAULT CURRENT TIMESTAMP \
 ) in usr1dms index in idx1dms

alter table NURSEOFF_VISIT_TEXT_DAT add constraint NURSEOFF_V_T_DAT primary key (SCHREGNO,VISIT_DATE,VISIT_HOUR,VISIT_MINUTE)

