-- $Id: 776c6f83ed2c96368abf98e1e708adbb18fa6e8d $

DROP TABLE NURSEOFFICE_DAT
CREATE TABLE NURSEOFFICE_DAT( \
    SCHREGNO      VARCHAR(8)    NOT NULL, \
    YEAR          VARCHAR(4)    NOT NULL, \
    DATE          TIMESTAMP     NOT NULL, \
    TREATMENT_DIV VARCHAR(2)    NOT NULL, \
    VISIT_REASON  VARCHAR(2), \
    PERIOD        VARCHAR(2), \
    TEMPERATURE   DECIMAL(3,1), \
    OCCURTIMECD   VARCHAR(2), \
    OCCURTIME     TIME, \
    BEDTIME       TIME, \
    RISINGTIME    TIME, \
    SLEEPING      VARCHAR(2), \
    BREAKFAST     VARCHAR(2), \
    NURSETREAT    VARCHAR(2), \
    REMARK        VARCHAR(120), \
    REGISTERCD    VARCHAR(8), \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE NURSEOFFICE_DAT ADD CONSTRAINT PK_NURSE_DAT PRIMARY KEY (SCHREGNO,YEAR,DATE,TREATMENT_DIV)