-- $Id: 65c1ed46df38bf8b47572edc293f9bea782a90f6 $

DROP TABLE NV_CCALC_EXEC_DAT

CREATE TABLE NV_CCALC_EXEC_DAT( \
    CALC_DATE           DATE          NOT NULL, \
    CALC_TIME           TIME          NOT NULL, \
    GRADE               VARCHAR(2)    NOT NULL, \
    CLASSCD         	VARCHAR(2) 	  NOT NULL , \
    SCHOOL_KIND      	VARCHAR(2)	  NOT NULL , \
    CURRICULUM_CD    	VARCHAR(2) 	  NOT NULL , \
    SUBCLASSCD          VARCHAR(6)    NOT NULL, \
    CREDIT_CALC         VARCHAR(1), \
    ATTEND_DATE         DATE, \
    YEAR                VARCHAR(4), \
    REGISTERCD          VARCHAR(8), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE NV_CCALC_EXEC_DAT ADD CONSTRAINT PK_NV_CC_EXE_DAT PRIMARY KEY (CALC_DATE,CALC_TIME,GRADE,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)
