-- $Id: c8129224044a7f0b497c3b97ad515e98ba839803 $

DROP TABLE PARTNER_SCHOOL_MST
CREATE TABLE PARTNER_SCHOOL_MST( \
    PARTNER_SCHOOLCD         VARCHAR(12)    NOT NULL, \
    PARTNER_SCHOOL_TYPE      VARCHAR(1), \
    PARTNER_SCHOOL_DISTCD    VARCHAR(4), \
    PARTNER_SCHOOL_DISTCD2   VARCHAR(3), \
    PARTNER_SCHOOL_DIV       VARCHAR(1), \
    PARTNER_SCHOOL_NAME      VARCHAR(75), \
    PARTNER_SCHOOL_KANA      VARCHAR(75), \
    PARTNER_SCHOOL_NAME_ABBV VARCHAR(30), \
    PARTNER_SCHOOL_KANA_ABBV VARCHAR(75), \
    PRINCNAME               VARCHAR(60), \
    PRINCNAME_SHOW          VARCHAR(30), \
    PRINCKANA               VARCHAR(120), \
    DISTRICTCD              VARCHAR(2), \
    PARTNER_SCHOOL_PREF_CD   VARCHAR(2), \
    PARTNER_SCHOOL_ZIPCD     VARCHAR(8), \
    PARTNER_SCHOOL_ADDR1     VARCHAR(150), \
    PARTNER_SCHOOL_ADDR2     VARCHAR(150), \
    PARTNER_SCHOOL_TELNO     VARCHAR(14), \
    PARTNER_SCHOOL_FAXNO     VARCHAR(14), \
    EDBOARDCD               VARCHAR(6), \
    REGISTERCD              VARCHAR(10), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE PARTNER_SCHOOL_MST ADD CONSTRAINT PK_PART_SCHOOL_M PRIMARY KEY (PARTNER_SCHOOLCD)