-- $Id: b951c6764767f0163c0bccf6c3475b8020b5ebc6 $

drop table PASS_SCORE_DAT

create table PASS_SCORE_DAT ( \
    YEAR           VARCHAR(4)   NOT NULL, \
    SEMESTER       VARCHAR(1)   NOT NULL, \
    TESTKINDCD     VARCHAR(2)   NOT NULL, \
    TESTITEMCD     VARCHAR(2)   NOT NULL, \
    SCORE_DIV      VARCHAR(2)   NOT NULL, \
    RUISEKI_DIV    VARCHAR(1)   NOT NULL, \
    CLASSCD        VARCHAR(2)   NOT NULL, \
    SCHOOL_KIND    VARCHAR(2)   NOT NULL, \
    CURRICULUM_CD  VARCHAR(2)   NOT NULL, \
    SUBCLASSCD     VARCHAR(6)   NOT NULL, \
    PASS_DIV       VARCHAR(1)   NOT NULL, \
    GRADE          VARCHAR(2)   NOT NULL, \
    HR_CLASS       VARCHAR(3)   NOT NULL, \
    COURSECD       VARCHAR(1)   NOT NULL, \
    MAJORCD        VARCHAR(3)   NOT NULL, \
    COURSECODE     VARCHAR(4)   NOT NULL, \
    SCORE_LINE     SMALLINT    , \
    REGISTERCD     VARCHAR(10) , \
    UPDATED        TIMESTAMP    DEFAULT CURRENT TIMESTAMP \
) in usr1dms index in idx1dms

alter table PASS_SCORE_DAT add constraint PK_PASS_SCORE primary key (YEAR,SEMESTER,TESTKINDCD,TESTITEMCD,SCORE_DIV,RUISEKI_DIV,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,PASS_DIV,GRADE,HR_CLASS,COURSECD,MAJORCD,COURSECODE)
