-- $Id: 8169ce41f21299088be3ab8acb4e86876a7b9ac5 $

DROP TABLE PORTFOLIO_HEAD_MST
CREATE TABLE PORTFOLIO_HEAD_MST( \
    SCHOOLCD            VARCHAR(12)   NOT NULL, \
    SCHOOL_KIND         VARCHAR(2)    NOT NULL, \
    COURSECD            VARCHAR(1)    NOT NULL, \
    SEQ                 VARCHAR(2)    NOT NULL, \
    HEADNAME            VARCHAR(60)   NOT NULL, \
    FIELDNAME           VARCHAR(128)  NOT NULL, \
    SHOWORDER           VARCHAR(2), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE PORTFOLIO_HEAD_MST ADD CONSTRAINT PK_PORT_HEAD_M PRIMARY KEY (SCHOOLCD,SCHOOL_KIND,COURSECD,SEQ)