-- $Id: c65297d1117205cf69fe7a3139ede93b830b1002 $

DROP TABLE POSITION_MST
CREATE TABLE POSITION_MST( \
    POSITIONCD           VARCHAR(4)    NOT NULL, \
    POSITIONNAME         VARCHAR(60), \
    POSITIONABBV1        VARCHAR(60), \
    POSITIONABBV2        VARCHAR(60), \
    BASE_POSITIONNAME    VARCHAR(60), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE POSITION_MST ADD CONSTRAINT PK_POSITION_MST PRIMARY KEY (POSITIONCD)