-- kanji=´Á»ú
-- $Id: d2128dcbe63b86ce47f28d158c1427dfdc0ee910 $

DROP TABLE PRG_DEFAULT_VALUE_DAT

CREATE TABLE PRG_DEFAULT_VALUE_DAT ( \
        "SCHOOLCD"        VARCHAR(12) NOT NULL, \
        "SCHOOL_KIND"     VARCHAR(2)  NOT NULL, \
        "PROGRAMID"       VARCHAR(50) NOT NULL, \
        "OBJ_NAME"        VARCHAR(50) NOT NULL, \
        "DEFAULT_VAL"     VARCHAR(90), \
        "REGISTERCD"      VARCHAR(10), \
        "UPDATED"         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE PRG_DEFAULT_VALUE_DAT ADD CONSTRAINT PK_PRG_DEFAULT_DAT PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, PROGRAMID, OBJ_NAME)
