-- kanji=´Á»ú
-- $Id: 28dbe2b6c06312de8d52264629c8c785d1d9db65 $

DROP TABLE PRG_STAMP_DAT

CREATE TABLE PRG_STAMP_DAT ( \
        "YEAR"            VARCHAR(4) NOT NULL, \
        "SEMESTER"        VARCHAR(1) NOT NULL, \
        "SCHOOLCD"        VARCHAR(12) NOT NULL, \
        "SCHOOL_KIND"     VARCHAR(2) NOT NULL, \
        "PROGRAMID"       VARCHAR(20) NOT NULL, \
        "SEQ"             VARCHAR(2)  NOT NULL, \
        "TITLE"           VARCHAR(90), \
        "FILE_NAME"       VARCHAR(90), \
        "REGISTERCD"      VARCHAR(10), \
        "UPDATED"         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE PRG_STAMP_DAT ADD CONSTRAINT PK_PRG_STAMP_DAT PRIMARY KEY (YEAR, SEMESTER, SCHOOLCD, SCHOOL_KIND, PROGRAMID, SEQ)
