-- $Id: fb33c237997c27add47f6f60820b811de5a81dc7 $

DROP TABLE PRGINFO_PROPERTIES
CREATE TABLE PRGINFO_PROPERTIES( \
    PROGRAMID  VARCHAR(20)   NOT NULL, \
    NAME       VARCHAR(50)   NOT NULL, \
    VALUE      VARCHAR(300), \
    SORT       SMALLINT, \
    REMARK     VARCHAR(300), \
    COMMENT_1  VARCHAR(300), \
    COMMENT_2  VARCHAR(300), \
    COMMENT_3  VARCHAR(300), \
    COMMENT_4  VARCHAR(300), \
    REGISTERCD VARCHAR(10), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE PRGINFO_PROPERTIES ADD CONSTRAINT PK_PROPERTIES PRIMARY KEY (PROGRAMID, NAME)