-- $Id: 64aae86c095c25e66772bc83b660c4f03b4147fb $

DROP TABLE PRGINFO_PROPERTIES_PRGID
CREATE TABLE PRGINFO_PROPERTIES_PRGID( \
    PROGRAMID  VARCHAR(20)   NOT NULL, \
    NAME       VARCHAR(50)   NOT NULL, \
    VALUE      VARCHAR(300), \
    SORT       SMALLINT, \
    REMARK     VARCHAR(300), \
    COMMENT_1  VARCHAR(300), \
    COMMENT_2  VARCHAR(300), \
    COMMENT_3  VARCHAR(300), \
    COMMENT_4  VARCHAR(300), \
    REGISTERCD VARCHAR(10), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE PRGINFO_PROPERTIES_PRGID ADD CONSTRAINT PK_PROPERTIES_PRGID PRIMARY KEY (PROGRAMID,NAME)

INSERT INTO PRGINFO_PROPERTIES_PRGID \
    SELECT \
        PROGRAMID, \
        NAME, \
        VALUE, \
        SORT, \
        WEATHER, \
        REMARK, \
        COMMENT_1, \
        COMMENT_2, \
        COMMENT_3, \
        COMMENT_4, \
        REGISTERCD, \
        UPDATED \
    FROM \
        PRGINFO_PROPERTIES_PRGID
