-- $Id: decc900a82b2496269f54471ec4b0654c74e8972 $

drop table PROFICIENCY_DOCUMENT_DAT

create table PROFICIENCY_DOCUMENT_DAT ( \
 YEAR              VARCHAR(4)     NOT NULL, \
 SEMESTER          VARCHAR(1)     NOT NULL, \
 PROFICIENCYDIV    VARCHAR(2)     NOT NULL, \
 PROFICIENCYCD     VARCHAR(4)     NOT NULL, \
 GRADE             VARCHAR(2)     NOT NULL, \
 COURSECD          VARCHAR(1)     NOT NULL, \
 MAJORCD           VARCHAR(3)     NOT NULL, \
 COURSECODE        VARCHAR(4)     NOT NULL, \
 PROFICIENCY_SUBCLASS_CD  VARCHAR(6)     NOT NULL, \
 FOOTNOTE          VARCHAR(1050) , \
 REGISTERCD        VARCHAR(10)   , \
 UPDATED           TIMESTAMP      DEFAULT CURRENT TIMESTAMP \
 ) in usr1dms index in idx1dms

alter table PROFICIENCY_DOCUMENT_DAT add constraint PK_PROFC_DOC_DAT primary key (YEAR,SEMESTER,PROFICIENCYDIV,PROFICIENCYCD,GRADE,COURSECD,MAJORCD,COURSECODE,PROFICIENCY_SUBCLASS_CD)
