
create table PV_CBT_FIELD_MST( \
    VERSION_ID   VARCHAR(12)  NOT NULL, \
    SUBCLASSCD   VARCHAR(2)   NOT NULL, \
    FIRST_ID     VARCHAR(2)   NOT NULL, \
    FIRST_NAME   VARCHAR(90) , \
    SECOND_ID    VARCHAR(2)   NOT NULL, \
    SECOND_NAME  VARCHAR(90) , \
    THIRD_ID     VARCHAR(2)   NOT NULL, \
    THIRD_NAME   VARCHAR(90) , \
    FOURTH_ID    VARCHAR(2)   NOT NULL, \
    FOURTH_NAME  VARCHAR(90) , \
    FIFTH_ID     VARCHAR(2)   NOT NULL, \
    FIFTH_NAME   VARCHAR(90) , \
    REGISTERCD   VARCHAR(10) , \
    UPDATED      TIMESTAMP    DEFAULT CURRENT TIMESTAMP \
 ) in usr1dms index in idx1dms

alter table PV_CBT_FIELD_MST add constraint PK_PV_CBT_FIELD_MST primary key (VERSION_ID,SUBCLASSCD,FIRST_ID,SECOND_ID,THIRD_ID,FOURTH_ID,FIFTH_ID)

