
create table PV_MBT_SCORE_DETAIL_DAT( \
    RECORD_KUBUN  VARCHAR(2)   NOT NULL, \
    YEAR          VARCHAR(4)   NOT NULL, \
    SCHOOL_CD     VARCHAR(30)  NOT NULL, \
    STUDENT_ID    VARCHAR(30)  NOT NULL, \
    TEACHING_CD   VARCHAR(5)   NOT NULL, \
    TAKE_CNT      SMALLINT     NOT NULL, \
    KIND_CD       VARCHAR(2)  , \
    JUDGE         VARCHAR(2)  , \
    QUESTION_NO   VARCHAR(15)  NOT NULL, \
    PART_LEVEL    VARCHAR(2)  , \
    FIELDNO       VARCHAR(10)  NOT NULL, \
    REGISTERCD    VARCHAR(10) , \
    UPDATED       TIMESTAMP    DEFAULT CURRENT TIMESTAMP \
 ) in usr1dms index in idx1dms

alter table PV_MBT_SCORE_DETAIL_DAT add constraint PK_PV_MBT_SCORE_DETAIL_DAT primary key (YEAR,SCHOOL_CD,STUDENT_ID,TEACHING_CD,TAKE_CNT,FIELDNO,QUESTION_NO)

