-- $Id: 89b496404bbd591c5ef3f833fe0f73136b708daf $

DROP TABLE PYP_ELEMENT_MST
CREATE TABLE PYP_ELEMENT_MST( \
    ELEMENT_DIV             VARCHAR(1)    NOT NULL, \
    ELEMENT_CD              VARCHAR(3)    NOT NULL, \
    ELEMENT_NAME            VARCHAR(100)          , \
    REGISTERCD              VARCHAR(10)           , \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN usr1dms index in idx1dms

ALTER TABLE PYP_ELEMENT_MST ADD CONSTRAINT PK_PYP_ELEMENT_MST PRIMARY KEY (ELEMENT_DIV, ELEMENT_CD)
