-- $Id: 1bd564888472d6a460b5ad8131fc1a6257a22607 $

DROP TABLE QUALIFIED_MST
CREATE TABLE QUALIFIED_MST( \
    QUALIFIED_CD   VARCHAR(4)    NOT NULL, \
    CONDITION_DIV  VARCHAR(1), \
    QUALIFIED_NAME VARCHAR(150), \
    QUALIFIED_ABBV VARCHAR(75), \
    SAKI_FLG       VARCHAR(1), \
    PROMOTER       VARCHAR(150), \
    MANAGEMENT_FLG VARCHAR(1), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE QUALIFIED_MST ADD CONSTRAINT PK_QUALIFIED_MST PRIMARY KEY (QUALIFIED_CD)