-- $Id: 2470db7e1c060b3217b0818cd265133e9a511b2b $

DROP TABLE QUESTION_FORMAT_DAT

CREATE TABLE QUESTION_FORMAT_DAT( \
     YEAR                   VARCHAR(4)  NOT NULL, \
     QUESTIONNAIRECD        VARCHAR(2)  NOT NULL, \
     QUESTIONITEM_NO        SMALLINT    NOT NULL, \
     QUESTION_CONTENTS      VARCHAR(1000), \
     ANSWER_PATTERN         VARCHAR(1), \
     ANSWER_SELECT_COUNT    SMALLINT, \
     REGISTERCD             VARCHAR(8), \
     UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE QUESTION_FORMAT_DAT ADD CONSTRAINT PK_QU_FORMAT_DAT PRIMARY KEY (YEAR, QUESTIONNAIRECD, QUESTIONITEM_NO)