-- $Id: 30870c16711a8c9f810e01f1977935403db09369 $

DROP TABLE RECORD_MOCK_ORDER_SDIV_DAT
CREATE TABLE RECORD_MOCK_ORDER_SDIV_DAT ( \
     YEAR           VARCHAR(4) NOT NULL, \
     GRADE          VARCHAR(2) NOT NULL, \
     COURSECD       VARCHAR(1) NOT NULL, \
     MAJORCD        VARCHAR(3) NOT NULL, \
     SEQ            SMALLINT   NOT NULL, \
     TEST_DIV       VARCHAR(1) NOT NULL, \
     SEMESTER       VARCHAR(1), \
     TESTKINDCD     VARCHAR(2), \
     TESTITEMCD     VARCHAR(2), \
     SCORE_DIV      VARCHAR(2), \
     PRISCHOOLCD    VARCHAR(7), \
     REGISTERCD     VARCHAR(8), \
     UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_MOCK_ORDER_SDIV_DAT ADD CONSTRAINT PK_REC_MK_ODR_SDIV PRIMARY KEY \
(YEAR, GRADE, COURSECD, MAJORCD, SEQ)
