-- $Id: 8db5ae41176d774e9febe0ebb3b67af04a4019ef $

DROP TABLE RECORD_TOTALSTUDYTIME_ITEM_MST

CREATE TABLE RECORD_TOTALSTUDYTIME_ITEM_MST( \
    CLASSCD           VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND       VARCHAR(2)    NOT NULL, \
    COLUMNNAME        VARCHAR(30)   NOT NULL, \
    ITEMNAME          VARCHAR(150) , \
    SHOWORDER         SMALLINT     , \
    SHOW_FLG          VARCHAR(1)   , \
    DATA_SIZE         VARCHAR(10)  , \
    PATTERN_DATA_DIV  VARCHAR(2)   , \
    PATTERN_SHOW_FLG  VARCHAR(1)   , \
    REMARK1           VARCHAR(30)  , \
    REMARK2           VARCHAR(30)  , \
    REMARK3           VARCHAR(30)  , \
    REGISTERCD        VARCHAR(10)  , \
    UPDATED           TIMESTAMP     DEFAULT CURRENT TIMESTAMP \
 ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_TOTALSTUDYTIME_ITEM_MST ADD CONSTRAINT PK_RECORD_T_IT_MST PRIMARY KEY (CLASSCD,SCHOOL_KIND,COLUMNNAME)

