-- $Id: 278db1d2dee7fa6c938568287af90b3538d53729 $

DROP TABLE RECORD_REMARK_DAT
CREATE TABLE RECORD_REMARK_DAT( \
    YEAR            VARCHAR(4)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    SCHREGNO        VARCHAR(8)    NOT NULL, \
    REMARK          VARCHAR(60), \
    RECOGNITION_FLG VARCHAR(1), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_REMARK_DAT ADD CONSTRAINT PK_REC_REMARK_DAT PRIMARY KEY (YEAR,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO)