-- kanji=漢字
-- $Id: 73913105e517f2c80e504477589e62c4bc228c6d $

DROP TABLE RECORD_RANK_EXEC_GCM_SDIV_DAT

CREATE TABLE RECORD_RANK_EXEC_GCM_SDIV_DAT( \
    SCHOOLCD      VARCHAR(12)   NOT NULL, \
    CALC_DATE     DATE          NOT NULL, \
    CALC_TIME     TIME          NOT NULL, \
    CLASSCD       VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND   VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD VARCHAR(2)    NOT NULL, \
    SUBCLASSCD    VARCHAR(6)    NOT NULL, \
    YEAR          VARCHAR(4), \
    SEMESTER      VARCHAR(1), \
    TESTKINDCD    VARCHAR(2), \
    TESTITEMCD    VARCHAR(2), \
    SCORE_DIV     VARCHAR(2), \
    GRADE         VARCHAR(2), \
    COURSECD      VARCHAR(1), \
    MAJORCD       VARCHAR(3), \
    CHAIRDATE     DATE, \
    ELECTDIV_FLG  VARCHAR(1), \
    REGISTERCD    VARCHAR(10), \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_RANK_EXEC_GCM_SDIV_DAT ADD CONSTRAINT PK_RCRK_EX_GCM_SDV PRIMARY KEY (SCHOOLCD,CALC_DATE,CALC_TIME,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)