-- kanji=漢字
-- $Id: 132454acffb037cb1fd6cfc956adff6d187dad09 $

DROP TABLE RECORD_RANK_CHAIR_DETAIL_SDIV_DAT
CREATE TABLE RECORD_RANK_CHAIR_DETAIL_SDIV_DAT \
(  \
    YEAR                  VARCHAR(4)    NOT NULL, \
    SEMESTER              VARCHAR(1)    NOT NULL, \
    TESTKINDCD            VARCHAR(2)    NOT NULL, \
    TESTITEMCD            VARCHAR(2)    NOT NULL, \
    SCORE_DIV             VARCHAR(2)    NOT NULL, \
    CLASSCD               VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND           VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD         VARCHAR(2)    NOT NULL, \
    SUBCLASSCD            VARCHAR(6)    NOT NULL, \
    CHAIRCD               VARCHAR(7)    NOT NULL, \
    SCHREGNO              VARCHAR(8)    NOT NULL, \
    RANK_DIV              VARCHAR(1)    NOT NULL, \
    RANK                  SMALLINT, \
    AVG_RANK              SMALLINT, \
    DEVIATION             DECIMAL(4,1), \
    DEVIATION_RANK        SMALLINT, \
    REGISTERCD            VARCHAR(10), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_RANK_CHAIR_DETAIL_SDIV_DAT ADD CONSTRAINT PK_REC_R_CHR_SD_DT PRIMARY KEY (YEAR,SEMESTER,TESTKINDCD,TESTITEMCD,SCORE_DIV,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,CHAIRCD,SCHREGNO,RANK_DIV)