-- kanji=漢字
-- $Id: 5b1c25efbc8b9c76b78b572037adcd0b17c2b663 $

DROP TABLE RECORD_CHKFIN_SDIV_DAT
CREATE TABLE RECORD_CHKFIN_SDIV_DAT \
(  \
    YEAR            VARCHAR (4) NOT NULL, \
    SEMESTER        VARCHAR (1) NOT NULL, \
    CLASSCD         VARCHAR (2) NOT NULL, \
    SCHOOL_KIND     VARCHAR (2) NOT NULL, \
    CURRICULUM_CD   VARCHAR (2) NOT NULL, \
    SUBCLASSCD      VARCHAR (6) NOT NULL, \
    CHAIRCD         VARCHAR (7) NOT NULL, \
    TESTKINDCD      VARCHAR (2) NOT NULL, \
    TESTITEMCD      VARCHAR (2) NOT NULL, \
    RECORD_DIV      VARCHAR (2) NOT NULL, \
    EXECUTEDATE     DATE, \
    EXECUTED        VARCHAR (1), \
    REGISTERCD      VARCHAR (8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_CHKFIN_SDIV_DAT ADD CONSTRAINT PK_REC_CF_SD_DAT \
PRIMARY KEY (YEAR, SEMESTER, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, CHAIRCD, TESTKINDCD, TESTITEMCD, RECORD_DIV)
