-- $Id: dbd59fce94cef2bd4df76451db394ff611639da6 $

DROP TABLE RECORD_RANK_DETAIL_SDIV_DAT
CREATE TABLE RECORD_RANK_DETAIL_SDIV_DAT( \
    YEAR                  VARCHAR(4)    NOT NULL, \
    SEMESTER              VARCHAR(1)    NOT NULL, \
    TESTKINDCD            VARCHAR(2)    NOT NULL, \
    TESTITEMCD            VARCHAR(2)    NOT NULL, \
    SCORE_DIV             VARCHAR(2)    NOT NULL, \
    CLASSCD               VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND           VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD         VARCHAR(2)    NOT NULL, \
    SUBCLASSCD            VARCHAR(6)    NOT NULL, \
    SCHREGNO              VARCHAR(8)    NOT NULL, \
    RANK_DIV              VARCHAR(1)    NOT NULL, \
    RANK                  SMALLINT, \
    AVG_RANK              SMALLINT, \
    DEVIATION             DECIMAL(5,1), \
    DEVIATION_RANK        SMALLINT, \
    REGISTERCD            VARCHAR(10), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_RANK_DETAIL_SDIV_DAT ADD CONSTRAINT PK_REC_RANK_SD_DAT PRIMARY KEY (YEAR,SEMESTER,TESTKINDCD,TESTITEMCD,SCORE_DIV,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO,RANK_DIV)