-- kanji=漢字
-- $Id: 39293e104bc2a49f8ee0166cde95cecb22146ff3 $

DROP TABLE RECORD_RANK_CLASS_SDIV_DAT
CREATE TABLE RECORD_RANK_CLASS_SDIV_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    SEMESTER            VARCHAR(1) NOT NULL, \
    TESTKINDCD          VARCHAR(2) NOT NULL, \
    TESTITEMCD          VARCHAR(2) NOT NULL, \
    SCORE_DIV           VARCHAR(2) NOT NULL, \
    CLASS_DIV           VARCHAR(1) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    SCHREGNO            VARCHAR(8) NOT NULL, \
    RANK_DIV            VARCHAR(1) NOT NULL, \
    SCORE               DECIMAL(9,5), \
    AVG                 DECIMAL(9,5), \
    COUNT               SMALLINT, \
    SCORE_RANK          SMALLINT, \
    AVG_RANK            SMALLINT, \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_RANK_CLASS_SDIV_DAT ADD CONSTRAINT PK_REC_RANK_CLS_SD \
      PRIMARY KEY (YEAR, SEMESTER, TESTKINDCD, TESTITEMCD, SCORE_DIV, CLASS_DIV, CLASSCD, SCHOOL_KIND, SCHREGNO, RANK_DIV)
