-- kanji=漢字
-- $Id: 0d4d6667afcfd284983c830c03a5d109bd3e7d5d $

DROP TABLE RECORD_PROV_FLG_DAT

CREATE TABLE RECORD_PROV_FLG_DAT ( \
    YEAR           VARCHAR(4) NOT NULL, \
    CLASSCD        VARCHAR(2) NOT NULL, \
    SCHOOL_KIND    VARCHAR(2) NOT NULL, \
    CURRICULUM_CD  VARCHAR(2) NOT NULL, \
    SUBCLASSCD     VARCHAR(6) NOT NULL, \
    SCHREGNO       VARCHAR(8) NOT NULL, \
    PROV_FLG       VARCHAR(1), \
    PROV_SEMESTER   VARCHAR(1), \
    PROV_TESTKINDCD VARCHAR(2), \
    PROV_TESTITEMCD VARCHAR(2), \
    PROV_SCORE_DIV  VARCHAR(2), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_PROV_FLG_DAT ADD CONSTRAINT PK_REC_PRO_FLG_DT \
      PRIMARY KEY (YEAR,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO)
