-- $Id: 3ab0a32726ec414a224ae6b22a3c40af892a76ea $

DROP TABLE RECORD_DOCUMENT_KIND_DAT
CREATE TABLE RECORD_DOCUMENT_KIND_DAT( \
    YEAR            VARCHAR(4)    NOT NULL, \
    SEMESTER        VARCHAR(1)    NOT NULL, \
    TESTKINDCD      VARCHAR(2)    NOT NULL, \
    TESTITEMCD      VARCHAR(2)    NOT NULL, \
    GRADE           VARCHAR(2)    NOT NULL, \
    HR_CLASS        VARCHAR(3)    NOT NULL, \
    COURSECD        VARCHAR(1)    NOT NULL, \
    MAJORCD         VARCHAR(3)    NOT NULL, \
    COURSECODE      VARCHAR(4)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    KIND_DIV        VARCHAR(1)    NOT NULL, \
    FOOTNOTE        VARCHAR(1050), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_DOCUMENT_KIND_DAT ADD CONSTRAINT PK_RECORD_D_K_DAT PRIMARY KEY (YEAR,SEMESTER,TESTKINDCD,TESTITEMCD,GRADE,HR_CLASS,COURSECD,MAJORCD,COURSECODE,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,KIND_DIV)