-- $Id: d597449961f08959a2c2cfdcdc9cbae02b3935a5 $

DROP TABLE RECORD_TOTALSTUDYTIME_DAT
CREATE TABLE RECORD_TOTALSTUDYTIME_DAT( \
    YEAR               VARCHAR(4)    NOT NULL, \
    SEMESTER           VARCHAR(1)    NOT NULL, \
    CLASSCD            VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND        VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD      VARCHAR(2)    NOT NULL, \
    SUBCLASSCD         VARCHAR(6)    NOT NULL, \
    SCHREGNO           VARCHAR(8)    NOT NULL, \
    TOTALSTUDYTIME     VARCHAR(1900), \
    TOTALSTUDYTIME_FLG VARCHAR(1), \
    TOTALSTUDYACT      VARCHAR(1200), \
    REMARK1            VARCHAR(1200), \
    REGISTERCD         VARCHAR(10), \
    UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_TOTALSTUDYTIME_DAT ADD CONSTRAINT PK_RECORD_TOTA_DAT PRIMARY KEY (YEAR,SEMESTER,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO)
