-- $Id: 78993513475c4049ace9f33f8d55c49d1955d328 $

DROP TABLE RECORD_PROFICIENCY_ORDER_SDIV_DAT
CREATE TABLE RECORD_PROFICIENCY_ORDER_SDIV_DAT ( \
     YEAR           VARCHAR(4) NOT NULL, \
     GRADE          VARCHAR(2) NOT NULL, \
     COURSECD       VARCHAR(1) NOT NULL, \
     MAJORCD        VARCHAR(3) NOT NULL, \
     SEQ            SMALLINT   NOT NULL, \
     TEST_DIV       VARCHAR(1) NOT NULL, \
     SEMESTER       VARCHAR(1), \
     TESTKINDCD     VARCHAR(2), \
     TESTITEMCD     VARCHAR(2), \
     SCORE_DIV      VARCHAR(2), \
     PROFICIENCYDIV VARCHAR(2), \
     PROFICIENCYCD  VARCHAR(4), \
     REGISTERCD     VARCHAR(8), \
     UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_PROFICIENCY_ORDER_SDIV_DAT ADD CONSTRAINT PK_REC_PR_ODR_SDIV PRIMARY KEY \
(YEAR, GRADE, COURSECD, MAJORCD, SEQ)
