-- $Id: 4bdb1b929b4188badfd5a3ea889f8cb555b60141 $

DROP TABLE RECORD_SLUMP_DAT
CREATE TABLE RECORD_SLUMP_DAT( \
    YEAR            VARCHAR(4)    NOT NULL, \
    SEMESTER        VARCHAR(1)    NOT NULL, \
    TESTKINDCD      VARCHAR(2)    NOT NULL, \
    TESTITEMCD      VARCHAR(2)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    SCHREGNO        VARCHAR(8)    NOT NULL, \
    CHAIRCD         VARCHAR(7), \
    SLUMP           VARCHAR(1), \
    REMARK          VARCHAR(60), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_SLUMP_DAT ADD CONSTRAINT PK_RECORD_SLUM_DAT PRIMARY KEY (YEAR,SEMESTER,TESTKINDCD,TESTITEMCD,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO)