-- kanji=´Á»ú
-- $Id: 0fe95ccd208c4e7dddaf8bb4d4f54712f510094c $

drop table RECORD_INFO_SDIV_DAT

create table RECORD_INFO_SDIV_DAT( \
     YEAR           VARCHAR(4) NOT NULL, \
     SEMESTER       VARCHAR(1) NOT NULL, \
     TESTKINDCD     VARCHAR(2) NOT NULL, \
     TESTITEMCD     VARCHAR(2) NOT NULL, \
     SCORE_DIV      VARCHAR(2) NOT NULL, \
     CLASSCD        VARCHAR(2) NOT NULL, \
     SCHOOL_KIND    VARCHAR(2) NOT NULL, \
     CURRICULUM_CD  VARCHAR(2) NOT NULL, \
     SUBCLASSCD     VARCHAR(6) NOT NULL, \
     SCHREGNO       VARCHAR(8) NOT NULL, \
     SEQ            VARCHAR(3) NOT NULL, \
     SCORE          SMALLINT, \
     REMARK         VARCHAR(300), \
     REGISTERCD     VARCHAR(10), \
     UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) in usr1dms index in idx1dms

alter table RECORD_INFO_SDIV_DAT add constraint PK_RECORD_INFO_SD primary key (YEAR, SEMESTER, TESTKINDCD, TESTITEMCD, SCORE_DIV, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, SCHREGNO, SEQ)
