-- kanji=漢字
-- $Id: b2cf4680afa9f230b56299c29410d6aafe31bf14 $

DROP TABLE RECORD_RANK_EXEC_SDIV_DAT

CREATE TABLE RECORD_RANK_EXEC_SDIV_DAT( \
    CALC_DATE     DATE          NOT NULL, \
    CALC_TIME     TIME          NOT NULL, \
    CLASSCD       VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND   VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD VARCHAR(2)    NOT NULL, \
    SUBCLASSCD    VARCHAR(6)    NOT NULL, \
    YEAR          VARCHAR(4), \
    SEMESTER      VARCHAR(1), \
    TESTKINDCD    VARCHAR(2), \
    TESTITEMCD    VARCHAR(2), \
    SCORE_DIV     VARCHAR(2), \
    GRADE         VARCHAR(2), \
    CHAIRDATE     DATE, \
    ELECTDIV_FLG  VARCHAR(1), \
    REGISTERCD    VARCHAR(8), \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_RANK_EXEC_SDIV_DAT ADD CONSTRAINT PK_RC_RK_EX_SD_DT PRIMARY KEY (CALC_DATE,CALC_TIME,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)