
create table RECORD_EDUCATE_GUIDANCE_CONDUCT_DAT( \
    YEAR              VARCHAR(4)    NOT NULL, \
    SEMESTER          VARCHAR(1)    NOT NULL, \
    CLASSCD           VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND       VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD     VARCHAR(2)    NOT NULL, \
    SUBCLASSCD        VARCHAR(6)    NOT NULL, \
    SCHREGNO          VARCHAR(8)    NOT NULL, \
    CONDUCT_CONTENTS  VARCHAR(900) , \
    CONDUCT_EVAL      VARCHAR(900) , \
    REGISTERCD        VARCHAR(10)  , \
    UPDATED           TIMESTAMP     DEFAULT CURRENT TIMESTAMP \
 ) in usr1dms index in idx1dms

alter table RECORD_EDUCATE_GUIDANCE_CONDUCT_DAT add constraint PK_RC_ED_GUI_CND_D primary key (YEAR,SEMESTER,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO)


