-- kanji=漢字
-- $Id: cfc830e8837ba2aa02f3af5f9a8ed2a482c880fd $

-- 注意:このファイルは EUC/LFのみ でなければならない。
-- 適用方法:
--    1.データベース接続
--    2.db2 +c -f <このファイル>
--    3.コミットするなら、db2 +c commit。やり直すなら、db2 +c rollback

DROP TABLE REP_STANDARDDATE_COURSE_DAT_OLD
RENAME TABLE REP_STANDARDDATE_COURSE_DAT TO REP_STANDARDDATE_COURSE_DAT_OLD

CREATE TABLE REP_STANDARDDATE_COURSE_DAT \
    ( YEAR           VARCHAR(4) NOT NULL, \
      CLASSCD        VARCHAR(2) NOT NULL, \
      SCHOOL_KIND    VARCHAR(2) NOT NULL, \
      CURRICULUM_CD  VARCHAR(2) NOT NULL, \
      SUBCLASSCD     VARCHAR(6) NOT NULL, \
      COURSECD       VARCHAR(1) NOT NULL, \
      MAJORCD        VARCHAR(3) NOT NULL, \
      COURSECODE     VARCHAR(4) NOT NULL, \
      STANDARD_SEQ   SMALLINT   NOT NULL, \
      CHAIRCD        VARCHAR(7), \
      REPORTDIV      VARCHAR(2), \
      STANDARD_DATE  DATE, \
      RETURN_DATE    DATE, \
      DEADLINE_DATE  DATE, \
      REMARK         VARCHAR(60), \
      REGISTERCD     VARCHAR(8), \
      UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE REP_STANDARDDATE_COURSE_DAT ADD CONSTRAINT PK_REP_STDATE_DAT PRIMARY KEY (YEAR, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, COURSECD, MAJORCD, COURSECODE, STANDARD_SEQ)
