-- kanji=漢字
-- $Id:

DROP TABLE REPORT_DISEASE_ADDITION1_DAT

CREATE TABLE REPORT_DISEASE_ADDITION1_DAT \
      (EDBOARD_SCHOOLCD VARCHAR(12) NOT NULL, \
       YEAR             VARCHAR(4) NOT NULL, \
       EXECUTE_DATE     DATE NOT NULL, \
       FIXED_DATE       DATE, \
       REGISTERCD       VARCHAR(10), \
       UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
      ) in usr1dms index in idx1dms

alter table REPORT_DISEASE_ADDITION1_DAT add constraint PK_REPORT_D_A2_D primary key (EDBOARD_SCHOOLCD, YEAR, EXECUTE_DATE)
