-- kanji=´Á»ú
-- $Id: 61550f466693712f54fe3f34a7b3bebec950afb6 $

DROP TABLE REPORT_AFT_DISEASE_ADDITION441_COLLEGE_DAT

CREATE TABLE REPORT_AFT_DISEASE_ADDITION441_COLLEGE_DAT \
      (EDBOARD_SCHOOLCD     VARCHAR(12) NOT NULL, \
       YEAR                 VARCHAR(4)  NOT NULL, \
       EXECUTE_DATE         DATE        NOT NULL, \
       FIXED_DATE           DATE, \
       REGISTERCD           VARCHAR(10), \
       UPDATED      TIMESTAMP DEFAULT CURRENT TIMESTAMP \
      ) in usr1dms index in idx1dms

alter table REPORT_AFT_DISEASE_ADDITION441_COLLEGE_DAT add constraint PK_REP_AFT_441C \
primary key (EDBOARD_SCHOOLCD, YEAR, EXECUTE_DATE)
