-- kanji=漢字
-- $Id:

DROP TABLE REPORT_DISEASE_ADDITION2_DAT

CREATE TABLE REPORT_DISEASE_ADDITION2_DAT( \
    EDBOARD_SCHOOLCD VARCHAR(12)   NOT NULL, \
    YEAR             VARCHAR(4)    NOT NULL, \
    EXECUTE_DATE     DATE NOT NULL, \
    FIXED_DATE       DATE, \
    REGISTERCD       VARCHAR(10), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE REPORT_DISEASE_ADDITION2_DAT ADD CONSTRAINT PK_REPORT_D_A2_D PRIMARY KEY (EDBOARD_SCHOOLCD, YEAR, EXECUTE_DATE)
