-- kanji=´Á»ú
-- $Id: 3befc0d8e03af2c5103391699e9f8ee0eee82a42 $

DROP TABLE REPORT_AFT_DISEASE_ADDITION441_COLLEGE2_DAT

CREATE TABLE REPORT_AFT_DISEASE_ADDITION441_COLLEGE2_DAT \
      (EDBOARD_SCHOOLCD     VARCHAR(12) NOT NULL, \
       YEAR                 VARCHAR(4)  NOT NULL, \
       EXECUTE_DATE         DATE        NOT NULL, \
       FIXED_DATE           DATE, \
       REGISTERCD           VARCHAR(10), \
       UPDATED      TIMESTAMP DEFAULT CURRENT TIMESTAMP \
      ) in usr1dms index in idx1dms

alter table REPORT_AFT_DISEASE_ADDITION441_COLLEGE2_DAT add constraint PK_REP_AFT_441C2 \
primary key (EDBOARD_SCHOOLCD, YEAR, EXECUTE_DATE)
