-- kanji=´Á»ú
-- $Id: e6384b34f09435508579040054d739f11e21e797 $

DROP TABLE REPORT_AFT_DISEASE_ADDITION434_DAT

CREATE TABLE REPORT_AFT_DISEASE_ADDITION434_DAT \
      (EDBOARD_SCHOOLCD     VARCHAR(12) NOT NULL, \
       YEAR                 VARCHAR(4)  NOT NULL, \
       DATA_DIV             VARCHAR(3)  NOT NULL, \
       EXECUTE_DATE         DATE        NOT NULL, \
       FIXED_DATE           DATE, \
       REGISTERCD           VARCHAR(10), \
       UPDATED      TIMESTAMP DEFAULT CURRENT TIMESTAMP \
      ) in usr1dms index in idx1dms

alter table REPORT_AFT_DISEASE_ADDITION434_DAT add constraint PK_REP_AFT_D_434 \
primary key (EDBOARD_SCHOOLCD, YEAR, DATA_DIV, EXECUTE_DATE)
