-- kanji=´Á»ú
-- $Id: 503854b8ec84c88d3e992528b9b029c179dec9e5 $

DROP TABLE REPORT_AFT_DISEASE_ADDITION441_SENMON_DAT

CREATE TABLE REPORT_AFT_DISEASE_ADDITION441_SENMON_DAT \
      (EDBOARD_SCHOOLCD     VARCHAR(12) NOT NULL, \
       YEAR                 VARCHAR(4)  NOT NULL, \
       EXECUTE_DATE         DATE        NOT NULL, \
       FIXED_DATE           DATE, \
       REGISTERCD           VARCHAR(10), \
       UPDATED      TIMESTAMP DEFAULT CURRENT TIMESTAMP \
      ) in usr1dms index in idx1dms

alter table REPORT_AFT_DISEASE_ADDITION441_SENMON_DAT add constraint PK_REP_AFT_441S \
primary key (EDBOARD_SCHOOLCD, YEAR, EXECUTE_DATE)
