-- kanji=´Á»ú
-- $Id: a05d2ca9fa173841a6c9c9da0807d7d9711a08cb $

DROP TABLE REPORT_AFT_DISEASE_ADDITION441_SENMON2_DAT

CREATE TABLE REPORT_AFT_DISEASE_ADDITION441_SENMON2_DAT \
      (EDBOARD_SCHOOLCD     VARCHAR(12) NOT NULL, \
       YEAR                 VARCHAR(4)  NOT NULL, \
       EXECUTE_DATE         DATE        NOT NULL, \
       FIXED_DATE           DATE, \
       REGISTERCD           VARCHAR(10), \
       UPDATED      TIMESTAMP DEFAULT CURRENT TIMESTAMP \
      ) in usr1dms index in idx1dms

alter table REPORT_AFT_DISEASE_ADDITION441_SENMON2_DAT add constraint PK_REP_AFT_441S2 \
primary key (EDBOARD_SCHOOLCD, YEAR, EXECUTE_DATE)
