-- $Id: baa482d8e3a30b53d5b5d84626d39434e70ad37f $

drop table SCH_CHR_STF_DIARY_DETAIL_DAT

CREATE TABLE SCH_CHR_STF_DIARY_DETAIL_DAT( \
    SCHOOLCD          VARCHAR(12)   NOT NULL, \
    SCHOOL_KIND       VARCHAR(2)    NOT NULL, \
    STAFFCD           VARCHAR(10)   NOT NULL, \
    DIARY_DATE        DATE          NOT NULL, \
    PERIODCD          VARCHAR(1)    NOT NULL, \
    CHAIRCD           VARCHAR(7)    NOT NULL, \
    REMARK1           VARCHAR(250)  , \
    REMARK2           VARCHAR(250)  , \
    REMARK3           VARCHAR(250)  , \
    REMARK4           VARCHAR(250)  , \
    REMARK5           VARCHAR(250)  , \
    REGISTERCD        VARCHAR(10)   , \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCH_CHR_STF_DIARY_DETAIL_DAT ADD CONSTRAINT PK_SCH_CHR_STF_DIARY_DET PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, STAFFCD, DIARY_DATE, PERIODCD, CHAIRCD)
