-- $Id: 1b837ca04683b8c0b2aa6cd4ce83384bf9ca796f $

DROP   TABLE SCH_CHR_NOTIFY_FAC
CREATE TABLE SCH_CHR_NOTIFY_FAC \
( \
        YEAR          VARCHAR(4)      NOT NULL, \
        SEMESTER      VARCHAR(1)      NOT NULL, \
        PARENTSEQ     INTEGER         NOT NULL, \
        FACCD         VARCHAR(4)      NOT NULL, \
        REGISTERCD    VARCHAR(8), \
        UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCH_CHR_NOTIFY_FAC \
ADD CONSTRAINT PK_SCH_CHR_NTF_FAC  \
PRIMARY KEY  \
( \
YEAR, \
SEMESTER, \
PARENTSEQ, \
FACCD \
)


