-- $Id: 1eed1b85d096c58137044d943783a740173359b9 $

DROP TABLE SCH_CHR_COUNTFLG
CREATE TABLE SCH_CHR_COUNTFLG( \
    EXECUTEDATE DATE          NOT NULL, \
    PERIODCD    VARCHAR(1)    NOT NULL, \
    CHAIRCD     VARCHAR(7)    NOT NULL, \
    GRADE       VARCHAR(2)    NOT NULL, \
    HR_CLASS    VARCHAR(3)    NOT NULL, \
    COUNTFLG    VARCHAR(1), \
    LESSON_MODE VARCHAR(2)    NOT NULL, \
    REGISTERCD  VARCHAR(8), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCH_CHR_COUNTFLG ADD CONSTRAINT PK_SCH_CHR_COUNT PRIMARY KEY (EXECUTEDATE,PERIODCD,CHAIRCD,GRADE,HR_CLASS)