-- $Id: 0ca530248b4efcce1ed52ef371381c7588638ecf $

DROP TABLE SCH_CHR_REMARK_DAT

CREATE TABLE SCH_CHR_REMARK_DAT ( \
    EXECUTEDATE   DATE            NOT NULL, \
    PERIODCD      VARCHAR(1)      NOT NULL, \
    CHAIRCD       VARCHAR(7)      NOT NULL, \
    REMARK_DIV    VARCHAR(2)      NOT NULL, \
    REMARK        VARCHAR(500), \
    REGISTERCD    VARCHAR(10), \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCH_CHR_REMARK_DAT ADD CONSTRAINT PK_SCH_CHR_REM_D PRIMARY KEY (EXECUTEDATE, PERIODCD, CHAIRCD, REMARK_DIV)

