-- $Id: e724943deb3fa183a00f9dd93d224a1fdd4d7f1d $

drop table SCHOOL_DIARY_DAT

CREATE TABLE SCHOOL_DIARY_DAT( \
    SCHOOLCD        VARCHAR(12) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)  NOT NULL, \
    DIARY_DATE      DATE        NOT NULL, \
    WEATHER         VARCHAR(1), \
    WEATHER2        VARCHAR(1), \
    NEWS            VARCHAR(3000), \
    STAFFNEWS       VARCHAR(2000), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHOOL_DIARY_DAT ADD CONSTRAINT PK_SCHOOL_DIARY PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, DIARY_DATE)
