-- $Id: 17265516ecaf7262438084d99fb593e99e073fe4 $

drop table SCHOOL_DIARY_DETAIL_SEQ_DAT

CREATE TABLE SCHOOL_DIARY_DETAIL_SEQ_DAT( \
    SCHOOLCD        VARCHAR(12) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)  NOT NULL, \
    DIARY_DATE      DATE        NOT NULL, \
    SEQ             VARCHAR(3)  NOT NULL, \
    REMARK1         VARCHAR(678), \
    REMARK2         VARCHAR(678), \
    REMARK3         VARCHAR(1428), \
    REMARK4         VARCHAR(678), \
    REMARK5         VARCHAR(678), \
    REMARK6         VARCHAR(474), \
    REMARK7         VARCHAR(474), \
    REMARK8         VARCHAR(474), \
    REMARK9         VARCHAR(338), \
    REMARK10        VARCHAR(338), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHOOL_DIARY_DETAIL_SEQ_DAT ADD CONSTRAINT PK_SCHOOL_DIARYSEQ PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, DIARY_DATE, SEQ)
