-- $Id: 91562819a593debd4823663b7dd03dcca2f9c62c $

drop table SCHOOL_DIARY_DETAIL_DAT

CREATE TABLE SCHOOL_DIARY_DETAIL_DAT( \
    SCHOOLCD          VARCHAR(12) NOT NULL, \
    SCHOOL_KIND       VARCHAR(2)  NOT NULL, \
    DIARY_DATE        DATE        NOT NULL, \
    STAFF_DIV         VARCHAR(2)  NOT NULL, \
    GRADE             VARCHAR(2)  NOT NULL, \
    HR_CLASS          VARCHAR(3)  NOT NULL, \
    STAFFCD           VARCHAR(8)  NOT NULL, \
    COUNT             SMALLINT, \
    REGISTERCD        VARCHAR(10), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHOOL_DIARY_DETAIL_DAT ADD CONSTRAINT PK_SCHOOL_DIARY_DE PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, DIARY_DATE, STAFF_DIV, GRADE, HR_CLASS, STAFFCD)
