-- kanji=漢字
-- $Id: 8f7cdf2952124e94fc3c913598699e9dbc216a28 $

-- 注意:このファイルは EUC/LFのみ でなければならない。
-- 適用方法:
--    1.データベース接続
--    2.db2 +c -f <このファイル>
--    3.コミットするなら、db2 +c commit。やり直すなら、db2 +c rollback

DROP TABLE SCHOOL_BANK_MST

CREATE TABLE SCHOOL_BANK_MST \
( \
    SCHOOLCD          VARCHAR(12) NOT NULL, \
    SCHOOL_KIND       VARCHAR(2)  NOT NULL, \
    BANKTRANSFERCD    VARCHAR(4)  NOT NULL, \
    BANKTRANSFERNAME  VARCHAR(60), \
    BANKTRANSFERMONEY INTEGER, \
    BANKCD            VARCHAR(4),  \
    BANKNAME          VARCHAR(45),  \
    BANKNAME_KANA     VARCHAR(45),  \
    BRANCHCD          VARCHAR(3),  \
    BRANCHNAME        VARCHAR(45),  \
    BRANCHNAME_KANA   VARCHAR(45),  \
    DEPOSIT_ITEM      VARCHAR(1),  \
    ACCOUNTNO         VARCHAR(7),  \
    ACCOUNTNAME       VARCHAR(120), \
    ACCOUNTNAME_KANA  VARCHAR(120), \
    REGISTERCD        VARCHAR(10), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHOOL_BANK_MST \
ADD CONSTRAINT PK_SCHOOL_BANK_MST \
PRIMARY KEY \
(SCHOOLCD, SCHOOL_KIND, BANKTRANSFERCD)
