-- $Id: 59601d6a05f84f5f803c4f7ac42d19baf60a1aa9 $

DROP TABLE SCHREG_CHALLENGED_ASSESSMENT_MAIN_DAT
CREATE TABLE SCHREG_CHALLENGED_ASSESSMENT_MAIN_DAT( \
    YEAR                                VARCHAR(4)    NOT NULL, \
    SCHREGNO                            VARCHAR(8)    NOT NULL, \
    RECORD_DATE                         VARCHAR(10)   NOT NULL, \
    WRITING_DATE                        DATE          NOT NULL, \
    CHALLENGED_NAMES                    VARCHAR(300), \
    CHALLENGED_STATUS                   VARCHAR(500), \
    RECORD_STAFFNAME                    VARCHAR(75), \
    REGISTERCD                          VARCHAR(10), \
    UPDATED                             TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_CHALLENGED_ASSESSMENT_MAIN_DAT ADD CONSTRAINT PK_SCH_CHA_ASS_M_D PRIMARY KEY (YEAR, SCHREGNO, RECORD_DATE)