-- kanji=漢字
-- $Id: c8132bc5d1164db47a41bbb50a66ca428f914405 $

DROP TABLE SCHREG_STUDYREC_EXEC_HIST_DAT
CREATE TABLE SCHREG_STUDYREC_EXEC_HIST_DAT( \
    CALC_DATE               DATE NOT NULL, \
    CALC_TIME               TIME NOT NULL, \
    BEF_AFT_DIV             VARCHAR(1) NOT NULL, \
    SCHOOLCD                VARCHAR(1) NOT NULL, \
    YEAR                    VARCHAR(4) NOT NULL, \
    SCHREGNO                VARCHAR(8) NOT NULL, \
    ANNUAL                  VARCHAR(2) NOT NULL, \
    CLASSCD                 VARCHAR(2) NOT NULL, \
    SCHOOL_KIND             VARCHAR(2) NOT NULL, \
    CURRICULUM_CD           VARCHAR(2) NOT NULL, \
    SUBCLASSCD              VARCHAR(6) NOT NULL, \
    CLASSNAME               VARCHAR(30), \
    CLASSABBV               VARCHAR(15), \
    CLASSNAME_ENG           VARCHAR(40), \
    CLASSABBV_ENG           VARCHAR(30), \
    SUBCLASSES              SMALLINT, \
    SUBCLASSNAME            VARCHAR(90), \
    SUBCLASSABBV            VARCHAR(90), \
    SUBCLASSNAME_ENG        VARCHAR(40), \
    SUBCLASSABBV_ENG        VARCHAR(20), \
    VALUATION               SMALLINT, \
    GET_CREDIT              SMALLINT, \
    ADD_CREDIT              SMALLINT, \
    COMP_CREDIT             SMALLINT, \
    PRINT_FLG               VARCHAR(1), \
    CMD_DIV                 VARCHAR(1), \
    REGISTERCD              VARCHAR(10), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_STUDYREC_EXEC_HIST_DAT ADD CONSTRAINT PK_SCHREG_STUDYREC_EXEC_HIST_DAT PRIMARY KEY (CALC_DATE,CALC_TIME,BEF_AFT_DIV,SCHOOLCD,YEAR,SCHREGNO,ANNUAL,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)
