-- $Id: c4a1b869abcc0af2f5e89e5598a93907974f969c $

DROP TABLE SCHREG_CHALLENGED_PROFILE_MEDICAL_RECORD_DAT
CREATE TABLE SCHREG_CHALLENGED_PROFILE_MEDICAL_RECORD_DAT( \
    SCHREGNO                VARCHAR(8)    NOT NULL, \
    RECORD_DATE             VARCHAR(10)   NOT NULL, \
    RECORD_DIV              VARCHAR(1)    NOT NULL, \
    RECORD_SEQ              SMALLINT      NOT NULL, \
    NAMECD                  VARCHAR(3), \
    CENTERCD                VARCHAR(5), \
    CENTER_NAME             VARCHAR(90), \
    TELNO                   VARCHAR(14), \
    DISEASE_NAME            VARCHAR(48), \
    DOCTOR_NAME             VARCHAR(30), \
    ATTEND_STATUS           VARCHAR(120), \
    REGISTERCD              VARCHAR(10), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_CHALLENGED_PROFILE_MEDICAL_RECORD_DAT ADD CONSTRAINT PK_SCH_CHA_P_M_R_D PRIMARY KEY (SCHREGNO, RECORD_DATE, RECORD_DIV, RECORD_SEQ)