-- $Id: a45c6c360ac9201bcb8cd0ec71b49b8bfffe4eea $

DROP TABLE SCHREG_CHALLENGED_PROFILE_OTHER_RECORD_DAT
CREATE TABLE SCHREG_CHALLENGED_PROFILE_OTHER_RECORD_DAT( \
    SCHREGNO                VARCHAR(8)    NOT NULL, \
    RECORD_DATE             VARCHAR(10)   NOT NULL, \
    RECORD_DIV              VARCHAR(3)    NOT NULL, \
    RECORD_SEQ              SMALLINT      NOT NULL, \
    REMARK1                 VARCHAR(1700), \
    REMARK2                 VARCHAR(500), \
    REMARK3                 VARCHAR(500), \
    REMARK4                 VARCHAR(500), \
    REMARK5                 VARCHAR(500), \
    REMARK6                 VARCHAR(3000), \
    REMARK7                 VARCHAR(3000), \
    REMARK8                 VARCHAR(3000), \
    REGISTERCD              VARCHAR(10), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN usr16dms index in idx1dms

ALTER TABLE SCHREG_CHALLENGED_PROFILE_OTHER_RECORD_DAT ADD CONSTRAINT PK_SCH_CHA_P_OTHER_RECORD_DAT PRIMARY KEY (SCHREGNO, RECORD_DATE, RECORD_DIV, RECORD_SEQ)