-- $Id: d6697999e6a87c2a71cfd4d30258c3e587b3a49e $

DROP TABLE SCHREG_COMMITTEE_HIST_DAT
CREATE TABLE SCHREG_COMMITTEE_HIST_DAT( \
    SCHOOLCD      VARCHAR(12)   NOT NULL, \
    SCHOOL_KIND   VARCHAR(2)    NOT NULL, \
    YEAR          VARCHAR(4)    NOT NULL, \
    SEQ           INTEGER       NOT NULL, \
    SEMESTER      VARCHAR(1), \
    SCHREGNO      VARCHAR(8), \
    GRADE         VARCHAR(2), \
    COMMITTEE_FLG VARCHAR(1), \
    COMMITTEECD   VARCHAR(4), \
    CHARGENAME    VARCHAR(30), \
    EXECUTIVECD   VARCHAR(2), \
    REGISTERCD    VARCHAR(10), \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_COMMITTEE_HIST_DAT ADD CONSTRAINT PK_SCH_COMMIT_H_DT PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, YEAR,SEQ)