-- $Id$

DROP TABLE SCHREG_ABSENCE_HIGH_DAT
CREATE TABLE SCHREG_ABSENCE_HIGH_DAT( \
    YEAR              VARCHAR(4)    NOT NULL, \
    DIV               VARCHAR(1)    NOT NULL, \
    CLASSCD           VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND       VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD     VARCHAR(2)    NOT NULL, \
    SUBCLASSCD        VARCHAR(6)    NOT NULL, \
    SCHREGNO          VARCHAR(8)    NOT NULL, \
    COMP_ABSENCE_HIGH DECIMAL(4,1), \
    GET_ABSENCE_HIGH  DECIMAL(4,1), \
    LESSON            SMALLINT, \
    APPOINTED_DATE    DATE, \
    REGISTERCD        VARCHAR(8), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_ABSENCE_HIGH_DAT ADD CONSTRAINT PK_SCHREG_A_H_DAT PRIMARY KEY (YEAR,DIV,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO)

CREATE INDEX IDX_SCHRABHI_ACCUM ON SCHREG_ABSENCE_HIGH_DAT (SCHREGNO ASC, DIV ASC, YEAR ASC, CLASSCD ASC, GET_ABSENCE_HIGH ASC, COMP_ABSENCE_HIGH ASC, SUBCLASSCD ASC, SCHOOL_KIND ASC, CURRICULUM_CD ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS
