-- $Id: fbfca0948a48cca7801d86532e054ae895b75e39 $

DROP TABLE SCHREG_CHALLENGED_PROFILE_WELFARE_RECORD_ITEMCD_DAT
CREATE TABLE SCHREG_CHALLENGED_PROFILE_WELFARE_RECORD_ITEMCD_DAT( \
    SCHREGNO            VARCHAR(8)      NOT NULL, \
    RECORD_DATE         VARCHAR(10)     NOT NULL, \
    RECORD_DIV          VARCHAR(1)      NOT NULL, \
    RECORD_NO           VARCHAR(1)      NOT NULL, \
    RECORD_SEQ          SMALLINT        NOT NULL, \
    ITEMDIV             VARCHAR(5)      NOT NULL, \
    ITEMCD1             VARCHAR(3), \
    ITEMCD2             VARCHAR(3), \
    ITEMCD3             VARCHAR(3), \
    ITEMCD4             VARCHAR(3), \
    ITEMCD5             VARCHAR(3), \
    ITEMCD6             VARCHAR(3), \
    ITEMCD7             VARCHAR(3), \
    ITEMCD8             VARCHAR(3), \
    ITEMCD9             VARCHAR(3), \
    ITEMCD10            VARCHAR(3), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_CHALLENGED_PROFILE_WELFARE_RECORD_ITEMCD_DAT ADD CONSTRAINT PK_SCH_CH_P_W_R_I PRIMARY KEY (SCHREGNO, RECORD_DATE, RECORD_DIV, RECORD_NO, RECORD_SEQ, ITEMDIV)
