-- $Id: c2fca9e2c8c20d24b8f37c7a3ab3cdec823e42bf $

drop   table SCHREG_QUALIFIED_BANK_DAT

create table SCHREG_QUALIFIED_BANK_DAT \
   (SCHREGNO        VARCHAR(8)   NOT NULL, \
    CLASSCD         VARCHAR(2)   NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)   NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)   NOT NULL, \
    SUBCLASSCD      VARCHAR(6)   NOT NULL, \
    SEQ             SMALLINT     NOT NULL, \
    REGDDATE        DATE         NOT NULL, \
    REGDYEAR        VARCHAR(4)   NOT NULL, \
    MINUTES         SMALLINT     NOT NULL, \
    REMARK          VARCHAR(90), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
   ) IN USR1DMS INDEX IN IDX1DMS

alter table SCHREG_QUALIFIED_BANK_DAT add constraint PK_SCH_QUAL_BANK primary key (SCHREGNO,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SEQ)

