-- $Id: 935688786a679987e9fa2fe2e6a8ebe326016831 $

DROP TABLE SCHREG_CHALLENGED_PROFILE_MAIN_DAT
CREATE TABLE SCHREG_CHALLENGED_PROFILE_MAIN_DAT( \
    SCHREGNO                      VARCHAR(8)    NOT NULL, \
    RECORD_DATE                   VARCHAR(10)   NOT NULL, \
    WRITING_DATE                  DATE          NOT NULL, \
    TSUUGAKU_DIV1                 VARCHAR(1)   , \
    TSUUGAKU_DIV1_REMARK          VARCHAR(220) , \
    TSUUGAKU_DIV2                 VARCHAR(1)   , \
    TSUUGAKU_DIV2_REMARK          VARCHAR(220) , \
    ATTEND_HOGOSHA_FLG            VARCHAR(1)   , \
    CHALLENGED_NAMES              VARCHAR(270) , \
    CHALLENGED_STATUS             VARCHAR(820) , \
    CHALLENGED_CARD_DIV           VARCHAR(2)   , \
    CHALLENGED_CARD_AREA_NAME     VARCHAR(2)   , \
    CHALLENGED_CARD_AREA_NAME2    VARCHAR(2)   , \
    CHALLENGED_CARD_AREA_NAME3    VARCHAR(2)   , \
    CHALLENGED_CARD_AREA_NAME4    VARCHAR(2)   , \
    CHALLENGED_CARD_AREA_NAME5    VARCHAR(2)   , \
    CHALLENGED_CARD_CLASS         VARCHAR(2)   , \
    CHALLENGED_CARD_RANK          VARCHAR(2)   , \
    CHALLENGED_CARD_NAME          VARCHAR(135) , \
    CHALLENGED_CARD_GRANT_FLG     VARCHAR(1)   , \
    CHALLENGED_CARD_GRANT_YM      VARCHAR(7)   , \
    CHALLENGED_CARD_CHECK_YM      VARCHAR(7)   , \
    CHALLENGED_CARD_REMARK        VARCHAR(45)  , \
    CHALLENGED_CARD_BAST_YM       VARCHAR(7)   , \
    WELFARE_MEDICAL_RECEIVE_FLG   VARCHAR(1)   , \
    WELFARE_MEDICAL_RECEIVE_DIV   VARCHAR(2)   , \
    WELFARE_MEDICAL_RECEIVE_DIV2  VARCHAR(2)   , \
    WELFARE_MEDICAL_RECEIVE_DIV3  VARCHAR(2)   , \
    WELFARE_MEDICAL_RECEIVE_DIV4  VARCHAR(2)   , \
    WELFARE_MEDICAL_RECEIVE_DIV5  VARCHAR(2)   , \
    P_SCHOOL_CD                   VARCHAR(12)  , \
    J_SCHOOL_CD                   VARCHAR(12)  , \
    EVACUATION_AREA               VARCHAR(60)  , \
    IMPORTANT_NOTICE              VARCHAR(600) , \
    REMARK                        VARCHAR(1700) , \
    RECORD_STAFFNAME              VARCHAR(75), \
    REGISTERCD                    VARCHAR(10)  , \
    UPDATED                       TIMESTAMP     DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_CHALLENGED_PROFILE_MAIN_DAT ADD CONSTRAINT PK_SCH_CHA_PRO_M_D PRIMARY KEY (SCHREGNO, RECORD_DATE)
