-- $Id: 6e4597769b7479135a414eb718e15a3067086282 $

DROP TABLE SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_STATUS_DAT
CREATE TABLE SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_STATUS_DAT( \
    SCHREGNO                            VARCHAR(8)    NOT NULL, \
    RECORD_DATE                         VARCHAR(10)   NOT NULL, \
    DATA_DIV                            VARCHAR(2)    NOT NULL, \
    STATUS                              VARCHAR(1800), \
    REGISTERCD                          VARCHAR(10), \
    UPDATED                             TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_STATUS_DAT ADD CONSTRAINT PK_SCH_CHA_TSP_S_D PRIMARY KEY (SCHREGNO, RECORD_DATE, DATA_DIV)