-- $Id: c1cfd8899b32387299f53ce04fc2fbccc97d5e96 $

DROP TABLE SCHREG_QUALIFIED_HOBBY_DAT
CREATE TABLE SCHREG_QUALIFIED_HOBBY_DAT( \
    YEAR          VARCHAR(4)    NOT NULL, \
    SCHREGNO      VARCHAR(8)    NOT NULL, \
    SEQ           SMALLINT      NOT NULL, \
    REGDDATE      DATE          NOT NULL, \
    CLASSCD       VARCHAR(2), \
    SCHOOL_KIND   VARCHAR(2), \
    CURRICULUM_CD VARCHAR(2), \
    SUBCLASSCD    VARCHAR(6), \
    CONDITION_DIV VARCHAR(1), \
    QUALIFIED_CD  VARCHAR(4), \
    CONTENTS      VARCHAR(90), \
    RANK          VARCHAR(3), \
    REMARK        VARCHAR(90), \
    CREDITS       SMALLINT, \
    CERTIFICATE   VARCHAR(1), \
    SCORE         SMALLINT, \
    REGISTERCD    VARCHAR(10), \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_QUALIFIED_HOBBY_DAT ADD CONSTRAINT PK_SCH_QUAL_H_DAT PRIMARY KEY (YEAR,SCHREGNO,SEQ)
