-- $Id: cff4441cd87fd4548eaad7d20115435f0ee3d214 $

DROP TABLE SCHREG_ABSENCE_HIGH_SPECIAL_DAT
CREATE TABLE SCHREG_ABSENCE_HIGH_SPECIAL_DAT( \
    YEAR              VARCHAR(4)    NOT NULL, \
    DIV               VARCHAR(1)    NOT NULL, \
    SPECIAL_GROUP_CD  VARCHAR(3)    NOT NULL, \
    SCHREGNO          VARCHAR(8)    NOT NULL, \
    COMP_ABSENCE_HIGH DECIMAL(4,1), \
    GET_ABSENCE_HIGH  DECIMAL(4,1), \
    LESSON            SMALLINT, \
    APPOINTED_DATE    DATE, \
    REGISTERCD        VARCHAR(8), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_ABSENCE_HIGH_SPECIAL_DAT ADD CONSTRAINT PK_SCH_A_H_S_DAT PRIMARY KEY (YEAR,DIV,SPECIAL_GROUP_CD,SCHREGNO)