-- $Id: dc4b555ed143b037dbd37359642b94d8a03a40ff $

DROP TABLE SCHREG_CHALLENGED_OFFICIAL_DATA_DOCUMENTS_DAT
CREATE TABLE SCHREG_CHALLENGED_OFFICIAL_DATA_DOCUMENTS_DAT( \
    YEAR                                VARCHAR(4)    NOT NULL, \
    SCHREGNO                            VARCHAR(8)    NOT NULL, \
    RECORD_DATE                         VARCHAR(10)   NOT NULL, \
    DATA_DIV                            VARCHAR(2)    NOT NULL, \
    DOCUMENTS                           VARCHAR(1250), \
    REGISTERCD                          VARCHAR(8), \
    UPDATED                             TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_CHALLENGED_OFFICIAL_DATA_DOCUMENTS_DAT ADD CONSTRAINT PK_SCH_CHA_OF_D_DC PRIMARY KEY (YEAR, SCHREGNO, RECORD_DATE, DATA_DIV)