-- kanji=漢字
-- $Id: 3f4247dedb1ae5150d1c0e624f87acc0642d9028 $

DROP TABLE SCHREG_STUDYREC_DETAIL_EXEC_HIST_DAT
CREATE TABLE SCHREG_STUDYREC_DETAIL_EXEC_HIST_DAT( \
    CALC_DATE           DATE NOT NULL, \
    CALC_TIME           TIME NOT NULL, \
    BEF_AFT_DIV         VARCHAR(1) NOT NULL, \
    SCHOOLCD            VARCHAR(1) NOT NULL, \
    YEAR                VARCHAR(4) NOT NULL, \
    SCHREGNO            VARCHAR(8) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    CURRICULUM_CD       VARCHAR(2) NOT NULL, \
    SUBCLASSCD          VARCHAR(6) NOT NULL, \
    SEQ                 VARCHAR(3) NOT NULL, \
    REMARK1             VARCHAR(3500), \
    REMARK2             VARCHAR(1000), \
    CMD_DIV             VARCHAR(1), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_STUDYREC_DETAIL_EXEC_HIST_DAT ADD CONSTRAINT PK_SCHREG_STUDYREC_DETAIL_EXEC_HIST_DAT PRIMARY KEY (CALC_DATE,CALC_TIME,BEF_AFT_DIV,SCHOOLCD,YEAR,SCHREGNO,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SEQ)
