-- kanji=漢字
-- $Id: 150d5d037d564f92752424f3290693fbbe4d1dd0 $

DROP TABLE SCHREG_STUDYREC_RANK_CLASS_DAT
CREATE TABLE SCHREG_STUDYREC_RANK_CLASS_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    CLASS_DIV           VARCHAR(1) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    SCHREGNO            VARCHAR(8) NOT NULL, \
    RANK_DIV            VARCHAR(1) NOT NULL, \
    SCORE               DECIMAL(9,5), \
    AVG                 DECIMAL(9,5), \
    COUNT               SMALLINT, \
    SCORE_RANK          SMALLINT, \
    AVG_RANK            SMALLINT, \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_STUDYREC_RANK_CLASS_DAT ADD CONSTRAINT PK_STUDYREC_RNKCLS \
      PRIMARY KEY (YEAR, CLASS_DIV, CLASSCD, SCHOOL_KIND, SCHREGNO, RANK_DIV)
