-- $Id: 26fa5c386371b8fb71d12a122c2758e7a435f119 $

DROP TABLE SCHREG_ADDRESS_DAT
CREATE TABLE SCHREG_ADDRESS_DAT( \
    SCHREGNO    VARCHAR(8)    NOT NULL, \
    ISSUEDATE   DATE          NOT NULL, \
    EXPIREDATE  DATE, \
    ZIPCD       VARCHAR(8), \
    AREACD      VARCHAR(2), \
    ADDR1       VARCHAR(150), \
    ADDR2       VARCHAR(150), \
    ADDR_FLG    VARCHAR(1), \
    ADDR1_ENG   VARCHAR(150), \
    ADDR2_ENG   VARCHAR(150), \
    TELNO       VARCHAR(14), \
    TELNO_MEMO  VARCHAR(24), \
    TELNO2      VARCHAR(14), \
    TELNO2_MEMO VARCHAR(24), \
    FAXNO       VARCHAR(14), \
    EMAIL       VARCHAR(50), \
    REGISTERCD  VARCHAR(10), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_ADDRESS_DAT ADD CONSTRAINT PK_SCHREG_ADDRESS PRIMARY KEY (SCHREGNO,ISSUEDATE)