-- kanji=漢字
-- $Id: 0ab63e29c3589d485ccd718dea4c84f073dc462e $

DROP   TABLE SCHREG_STUDYREC_AVG_CLASS_DAT
CREATE TABLE SCHREG_STUDYREC_AVG_CLASS_DAT ( \
    YEAR                VARCHAR(4) NOT NULL, \
    CLASS_DIV           VARCHAR(1) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    AVG_DIV             VARCHAR(1) NOT NULL, \
    GRADE               VARCHAR(2) NOT NULL, \
    HR_CLASS            VARCHAR(3) NOT NULL, \
    COURSECD            VARCHAR(1) NOT NULL, \
    MAJORCD             VARCHAR(3) NOT NULL, \
    COURSECODE          VARCHAR(4) NOT NULL, \
    SCORE               DECIMAL(12,5), \
    AVG                 DECIMAL(9,5), \
    COUNT               SMALLINT, \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_STUDYREC_AVG_CLASS_DAT ADD CONSTRAINT PK_STUDYREC_AVGCLS \
      PRIMARY KEY (YEAR, CLASS_DIV, CLASSCD, SCHOOL_KIND, AVG_DIV, GRADE, HR_CLASS, COURSECD, MAJORCD, COURSECODE)
