-- $Id: e29b588e13f5546174dacf7ae6beac3194807abf $

DROP TABLE SCHREG_SEND_ADDRESS_DAT
CREATE TABLE SCHREG_SEND_ADDRESS_DAT( \
    SCHREGNO              VARCHAR(8)    NOT NULL, \
    DIV                   VARCHAR(1)    NOT NULL, \
    SEND_RELATIONSHIP     VARCHAR(2), \
    SEND_NAME             VARCHAR(120), \
    SEND_KANA             VARCHAR(240), \
    SEND_SEX              VARCHAR(1), \
    SEND_ZIPCD            VARCHAR(8), \
    SEND_AREACD           VARCHAR(2), \
    SEND_ADDR1            VARCHAR(150), \
    SEND_ADDR2            VARCHAR(150), \
    SEND_ADDR_FLG         VARCHAR(1), \
    SEND_TELNO            VARCHAR(14), \
    SEND_TELNO2           VARCHAR(14), \
    SEND_JOBCD            VARCHAR(2), \
    PUBLIC_OFFICE         VARCHAR(30), \
    REGISTERCD            VARCHAR(8), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_SEND_ADDRESS_DAT ADD CONSTRAINT PK_SCHREG_SAD PRIMARY KEY (SCHREGNO, DIV)