-- $Id: 41b7589e80d390bfc5f1900bc5af065350c868f6 $

DROP TABLE SCHREG_COMP_SUBCLASS_DAT

CREATE TABLE SCHREG_COMP_SUBCLASS_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    SCHREGNO            VARCHAR(8) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    CURRICULUM_CD       VARCHAR(2) NOT NULL, \
    SUBCLASSCD          VARCHAR(6) NOT NULL, \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_COMP_SUBCLASS_DAT ADD CONSTRAINT PK_SCH_COMP_SUB PRIMARY KEY (YEAR, SCHREGNO, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)
