-- $Id: 9d8282a9f9c395a063c542191cbe7cdd4933208f $

DROP TABLE SCHREG_CHALLENGED_SUPPORTPLAN_WELFARE_RECORD_DAT
CREATE TABLE SCHREG_CHALLENGED_SUPPORTPLAN_WELFARE_RECORD_DAT( \
    YEAR                    VARCHAR(4)    NOT NULL, \
    SCHREGNO                VARCHAR(8)    NOT NULL, \
    RECORD_DATE             VARCHAR(10)   NOT NULL, \
    RECORD_DIV              VARCHAR(1)    NOT NULL, \
    RECORD_SEQ              SMALLINT      NOT NULL, \
    SUPPORT_PRESENT         VARCHAR(240), \
    SUPPORT_MEANS           VARCHAR(240), \
    SUPPORT_ASSESS          VARCHAR(240), \
    SERVICE_NEED_FUTURE     VARCHAR(300), \
    MEETING_DATE            DATE, \
    TEAM_MEMBERS            VARCHAR(120), \
    MEETING_SUMMARY         VARCHAR(525), \
    REGISTERCD              VARCHAR(8), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_CHALLENGED_SUPPORTPLAN_WELFARE_RECORD_DAT ADD CONSTRAINT PK_SCH_CH_S_WE_R_D PRIMARY KEY (YEAR, SCHREGNO, RECORD_DATE, RECORD_DIV, RECORD_SEQ)