-- $Id: 10ff6cd8e63d8ae46442d83012939c9b6045fbb4 $

DROP TABLE SCHREG_REGD_GHR_HDAT

CREATE TABLE SCHREG_REGD_GHR_HDAT( \
    YEAR                VARCHAR(4)      NOT NULL, \
    SEMESTER            VARCHAR(1)      NOT NULL, \
    GHR_CD              VARCHAR(2)      NOT NULL, \
    GHR_NAME            VARCHAR(30), \
    GHR_NAMEABBV        VARCHAR(30), \
    TR_CD1              VARCHAR(8), \
    TR_CD2              VARCHAR(8), \
    TR_CD3              VARCHAR(8), \
    SUBTR_CD1           VARCHAR(8), \
    SUBTR_CD2           VARCHAR(8), \
    SUBTR_CD3           VARCHAR(8), \
    REGISTERCD          VARCHAR(8), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_REGD_GHR_HDAT ADD CONSTRAINT PK_SCHRG_RGD_GHR_H PRIMARY KEY (YEAR, SEMESTER, GHR_CD)
