-- $Id: cc82df29ddc1f6274ac70ae2cc67425b09200360 $

DROP TABLE SCHREG_CHALLENGED_SUPPORTBOOK_MAIN_DAT
CREATE TABLE SCHREG_CHALLENGED_SUPPORTBOOK_MAIN_DAT( \
    YEAR                                VARCHAR(4)    NOT NULL, \
    SCHREGNO                            VARCHAR(8)    NOT NULL, \
    RECORD_DATE                         VARCHAR(10)   NOT NULL, \
    WRITING_DATE                        DATE          NOT NULL, \
    CHALLENGED_NAMES                    VARCHAR(270), \
    CHALLENGED_POPULAR_NAME             VARCHAR(270), \
    CHRONIC_DISEASE                     VARCHAR(630), \
    HOW_COMMUNICATION                   VARCHAR(750), \
    TROUBLED_BEHAVIOR_SUPPORT           VARCHAR(880), \
    BAD_CONDITION_SIGN                  VARCHAR(880), \
    REGISTERCD                          VARCHAR(8), \
    UPDATED                             TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_CHALLENGED_SUPPORTBOOK_MAIN_DAT ADD CONSTRAINT PK_SCH_CHA_SPB_M_D PRIMARY KEY (YEAR, SCHREGNO, RECORD_DATE)