-- $Id: 25400e5c5022fe1c72789528aa0e006ea75a14a5 $

DROP TABLE SCHREG_CHALLENGED_SUPPORTPLAN_SCHOOL_RECORD_DAT
CREATE TABLE SCHREG_CHALLENGED_SUPPORTPLAN_SCHOOL_RECORD_DAT( \
    YEAR                    VARCHAR(4)    NOT NULL, \
    SCHREGNO                VARCHAR(8)    NOT NULL, \
    RECORD_DATE             VARCHAR(10)   NOT NULL, \
    RECORD_DIV              VARCHAR(1)    NOT NULL, \
    RECORD_SEQ              SMALLINT      NOT NULL, \
    GOAL_FUTURE             VARCHAR(525), \
    LONG_TERM_GOAL          VARCHAR(210), \
    LONG_TERM_ASSESS        VARCHAR(225), \
    SHORT_TERM_GOAL         VARCHAR(210), \
    SHORT_TERM_MEANS        VARCHAR(294), \
    SHORT_TERM_ASSESS       VARCHAR(294), \
    CLUB_NAME               VARCHAR(60), \
    CLUB_S_YEAR_MONTH       VARCHAR(7), \
    REGISTERCD              VARCHAR(8), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_CHALLENGED_SUPPORTPLAN_SCHOOL_RECORD_DAT ADD CONSTRAINT PK_SCH_CH_S_SC_R_D PRIMARY KEY (YEAR, SCHREGNO, RECORD_DATE, RECORD_DIV, RECORD_SEQ)