-- $Id: f2c5f889965f8b9c65a588ac99b91f7b2b2726b6 $

DROP TABLE SCHREG_CHALLENGED_ASSESSMENT_CHECK_RECORD_DAT
CREATE TABLE SCHREG_CHALLENGED_ASSESSMENT_CHECK_RECORD_DAT( \
    YEAR                    VARCHAR(4)    NOT NULL, \
    SCHREGNO                VARCHAR(8)    NOT NULL, \
    RECORD_DATE             VARCHAR(10)   NOT NULL, \
    RECORD_SEQ              SMALLINT      NOT NULL, \
    CHECK_DATE              DATE, \
    CENTERCD                VARCHAR(5), \
    CHECK_NAME              VARCHAR(120), \
    CHECKER                 VARCHAR(30), \
    CHECK_REMARK            VARCHAR(840), \
    REGISTERCD              VARCHAR(8), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_CHALLENGED_ASSESSMENT_CHECK_RECORD_DAT ADD CONSTRAINT PK_SCH_CH_A_CH_R_D PRIMARY KEY (YEAR, SCHREGNO, RECORD_DATE, RECORD_SEQ)