-- $Id: 64d9d0693e6b990151cf9b5975e47b01a82fa17a $

DROP TABLE SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CONSULTATION_RECORD_DAT
CREATE TABLE SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CONSULTATION_RECORD_DAT( \
    SCHREGNO                VARCHAR(8)    NOT NULL, \
    RECORD_DATE             VARCHAR(10)   NOT NULL, \
    RECORD_SEQ              SMALLINT      NOT NULL, \
    MEETING_NAME            VARCHAR(150), \
    MEETING_DATE            DATE, \
    TEAM_MEMBERS            VARCHAR(150), \
    MEETING_SUMMARY         VARCHAR(600), \
    REGISTERCD              VARCHAR(10), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CONSULTATION_RECORD_DAT ADD CONSTRAINT PK_SCH_CH_TS_CO_R PRIMARY KEY (SCHREGNO, RECORD_DATE, RECORD_SEQ)