-- $Id: a5e551264b12a74cd9e6174148d5d19df4c795f4 $

DROP TABLE SCHREG_NAME_SETUP_DAT
CREATE TABLE SCHREG_NAME_SETUP_DAT( \
    SCHREGNO              VARCHAR(8)    NOT NULL, \
    DIV                   VARCHAR(2)    NOT NULL, \
    NAME_OUTPUT_FLG       VARCHAR(1), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_NAME_SETUP_DAT ADD CONSTRAINT PK_SCHREG_N_S_DAT PRIMARY KEY (SCHREGNO,DIV)