-- kanji=?Á»?
-- $Id: 6edb697d52b88f0436c1d093d94f4d0e04f94a2a $

DROP TABLE SCHREG_STUDYREC_DETAIL_DAT
CREATE TABLE SCHREG_STUDYREC_DETAIL_DAT( \
    SCHOOLCD            VARCHAR(1)    NOT NULL, \
    YEAR                VARCHAR(4)    NOT NULL, \
    SCHREGNO            VARCHAR(8)    NOT NULL, \
    CLASSCD             VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND         VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD       VARCHAR(2)    NOT NULL, \
    SUBCLASSCD          VARCHAR(6)    NOT NULL, \
    SEQ                 VARCHAR(3)    NOT NULL, \
    REMARK1             VARCHAR(3500), \
    REMARK2             VARCHAR(1000), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_STUDYREC_DETAIL_DAT ADD CONSTRAINT PK_SCHREG_STUDY_DE PRIMARY KEY (SCHOOLCD,YEAR,SCHREGNO,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SEQ)
