-- $Id: 6e6493ba00b6449978bcf4669e4fce5ae1d64282 $

DROP TABLE SCHREG_CHALLENGED_TEACHER_TAKEOVER_MAIN_DAT
CREATE TABLE SCHREG_CHALLENGED_TEACHER_TAKEOVER_MAIN_DAT( \
    YEAR                                VARCHAR(4)    NOT NULL, \
    SCHREGNO                            VARCHAR(8)    NOT NULL, \
    RECORD_DATE                         VARCHAR(10)   NOT NULL, \
    WRITING_DATE                        DATE          NOT NULL, \
    REGISTERCD                          VARCHAR(8), \
    UPDATED                             TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_CHALLENGED_TEACHER_TAKEOVER_MAIN_DAT ADD CONSTRAINT PK_SCH_CHA_TC_T_M PRIMARY KEY (YEAR, SCHREGNO, RECORD_DATE)