-- $Id: b6fc25ed77f6a2e45be27091840e133e9d31c356 $

DROP TABLE SCHREG_TRAINHIST_DAT
CREATE TABLE SCHREG_TRAINHIST_DAT( \
    YEAR         VARCHAR(4)    NOT NULL, \
    TRAINDATE    DATE          NOT NULL, \
    SCHREGNO     VARCHAR(8)    NOT NULL, \
    PATIENTCD    VARCHAR(2), \
    STAFFCD      VARCHAR(8), \
    HOWTOTRAINCD VARCHAR(2), \
    CONTENT      VARCHAR(458), \
    REGISTERCD   VARCHAR(8), \
    UPDATED      TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_TRAINHIST_DAT ADD CONSTRAINT PK_SCHREGTRAINHIST PRIMARY KEY (YEAR,TRAINDATE,SCHREGNO)