-- $Id: e33885b2226c8413406185cab4e01f68d2aa2fa8 $

DROP TABLE SCHREG_BASE_DETAIL_COMEBACK_MST

CREATE TABLE SCHREG_BASE_DETAIL_COMEBACK_MST \
    (SCHREGNO            VARCHAR(8)    NOT NULL, \
     COMEBACK_DATE       DATE          NOT NULL, \
     BASE_SEQ            VARCHAR(3)    NOT NULL, \
     BASE_REMARK1        VARCHAR(768), \
     BASE_REMARK2        VARCHAR(768), \
     BASE_REMARK3        VARCHAR(768), \
     BASE_REMARK4        VARCHAR(768), \
     BASE_REMARK5        VARCHAR(768), \
     BASE_REMARK6        VARCHAR(768), \
     REGISTERCD          VARCHAR(8), \
     UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_BASE_DETAIL_COMEBACK_MST ADD CONSTRAINT PK_SCHREG_B_D_COME PRIMARY KEY (SCHREGNO, COMEBACK_DATE, BASE_SEQ)
