-- $Id: 177e7f81b703e3e267a47871cfd971f5e16550a8 $

DROP TABLE SEMESTER_DETAIL_MST
CREATE TABLE SEMESTER_DETAIL_MST( \
    YEAR            VARCHAR(4)    NOT NULL, \
    SEMESTER        VARCHAR(1)    NOT NULL, \
    SEMESTER_DETAIL VARCHAR(1)    NOT NULL, \
    SEMESTERNAME    VARCHAR(30), \
    SDATE           DATE, \
    EDATE           DATE, \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SEMESTER_DETAIL_MST ADD CONSTRAINT PK_SEM_DETAIL_MST PRIMARY KEY (YEAR,SEMESTER,SEMESTER_DETAIL)