-- $Id: cba1cabac27564112d8af4f52fd3f81720e136c2 $

DROP TABLE SEMESTER_GRADE_MST
CREATE TABLE SEMESTER_GRADE_MST( \
    YEAR         VARCHAR(4)    NOT NULL, \
    SEMESTER     VARCHAR(1)    NOT NULL, \
    GRADE        VARCHAR(2)    NOT NULL, \
    SEMESTERNAME VARCHAR(30), \
    SDATE        DATE, \
    EDATE        DATE, \
    REGISTERCD   VARCHAR(8), \
    UPDATED      TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SEMESTER_GRADE_MST ADD CONSTRAINT PK_SEMESTER_G PRIMARY KEY (YEAR, SEMESTER, GRADE)