-- $Id$

DROP TABLE SESSIONS

CREATE TABLE SESSIONS ( \
  SESSION_ID VARCHAR(32) NOT NULL, \
  SESSION_DATA VARCHAR(3000) NOT NULL, \
  SESSION_EXPIRATION INTEGER NOT NULL, \
  SESSION_UPDATED VARCHAR(20) NOT NULL, \
  PRIMARY KEY (SESSION_ID) \
)