-- $Id: c56395c3e75b59f0144edb717dd7bf10850c59fb $

DROP TABLE SPECIAL_REASON_DAT
CREATE TABLE SPECIAL_REASON_DAT( \
    YEAR               VARCHAR(4)    NOT NULL, \
    SCHREGNO           VARCHAR(8)    NOT NULL, \
    SPECIAL_REASON_DIV VARCHAR(2)    NOT NULL, \
    REMARK             VARCHAR(120), \
    REGISTERCD         VARCHAR(8), \
    UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SPECIAL_REASON_DAT ADD CONSTRAINT PK_SPECIAL_REA_DAT PRIMARY KEY (YEAR,SCHREGNO,SPECIAL_REASON_DIV)