-- kanji=´Á»ú
-- $Id: b1ad5379b95b32e0454a39c5c995dbee3c768fea $

DROP TABLE SPECIALACT_SCORE_DAT

CREATE TABLE SPECIALACT_SCORE_DAT \
      (YEAR           VARCHAR(4) NOT NULL, \
       SEMESTER       VARCHAR(1) NOT NULL, \
       CLASSCD        VARCHAR(2) NOT NULL, \
       SCHOOL_KIND    VARCHAR(2) NOT NULL, \
       CURRICULUM_CD  VARCHAR(2) NOT NULL, \
       SUBCLASSCD     VARCHAR(6) NOT NULL, \
       SCHREGNO       VARCHAR(8) NOT NULL, \
       VALUE          SMALLINT, \
       REGISTERCD     VARCHAR(8), \
       UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
      ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SPECIALACT_SCORE_DAT ADD CONSTRAINT PK_SPACT_SCORE_DAT \
      PRIMARY KEY (YEAR,SEMESTER,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO)
