-- $Id: 0630777a740d03540c2e603db91c20a8c517bc3a $

DROP TABLE SPORTS_SCORE_INQUIRY_DAT
CREATE TABLE SPORTS_SCORE_INQUIRY_DAT ( \
    YEAR                  VARCHAR(4)    NOT NULL, \
    SCHREGNO              VARCHAR(8)    NOT NULL, \
    INQUIRYCD             VARCHAR(2)    NOT NULL, \
    VALUE                 VARCHAR(1)    , \
    REGISTERCD            VARCHAR(10)    , \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SPORTS_SCORE_INQUIRY_DAT ADD CONSTRAINT PK_SPORTS_SC_DAT PRIMARY KEY (YEAR, SCHREGNO, INQUIRYCD)
