-- $Id: 4c445136204f818afb411678f92ad625217d3417 $

DROP TABLE SPORTS_ITEM_SCORE_BASE_MST
CREATE TABLE SPORTS_ITEM_SCORE_BASE_MST ( \
    YEAR                    VARCHAR(4)    NOT NULL, \
    ITEMCD                  VARCHAR(3)    NOT NULL, \
    SEX                     VARCHAR(1)    NOT NULL, \
    SCORE_LEVEL             SMALLINT      NOT NULL, \
    RECORD_LOW              DECIMAL(6, 3)         , \
    RECORD_HIGH             DECIMAL(6, 3)         , \
    REGISTERCD              VARCHAR(10)           , \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SPORTS_ITEM_SCORE_BASE_MST ADD CONSTRAINT PK_SPORTS_ITEM_SCORE_BASE_D PRIMARY KEY (YEAR, ITEMCD, SEX, SCORE_LEVEL)
