-- $Id: b42986fe35446959a89cc4b2c7871761589250e3 $

DROP TABLE SPORTS_ITEM_MST
CREATE TABLE SPORTS_ITEM_MST ( \
    ITEMCD                VARCHAR(3)    NOT NULL, \
    ITEMNAME              VARCHAR(60), \
    ITEMABBV              VARCHAR(60), \
    UNIT                  VARCHAR(9), \
    SHOWORDER             SMALLINT, \
    REGISTERCD            VARCHAR(8), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SPORTS_ITEM_MST ADD CONSTRAINT PK_SPORTS_ITEM_MST PRIMARY KEY (ITEMCD)
