-- $Id: ca9f73aeed5770f10fe0060bc1f44f4616963b49 $

DROP TABLE STAFF_DETAIL_SEQ_MST
CREATE TABLE STAFF_DETAIL_SEQ_MST( \
    STAFFCD             VARCHAR(10)    NOT NULL, \
    STAFF_SEQ           VARCHAR(3)    NOT NULL, \
    FIELD1              VARCHAR(15), \
    FIELD2              VARCHAR(15), \
    FIELD3              VARCHAR(120), \
    FIELD4              VARCHAR(120), \
    FIELD5              VARCHAR(120), \
    REGISTERCD          VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE STAFF_DETAIL_SEQ_MST ADD CONSTRAINT PK_STAFF_DET_SEQ PRIMARY KEY (STAFFCD, STAFF_SEQ)