-- $Id: de6912697bb7d448ca0320b3cc76dce0d06d787a $

DROP TABLE STAFF_DETAIL_MST
CREATE TABLE STAFF_DETAIL_MST( \
    YEAR                VARCHAR(4)    NOT NULL, \
    STAFFCD             VARCHAR(8)    NOT NULL, \
    STAFF_SEQ           VARCHAR(3)    NOT NULL, \
    FIELD1              VARCHAR(15), \
    FIELD2              VARCHAR(15), \
    FIELD3              VARCHAR(120), \
    FIELD4              VARCHAR(120), \
    FIELD5              VARCHAR(120), \
    REGISTERCD          VARCHAR(8), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE STAFF_DETAIL_MST ADD CONSTRAINT PK_STAFF_DETAIL PRIMARY KEY (YEAR, STAFFCD, STAFF_SEQ)