-- $Id: 992d60f6b367a78db332cc95ca12c4e0629998e8 $

DROP TABLE STAFF_NAME_SETUP_DAT
CREATE TABLE STAFF_NAME_SETUP_DAT( \
    YEAR                VARCHAR(4)    NOT NULL, \
    STAFFCD             VARCHAR(8)    NOT NULL, \
    DIV                 VARCHAR(2)    NOT NULL, \
    NAME_OUTPUT_FLG     VARCHAR(1), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE STAFF_NAME_SETUP_DAT ADD CONSTRAINT PK_STAFF_N_S_DAT PRIMARY KEY (YEAR,STAFFCD,DIV)