-- $Id: d62b76e0be692f6c780dbbdd6f4b0601ec582931 $

DROP TABLE STAFF_CLASS_HIST_DAT
CREATE TABLE STAFF_CLASS_HIST_DAT( \
    YEAR       VARCHAR(4)    NOT NULL, \
    SEMESTER   VARCHAR(1)    NOT NULL, \
    GRADE      VARCHAR(3)    NOT NULL, \
    HR_CLASS   VARCHAR(3)    NOT NULL, \
    TR_DIV     VARCHAR(1)    NOT NULL, \
    FROM_DATE  DATE          NOT NULL, \
    TO_DATE    DATE, \
    STAFFCD    VARCHAR(8), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE STAFF_CLASS_HIST_DAT ADD CONSTRAINT PK_STF_CLASS_HIST PRIMARY KEY (YEAR,SEMESTER,GRADE,HR_CLASS,TR_DIV,FROM_DATE)