-- $Id: 79f7ed303ea936063dcd2093bc61c1682f148e75 $

drop table STAFF_NAME_HIST_DAT

CREATE TABLE STAFF_NAME_HIST_DAT( \
    STAFFCD               VARCHAR(8)  NOT NULL, \
    SDATE                 DATE        NOT NULL, \
    EDATE                 DATE, \
    STAFFNAME             VARCHAR(60), \
    STAFFNAME_SHOW        VARCHAR(60), \
    STAFFNAME_KANA        VARCHAR(120), \
    STAFFNAME_ENG         VARCHAR(60), \
    STAFFNAME_REAL        VARCHAR(120), \
    STAFFNAME_KANA_REAL   VARCHAR(240), \
    REGISTERCD            VARCHAR(8), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE STAFF_NAME_HIST_DAT ADD CONSTRAINT PK_STAFF_NAME_HIST PRIMARY KEY (STAFFCD, SDATE)
