-- $Id: c01a8132b23ebb4bd3d756919bdd3430cf830077 $

DROP TABLE STAFF_CLASS_HIST_FI_DAT

CREATE TABLE STAFF_CLASS_HIST_FI_DAT( \
    YEAR                VARCHAR(4)      NOT NULL, \
    SEMESTER            VARCHAR(1)      NOT NULL, \
    GRADE               VARCHAR(2)      NOT NULL, \
    HR_CLASS            VARCHAR(3)      NOT NULL, \
    TR_DIV              VARCHAR(1)      NOT NULL, \
    FROM_DATE           DATE            NOT NULL, \
    TO_DATE             DATE, \
    STAFFCD             VARCHAR(8), \
    REGISTERCD          VARCHAR(8), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE STAFF_CLASS_HIST_FI_DAT ADD CONSTRAINT PK_STF_C_H_FI_DAT PRIMARY KEY (YEAR,SEMESTER,GRADE,HR_CLASS,TR_DIV,FROM_DATE)