-- $Id: 89cf2569692af0a64dfa930b33422a01d4f5200f $

drop table STAFF_ANOTHER_DAT

CREATE TABLE STAFF_ANOTHER_DAT( \
    EDBOARD_SCHOOLCD      VARCHAR(12) NOT NULL, \
    STAFFCD               VARCHAR(8)  NOT NULL, \
    STAFF_DIV             VARCHAR(1)  NOT NULL, \
    REMARK                VARCHAR(120), \
    REGISTERCD            VARCHAR(8), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE STAFF_ANOTHER_DAT ADD CONSTRAINT PK_STAFF_ANOTHER PRIMARY KEY (EDBOARD_SCHOOLCD, STAFFCD)
