-- $Id: 9195f8758225cbe28badc45cfe4d082c109015ed $

DROP TABLE STAFF_CLASS_HIST_GHR_DAT

CREATE TABLE STAFF_CLASS_HIST_GHR_DAT( \
    YEAR                VARCHAR(4)      NOT NULL, \
    SEMESTER            VARCHAR(1)      NOT NULL, \
    GHR_CD              VARCHAR(2)      NOT NULL, \
    TR_DIV              VARCHAR(1)      NOT NULL, \
    FROM_DATE           DATE            NOT NULL, \
    TO_DATE             DATE, \
    STAFFCD             VARCHAR(8), \
    REGISTERCD          VARCHAR(8), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE STAFF_CLASS_HIST_GHR_DAT ADD CONSTRAINT PK_STF_CLS_HST_GHR PRIMARY KEY (YEAR,SEMESTER,GHR_CD,TR_DIV,FROM_DATE)