-- $Id: 40ad7aeea077d90834127079170d2c967315af7c $

drop table STAFF_ADDRESS_DAT

CREATE TABLE STAFF_ADDRESS_DAT( \
    STAFFCD     VARCHAR(8)  NOT NULL, \
    SDATE       DATE        NOT NULL, \
    EDATE       DATE, \
    STAFFZIPCD  VARCHAR(8), \
    STAFFADDR1  VARCHAR(150), \
    STAFFADDR2  VARCHAR(150), \
    STAFFTELNO  VARCHAR(14), \
    STAFFFAXNO  VARCHAR(14), \
    STAFFE_MAIL VARCHAR(50), \
    REGISTERCD  VARCHAR(8), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE STAFF_ADDRESS_DAT ADD CONSTRAINT PK_STAFF_ADDRESS PRIMARY KEY (STAFFCD, SDATE)
