-- kanji=漢字
-- $Id: 7bd99c0737276e886690c9bdcb94c795466e0ad6 $

DROP TABLE STUDYREC_PROV_FLG_EXEC_HIST_DAT

CREATE TABLE STUDYREC_PROV_FLG_EXEC_HIST_DAT ( \
    CALC_DATE               DATE NOT NULL, \
    CALC_TIME               TIME NOT NULL, \
    BEF_AFT_DIV             VARCHAR(1) NOT NULL, \
    SCHOOLCD                VARCHAR(1) NOT NULL, \
    YEAR                    VARCHAR(4) NOT NULL, \
    SCHREGNO                VARCHAR(8) NOT NULL, \
    CLASSCD                 VARCHAR(2) NOT NULL, \
    SCHOOL_KIND             VARCHAR(2) NOT NULL, \
    CURRICULUM_CD           VARCHAR(2) NOT NULL, \
    SUBCLASSCD              VARCHAR(6) NOT NULL, \
    PROV_FLG                VARCHAR(1), \
    PROV_SEMESTER           VARCHAR(1), \
    PROV_TESTKINDCD         VARCHAR(2), \
    PROV_TESTITEMCD         VARCHAR(2), \
    PROV_SCORE_DIV          VARCHAR(2), \
    CMD_DIV                 VARCHAR(1), \
    REGISTERCD              VARCHAR(10), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE STUDYREC_PROV_FLG_EXEC_HIST_DAT ADD CONSTRAINT PK_STUDYREC_PROV_FLG_EXEC_HIST_DAT PRIMARY KEY (CALC_DATE,CALC_TIME,BEF_AFT_DIV,SCHOOLCD,YEAR,SCHREGNO,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)
