-- $Id: deff6da141f1fc219018bfad7547ea9b0bd1270a $

DROP TABLE STUDYRECREMARK_DAT
CREATE TABLE STUDYRECREMARK_DAT( \
    YEAR            VARCHAR(4)    NOT NULL, \
    SCHREGNO        VARCHAR(8)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    REMARK          VARCHAR(150), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE STUDYRECREMARK_DAT ADD CONSTRAINT PK_STUDYCLASS_DAT PRIMARY KEY (YEAR,SCHREGNO,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)