-- $Id: d6183d97d39e2b269c302e38ee424f7f8dda4438 $

DROP TABLE SUBCLASS_MST
CREATE TABLE SUBCLASS_MST( \
    CLASSCD            VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND        VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD      VARCHAR(2)    NOT NULL, \
    SUBCLASSCD         VARCHAR(6)    NOT NULL, \
    SUBCLASSNAME       VARCHAR(150), \
    SUBCLASSABBV       VARCHAR(90), \
    SUBCLASSNAME_ENG   VARCHAR(90), \
    SUBCLASSABBV_ENG   VARCHAR(90), \
    SUBCLASSORDERNAME1 VARCHAR(150), \
    SUBCLASSORDERNAME2 VARCHAR(150), \
    SUBCLASSORDERNAME3 VARCHAR(150), \
    SHOWORDER          SMALLINT, \
    SHOWORDER2         SMALLINT, \
    SHOWORDER3         SMALLINT, \
    SUBCLASSCD2        VARCHAR(6), \
    SUBCLASSCD3        VARCHAR(6), \
    ELECTDIV           VARCHAR(1), \
    REGISTERCD         VARCHAR(10), \
    UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SUBCLASS_MST ADD CONSTRAINT PK_SUBCLASS_MST PRIMARY KEY (CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)