-- $Id: 13323a3574a798075ae245940e9df5e623362924 $

drop table   SUBCLASS_ADJUST_DAT

create table SUBCLASS_ADJUST_DAT( \
    YEAR          VARCHAR(4) NOT NULL, \
    SEMESTER      VARCHAR(1) NOT NULL, \
    GRADE         VARCHAR(2) NOT NULL, \
    CLASSCD       VARCHAR(2) NOT NULL, \
    SCHOOL_KIND   VARCHAR(2) NOT NULL, \
    CURRICULUM_CD VARCHAR(2) NOT NULL, \
    SUBCLASSCD    VARCHAR(6) NOT NULL, \
    VALUE         SMALLINT, \
    REGISTERCD    VARCHAR(8),  \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) in usr1dms index in idx1dms


alter table SUBCLASS_ADJUST_DAT \
add constraint PK_SUB_AD_DAT \
primary key ( YEAR, SEMESTER, GRADE, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)

