-- kanji=Š¿Žš
-- $Id: 2918b39dce85bf4af1b93907cf9ec2c3aefe90c3 $

DROP TABLE SUBCLASS_WEIGHTING_COURSE_DAT
CREATE TABLE SUBCLASS_WEIGHTING_COURSE_DAT( \
    YEAR                      VARCHAR(4) NOT NULL, \
    FLG                       VARCHAR(2) NOT NULL, \
    GRADE                     VARCHAR(2) NOT NULL, \
    COURSECD                  VARCHAR(1) NOT NULL, \
    MAJORCD                   VARCHAR(3) NOT NULL, \
    COURSECODE                VARCHAR(4) NOT NULL, \
    COMBINED_CLASSCD          VARCHAR(2) NOT NULL, \
    COMBINED_SCHOOL_KIND      VARCHAR(2) NOT NULL, \
    COMBINED_CURRICULUM_CD    VARCHAR(2) NOT NULL, \
    COMBINED_SUBCLASSCD       VARCHAR(6) NOT NULL, \
    SEQ                       VARCHAR(2) NOT NULL, \
    ATTEND_CLASSCD            VARCHAR(2) NOT NULL, \
    ATTEND_SCHOOL_KIND        VARCHAR(2) NOT NULL, \
    ATTEND_CURRICULUM_CD      VARCHAR(2) NOT NULL, \
    ATTEND_SUBCLASSCD         VARCHAR(6) NOT NULL, \
    WEIGHTING                 SMALLINT, \
    WEIGHTING2                DECIMAL(5,2), \
    REGISTERCD                VARCHAR(8), \
    UPDATED                   TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SUBCLASS_WEIGHTING_COURSE_DAT ADD CONSTRAINT SUBCLASS_WEI_C_DAT \
        PRIMARY KEY (YEAR, FLG, GRADE, COURSECD, MAJORCD, COURSECODE, COMBINED_CLASSCD, COMBINED_SCHOOL_KIND, COMBINED_CURRICULUM_CD, COMBINED_SUBCLASSCD, SEQ, ATTEND_CLASSCD, ATTEND_SCHOOL_KIND, ATTEND_CURRICULUM_CD, ATTEND_SUBCLASSCD)
