-- kanji=Š¿Žš
-- $Id: a8372d21dfa8c07f0dedd4d16c0e7b54a25513e4 $

DROP TABLE SUBCLASS_SEMVAL_ADJUST_DAT
CREATE TABLE SUBCLASS_SEMVAL_ADJUST_DAT( \
    YEAR       VARCHAR(4)    NOT NULL, \
    SEMESTER   VARCHAR(1)    NOT NULL, \
    GRADE      VARCHAR(2)    NOT NULL, \
    GROUP_CD   VARCHAR(3)    NOT NULL, \
    CLASSCD       VARCHAR(2) NOT NULL, \
    SCHOOL_KIND   VARCHAR(2) NOT NULL, \
    CURRICULUM_CD VARCHAR(2) NOT NULL, \
    SUBCLASSCD VARCHAR(6)    NOT NULL, \
    TOTAL      SMALLINT, \
    ADJUST     SMALLINT, \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SUBCLASS_SEMVAL_ADJUST_DAT ADD CONSTRAINT PK_SUB_SMV_ADJ_DAT PRIMARY KEY (YEAR,SEMESTER,GRADE,GROUP_CD,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)