-- $Id: 97b72f55c2f1bddf696912b61909bfbfc01dfa28 $

DROP TABLE SUBCLASS_GRADE_DAT
CREATE TABLE SUBCLASS_GRADE_DAT ( \
    YEAR                  VARCHAR(4)    NOT NULL, \
    GRADE                 VARCHAR(2)    NOT NULL, \
    RECORD_DIV            VARCHAR(1)    NOT NULL, \
    CLASSCD               VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND           VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD         VARCHAR(2)    NOT NULL, \
    SUBCLASSCD            VARCHAR(6)    NOT NULL, \
    TEXT_HYOKA_FLG        VARCHAR(1), \
    REGISTERCD            VARCHAR(8), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SUBCLASS_GRADE_DAT ADD CONSTRAINT PK_SUB_GRD_DAT PRIMARY KEY (YEAR, GRADE, RECORD_DIV, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)
