-- kanji=Š¿Žš
-- $Id: 75c48f490ef27416cb6162cbdd50cbf762f8fbe5 $

DROP TABLE SUBCLASS_SEMVAL_PERCENT_DAT
CREATE TABLE SUBCLASS_SEMVAL_PERCENT_DAT( \
    YEAR                    VARCHAR(4)    NOT NULL, \
    SEMESTER                VARCHAR(1)    NOT NULL, \
    GRADE                   VARCHAR(2)    NOT NULL, \
    GROUP_CD                VARCHAR(3)    NOT NULL, \
    CLASSCD       			VARCHAR(2) 	  NOT NULL, \
    SCHOOL_KIND   			VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD 			VARCHAR(2)    NOT NULL, \
    SUBCLASSCD              VARCHAR(6)    NOT NULL, \
    SEQ                     SMALLINT      NOT NULL, \
    TESTDIV                 VARCHAR(1), \
    TESTKINDCD              VARCHAR(2), \
    TESTITEMCD              VARCHAR(2), \
    PROFICIENCYDIV          VARCHAR(2), \
    PROFICIENCYCD           VARCHAR(4), \
    PROFICIENCY_SUBCLASS_CD VARCHAR(6), \
    PERCENT                 SMALLINT, \
    PERFECT                 SMALLINT, \
    REGISTERCD              VARCHAR(8), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SUBCLASS_SEMVAL_PERCENT_DAT ADD CONSTRAINT PK_SUB_SMV_PER_DAT PRIMARY KEY (YEAR,SEMESTER,GRADE,GROUP_CD,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SEQ)