-- kanji=漢字
-- $Id: d487d4ac32d9963c53c38c7458c361e16540dccd $

DROP TABLE SUBCLASS_DETAIL_DAT
CREATE TABLE SUBCLASS_DETAIL_DAT \
(  \
    YEAR              VARCHAR(4)  NOT NULL, \
    CLASSCD           VARCHAR(2)  NOT NULL, \
    SCHOOL_KIND       VARCHAR(2)  NOT NULL, \
    CURRICULUM_CD     VARCHAR(2)  NOT NULL, \
    SUBCLASSCD        VARCHAR(6)  NOT NULL, \
    SUBCLASS_SEQ      VARCHAR(3)  NOT NULL, \
    SUBCLASS_REMARK1  VARCHAR(15), \
    SUBCLASS_REMARK2  VARCHAR(15), \
    SUBCLASS_REMARK3  VARCHAR(15), \
    SUBCLASS_REMARK4  VARCHAR(15), \
    SUBCLASS_REMARK5  VARCHAR(15), \
    SUBCLASS_REMARK6  VARCHAR(15), \
    SUBCLASS_REMARK7  VARCHAR(15), \
    SUBCLASS_REMARK8  VARCHAR(15), \
    SUBCLASS_REMARK9  VARCHAR(15), \
    SUBCLASS_REMARK10 VARCHAR(15), \
    ORIGINAL_CD     VARCHAR(4), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SUBCLASS_DETAIL_DAT ADD CONSTRAINT PK_SUBCL_DTL_DAT \
PRIMARY KEY (YEAR,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SUBCLASS_SEQ)


