-- $Id: c5dcfc9feab7f0d217623646d4dd8139e6d30b1b $

DROP TABLE TEAM_MEMBER_MST
CREATE TABLE TEAM_MEMBER_MST( \
    MEMBERCD                VARCHAR(7)    NOT NULL, \
    NAME                    VARCHAR(120), \
    ABBV                    VARCHAR(120), \
    REGISTERCD              VARCHAR(8), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE TEAM_MEMBER_MST ADD CONSTRAINT PK_TEAM_MEM_MST PRIMARY KEY (MEMBERCD)