-- $Id: 8cc2555d34f65eb9f3c2976ea65d0ed54e1c8b4e $

DROP TABLE TESTSCORE_DAT
CREATE TABLE TESTSCORE_DAT( \
    YEAR            VARCHAR(4)    NOT NULL, \
    SEMESTER        VARCHAR(1)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    TESTKINDCD      VARCHAR(2)    NOT NULL, \
    TESTITEMCD      VARCHAR(2)    NOT NULL, \
    SCHREGNO        VARCHAR(8)    NOT NULL, \
    CHAIRCD         VARCHAR(7), \
    ATTEND_FLG      VARCHAR(1), \
    SCORE           smallint, \
    VALUE           smallint, \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE TESTSCORE_DAT ADD CONSTRAINT PK_TESTSCORE_DAT PRIMARY KEY (YEAR, SEMESTER, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, TESTKINDCD, TESTITEMCD, SCHREGNO)