-- $Id: 952ad5f4b3a6bb82b65a9dfcd8f9c53132091782 $

DROP TABLE TESTITEM_MST_COUNTFLG_NEW
CREATE TABLE TESTITEM_MST_COUNTFLG_NEW( \
    YEAR            VARCHAR(4)    NOT NULL, \
    TESTKINDCD      VARCHAR(2)    NOT NULL, \
    TESTITEMCD      VARCHAR(2)    NOT NULL, \
    TESTITEMNAME    VARCHAR(30), \
    COUNTFLG        VARCHAR(1), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE TESTITEM_MST_COUNTFLG_NEW ADD CONSTRAINT PK_TESTITEM_M_CF_N PRIMARY KEY (YEAR,TESTKINDCD,TESTITEMCD)