-- $Id: 90561f53fd3ba36daa6617407175288024d48639 $

DROP TABLE TESTITEM_MST
CREATE TABLE TESTITEM_MST( \
    YEAR            VARCHAR(4)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    TESTKINDCD      VARCHAR(2)    NOT NULL, \
    TESTITEMCD      VARCHAR(2)    NOT NULL, \
    TESTITEMNAME    VARCHAR(30), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE TESTITEM_MST ADD CONSTRAINT PK_TESTITEM_MST PRIMARY KEY (YEAR, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, TESTKINDCD, TESTITEMCD)