-- $Id: f6c23b6309ab76977b195286ddde75635bd56980 $

DROP TABLE TEXTBOOK_YDAT

CREATE TABLE TEXTBOOK_YDAT  \
(  \
        "YEAR"           VARCHAR(4)      NOT NULL, \
        "TEXTBOOKCD"     VARCHAR(12)     NOT NULL, \
        "REGISTERCD"     VARCHAR(8),  \
        "UPDATED"        TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS


ALTER TABLE TEXTBOOK_YDAT  \
ADD CONSTRAINT PK_TEXTBOOK_YDAT  \
PRIMARY KEY  \
( \
YEAR, \
TEXTBOOKCD \
)

