-- $Id: 525cac9cfe2f8442185407f3cd4ba57127350eb6 $

DROP TABLE USER_MST
CREATE TABLE USER_MST( \
    SCHOOLCD       VARCHAR(12) NOT NULL, \
    SCHOOL_KIND    VARCHAR(2)  NOT NULL, \
    STAFFCD        VARCHAR(8)    NOT NULL, \
    USERID         VARCHAR(32), \
    PASSWD         VARCHAR(32), \
    INVALID_FLG    VARCHAR(1), \
    PWDTERMCHK_FLG VARCHAR(1), \
    USE_LDAP       VARCHAR(2), \
    CHG_PWD_FLG    VARCHAR(1), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE USER_MST ADD CONSTRAINT PK_USER_MST PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, STAFFCD)
