-- $Id: 14ddf0c6d8b94d46680de9f976c928477a799600 $

DROP TABLE USERGROUP_DAT_OLD
RENAME TABLE USERGROUP_DAT TO USERGROUP_DAT_OLD
CREATE TABLE USERGROUP_DAT( \
    YEAR           VARCHAR(4)  NOT NULL, \
    SCHOOLCD       VARCHAR(12) NOT NULL, \
    SCHOOL_KIND    VARCHAR(2)  NOT NULL, \
    GROUPCD        VARCHAR(4)  NOT NULL, \
    STAFFCD        VARCHAR(10) NOT NULL, \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE USERGROUP_DAT ADD CONSTRAINT PK_USERGROUP_DAT PRIMARY KEY (YEAR, SCHOOLCD, SCHOOL_KIND, GROUPCD, STAFFCD)