-- $Id: f7f09ccf3c14ce3d8fdb289493d571509501e0e7 $

DROP TABLE USER_PWD_HIST_MST

CREATE TABLE USER_PWD_HIST_MST( \
    STAFFCD        VARCHAR(10) NOT NULL, \
    PASSWD         VARCHAR(32) NOT NULL, \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE USER_PWD_HIST_MST ADD CONSTRAINT PK_USER_PWD_HIST_M PRIMARY KEY (STAFFCD,PASSWD)