-- $Id: 6587a37f51f1709f930cf27b95763c9da2fd736c $

DROP TABLE USERGROUP_MST_OLD
RENAME TABLE USERGROUP_MST TO USERGROUP_MST_OLD
CREATE TABLE USERGROUP_MST( \
    SCHOOLCD       VARCHAR(12) NOT NULL, \
    SCHOOL_KIND    VARCHAR(2)  NOT NULL, \
    GROUPCD        VARCHAR(4)  NOT NULL, \
    GROUPNAME      VARCHAR(60), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE USERGROUP_MST ADD CONSTRAINT PK_USERGROUP_MST PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, GROUPCD)