-- kanji=漢字
-- 実行前にDROP FUNCTION SECURITY_CHK_MNU、SECURITY_CHK_PRG実行し、再度FUNCTIONのSCRIPTを実行する必要あり

DROP TABLE USERAUTH_DAT_OLD
RENAME TABLE USERAUTH_DAT TO USERAUTH_DAT_OLD
CREATE TABLE USERAUTH_DAT( \
    SCHOOLCD        VARCHAR(12) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    STAFFCD         VARCHAR(10) NOT NULL, \
    MENUID          VARCHAR(11) NOT NULL, \
    USERAUTH        VARCHAR(1), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE USERAUTH_DAT ADD CONSTRAINT PK_USERAUTH_DAT PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, STAFFCD, MENUID)