-- $Id: c334fd85b6bef58f19f52106920c06d4b2544b8e $

DROP TABLE WELFARE_SERVICECD_MST
CREATE TABLE WELFARE_SERVICECD_MST( \
    SERVICE_CENTERCD        VARCHAR(10)   NOT NULL, \
    SERVICE_CENTERCD_EDABAN VARCHAR(2)    NOT NULL, \
    SERVICECD               VARCHAR(2)    NOT NULL, \
    REGISTERCD              VARCHAR(8), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \ 
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE WELFARE_SERVICECD_MST ADD CONSTRAINT PK_WEL_SCD_MST PRIMARY KEY (SERVICE_CENTERCD, SERVICE_CENTERCD_EDABAN, SERVICECD)