-- $Id: rep-entexam_natpubpri_mst.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE ENTEXAM_NATPUBPRI_MST_OLD
RENAME TABLE ENTEXAM_NATPUBPRI_MST TO ENTEXAM_NATPUBPRI_MST_OLD
CREATE TABLE ENTEXAM_NATPUBPRI_MST( \
    NATPUBPRI_CD   VARCHAR(1)    NOT NULL, \
    NATPUBPRI_NAME VARCHAR(9)    NOT NULL, \
    NATPUBPRI_ABBV VARCHAR(9), \
    REGISTERCD     VARCHAR(8), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO ENTEXAM_NATPUBPRI_MST \
    SELECT \
        substr(NATPUBPRI_CD,2,1) AS NATPUBPRI_CD, \
        NATPUBPRI_NAME, \
        NATPUBPRI_ABBV, \
        REGISTERCD, \
        UPDATED \
    FROM \
        ENTEXAM_NATPUBPRI_MST_OLD

ALTER TABLE ENTEXAM_NATPUBPRI_MST ADD CONSTRAINT PK_ENTEXAM_NAT_MST PRIMARY KEY (NATPUBPRI_CD)