-- $Id: rep-entexam_hall_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE ENTEXAM_HALL_DAT_OLD
RENAME TABLE ENTEXAM_HALL_DAT TO ENTEXAM_HALL_DAT_OLD
CREATE TABLE ENTEXAM_HALL_DAT( \
    APPLICANTDIV  VARCHAR(1)    NOT NULL, \
    TESTDIV       VARCHAR(1)    NOT NULL, \
    EXAM_TYPE     VARCHAR(1)    NOT NULL, \
    EXAMHALLCD    VARCHAR(4)    NOT NULL, \
    EXAMHALL_NAME VARCHAR(30), \
    CAPA_CNT      SMALLINT, \
    S_RECEPTNO    VARCHAR(5), \
    E_RECEPTNO    VARCHAR(5), \
    REGISTERCD    VARCHAR(8), \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO ENTEXAM_HALL_DAT \
    SELECT \
        '1' AS APPLICANTDIV, \
        TESTDIV, \
        EXAM_TYPE, \
        EXAMHALLCD, \
        EXAMHALL_NAME, \
        CAPA_CNT, \
        S_RECEPTNO, \
        E_RECEPTNO, \
        REGISTERCD, \
        UPDATED \
    FROM \
        ENTEXAM_HALL_DAT_OLD

ALTER TABLE ENTEXAM_HALL_DAT ADD CONSTRAINT PK_ENTEXAM_HALL PRIMARY KEY (APPLICANTDIV,TESTDIV,EXAM_TYPE,EXAMHALLCD)