DROP TABLE SCHREG_RECOMMENDATION_WISH_DAT
CREATE TABLE SCHREG_RECOMMENDATION_WISH_DAT( \
    YEAR               VARCHAR(4)    NOT NULL, \
    SCHREGNO           VARCHAR(8)    NOT NULL, \
    WISH_RANK          VARCHAR(2)    NOT NULL, \
    SCHOOL_CD          VARCHAR(8)    NOT NULL, \
    BU_CD              VARCHAR(2), \
    KA_CD              VARCHAR(1), \
    RECOMMENDATION_FLG VARCHAR(1), \
    REGISTERCD         VARCHAR(8), \
    UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS
ALTER TABLE SCHREG_RECOMMENDATION_WISH_DAT ADD CONSTRAINT PK_SCHREG_REC_WISH PRIMARY KEY (YEAR,SCHREGNO,WISH_RANK)