-- $Id: entexam_applicanthope_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE ENTEXAM_APPLICANTHOPE_DAT
CREATE TABLE ENTEXAM_APPLICANTHOPE_DAT( \
    ENTEXAMYEAR    VARCHAR(4)    NOT NULL, \
    EXAMNO         VARCHAR(5)    NOT NULL, \
    TESTSUBCLASSCD VARCHAR(1)    NOT NULL, \
    HOPEFLG        VARCHAR(1), \
    INC_HOPEFLG    VARCHAR(1), \
    REGISTERCD     VARCHAR(8), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_APPLICANTHOPE_DAT ADD CONSTRAINT PK_ENTEXAM_APP_DAT PRIMARY KEY (ENTEXAMYEAR,EXAMNO,TESTSUBCLASSCD)