-- $Id: entexam_control_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE ENTEXAM_CONTROL_DAT
CREATE TABLE ENTEXAM_CONTROL_DAT( \
    ENTEXAMYEAR    VARCHAR(4)    NOT NULL, \
    TESTSUBCLASSCD VARCHAR(1)    NOT NULL, \
    TESTPAPERCD    VARCHAR(1)    NOT NULL, \
    EXAMHALLCD     VARCHAR(4)    NOT NULL, \
    CONTROL_FLG    VARCHAR(1), \
    REGISTERCD     VARCHAR(8), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_CONTROL_DAT ADD CONSTRAINT PK_ENTEXAM_CON_DAT PRIMARY KEY (ENTEXAMYEAR,TESTSUBCLASSCD,TESTPAPERCD,EXAMHALLCD)