-- $Id: entexam_applicantdesire_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE ENTEXAM_APPLICANTDESIRE_DAT
CREATE TABLE ENTEXAM_APPLICANTDESIRE_DAT( \
    ENTEXAMYEAR         VARCHAR(4)    NOT NULL, \
    APPLICANTDIV        VARCHAR(1)    NOT NULL, \
    TESTDIV             VARCHAR(1)    NOT NULL, \
    EXAMNO              VARCHAR(5)    NOT NULL, \
    DESIREDIV           VARCHAR(1)    NOT NULL, \
    RECOM_KIND          VARCHAR(1), \
    SHDIV               VARCHAR(1), \
    REGISTERCD          VARCHAR(8), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_APPLICANTDESIRE_DAT ADD CONSTRAINT PK_ENTEXAM_APDESIR PRIMARY KEY (ENTEXAMYEAR, APPLICANTDIV, TESTDIV, EXAMNO)