-- $Id: entexam_applicantwish_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE ENTEXAM_APPLICANTWISH_DAT
CREATE TABLE ENTEXAM_APPLICANTWISH_DAT( \
    ENTEXAMYEAR VARCHAR(4)    NOT NULL, \
    EXAMNO      VARCHAR(5)    NOT NULL, \
    WISHNO      VARCHAR(1)    NOT NULL, \
    MAJORLCD    VARCHAR(2), \
    MAJORSCD    VARCHAR(1), \
    REGISTERCD  VARCHAR(8), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_APPLICANTWISH_DAT ADD CONSTRAINT PK_ENTEXAM_AW_DAT PRIMARY KEY (ENTEXAMYEAR,EXAMNO,WISHNO)