-- kanji=漢字
-- $Id: $

drop table ENTEXAM_TRANSFER_FORMS_WK_MST_OLD

rename table ENTEXAM_TRANSFER_FORMS_WK_MST to ENTEXAM_TRANSFER_FORMS_WK_MST_OLD

create table ENTEXAM_TRANSFER_FORMS_WK_MST( \
    ENTEXAMYEAR      VARCHAR(4)    NOT NULL, \
    APPLICANTDIV     VARCHAR(1)    NOT NULL, \
    PATTERN_CD       VARCHAR(3)    NOT NULL, \
    TOKUTAI_SELECT   VARCHAR(1)    NOT NULL, \
    PATTERN_NAME     VARCHAR(30)  , \
    PREF_NAME        VARCHAR(12)  , \
    ACCOUNT_NUMBER1  VARCHAR(5)   , \
    ACCOUNT_NUMBER2  VARCHAR(1)   , \
    ACCOUNT_NUMBER3  VARCHAR(7)   , \
    MEMBER           VARCHAR(30)  , \
    SUBJECT          VARCHAR(24)  , \
    COMMUNICATION    VARCHAR(360) , \
    TRANSFER_MONEY   INTEGER      , \
    REGISTERCD       VARCHAR(10)  , \
    UPDATED          TIMESTAMP     DEFAULT CURRENT TIMESTAMP \
 ) in usr1dms index in idx1dms

alter table ENTEXAM_TRANSFER_FORMS_WK_MST add constraint PK_ENTEXAM_TRANSFER_FORMS_WK_MST primary key (ENTEXAMYEAR,APPLICANTDIV,PATTERN_CD,TOKUTAI_SELECT)

insert into ENTEXAM_TRANSFER_FORMS_WK_MST( \
    ENTEXAMYEAR, \
    APPLICANTDIV, \
    PATTERN_CD, \
    TOKUTAI_SELECT, \
    PATTERN_NAME, \
    PREF_NAME, \
    ACCOUNT_NUMBER1, \
    ACCOUNT_NUMBER2, \
    ACCOUNT_NUMBER3, \
    MEMBER, \
    SUBJECT, \
    COMMUNICATION, \
    TRANSFER_MONEY, \
    REGISTERCD, \
    UPDATED \
 ) select  \
    ENTEXAMYEAR, \
    APPLICANTDIV, \
    PATTERN_CD, \
    '2' as TOKUTAI_SELECT, \
    PATTERN_NAME, \
    PREF_NAME, \
    ACCOUNT_NUMBER1, \
    ACCOUNT_NUMBER2, \
    ACCOUNT_NUMBER3, \
    MEMBER, \
    SUBJECT, \
    COMMUNICATION, \
    TRANSFER_MONEY, \
    REGISTERCD, \
    UPDATED \
 from ENTEXAM_TRANSFER_FORMS_WK_MST_OLD

