-- kanji=´Á»ú
DROP TABLE ENTEXAM_PASSINGMARK_MST_OLD
RENAME TABLE ENTEXAM_PASSINGMARK_MST TO ENTEXAM_PASSINGMARK_MST_OLD
CREATE TABLE ENTEXAM_PASSINGMARK_MST( \
    ENTEXAMYEAR          VARCHAR(4)    NOT NULL, \
    APPLICANTDIV         VARCHAR(1)    NOT NULL, \
    TESTDIV              VARCHAR(1)    NOT NULL, \
    EXAM_TYPE            VARCHAR(1)    NOT NULL, \
    SHDIV                VARCHAR(1)    NOT NULL, \
    COURSECD             VARCHAR(1)    NOT NULL, \
    MAJORCD              VARCHAR(3)    NOT NULL, \
    EXAMCOURSECD         VARCHAR(4)    NOT NULL, \
    BORDER_SCORE         SMALLINT, \
    SUCCESS_CNT          SMALLINT, \
    BACK_RATE            SMALLINT, \
    CAPA_CNT             SMALLINT, \
    BORDER_SCORE_CANDI   SMALLINT, \
    SUCCESS_CNT_CANDI    SMALLINT, \
    BORDER_DEVIATION     DECIMAL(4,1), \
    SUCCESS_CNT_SPECIAL  SMALLINT, \
    SUCCESS_CNT_SPECIAL2 SMALLINT, \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO ENTEXAM_PASSINGMARK_MST \
    SELECT \
        ENTEXAMYEAR, \
        APPLICANTDIV, \
        TESTDIV, \
        EXAM_TYPE, \
        SHDIV, \
        COURSECD, \
        MAJORCD, \
        EXAMCOURSECD, \
        BORDER_SCORE, \
        SUCCESS_CNT, \
        BACK_RATE, \
        CAPA_CNT, \
        BORDER_SCORE_CANDI, \
        SUCCESS_CNT_CANDI, \
        BORDER_DEVIATION, \
        CAST(NULL AS SMALLINT) AS SUCCESS_CNT_SPECIAL, \
        CAST(NULL AS SMALLINT) AS SUCCESS_CNT_SPECIAL2, \
        REGISTERCD, \
        UPDATED \
    FROM \
        ENTEXAM_PASSINGMARK_MST_OLD

ALTER TABLE ENTEXAM_PASSINGMARK_MST ADD CONSTRAINT PK_ENTEXAM_PASS PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,EXAM_TYPE,SHDIV,COURSECD,MAJORCD,EXAMCOURSECD)