-- $Id: rep-entexam_interview_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE ENTEXAM_INTERVIEW_DAT_OLD
RENAME TABLE ENTEXAM_INTERVIEW_DAT TO ENTEXAM_INTERVIEW_DAT_OLD
CREATE TABLE ENTEXAM_INTERVIEW_DAT( \
    ENTEXAMYEAR               VARCHAR(4)    NOT NULL, \
    APPLICANTDIV              VARCHAR(1)    NOT NULL, \
    TESTDIV                   VARCHAR(1)    NOT NULL, \
    EXAMNO                    VARCHAR(5)    NOT NULL, \
    INTERVIEW_REMARK          VARCHAR(210), \
    INTERVIEW_VALUE           VARCHAR(1), \
    COMPOSITION_VALUE         VARCHAR(1), \
    INTERVIEW_A               VARCHAR(1), \
    INTERVIEW_B               VARCHAR(1), \
    INTERVIEW_C               VARCHAR(1), \
    INTERVIEW_REMARK2         VARCHAR(210), \
    INTERVIEW_VALUE2          VARCHAR(1), \
    INTERVIEW_REMARK3         VARCHAR(210), \
    REGISTERCD                VARCHAR(8), \
    UPDATED                   TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO ENTEXAM_INTERVIEW_DAT \
    SELECT \
        ENTEXAMYEAR, \
        APPLICANTDIV, \
        TESTDIV, \
        EXAMNO, \
        INTERVIEW_REMARK, \
        INTERVIEW_VALUE, \
        COMPOSITION_VALUE, \
        CAST(NULL AS VARCHAR(1)) AS INTERVIEW_A, \
        CAST(NULL AS VARCHAR(1)) AS INTERVIEW_B, \
        CAST(NULL AS VARCHAR(1)) AS INTERVIEW_C, \
        CAST(NULL AS VARCHAR(210)) AS INTERVIEW_REMARK2, \
        CAST(NULL AS VARCHAR(1)) AS INTERVIEW_VALUE2, \
        CAST(NULL AS VARCHAR(210)) AS INTERVIEW_REMARK3, \
        REGISTERCD, \
        UPDATED \
    FROM \
        ENTEXAM_INTERVIEW_DAT_OLD

ALTER TABLE ENTEXAM_INTERVIEW_DAT ADD CONSTRAINT PK_ENTEXAM_INTERVI PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,EXAMNO)