-- $Id: reduction_country_add_mst.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE REDUCTION_COUNTRY_ADD_MST

CREATE TABLE REDUCTION_COUNTRY_ADD_MST( \
    YEAR                VARCHAR(4)    NOT NULL, \
    GRADE               VARCHAR(2)    NOT NULL, \
    REDUCTION_SEQ       INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ,MINVALUE 1, NO MAXVALUE, NO CYCLE, NO CACHE, ORDER), \
    REDUCTION_ADD_MONEY INTEGER, \
    INCOME_LOW          INTEGER, \
    INCOME_HIGH         INTEGER, \
    REDUCTIONREMARK     VARCHAR(75), \
    REGISTERCD          VARCHAR(8), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE REDUCTION_COUNTRY_ADD_MST ADD CONSTRAINT PK_REDUCTION_CA_M PRIMARY KEY (YEAR, GRADE, REDUCTION_SEQ)
