-- kanji=´Á»ú
-- $Id: rep-expense_grp_s_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

drop table EXPENSE_GRP_S_DAT_OLD
create table EXPENSE_GRP_S_DAT_OLD like EXPENSE_GRP_S_DAT
insert into EXPENSE_GRP_S_DAT_OLD select * from EXPENSE_GRP_S_DAT

DROP TABLE EXPENSE_GRP_S_DAT

CREATE TABLE EXPENSE_GRP_S_DAT \
( \
        "YEAR"            VARCHAR(4) NOT NULL, \
        "EXPENSE_GRP_CD"  VARCHAR(4) NOT NULL, \
        "EXPENSE_M_CD"    VARCHAR(2) NOT NULL, \
        "EXPENSE_S_CD"    VARCHAR(2) NOT NULL, \
        "REGISTERCD"      VARCHAR(8), \
        "UPDATED"         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EXPENSE_GRP_S_DAT ADD CONSTRAINT PK_EXP_GRP_S_DAT PRIMARY KEY (YEAR,EXPENSE_GRP_CD,EXPENSE_M_CD,EXPENSE_S_CD)

insert into EXPENSE_GRP_S_DAT \
select \
    t1.YEAR, \
    t1.EXPENSE_GRP_CD, \
    t2.EXPENSE_M_CD, \
    t1.EXPENSE_S_CD, \
    t1.REGISTERCD, \
    t1.UPDATED \
from \
    EXPENSE_GRP_S_DAT_OLD t1 \
    left join EXPENSE_S_MST_OLD t2 on t1.YEAR = t2.YEAR AND t1.EXPENSE_S_CD = t2.EXPENSE_S_CD
