-- $Id: rep-reduction_authorize_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE REDUCTION_AUTHORIZE_DAT_OLD
CREATE TABLE REDUCTION_AUTHORIZE_DAT_OLD LIKE REDUCTION_AUTHORIZE_DAT
INSERT INTO REDUCTION_AUTHORIZE_DAT_OLD SELECT * FROM REDUCTION_AUTHORIZE_DAT

DROP TABLE REDUCTION_AUTHORIZE_DAT

CREATE TABLE REDUCTION_AUTHORIZE_DAT( \
    SCHREGNO                VARCHAR(8)    NOT NULL, \
    DATA_DIV                VARCHAR(1)    NOT NULL, \
    DATA_DIV_SUB            VARCHAR(1)    NOT NULL, \
    RENBAN                  VARCHAR(4), \
    PASSNO                  VARCHAR(16), \
    STATUS                  VARCHAR(2), \
    REASON                  VARCHAR(450), \
    DIS_APPLY_MONTH         VARCHAR(2), \
    RECEIVE_MONEY           INTEGER, \
    SUP_LIMIT_MONTH         VARCHAR(2), \
    LIMIT_CREDIT            VARCHAR(3), \
    REMARK                  VARCHAR(450), \
    APPLY_DATE              DATE, \
    DECIDE_DATE             DATE, \
    BEGIN_YEARMONTH         VARCHAR(6), \
    REMAIN_SUP_LIMIT_MONTH  VARCHAR(2), \
    REGISTERCD              VARCHAR(8), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE REDUCTION_AUTHORIZE_DAT ADD CONSTRAINT PK_REDUC_AUTH_DAT PRIMARY KEY (SCHREGNO, DATA_DIV, DATA_DIV_SUB)

INSERT INTO \
REDUCTION_AUTHORIZE_DAT \
( \
SELECT \
    SCHREGNO, \
    '1' AS DATA_DIV, \
    '1' AS DATA_DIV_SUB, \
    CASE WHEN PASSNO IS NOT NULL \
         THEN CAST(RIGHT(PASSNO, 4) AS VARCHAR(4)) \
         ELSE NULL \
    END AS RENBAN, \
    PASSNO, \
    STATUS, \
    REASON, \
    DIS_APPLY_MONTH, \
    RECEIVE_MONEY, \
    SUP_LIMIT_MONTH, \
    LIMIT_CREDIT, \
    REMARK, \
    APPLY_DATE, \
    DECIDE_DATE, \
    BEGIN_YEARMONTH, \
    REMAIN_SUP_LIMIT_MONTH, \
    REGISTERCD, \
    UPDATED \
FROM \
    REDUCTION_AUTHORIZE_DAT_OLD \
)

