-- $Id: 73499d4b956deb270af7a933686443ca2a443b08 $

DROP TABLE DOCUMENT_MST
CREATE TABLE DOCUMENT_MST( \
    DOCUMENTCD                VARCHAR(2)    NOT NULL, \
    TITLE                     VARCHAR(120)  , \
    TEXT                      VARCHAR(1600) , \
    FOOTNOTE                  VARCHAR(1600) , \
    REGISTERCD                VARCHAR(10), \
    UPDATED                   TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE DOCUMENT_MST ADD CONSTRAINT PK_DOCUMENT_DAT PRIMARY KEY (DOCUMENTCD)