-- $Id: $

DROP TABLE ENTEXAM_STD_HALL_MST
CREATE TABLE ENTEXAM_STD_HALL_MST( \
    YEAR                VARCHAR(4)    NOT NULL, \
    PLACE_ID            VARCHAR(4)    NOT NULL, \
    PLACE_NAME          VARCHAR(60)   , \
    SEATS               SMALLINT      , \
    REGISTERCD          VARCHAR(10)   , \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS
ALTER TABLE ENTEXAM_STD_HALL_MST ADD CONSTRAINT PK_ENTEXAM_STD_HALL_MST PRIMARY KEY (YEAR, PLACE_ID)
