-- $Id: $

DROP TABLE ENTEXAM_STD_RECEPT_DAT
CREATE TABLE ENTEXAM_STD_RECEPT_DAT( \
    YEAR                VARCHAR(4)    NOT NULL, \
    EXAMNO              VARCHAR(8)    NOT NULL, \
    EXAM_SCHOOL_KIND    VARCHAR(2)    NOT NULL, \
    APPLICANT_DIV       VARCHAR(2)    NOT NULL, \
    COURSE_DIV          VARCHAR(4)    NOT NULL, \
    FREQUENCY           VARCHAR(2)    NOT NULL, \
    RECEPTNO            VARCHAR(4)    NOT NULL, \
    JUDGEMENT           VARCHAR(1)    , \
    SUC_COURSECD        VARCHAR(1)    , \
    SUC_MAJORCD         VARCHAR(3)    , \
    SUC_COURSECODE      VARCHAR(4)    , \
    REGISTERCD          VARCHAR(10)   , \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS
ALTER TABLE ENTEXAM_STD_RECEPT_DAT ADD CONSTRAINT PK_ENTEXAM_STD_RECEPT_DAT PRIMARY KEY (YEAR, EXAMNO, EXAM_SCHOOL_KIND, APPLICANT_DIV, COURSE_DIV, FREQUENCY, RECEPTNO)
