-- kanji=漢字
-- $Id: 201aa2f26f05ea075de9dd3eecb39f8a7bffe060 $

DROP TABLE ENTEXAM_TESTDIV_MST

CREATE TABLE ENTEXAM_TESTDIV_MST \
( \
    ENTEXAMYEAR         VARCHAR(4)  NOT NULL, \
    APPLICANTDIV        VARCHAR(1)  NOT NULL, \
    TESTDIV             VARCHAR(2)  NOT NULL, \
    TESTDIV_NAME        VARCHAR(60), \
    TESTDIV_ABBV        VARCHAR(30), \
    INTERVIEW_DIV       VARCHAR(1), \
    CAPACITY            SMALLINT, \
    TEST_DATE           DATE, \
    TEST_DATE1          VARCHAR(30), \
    TEST_DATE2          VARCHAR(30), \
    PROCEDURE_DATE1     VARCHAR(30), \
    PROCEDURE_DATE2     VARCHAR(30), \
    DEFAULT_FLG         VARCHAR(1), \
    KIKOKU_FLG          VARCHAR(1), \
    PRETEST_FLG         VARCHAR(1), \
    SHOWORDER           SMALLINT, \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_TESTDIV_MST ADD CONSTRAINT PK_ENTEXAM_TESTDIV PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV)
