-- $Id: 395151e517a9b5e315427ddcc76d38a8e79d014d $

DROP TABLE ENTEXAM_SCH_PTRN_HDAT
CREATE TABLE ENTEXAM_SCH_PTRN_HDAT( \
    ENTEXAMYEAR    VARCHAR(4)    NOT NULL, \
    APPLICANTDIV   VARCHAR(1)    NOT NULL, \
    TESTDIV        VARCHAR(2)    NOT NULL, \
    PATTERN_NO     VARCHAR(1)    NOT NULL, \
    PATTERN_NAME   VARCHAR(60), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_SCH_PTRN_HDAT ADD CONSTRAINT PK_ENT_SCH_PTN_HDT PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,PATTERN_NO)