DROP TABLE ENTEXAM_PAYMENT_EXEMPTION_MST

CREATE TABLE ENTEXAM_PAYMENT_EXEMPTION_MST \
( \
    ENTEXAMYEAR         VARCHAR(4) NOT NULL, \
    APPLICANTDIV        VARCHAR(1) NOT NULL, \
    DIV                 VARCHAR(1) NOT NULL, \
    ITEM_CD             VARCHAR(2) NOT NULL, \
    KIND_CD             VARCHAR(1) NOT NULL, \
    EXEMPTION_CD        VARCHAR(2) NOT NULL, \
    EXEMPTION_MONEY     INTEGER, \
    REGISTERCD          VARCHAR(10),  \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_PAYMENT_EXEMPTION_MST ADD CONSTRAINT PK_ENTEXAM_PAY_E_M PRIMARY KEY (ENTEXAMYEAR, APPLICANTDIV, DIV, ITEM_CD, KIND_CD, EXEMPTION_CD)
