-- KANJI=´Á»ú
-- $ID: $

DROP TABLE ENTEXAM_HALL_DAT

CREATE TABLE ENTEXAM_HALL_DAT ( \
    TESTDIV                 VARCHAR(2)  NOT NULL, \
    EXAM_TYPE               VARCHAR(2)  NOT NULL, \
    EXAMHALLCD              VARCHAR(4)  NOT NULL, \
    EXAMHALL_NAME           VARCHAR(30) , \
    EXAMHALL_ABBV           VARCHAR(30) , \
    CAPA_CNT                INTEGER , \
    S_RECEPTNO              VARCHAR(10) , \
    E_RECEPTNO              VARCHAR(10) , \
    REGISTERCD              VARCHAR(10) , \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_HALL_DAT ADD CONSTRAINT PK_ENTEXAM_HALL \
      PRIMARY KEY (TESTDIV, EXAM_TYPE, EXAMHALLCD)