
DROP TABLE ENTEXAM_JUDGE_TMP
CREATE TABLE ENTEXAM_JUDGE_TMP( \
    ENTEXAMYEAR     VARCHAR(4)    NOT NULL, \
    APPLICANTDIV    VARCHAR(1)    NOT NULL, \
    TESTDIV         VARCHAR(2)    NOT NULL, \
    EXAM_TYPE       VARCHAR(2)    NOT NULL, \
    RECEPTNO        VARCHAR(10)   NOT NULL, \
    EXAMNO          VARCHAR(10)   NOT NULL, \
    JUDGE_SHDIV      VARCHAR(1), \
    JUDGE_COURSECD   VARCHAR(1), \
    JUDGE_MAJORCD    VARCHAR(3), \
    JUDGE_COURSECODE VARCHAR(4), \
    JUDGE_EXAM_TYPE VARCHAR(2), \
    JUDGEDIV        VARCHAR(1), \
    SENGAN_JUDGEDIV  VARCHAR(1), \
    HEIGAN_JUDGEDIV  VARCHAR(1), \
    REGISTERCD       VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    NAIDAKU_FLG     VARCHAR(1) \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_JUDGE_TMP ADD CONSTRAINT PK_ENTEXAM_JUDGE PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,EXAM_TYPE,RECEPTNO)