-- $Id: 0ea70e81cc7f4aae6e292a83d3af129ac490a49c $

DROP TABLE ENTEXAM_PERFECT_MST
CREATE TABLE ENTEXAM_PERFECT_MST( \
    ENTEXAMYEAR    VARCHAR(4)    NOT NULL, \
    APPLICANTDIV   VARCHAR(1)    NOT NULL, \
    TESTDIV        VARCHAR(2)    NOT NULL, \
    COURSECD       VARCHAR(1)    NOT NULL, \
    MAJORCD        VARCHAR(3)    NOT NULL, \
    EXAMCOURSECD   VARCHAR(4)    NOT NULL, \
    TESTSUBCLASSCD VARCHAR(2)    NOT NULL, \
    PERFECT        SMALLINT, \
    RATE           SMALLINT, \
    MAGNIFYING     DECIMAL(2,1), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_PERFECT_MST ADD CONSTRAINT PK_ENTEXAM_PERF PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,COURSECD,MAJORCD,EXAMCOURSECD,TESTSUBCLASSCD)
