-- $Id: $

DROP TABLE ENTEXAM_STD_PERFECT_MST
CREATE TABLE ENTEXAM_STD_PERFECT_MST( \
    YEAR                VARCHAR(4)    NOT NULL, \
    EXAM_SCHOOL_KIND    VARCHAR(2)    NOT NULL, \
    APPLICANT_DIV       VARCHAR(2)    NOT NULL, \
    COURSE_DIV          VARCHAR(4)    NOT NULL, \
    FREQUENCY           VARCHAR(2)    NOT NULL, \
    EXAM_SUBCLASS       VARCHAR(2)    NOT NULL, \
    STEPS               VARCHAR(3)    NOT NULL, \
    LABEL               VARCHAR(2)    , \
    VALUE               VARCHAR(3)    , \
    REGISTERCD          VARCHAR(10)   , \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS
ALTER TABLE ENTEXAM_STD_PERFECT_MST ADD CONSTRAINT PK_ENTEXAM_STD_PERFECT_MST PRIMARY KEY (YEAR, EXAM_SCHOOL_KIND, APPLICANT_DIV, COURSE_DIV, FREQUENCY, EXAM_SUBCLASS, STEPS)
