-- $Id: 68d245f7a9b32ab65489de1bf074704983d9d382 $

DROP TABLE ENTEXAM_APPLICANTDESIRE_DAT
CREATE TABLE ENTEXAM_APPLICANTDESIRE_DAT( \
    ENTEXAMYEAR         VARCHAR(4)    NOT NULL, \
    APPLICANTDIV        VARCHAR(1)    NOT NULL, \
    TESTDIV             VARCHAR(2)    NOT NULL, \
    EXAMNO              VARCHAR(10)   NOT NULL, \
    DESIREDIV           VARCHAR(1)    NOT NULL, \
    RECOM_KIND          VARCHAR(1), \
    SHDIV               VARCHAR(1), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_APPLICANTDESIRE_DAT ADD CONSTRAINT PK_ENTEXAM_APDESIR PRIMARY KEY (ENTEXAMYEAR, APPLICANTDIV, TESTDIV, EXAMNO)