-- $Id: dd77c03d0e8a28400ca006648f97fcd31105d43f $

DROP TABLE ENTEXAM_APPLICANTACTIVITY_DAT
CREATE TABLE ENTEXAM_APPLICANTACTIVITY_DAT( \
    ENTEXAMYEAR         VARCHAR(4)    NOT NULL, \
    APPLICANTDIV        VARCHAR(1)    NOT NULL, \
    EXAMNO              VARCHAR(10)   NOT NULL, \
    ACTIVITY            VARCHAR(60), \
    RESULTS             VARCHAR(240), \
    SECTION             VARCHAR(60), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_APPLICANTACTIVITY_DAT ADD CONSTRAINT PK_ENTEXAM_APACTIV PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,EXAMNO)