-- $Id: 6f13014bfd8d5a35a6bd71915b0161b1643e3962 $
drop table ENTEXAM_APPLICANTBASE_PRE_DAT

CREATE TABLE ENTEXAM_APPLICANTBASE_PRE_DAT( \
    ENTEXAMYEAR    VARCHAR(4)    NOT NULL, \
    APPLICANTDIV   VARCHAR(1)    NOT NULL, \
    PRE_RECEPTNO   VARCHAR(10)   NOT NULL, \
    PRE_TESTDIV    VARCHAR(2)    NOT NULL, \
    PRE_EXAM_TYPE  VARCHAR(2), \
    PRE_RECEPTDIV  VARCHAR(1), \
    PRE_RECEPTDATE DATE, \
    NAME           VARCHAR(60), \
    NAME_KANA      VARCHAR(120), \
    SEX            VARCHAR(1), \
    GNAME          VARCHAR(60), \
    GKANA          VARCHAR(120), \
    ZIPCD          VARCHAR(8), \
    ADDRESS1       VARCHAR(75), \
    ADDRESS2       VARCHAR(75), \
    TELNO          VARCHAR(14), \
    FS_CD          VARCHAR(7), \
    PS_CD          VARCHAR(7), \
    PS_CONTACT     VARCHAR(1), \
    BUS_USE        VARCHAR(1), \
    STATIONDIV     VARCHAR(1), \
    BUS_USER_COUNT SMALLINT, \
    REMARK         VARCHAR(45), \
    RECOM_EXAMNO   VARCHAR(10), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_APPLICANTBASE_PRE_DAT ADD CONSTRAINT PK_ENTEXAM_APP_PRE PRIMARY KEY (ENTEXAMYEAR,PRE_RECEPTNO)
