-- KANJI=´Á»ú
-- $ID: $

DROP TABLE ENTEXAM_APPLICANTCONS_DAT

CREATE TABLE ENTEXAM_APPLICANTCONS_DAT ( \
    ENTEXAMYEAR             VARCHAR(4)  NOT NULL, \
    APPLICANTDIV            VARCHAR(1)  NOT NULL, \
    TESTDIV                 VARCHAR(2)  NOT NULL, \
    EXAMNO                  VARCHAR(10) NOT NULL, \
    SHDIV                   VARCHAR(1)  NOT NULL, \
    COURSECD                VARCHAR(1)  NOT NULL, \
    MAJORCD                 VARCHAR(3)  NOT NULL, \
    EXAMCOURSECD            VARCHAR(4)  NOT NULL, \
    JUDGEMENT               VARCHAR(1)  , \
    REGISTERCD              VARCHAR(10) , \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_APPLICANTCONS_DAT ADD CONSTRAINT PK_ENTEXAM_APCNS \
      PRIMARY KEY (ENTEXAMYEAR, APPLICANTDIV, TESTDIV, EXAMNO, SHDIV, COURSECD, MAJORCD, EXAMCOURSECD)