-- $Id: 83d4b775327882458dce42e933e5ea2de01491c5 $

DROP TABLE ENTEXAM_HALL_LIST_YDAT
CREATE TABLE ENTEXAM_HALL_LIST_YDAT( \
    ENTEXAMYEAR   VARCHAR(4)    NOT NULL, \
    APPLICANTDIV  VARCHAR(1)    NOT NULL, \
    TESTDIV       VARCHAR(2)    NOT NULL, \
    EXAM_TYPE     VARCHAR(2)    NOT NULL, \
    EXAMHALLCD    VARCHAR(4)    NOT NULL, \
    RECEPTNO      VARCHAR(10)   NOT NULL, \
    REGISTERCD    VARCHAR(10), \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_HALL_LIST_YDAT ADD CONSTRAINT PK_ENTEXAM_HAL_L_Y PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,EXAM_TYPE,EXAMHALLCD,RECEPTNO)