DROP TABLE ENTEXAM_PAYMENT_ITEM_MST

CREATE TABLE ENTEXAM_PAYMENT_ITEM_MST \
( \
    ENTEXAMYEAR         VARCHAR(4) NOT NULL, \
    APPLICANTDIV        VARCHAR(1) NOT NULL, \
    DIV                 VARCHAR(1) NOT NULL, \
    ITEM_CD             VARCHAR(2) NOT NULL, \
    ITEM_NAME           VARCHAR(60),  \
    ITEM_MONEY          INTEGER, \
    REMARK1             VARCHAR(2), \
    REMARK2             VARCHAR(2), \
    REMARK3             VARCHAR(2), \
    REMARK4             VARCHAR(2), \
    REMARK5             VARCHAR(2), \
    REMARK6             VARCHAR(150), \
    REMARK7             VARCHAR(150), \
    REMARK8             VARCHAR(150), \
    REMARK9             VARCHAR(150), \
    REMARK10            VARCHAR(150), \
    REGISTERCD          VARCHAR(10),  \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_PAYMENT_ITEM_MST ADD CONSTRAINT PK_ENTEXAM_PAY_I_M PRIMARY KEY (ENTEXAMYEAR, APPLICANTDIV, DIV, ITEM_CD)
