-- $Id: $

DROP TABLE ENTEXAM_RECRUIT_ADVICE_DETAIL_DAT
CREATE TABLE ENTEXAM_RECRUIT_ADVICE_DETAIL_DAT( \
    ENTEXAMYEAR         VARCHAR(4)    NOT NULL, \
    EXAMNO              VARCHAR(10)   NOT NULL, \
    SEQ                 VARCHAR(3)    NOT NULL, \
    REMARK1             VARCHAR(310)  , \
    REMARK2             VARCHAR(310)  , \
    REMARK3             VARCHAR(310)  , \
    REMARK4             VARCHAR(750)  , \
    REMARK5             VARCHAR(750)  , \
    REMARK6             VARCHAR(750)  , \
    REMARK7             VARCHAR(150)  , \
    REMARK8             VARCHAR(150)  , \
    REMARK9             VARCHAR(150)  , \
    REMARK10            VARCHAR(150)  , \
    REMARK11            VARCHAR(150)  , \
    REMARK12            VARCHAR(150)  , \
    REGISTERCD          VARCHAR(10)   , \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS
ALTER TABLE ENTEXAM_RECRUIT_ADVICE_DETAIL_DAT ADD CONSTRAINT PK_ENTEXAM_RECRUIT_ADVICE_DETAIL_DAT PRIMARY KEY (ENTEXAMYEAR, EXAMNO, SEQ)
