-- $Id: 18ecc70cc23141f782954a8c76c58c8748624da9 $

DROP TABLE ENTEXAM_SAKUBUN_DAT

CREATE TABLE ENTEXAM_SAKUBUN_DAT( \
    ENTEXAMYEAR         VARCHAR(4)    NOT NULL, \
    APPLICANTDIV        VARCHAR(1)    NOT NULL, \
    TESTDIV             VARCHAR(2)    NOT NULL, \
    EXAMNO              VARCHAR(10)   NOT NULL, \
    TOTAL               SMALLINT, \
    SCORE1              SMALLINT, \
    SCORE2              SMALLINT, \
    SCORE3              SMALLINT, \
    VALUE1              VARCHAR(10), \
    VALUE2              VARCHAR(10), \
    VALUE3              VARCHAR(10), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_SAKUBUN_DAT ADD CONSTRAINT PK_ENTEXAM_SAKUBUN PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,EXAMNO)