-- KANJI=´Á»ú
-- $ID: $

DROP TABLE ENTEXAM_DESIRE_DAT

CREATE TABLE ENTEXAM_DESIRE_DAT ( \
    ENTEXAMYEAR             VARCHAR(4)  NOT NULL, \
    APPLICANTDIV            VARCHAR(1)  NOT NULL, \
    TESTDIV                 VARCHAR(2)  NOT NULL, \
    EXAMNO                  VARCHAR(10) NOT NULL, \
    APPLICANT_DIV           VARCHAR(1)  , \
    EXAMINEE_DIV            VARCHAR(1)  , \
    REGISTERCD              VARCHAR(10) , \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_DESIRE_DAT ADD CONSTRAINT PK_ENTEXAM_DESIRE \
      PRIMARY KEY (ENTEXAMYEAR, APPLICANTDIV, TESTDIV, EXAMNO)