-- $Id: $

DROP TABLE ENTEXAM_RECRUIT_ADVICE_DAT
CREATE TABLE ENTEXAM_RECRUIT_ADVICE_DAT( \
    ENTEXAMYEAR         VARCHAR(4)    NOT NULL, \
    EXAMNO              VARCHAR(10)   NOT NULL, \
    STAFFCD             VARCHAR(10)   , \
    FS_CD               VARCHAR(12)   , \
    FS_AREA_CD          VARCHAR(12)   , \
    NAME                VARCHAR(120)  , \
    EXCLUSION           VARCHAR(1)    , \
    REGISTERCD          VARCHAR(10)   , \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS
ALTER TABLE ENTEXAM_RECRUIT_ADVICE_DAT ADD CONSTRAINT PK_ENTEXAM_RECRUIT_ADVICE_DAT PRIMARY KEY (ENTEXAMYEAR, EXAMNO)
