-- $Id: $

DROP TABLE ENTEXAM_STD_MST
CREATE TABLE ENTEXAM_STD_MST( \
    YEAR                VARCHAR(4)    NOT NULL, \
    EXAM_SCHOOL_KIND    VARCHAR(2)    NOT NULL, \
    APPLICANT_DIV       VARCHAR(2)    NOT NULL, \
    COURSE_DIV          VARCHAR(4)    NOT NULL, \
    FREQUENCY           VARCHAR(2)    NOT NULL, \
    EXAM_NAME           VARCHAR(60)   , \
    EXAM_DATE           DATE          , \
    AM_PM               VARCHAR(1)    , \
    EXAM_NO_BAND        VARCHAR(5)    , \
    REGISTERCD          VARCHAR(10)   , \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS
ALTER TABLE ENTEXAM_STD_MST ADD CONSTRAINT PK_ENTEXAM_STD_MST PRIMARY KEY (YEAR, EXAM_SCHOOL_KIND, APPLICANT_DIV, COURSE_DIV, FREQUENCY)
