-- kanji=漢字
-- $Id: d1b6580202c4b4160238066994a1775d2d61ac6e $

DROP TABLE ENTEXAM_CLASSIFY_MST

CREATE TABLE ENTEXAM_CLASSIFY_MST \
( \
    ENTEXAMYEAR         VARCHAR(4)  NOT NULL, \
    APPLICANTDIV        VARCHAR(1)  NOT NULL, \
    CLASSIFY_CD         VARCHAR(2)  NOT NULL, \
    CLASSIFY_NAME       VARCHAR(30), \
    MARK                VARCHAR(2), \
    PLUS_POINT          VARCHAR(3), \
    COMMITMENT_FLG      VARCHAR(1), \
    CALC_FLG            VARCHAR(1), \
    ORDER               SMALLINT, \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_CLASSIFY_MST ADD CONSTRAINT PK_ENTEXAM_CLASSIFY_MST PRIMARY KEY (ENTEXAMYEAR, APPLICANTDIV, CLASSIFY_CD)
