-- $Id: $

DROP TABLE ENTEXAM_STD_RANK_DAT
CREATE TABLE ENTEXAM_STD_RANK_DAT( \
    YEAR                VARCHAR(4)    NOT NULL, \
    RECEPTNO            VARCHAR(4)    NOT NULL, \
    EXAM_SUBCLASS       VARCHAR(2)    NOT NULL, \
    SUMMARY_DIV         VARCHAR(2)    NOT NULL, \
    EXAM_SCORE          DECIMAL(5,2)  , \
    REGISTERCD          VARCHAR(10)   , \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS
ALTER TABLE ENTEXAM_STD_RANK_DAT ADD CONSTRAINT PK_ENTEXAM_STD_RANK_DAT PRIMARY KEY (YEAR, RECEPTNO, EXAM_SUBCLASS, SUMMARY_DIV)
