-- $Id: c40a9c6d30da131cd741ed83ad8dd1c3654abfc8 $

DROP TABLE ENTEXAM_HALL_YDAT
CREATE TABLE ENTEXAM_HALL_YDAT( \
    ENTEXAMYEAR   VARCHAR(4)    NOT NULL, \
    APPLICANTDIV  VARCHAR(1)    NOT NULL, \
    TESTDIV       VARCHAR(2)    NOT NULL, \
    EXAM_TYPE     VARCHAR(2)    NOT NULL, \
    EXAMHALLCD    VARCHAR(4)    NOT NULL, \
    EXAMHALL_NAME VARCHAR(30), \
    EXAMHALL_ABBV VARCHAR(30), \
    CAPA_CNT      INTEGER , \
    S_RECEPTNO    VARCHAR(10), \
    E_RECEPTNO    VARCHAR(10), \
    REGISTERCD    VARCHAR(10), \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_HALL_YDAT ADD CONSTRAINT PK_ENTEXAM_HAL_Y PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,EXAM_TYPE,EXAMHALLCD)