-- $Id$

drop table ENTEXAM_TOKEI_HIGH_LOW_HISTORY_DAT

create table ENTEXAM_TOKEI_HIGH_LOW_HISTORY_DAT( \
    ENTEXAMYEAR     VARCHAR(4)   NOT NULL, \
    APPLICANTDIV    VARCHAR(1)   NOT NULL, \
    TESTDIV         VARCHAR(2)   NOT NULL, \
    SHDIV           VARCHAR(1)   NOT NULL, \
    COURSECODE      VARCHAR(4)   NOT NULL, \
    SEX             VARCHAR(1)   NOT NULL, \
    TESTSUBCLASSCD  VARCHAR(2)   NOT NULL, \
    HIGHSCORE       SMALLINT, \
    LOWSCORE        SMALLINT, \
    AVG             DECIMAL(4,1), \
    TOTAL           INTEGER, \
    COUNT           SMALLINT, \
    REGISTERCD      VARCHAR(10) , \
    UPDATED         TIMESTAMP    DEFAULT CURRENT TIMESTAMP \
 ) in usr1dms index in idx1dms

alter table ENTEXAM_TOKEI_HIGH_LOW_HISTORY_DAT add constraint PK_ENTEXAM_THLH_D primary key (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,SHDIV,COURSECODE,SEX,TESTSUBCLASSCD)
