-- KANJI=´Á»ú
-- $ID: $

DROP TABLE ENTEXAM_JUDGECOMP_MST

CREATE TABLE ENTEXAM_JUDGECOMP_MST ( \
    ENTEXAMYEAR             VARCHAR(4)  NOT NULL, \
    COURSECD                VARCHAR(1)  NOT NULL, \
    MAJORCD                 VARCHAR(3)  NOT NULL, \
    EXAMCOURSECD            VARCHAR(4)  NOT NULL, \
    SHDIV                   VARCHAR(1)  NOT NULL, \
    JUDGEMENT               VARCHAR(1)  NOT NULL, \
    CMP_COURSECD            VARCHAR(1)  NOT NULL, \
    CMP_MAJORCD             VARCHAR(3)  NOT NULL, \
    CMP_EXAMCOURSECD        VARCHAR(4)  NOT NULL, \
    S_JUDGEMENT             VARCHAR(1)  , \
    H_JUDGEMENT             VARCHAR(1)  , \
    REGISTERCD              VARCHAR(10) , \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_JUDGECOMP_MST ADD CONSTRAINT PK_ENTEXAM_JCMP \
      PRIMARY KEY (ENTEXAMYEAR, COURSECD, MAJORCD, EXAMCOURSECD, SHDIV, JUDGEMENT, CMP_COURSECD, CMP_MAJORCD, CMP_EXAMCOURSECD)