-- $Id: 829d43452e74a5b4c0a5265d7f809bd51b3dbf1b $

DROP TABLE ENTEXAM_PERFECT_PRE_MST
CREATE TABLE ENTEXAM_PERFECT_PRE_MST( \
    ENTEXAMYEAR    VARCHAR(4)    NOT NULL, \
    APPLICANTDIV   VARCHAR(1)    NOT NULL, \
    PRE_EXAM_TYPE  VARCHAR(2)    NOT NULL, \
    TESTSUBCLASSCD VARCHAR(1)    NOT NULL, \
    PERFECT        SMALLINT, \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_PERFECT_PRE_MST ADD CONSTRAINT PK_ENTEXAM_PER_PRE PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,PRE_EXAM_TYPE,TESTSUBCLASSCD)