-- $Id: 5ddfff2ca3e251682645ad028abe61cbe2ef4882 $

DROP TABLE ENTEXAM_KAIJI_DAT
CREATE TABLE ENTEXAM_KAIJI_DAT( \
    ENTEXAMYEAR        VARCHAR(4)    NOT NULL, \
    APPLICANTDIV       VARCHAR(1)    NOT NULL, \
    TESTDIV            VARCHAR(2)    NOT NULL, \
    EXAM_TYPE          VARCHAR(2)    NOT NULL, \
    RECEPTNO           VARCHAR(10)   NOT NULL, \
    KAIJI_SUBCLASSCD   VARCHAR(2)    NOT NULL, \
    SCORE              VARCHAR(4), \
    REGISTERCD         VARCHAR(10), \
    UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_KAIJI_DAT ADD CONSTRAINT PK_ENTEXAM_KAIJI PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,EXAM_TYPE,RECEPTNO,KAIJI_SUBCLASSCD)