DROP FUNCTION LAST_DAY

CREATE FUNCTION LAST_DAY (D Date) \
 RETURNS Date \
 SPECIFIC LAST_DAYOracle \
 LANGUAGE SQL \
 CONTAINS SQL \
 NO EXTERNAL ACTION \
 DETERMINISTIC \
 RETURN \
SELECT D - day(D) day \ 
FROM \
(Values (D + 1 month)) AS Q (D)
