-- $Id: 31245ee74c174573251f74a6c1daa3c83251da72 $

DROP TABLE ENTEXAM_JUDGE_TMP
CREATE TABLE ENTEXAM_JUDGE_TMP( \
    ENTEXAMYEAR     VARCHAR(4)    NOT NULL, \
    APPLICANTDIV    VARCHAR(1)    NOT NULL, \
    TESTDIV         VARCHAR(2)    NOT NULL, \
    EXAM_TYPE       VARCHAR(2)    NOT NULL, \
    RECEPTNO        VARCHAR(10)   NOT NULL, \
    EXAMNO          VARCHAR(10)   NOT NULL, \
    JUDGE_EXAM_TYPE VARCHAR(1), \
    JUDGEDIV        VARCHAR(1), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_JUDGE_TMP ADD CONSTRAINT PK_ENTEXAM_JUDGE PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,EXAM_TYPE,RECEPTNO)