-- $Id: ac2a14a15c17ece935acb01e6032eab8c63575a9 $

DROP TABLE ENTEXAM_PERFECT_MST
CREATE TABLE ENTEXAM_PERFECT_MST( \
    ENTEXAMYEAR    VARCHAR(4)    NOT NULL, \
    APPLICANTDIV   VARCHAR(1)    NOT NULL, \
    TESTDIV        VARCHAR(2)    NOT NULL, \
    COURSECD       VARCHAR(1)    NOT NULL, \
    MAJORCD        VARCHAR(3)    NOT NULL, \
    EXAMCOURSECD   VARCHAR(4)    NOT NULL, \
    TESTSUBCLASSCD VARCHAR(1)    NOT NULL, \
    PERFECT        SMALLINT, \
    RATE           SMALLINT, \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_PERFECT_MST ADD CONSTRAINT PK_ENTEXAM_PERF PRIMARY KEY (ENTEXAMYEAR,APPLICANTDIV,TESTDIV,COURSECD,MAJORCD,EXAMCOURSECD,TESTSUBCLASSCD)