-- $Id: v_collect_m_mst.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP VIEW V_COLLECT_M_MST

CREATE VIEW V_COLLECT_M_MST \
   (YEAR, \
    COLLECT_L_CD, \
    COLLECT_M_CD, \
    COLLECT_M_NAME, \
    COLLECT_S_EXIST_FLG, \
    COLLECT_M_MONEY, \
    PAY_DIV, \
    PAY_DATE, \
    IS_JUGYOURYOU, \
    REMARK, \
    SEX, \
    GRD_YOTEI, \
    MUSYOU) \
AS \
SELECT \
    T1.YEAR, \
    T1.COLLECT_L_CD, \
    T1.COLLECT_M_CD, \
    T1.COLLECT_M_NAME, \
    T1.COLLECT_S_EXIST_FLG, \
    T1.COLLECT_M_MONEY, \
    T1.PAY_DIV, \
    T1.PAY_DATE, \
    T1.IS_JUGYOURYOU, \
    T1.REMARK, \
    L1.TOKUSYU_VAL AS SEX, \
    L2.TOKUSYU_VAL AS GRD_YOTEI, \
    L3.TOKUSYU_VAL AS MUSYOU \
FROM \
    COLLECT_M_MST T1 \
    LEFT JOIN COLLECT_M_DETAIL_DAT L1 ON T1.YEAR = L1.YEAR \
         AND T1.COLLECT_L_CD = L1.COLLECT_L_CD \
         AND T1.COLLECT_M_CD = L1.COLLECT_M_CD \
         AND L1.TOKUSYU_CD = '001' \
    LEFT JOIN COLLECT_M_DETAIL_DAT L2 ON T1.YEAR = L2.YEAR \
         AND T1.COLLECT_L_CD = L2.COLLECT_L_CD \
         AND T1.COLLECT_M_CD = L2.COLLECT_M_CD \
         AND L2.TOKUSYU_CD = '002' \
    LEFT JOIN COLLECT_M_DETAIL_DAT L3 ON T1.YEAR = L3.YEAR \
         AND T1.COLLECT_L_CD = L3.COLLECT_L_CD \
         AND T1.COLLECT_M_CD = L3.COLLECT_M_CD \
         AND L3.TOKUSYU_CD = '003'
