-- $Id: v_collect_grp_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP VIEW V_COLLECT_GRP_DAT

CREATE VIEW V_COLLECT_GRP_DAT \
   (YEAR, \
    COLLECT_GRP_CD, \
    COLLECT_GRP_NAME, \
    COLLECT_L_CD, \
    COLLECT_M_CD, \
    COLLECT_S_CD, \
    COLLECT_KOJIN_FLG \
    ) \
AS \
SELECT \
    T1.YEAR, \
    T1.COLLECT_GRP_CD, \
    T2.COLLECT_GRP_NAME, \
    T1.COLLECT_L_CD, \
    T1.COLLECT_M_CD, \
    T1.COLLECT_S_CD, \
    VALUE(T2.COLLECT_KOJIN_FLG, '0') AS COLLECT_KOJIN_FLG \
FROM \
    COLLECT_GRP_DAT T1, \
    COLLECT_GRP_MST T2 \
WHERE \
    T1.YEAR = T2.YEAR \
    AND T1.COLLECT_GRP_CD = T2.COLLECT_GRP_CD
