
DROP VIEW V_STAFF_MST

CREATE VIEW V_STAFF_MST AS \
    SELECT \
    T1.YEAR, \
    T2.STAFFCD, \
    T2.STAFFNAME, \
    T2.STAFFNAME_SHOW, \
    T2.STAFFNAME_KANA, \
    T2.STAFFNAME_ENG, \
    T2.JOBCD, \
    T2.SECTIONCD, \
    T2.DUTYSHARECD, \ 
    T2.CHARGECLASSCD, \
    T2.STAFFSEX, \
    T2.STAFFBIRTHDAY, \
    T2.STAFFZIPCD, \
    T2.STAFFADDR1, \
    T2.STAFFADDR2, \
    T2.STAFFTELNO, \
    T2.STAFFFAXNO, \
    T2.STAFFE_MAIL, \
    T2.UPDATED \
    FROM  STAFF_YDAT T1, STAFF_MST T2 \
    WHERE T1.STAFFCD = T2.STAFFCD

