-- kanji=漢字
-- $Id: v_kojin_taiyoyoyaku_hist_dat.sql 74435 2020-05-20 07:59:16Z yamashiro $

DROP VIEW V_KOJIN_TAIYOYOYAKU_HIST_DAT

CREATE VIEW V_KOJIN_TAIYOYOYAKU_HIST_DAT \
    (KOJIN_NO, \
     SHIKIN_SHOUSAI_DIV, \
     SHINSEI_YEAR, \
     UKE_YEAR, \
     UKE_NO, \
     UKE_EDABAN, \
     YOYAKU_SHINSEI_DATE, \
     SHUUGAKU_NO, \
     NENREI, \
     KIKON_FLG, \
     J_SCHOOL_CD, \
     J_GRAD_DIV, \
     J_GRAD_YM, \
     KIBOU_H_SCHOOL_DIV, \
     YOYAKU_KIBOU_GK, \
     S_YOYAKU_KIBOU_YM, \
     E_YOYAKU_KIBOU_YM, \
     SHITAKUKIN_KIBOU_FLG, \
     SHINSEI_DIV, \
     SETAI_SEQ, \
     SHORI_JYOUKYOU, \
     RENTAI_CD, \
     SHINKEN1_CD, \
     SHINKEN2_CD, \
     SHUTARU_CD, \
     SHINSEI_KANRYOU_FLG, \
     SHINSEI_CANCEL_FLG, \
     SHINSEI_CANCEL_DATE, \
     KETTEI_DATE, \
     KETTEI_FLG \
    ) \
AS \
WITH MAX_YOYAKU AS ( \
SELECT \
    KOJIN_NO, \
    MIN(SHIKIN_SHOUSAI_DIV) AS SHOUSAI \
FROM \
    KOJIN_TAIYOYOYAKU_HIST_DAT \
GROUP BY \
    KOJIN_NO \
) \
SELECT \
    T1.KOJIN_NO, \
    T1.SHIKIN_SHOUSAI_DIV, \
    T1.SHINSEI_YEAR, \
    T1.UKE_YEAR, \
    T1.UKE_NO, \
    T1.UKE_EDABAN, \
    T1.YOYAKU_SHINSEI_DATE, \
    T1.SHUUGAKU_NO, \
    T1.NENREI, \
    T1.KIKON_FLG, \
    T1.J_SCHOOL_CD, \
    T1.J_GRAD_DIV, \
    T1.J_GRAD_YM, \
    T1.KIBOU_H_SCHOOL_DIV, \
    T1.YOYAKU_KIBOU_GK, \
    T1.S_YOYAKU_KIBOU_YM, \
    T1.E_YOYAKU_KIBOU_YM, \
    T1.SHITAKUKIN_KIBOU_FLG, \
    T1.SHINSEI_DIV, \
    T1.SETAI_SEQ, \
    T1.SHORI_JYOUKYOU, \
    T1.RENTAI_CD, \
    T1.SHINKEN1_CD, \
    T1.SHINKEN2_CD, \
    T1.SHUTARU_CD, \
    T1.SHINSEI_KANRYOU_FLG, \
    T1.SHINSEI_CANCEL_FLG, \
    T1.SHINSEI_CANCEL_DATE, \
    T1.KETTEI_DATE, \
    T1.KETTEI_FLG \
FROM \
    KOJIN_TAIYOYOYAKU_HIST_DAT T1, \
    MAX_YOYAKU T2 \
WHERE \
    T1.KOJIN_NO = T2.KOJIN_NO \
    AND T1.SHIKIN_SHOUSAI_DIV = T2.SHOUSAI
