
------------------------------------------------
-- 表の DDL ステートメント "DB2INST1"."DESASTER_DAT"
------------------------------------------------
DROP TABLE DESASTER_DAT

CREATE TABLE DESASTER_DAT \
( \
 		   YEAR				VARCHAR(4) 	NOT NULL , \
 		   DESASDATE		DATE  		NOT NULL , \
 		   DESASTIME	    TIME  		NOT NULL , \
		   SCHREGNO  		VARCHAR(6)  NOT NULL,  \
		   DISAS_SUBCLASS  	VARCHAR(16) ,  \
		   DISAS_REMARK1  	VARCHAR(22) ,  \
		   DISAS_REMARK2 	VARCHAR(16) ,  \
		   DISAS_REMARK3  	VARCHAR(16) ,  \
		   DISAS_REMARK  	VARCHAR(190) ,  \
		   SITUATION  		VARCHAR(542) ,  \
		   MANAGEMENT  		VARCHAR(406) ,  \
		   D_STAFFCD1  		VARCHAR(14) ,  \
		   D_STAFFCD2 		VARCHAR(14) ,  \
		   D_STAFFCD3 		VARCHAR(14) ,  \
		   REMARK  			VARCHAR(270) ,  \
 		   R_STAFFCD1		VARCHAR(30) , \
 		   R_STAFFCD2		VARCHAR(30) , \
		   UPDATED  		TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP) \
		 IN  USR1DMS  INDEX IN  IDX1DMS

-- 表の 1 次キーの DDL ステートメント  DB2INST1 . DESASTER_DAT 
ALTER TABLE  DB2INST1 . DESASTER_DAT \
	ADD CONSTRAINT  PK_DESASTER_DAT  PRIMARY KEY \
		( YEAR,DESASDATE,DESASTIME,SCHREGNO )

