-- $Id: 7eec6cb92b0b18a148fb33561257b94af53444bb $

DROP TABLE ENTEXAM_APPLICANTCONFRPT_DETAIL_DAT_OLD

RENAME TABLE ENTEXAM_APPLICANTCONFRPT_DETAIL_DAT TO ENTEXAM_APPLICANTCONFRPT_DETAIL_DAT_OLD

CREATE TABLE ENTEXAM_APPLICANTCONFRPT_DETAIL_DAT( \
    ENTEXAMYEAR        VARCHAR(4)   NOT NULL, \
    APPLICANTDIV       VARCHAR(1)   NOT NULL, \
    EXAMNO             VARCHAR(10)  NOT NULL, \
    SEQ                VARCHAR(3)   NOT NULL, \
    REMARK1            VARCHAR(150), \
    REMARK2            VARCHAR(150), \
    REMARK3            VARCHAR(150), \
    REMARK4            VARCHAR(750), \
    REMARK5            VARCHAR(750), \
    REMARK6            VARCHAR(750), \
    REMARK7            VARCHAR(150), \
    REMARK8            VARCHAR(150), \
    REMARK9            VARCHAR(150), \
    REMARK10           VARCHAR(150), \
    REMARK11           VARCHAR(150), \
    REMARK12           VARCHAR(150), \
    REGISTERCD         VARCHAR(10), \
    UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO ENTEXAM_APPLICANTCONFRPT_DETAIL_DAT \
    SELECT \
        ENTEXAMYEAR, \
        APPLICANTDIV, \
        EXAMNO, \
        SEQ, \
        REMARK1, \
        REMARK2, \
        REMARK3, \
        REMARK4, \
        REMARK5, \
        REMARK6, \
        REMARK7, \
        REMARK8, \
        REMARK9, \
        REMARK10, \
        REMARK11, \
        REMARK12, \
        REGISTERCD, \
        UPDATED \
    FROM \
        ENTEXAM_APPLICANTCONFRPT_DETAIL_DAT_OLD

ALTER TABLE ENTEXAM_APPLICANTCONFRPT_DETAIL_DAT ADD CONSTRAINT PK_EEXAM_APCNRPTDE PRIMARY KEY (ENTEXAMYEAR, APPLICANTDIV, EXAMNO, SEQ)