-- $Id: entexam_hall_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE ENTEXAM_HALL_DAT
CREATE TABLE ENTEXAM_HALL_DAT( \
    APPLICANTDIV  VARCHAR(1)    NOT NULL, \
    TESTDIV       VARCHAR(1)    NOT NULL, \
    EXAM_TYPE     VARCHAR(1)    NOT NULL, \
    EXAMHALLCD    VARCHAR(4)    NOT NULL, \
    EXAMHALL_NAME VARCHAR(30), \
    CAPA_CNT      SMALLINT, \
    S_RECEPTNO    VARCHAR(5), \
    E_RECEPTNO    VARCHAR(5), \
    REGISTERCD    VARCHAR(8), \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_HALL_DAT ADD CONSTRAINT PK_ENTEXAM_HALL PRIMARY KEY (APPLICANTDIV,TESTDIV,EXAM_TYPE,EXAMHALLCD)