-- $Id: majorl_mst.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE MAJORL_MST
CREATE TABLE MAJORL_MST( \
    MAJORLCD   VARCHAR(2)    NOT NULL, \
    MAJORLNAME VARCHAR(60), \
    MAJORLABBV VARCHAR(6), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE MAJORL_MST ADD CONSTRAINT PK_MAJORS_MST PRIMARY KEY (MAJORLCD)