-- $Id: majors_mst.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE MAJORS_MST
CREATE TABLE MAJORS_MST( \
    MAJORLCD   VARCHAR(2)    NOT NULL, \
    MAJORSCD   VARCHAR(1)    NOT NULL, \
    MAJORSNAME VARCHAR(60), \
    MAJORSABBV VARCHAR(6), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE MAJORS_MST ADD CONSTRAINT PK_MAJORS_MST PRIMARY KEY (MAJORLCD,MAJORSCD)