--°Ñ°÷²ñ¥Þ¥¹¥¿ 2004/7/15
--COMMITTEECD size 2¢ª4 2004/11/26 m-yama
DROP TABLE COMMITTEE_MST

CREATE TABLE COMMITTEE_MST \
(  \
        "COMMITTEE_FLG"         VARCHAR(1)       NOT NULL, \
        "COMMITTEECD"           VARCHAR(4)       NOT NULL, \
        "COMMITTEENAME"         VARCHAR(30), \
        "REGISTERCD"            VARCHAR(8), \
        "UPDATED"               TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COMMITTEE_MST  \
ADD CONSTRAINT PK_COMMITTEE_MST  \
PRIMARY KEY  \
(COMMITTEE_FLG,COMMITTEECD)
