--°Ñ°÷²ñÇ¯ÅÙ¥Ç¡¼¥¿ 2004/7/15
--COMMITTEECD size 2¢ª4 2004/11/26 m-yama
DROP TABLE COMMITTEE_YDAT

CREATE TABLE COMMITTEE_YDAT \
(  \
        "YEAR"                  VARCHAR(4)      NOT NULL, \
        "COMMITTEE_FLG"         VARCHAR(1)      NOT NULL, \
        "COMMITTEECD"           VARCHAR(4)      NOT NULL, \
        "REGISTERCD"            VARCHAR(8), \
        "UPDATED"               TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COMMITTEE_YDAT  \
ADD CONSTRAINT PK_COMMITTEE_YDAT  \
PRIMARY KEY  \
(YEAR,COMMITTEE_FLG,COMMITTEECD)
