-- kanji=Š¿Žš
-- $Id: course_group_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE COURSE_GROUP_DAT
CREATE TABLE COURSE_GROUP_DAT( \
    YEAR       VARCHAR(4)    NOT NULL, \
    GRADE      VARCHAR(2)    NOT NULL, \
    HR_CLASS   VARCHAR(3)    NOT NULL, \
    COURSECODE VARCHAR(4)    NOT NULL, \
    COURSE_SEQ VARCHAR(4)    NOT NULL, \
    GROUP_NAME VARCHAR(45), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COURSE_GROUP_DAT ADD CONSTRAINT PK_COURSE_GRP_DAT PRIMARY KEY (YEAR,GRADE,HR_CLASS,COURSECODE)
