--類型評定ヘッダマスタ
DROP TABLE TYPE_ASSES_HDAT

CREATE TABLE TYPE_ASSES_HDAT  \
(  \
        "YEAR"                  VARCHAR(4)      NOT NULL, \
        "TYPE_ASSES_CD"         VARCHAR(1)      NOT NULL, \
        "TYPE_GROUP_AVE_HIGH"   DECIMAL(3,0), \
        "TYPE_GROUP_AVE_LOW"    DECIMAL(3,0), \
        "REGISTERCD"            VARCHAR(8), \
        "UPDATED"               TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE TYPE_ASSES_HDAT  \
ADD CONSTRAINT PK_TYPE_ASSES_HDAT  \
PRIMARY KEY  \
(YEAR,TYPE_ASSES_CD)
