--類型評定マスタ
DROP TABLE TYPE_ASSES_MST

CREATE TABLE TYPE_ASSES_MST \
(  \
        "YEAR"                  VARCHAR(4)      NOT NULL, \
        "TYPE_ASSES_CD"         VARCHAR(1)      NOT NULL, \
        "TYPE_ASSES_LEVEL"      VARCHAR(1)      NOT NULL, \
        "TYPE_ASSES_HIGH"       DECIMAL(3,0), \
        "TYPE_ASSES_LOW"        DECIMAL(3,0), \
        "REGISTERCD"            VARCHAR(8), \
        "UPDATED"               TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE TYPE_ASSES_MST  \
ADD CONSTRAINT PK_TYPE_ASSES_MST  \
PRIMARY KEY  \
(YEAR,TYPE_ASSES_CD,TYPE_ASSES_LEVEL)
