// kanji=漢字
/*
 * $Id: 47917e39400e7c5cafb58e970a207bf8d7db9238 $
 *
 * 作成日: 2008/01/26 16:05:22 - JST
 * 作成者: m-yama
 *
 * Copyright(C) 2008-2012 ALP Okinawa Co.,Ltd. All rights reserved.
 */
package servletpack.KNJWP;

import java.sql.ResultSet;
import java.sql.SQLException;

//import org.apache.commons.logging.Log;
//import org.apache.commons.logging.LogFactory;

/**
 * <<クラスの説明>>。
 * @author m-yama
 * @version $Id: 47917e39400e7c5cafb58e970a207bf8d7db9238 $
 */
public class KNJWP300SubPayMent extends KNJWP300SubAbstract {

    /**
     * コンストラクタ。
     * @param param
     * @throws Exception
     */
    protected KNJWP300SubPayMent(KNJWP300Param param) throws Exception {
        super(param);
        
    }

    /**
     * {@inheritDoc}
     */
    protected String getSql() {
        final String sql = ""
            + " WITH PAY_HIST_DETAIL AS ( "
            + " SELECT "
            + "     T1.SLIP_NO, "
            + "     T1.APPLICANTNO, "
            + "     T1.COMMODITY_CD, "
            + "     VALUE(L1.TAX_PERCENT, 0) AS TAX_PERCENT, "
            + "     SUM(VALUE(T1.PAYMENT_MONEY, 0)) AS PAYMENT_MONEY "
            + " FROM "
            + "     PAYMENT_MONEY_HIST_DETAILS_DAT T1 "
            + "     INNER JOIN CLAIM_DAT I1 ON T1.SLIP_NO = I1.SLIP_NO "
            + "           AND T1.APPLICANTNO = I1.APPLICANTNO "
            + "           AND VALUE(I1.CANCEL_FLG, '0') = '0' "
            + "     LEFT JOIN COMMODITY_MST L1 ON T1.COMMODITY_CD = L1.COMMODITY_CD "
            + " WHERE "
            + "     T1.PAYMENT_DATE BETWEEN '" + _param._fromData + "' AND '" + _param._toDate + "' "
            + " GROUP BY "
            + "     T1.SLIP_NO, "
            + "     T1.APPLICANTNO, "
            + "     T1.COMMODITY_CD, "
            + "     L1.TAX_PERCENT "
            + " ), MAIN_T_SUB AS ( "
            + " SELECT "
            + "     T1.SLIP_NO, "
            + "     T1.APPLICANTNO, "
            + "     T1.COMMODITY_CD, "
            + "     VALUE(T1.PAYMENT_MONEY, 0) AS PAYMENT_MONEY, "
            + "     CASE WHEN T1.TAX_PERCENT = 0 "
            + "          THEN VALUE(T1.PAYMENT_MONEY, 0) "
            + "          ELSE (trunc(float(VALUE(T1.PAYMENT_MONEY, 0) / (T1.TAX_PERCENT / 100  + 1) * 10) / 10, 0)) "
            + "     END AS PRICE, "
            + "     VALUE(T1.PAYMENT_MONEY, 0) - (trunc(float(VALUE(T1.PAYMENT_MONEY, 0) / (T1.TAX_PERCENT / 100  + 1) * 10) / 10, 0)) AS TAX "
            + " FROM "
            + "     PAY_HIST_DETAIL T1 "
            + " GROUP BY "
            + "     T1.SLIP_NO, "
            + "     T1.APPLICANTNO, "
            + "     T1.COMMODITY_CD, "
            + "     T1.PAYMENT_MONEY, "
            + "     T1.TAX_PERCENT "
            + " ), MAIN_PAY AS ( "
            + " SELECT "
            + "     * "
            + " FROM "
            + "     MAIN_T_SUB "
            + " UNION ALL "
            + " SELECT "
            + "     SLIP.SLIP_NO AS SLIP_NO, "
            + "     T1.APPLICANTNO, "
            + "     '99001' AS COMMODITY_CD, "
            + "     VALUE(P_OVER.OVER_PAYMENT, 0) AS PAYMENT_MONEY, "
            + "     0 AS PRICE, "
            + "     0 AS TAX "
            + " FROM "
            + "     APPLICANT_BASE_MST T1 "
            + "     LEFT JOIN (SELECT "
            + "                    L1.APPLICANTNO, "
            + "                    SUM(L1.OVER_PAYMENT) AS OVER_PAYMENT "
            + "                FROM "
            + "                    OVER_PAYMENT_HIST_DAT L1 "
            + "                WHERE "
            + "                    L1.OVER_PAY_DATE BETWEEN '" + _param._fromData + "' AND '" + _param._toDate + "' "
            + "                GROUP BY "
            + "                    L1.APPLICANTNO "
            + "          ) P_OVER ON P_OVER.APPLICANTNO = T1.APPLICANTNO "
            + "     LEFT JOIN (SELECT "
            + "                    L2.APPLICANTNO, "
            + "                    MIN(L2.SLIP_NO) AS SLIP_NO "
            + "                FROM "
            + "                    MAIN_T_SUB L2 "
            + "                GROUP BY "
            + "                    L2.APPLICANTNO "
            + "          ) SLIP ON SLIP.APPLICANTNO = T1.APPLICANTNO "
            + " WHERE "
            + "     VALUE(P_OVER.OVER_PAYMENT, 0) > 0 "
            + " UNION ALL "
            + " SELECT "
            + "     SLIP.SLIP_NO AS SLIP_NO, "
            + "     T1.APPLICANTNO, "
            + "     '99003' AS COMMODITY_CD, "
            + "     VALUE(P_OVER.OVER_PAYMENT, 0) * -1 AS PAYMENT_MONEY, "
            + "     0 AS PRICE, "
            + "     0 AS TAX "
            + " FROM "
            + "     APPLICANT_BASE_MST T1 "
            + "     LEFT JOIN (SELECT "
            + "                    L1.APPLICANTNO, "
            + "                    SUM(L1.OVER_PAYMENT) AS OVER_PAYMENT "
            + "                FROM "
            + "                    OVER_PAYMENT_HIST_DAT L1 "
            + "                WHERE "
            + "                    L1.OVER_PAY_DATE BETWEEN '" + _param._fromData + "' AND '" + _param._toDate + "' "
            + "                    AND L1.OVER_PAYMENT_DIV = '02' "
            + "                GROUP BY "
            + "                    L1.APPLICANTNO "
            + "          ) P_OVER ON P_OVER.APPLICANTNO = T1.APPLICANTNO "
            + "     LEFT JOIN (SELECT "
            + "                    L2.APPLICANTNO, "
            + "                    MIN(L2.SLIP_NO) AS SLIP_NO "
            + "                FROM "
            + "                    MAIN_T_SUB L2 "
            + "                GROUP BY "
            + "                    L2.APPLICANTNO "
            + "          ) SLIP ON SLIP.APPLICANTNO = T1.APPLICANTNO "
            + " WHERE "
            + "     VALUE(P_OVER.OVER_PAYMENT, 0) > 0 "
            + " UNION ALL "
            + " SELECT "
            + "     SLIP.SLIP_NO AS SLIP_NO, "
            + "     T1.APPLICANTNO, "
            + "     '99002' AS COMMODITY_CD, "
            + "     VALUE(RE_PAY.RE_PAYMENT, 0) * -1 AS PAYMENT_MONEY, "
            + "     0 AS PRICE, "
            + "     0 AS TAX "
            + " FROM "
            + "     APPLICANT_BASE_MST T1 "
            + "     LEFT JOIN (SELECT "
            + "                    L2.APPLICANTNO, "
            + "                    SUM(L2.RE_PAYMENT) AS RE_PAYMENT "
            + "                FROM "
            + "                    RE_PAYMENT_HIST_DAT L2 "
            + "                WHERE "
            + "                    L2.RE_PAY_DATE BETWEEN '" + _param._fromData + "' AND '" + _param._toDate + "' "
            + "                GROUP BY "
            + "                    L2.APPLICANTNO "
            + "          ) RE_PAY ON RE_PAY.APPLICANTNO = T1.APPLICANTNO "
            + "     LEFT JOIN (SELECT "
            + "                    L2.APPLICANTNO, "
            + "                    MIN(L2.SLIP_NO) AS SLIP_NO "
            + "                FROM "
            + "                    MAIN_T_SUB L2 "
            + "                GROUP BY "
            + "                    L2.APPLICANTNO "
            + "          ) SLIP ON SLIP.APPLICANTNO = T1.APPLICANTNO "
            + " WHERE "
            + "     VALUE(RE_PAY.RE_PAYMENT, 0) > 0 "
            + " ), COMMODITY AS ( "
            + " SELECT "
            + "     COMMODITY_CD "
            + " FROM "
            + "     COMMODITY_MST "
            + " WHERE "
            + "     VALUE(SALES_DIV, '0') = '1' "
            + " ), APP_SLIP_SUB AS ( "
            + " SELECT "
            + "     T1.SLIP_NO, "
            + "     T1.APPLICANTNO "
            + " FROM "
            + "     CLAIM_DETAILS_DAT T1, "
            + "     CLAIM_DAT T2 "
            + " WHERE "
            + "     EXISTS (SELECT "
            + "                 * "
            + "             FROM "
            + "                 COMMODITY CT "
            + "             WHERE "
            + "                 CT.COMMODITY_CD = T1.COMMODITY_CD "
            + "            ) "
            + "     AND VALUE(T1.DUMMY_FLG, '0') = '0' "
            + "     AND substr(T1.SLIP_NO, 1, 2) = '" + _param._year.substring(2) + "' "
            + "     AND T1.SLIP_NO = T2.SLIP_NO "
            + "     AND T1.APPLICANTNO = T2.APPLICANTNO "
            + "     AND VALUE(T2.CANCEL_FLG, '0') = '0' "
            + " GROUP BY "
            + "     T1.SLIP_NO, "
            + "     T1.APPLICANTNO "
            + " ), APP_SLIP_SUB2 AS ( "
            + " SELECT "
            + "     T1.SLIP_NO, "
            + "     T1.APPLICANTNO "
            + " FROM "
            + "     CLAIM_DETAILS_DAT T1, "
            + "     CLAIM_DAT T2 "
            + " WHERE "
            + "     NOT EXISTS (SELECT "
            + "                     * "
            + "                 FROM "
            + "                     APP_SLIP_SUB APP "
            + "                 WHERE "
            + "                     APP.SLIP_NO = T1.SLIP_NO "
            + "                ) "
            + "     AND VALUE(T1.DUMMY_FLG, '0') = '0' "
            + "     AND substr(T1.SLIP_NO, 1, 2) = '" + _param._year.substring(2) + "' "
            + "     AND T1.SLIP_NO = T2.SLIP_NO "
            + "     AND T1.APPLICANTNO = T2.APPLICANTNO "
            + "     AND VALUE(T2.CANCEL_FLG, '0') = '0' "
            + " GROUP BY "
            + "     T1.SLIP_NO, "
            + "     T1.APPLICANTNO "
            + " ), APP_SLIP AS ( "
            + " SELECT "
            + "     '1' AS DATA_DIV, "
            + "     T1.APPLICANTNO, "
            + "     SUM(T1.PAYMENT_MONEY) AS PAYMENT_MONEY "
            + " FROM "
            + "     MAIN_PAY T1 "
            + " WHERE "
            + "     EXISTS (SELECT "
            + "                 * "
            + "             FROM "
            + "                 APP_SLIP_SUB APP_S "
            + "             WHERE "
            + "                 APP_S.SLIP_NO = T1.SLIP_NO "
            + "                 AND APP_S.APPLICANTNO = T1.APPLICANTNO "
            + "            ) "
            + " GROUP BY "
            + "     T1.APPLICANTNO "
            + " ), APP_SLIP2 AS ( "
            + " SELECT "
            + "     '2' AS DATA_DIV, "
            + "     T1.APPLICANTNO, "
            + "     SUM(T1.PAYMENT_MONEY) AS PAYMENT_MONEY "
            + " FROM "
            + "     MAIN_PAY T1 "
            + " WHERE "
            + "     EXISTS (SELECT "
            + "                 * "
            + "             FROM "
            + "                 APP_SLIP_SUB2 APP_S "
            + "             WHERE "
            + "                 APP_S.SLIP_NO = T1.SLIP_NO "
            + "                 AND APP_S.APPLICANTNO = T1.APPLICANTNO "
            + "            ) "
            + " GROUP BY "
            + "     T1.APPLICANTNO "
            + " ), APP_SLIP3 AS ( "
            + " SELECT "
            + "     '1' AS DATA_DIV, "
            + "     T1.APPLICANTNO, "
            + "     SUM(L1.PAYMENT_MONEY) AS PAYMENT_MONEY "
            + " FROM "
            + "     APP_SLIP_SUB T1 "
            + "     INNER JOIN MAIN_PAY L1 ON L1.APPLICANTNO = T1.APPLICANTNO "
            + " WHERE "
            + "     NOT EXISTS ( "
            + "             SELECT "
            + "                 * "
            + "             FROM "
            + "                 APP_SLIP "
            + "             WHERE "
            + "                 APP_SLIP.APPLICANTNO = T1.APPLICANTNO "
            + "            ) "
            + " GROUP BY "
            + "     T1.APPLICANTNO "
            + " ), APP_SLIP4 AS ( "
            + " SELECT "
            + "     '2' AS DATA_DIV, "
            + "     T1.APPLICANTNO, "
            + "     SUM(L1.PAYMENT_MONEY) AS PAYMENT_MONEY "
            + " FROM "
            + "     APP_SLIP_SUB2 T1 "
            + "     INNER JOIN MAIN_PAY L1 ON L1.APPLICANTNO = T1.APPLICANTNO "
            + " WHERE "
            + "     NOT EXISTS ( "
            + "             SELECT "
            + "                 * "
            + "             FROM "
            + "                 APP_SLIP2 "
            + "             WHERE "
            + "                 APP_SLIP2.APPLICANTNO = T1.APPLICANTNO "
            + "            ) "
            + " GROUP BY "
            + "     T1.APPLICANTNO "
            + " ), APP_SLIP5 AS ( "
            + " SELECT "
            + "     '2' AS DATA_DIV, "
            + "     T1.APPLICANTNO, "
            + "     SUM(L1.PAYMENT_MONEY) AS PAYMENT_MONEY "
            + " FROM "
            + "     APPLICANT_BASE_MST T1 "
            + "     INNER JOIN MAIN_PAY L1 ON L1.APPLICANTNO = T1.APPLICANTNO "
            + " WHERE "
            + "     NOT EXISTS ( "
            + "             SELECT "
            + "                 * "
            + "             FROM "
            + "                 APP_SLIP "
            + "             WHERE "
            + "                 APP_SLIP.APPLICANTNO = T1.APPLICANTNO "
            + "            ) "
            + "     AND NOT EXISTS ( "
            + "             SELECT "
            + "                 * "
            + "             FROM "
            + "                 APP_SLIP2 "
            + "             WHERE "
            + "                 APP_SLIP2.APPLICANTNO = T1.APPLICANTNO "
            + "            ) "
            + "     AND NOT EXISTS ( "
            + "             SELECT "
            + "                 * "
            + "             FROM "
            + "                 APP_SLIP3 "
            + "             WHERE "
            + "                 APP_SLIP3.APPLICANTNO = T1.APPLICANTNO "
            + "            ) "
            + "     AND NOT EXISTS ( "
            + "             SELECT "
            + "                 * "
            + "             FROM "
            + "                 APP_SLIP4 "
            + "             WHERE "
            + "                 APP_SLIP4.APPLICANTNO = T1.APPLICANTNO "
            + "            ) "
            + " GROUP BY "
            + "     T1.APPLICANTNO "
            + " ), MAIN_T AS ( "
            + " SELECT "
            + "     * "
            + " FROM "
            + "     APP_SLIP "
            + " UNION ALL "
            + " SELECT "
            + "     * "
            + " FROM "
            + "     APP_SLIP2 "
            + " UNION ALL "
            + " SELECT "
            + "     * "
            + " FROM "
            + "     APP_SLIP3 "
            + " UNION ALL "
            + " SELECT "
            + "     * "
            + " FROM "
            + "     APP_SLIP4 "
            + " UNION ALL "
            + " SELECT "
            + "     * "
            + " FROM "
            + "     APP_SLIP5 "
            + " ), BASE_T AS ( "
            + " SELECT "
            + "     T1.DATA_DIV, "
            + "     CASE WHEN L1.SCHREGNO IS NOT NULL "
            + "          THEN L1.STUDENT_DIV "
            + "          ELSE I1.STUDENT_DIV "
            + "     END AS STUDENT_DIV, "
            + "     CASE WHEN L1.SCHREGNO IS NOT NULL "
            + "          THEN L2.COMMUTING_DIV "
            + "          ELSE L3.COMMUTING_DIV "
            + "     END AS COMMUTING_DIV, "
            + "     SUM(VALUE(T1.PAYMENT_MONEY, 0)) AS PAYMENT_MONEY, "
            + "     COUNT(T1.DATA_DIV) AS PAYMENT_CNT "
            + " FROM "
            + "     MAIN_T T1 "
            + "     INNER JOIN APPLICANT_BASE_MST I1 ON T1.APPLICANTNO = I1.APPLICANTNO "
            + "     LEFT JOIN SCHREG_REGD_DAT L1 ON L1.YEAR = '" + _param._year + "' "
            + "          AND L1.SEMESTER = '1' "
            + "          AND L1.SCHREGNO = I1.SCHREGNO "
            + "     LEFT JOIN STUDENTDIV_MST L2 ON L2.STUDENT_DIV = L1.STUDENT_DIV "
            + "     LEFT JOIN STUDENTDIV_MST L3 ON L3.STUDENT_DIV = I1.STUDENT_DIV "
            + " GROUP BY "
            + "     T1.DATA_DIV, "
            + "     CASE WHEN L1.SCHREGNO IS NOT NULL "
            + "          THEN L1.STUDENT_DIV "
            + "          ELSE I1.STUDENT_DIV "
            + "     END, "
            + "     CASE WHEN L1.SCHREGNO IS NOT NULL "
            + "          THEN L2.COMMUTING_DIV "
            + "          ELSE L3.COMMUTING_DIV "
            + "     END "
            + " ) "
            + " SELECT "
            + "     T1.DATA_DIV, "
            + "     T1.STUDENT_DIV, "
            + "     T1.COMMUTING_DIV, "
            + "     T1.PAYMENT_MONEY, "
            + "     T1.PAYMENT_CNT, "
            + "     VALUE(L1.TOTAL_PAYMENT_MONEY, 0) + VALUE(T1.PAYMENT_MONEY, 0) AS TOTAL_PAYMENT_MONEY, "
            + "     VALUE(L1.TOTAL_PAYMENT_CNT, 0) + VALUE(T1.PAYMENT_CNT, 0) AS TOTAL_PAYMENT_CNT "
            + " FROM "
            + "     BASE_T T1 "
            + "     LEFT JOIN MONTH_PAYMENT_DAT L1 ON L1.YEAR_MONTH = '" + _param._lastYearMonth + "' "
            + "          AND T1.DATA_DIV = L1.DATA_DIV "
            + "          AND T1.STUDENT_DIV = L1.STUDENT_DIV "
            + "          AND T1.COMMUTING_DIV = L1.COMMUTING_DIV "
            + " UNION ALL "
            + " SELECT "
            + "     T1.DATA_DIV, "
            + "     T1.STUDENT_DIV, "
            + "     T1.COMMUTING_DIV, "
            + "     0 AS PAYMENT_MONEY, "
            + "     0 AS PAYMENT_CNT, "
            + "     VALUE(T1.TOTAL_PAYMENT_MONEY, 0) AS TOTAL_PAYMENT_MONEY, "
            + "     VALUE(T1.TOTAL_PAYMENT_CNT, 0) AS TOTAL_PAYMENT_CNT "
            + " FROM "
            + "     MONTH_PAYMENT_DAT T1 "
            + " WHERE "
            + "     T1.YEAR_MONTH = '" + _param._lastYearMonth + "' "
            + "     AND NOT EXISTS (SELECT "
            + "                         * "
            + "                     FROM "
            + "                         (SELECT "
            + "                              E1.DATA_DIV, "
            + "                              E1.STUDENT_DIV, "
            + "                              E1.COMMUTING_DIV "
            + "                          FROM "
            + "                              BASE_T E1 "
            + "                          GROUP BY "
            + "                              E1.DATA_DIV, "
            + "                              E1.STUDENT_DIV, "
            + "                              E1.COMMUTING_DIV "
            + "                         ) T2 "
            + "                     WHERE "
            + "                         T1.DATA_DIV = T2.DATA_DIV "
            + "                         AND T1.STUDENT_DIV = T2.STUDENT_DIV "
            + "                         AND T1.COMMUTING_DIV = T2.COMMUTING_DIV "
            + "     ) "
            + "";

        return sql;
    }

    /**
     * {@inheritDoc}
     */
    protected String deleteSql(ResultSet rs) throws SQLException {
        final String rtnSql = ""
            + " DELETE FROM MONTH_PAYMENT_DAT "
            + " WHERE "
            + "     YEAR_MONTH = '" + _param._yearMonth + "' ";
        return rtnSql;
    }

    /**
     * {@inheritDoc}
     */
    protected String insertSql(ResultSet rs) throws SQLException {
        final String rtnSql = ""
            + " INSERT INTO MONTH_PAYMENT_DAT "
            + " values ( "
            + " '" + _param._yearMonth + "', "
            + " '" + rs.getString("DATA_DIV") + "', "
            + " '" + rs.getString("STUDENT_DIV") + "', "
            + " '" + rs.getString("COMMUTING_DIV") + "', "
            + rs.getString("PAYMENT_MONEY") + ", "
            + rs.getString("PAYMENT_CNT") + ", "
            + rs.getString("TOTAL_PAYMENT_MONEY") + ", "
            + rs.getString("TOTAL_PAYMENT_CNT") + ", "
            + " '" + _param._staffcd + "', "
            + " current timestamp "
            + ") ";

        return rtnSql;
    }

}
 // KNJWP300SubPayMent

// eof
