-- $Id: entexam_print_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE ENTEXAM_PRINT_DAT
CREATE TABLE ENTEXAM_PRINT_DAT( \
    ENTEXAMYEAR          VARCHAR(4)    NOT NULL, \
    EXAMNO               VARCHAR(5)    NOT NULL, \
    PRINTFLG             VARCHAR(1), \
    GET_YOUROKU          VARCHAR(1), \
    GET_MEDEXAM          VARCHAR(1), \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_PRINT_DAT ADD CONSTRAINT PK_ENTEXAM_PRINT PRIMARY KEY (ENTEXAMYEAR, EXAMNO)