-- $Id: entexam_judgement_history_dat.sql 56577 2017-10-22 11:35:50Z maeshiro $

DROP TABLE ENTEXAM_JUDGEMENT_HISTORY_DAT
CREATE TABLE ENTEXAM_JUDGEMENT_HISTORY_DAT( \
    ENTEXAMYEAR    VARCHAR(4)    NOT NULL, \
    JUDGEMENT      VARCHAR(1)    NOT NULL, \
    JUDGE_CNT      SMALLINT, \
    REGISTERCD     VARCHAR(8), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE ENTEXAM_JUDGEMENT_HISTORY_DAT ADD CONSTRAINT PK_ENTEXAM_JUDGE PRIMARY KEY (ENTEXAMYEAR,JUDGEMENT)