-- kanji=漢字
-- $Id: b49a3ad77fc2a6e9d436654eb19070943cb20568 $

-- 注意:このファイルは EUC/LFのみ でなければならない。
-- 適用方法:
--    1.データベース接続
--    2.db2 +c -f <このファイル>
--    3.コミットするなら、db2 +c commit。やり直すなら、db2 +c rollback
--
ALTER TABLE LEVY_REQUEST_INCOME_DAT         ALTER COLUMN COLLECT_S_CD SET DATA TYPE varchar(3)
update LEVY_REQUEST_INCOME_DAT set COLLECT_S_CD = '0' || COLLECT_S_CD

ALTER TABLE LEVY_REQUEST_INCOME_MEISAI_DAT  ALTER COLUMN INCOME_S_CD SET DATA TYPE varchar(3)
update LEVY_REQUEST_INCOME_MEISAI_DAT set INCOME_S_CD = '0' || INCOME_S_CD

ALTER TABLE LEVY_REQUEST_INCOME_SCHREG_DAT  ALTER COLUMN INCOME_S_CD SET DATA TYPE varchar(3)
update LEVY_REQUEST_INCOME_SCHREG_DAT set INCOME_S_CD = '0' || INCOME_S_CD

ALTER TABLE LEVY_REQUEST_KOUNYU_MEISAI_DAT  ALTER COLUMN KOUNYU_S_CD SET DATA TYPE varchar(3)
update LEVY_REQUEST_KOUNYU_MEISAI_DAT set KOUNYU_S_CD = '0' || KOUNYU_S_CD

ALTER TABLE LEVY_REQUEST_OUTGO_DAT          ALTER COLUMN COLLECT_S_CD SET DATA TYPE varchar(3)
update LEVY_REQUEST_OUTGO_DAT set COLLECT_S_CD = '0' || COLLECT_S_CD

ALTER TABLE LEVY_REQUEST_OUTGO_MEISAI_DAT   ALTER COLUMN OUTGO_S_CD SET DATA TYPE varchar(3)
update LEVY_REQUEST_OUTGO_MEISAI_DAT set OUTGO_S_CD = '0' || OUTGO_S_CD

ALTER TABLE LEVY_REQUEST_OUTGO_SCHREG_DAT   ALTER COLUMN OUTGO_S_CD SET DATA TYPE varchar(3)
update LEVY_REQUEST_OUTGO_SCHREG_DAT set OUTGO_S_CD = '0' || OUTGO_S_CD

ALTER TABLE LEVY_S_MST                      ALTER COLUMN LEVY_S_CD SET DATA TYPE varchar(3)
update LEVY_S_MST set LEVY_S_CD = '0' || LEVY_S_CD
