-- $Id: c019793044af88be0f40f2738c6483ee3c36a6a9 $

INSERT INTO HEXAM_RECORD_REMARK_DAT ( \
YEAR, \
SEMESTER, \
TESTKINDCD, \
TESTITEMCD, \
SCHREGNO, \
REMARK_DIV, \
REMARK1 \
) \
SELECT \
    YEAR, \
    '1' as SEMESTER, \
    '01' as TESTKINDCD, \
    '01' as TESTITEMCD, \
    SCHREGNO, \
    '2' as REMARK_DIV, \
    TOTALSTUDYTIME \
FROM \
    HREPORTREMARK_DAT \
WHERE \
    SEMESTER = '9'
