-- $Id: 095ca89926fae79f421d1a99f23d37ea777447f6 $

drop   table IBSUBCLASS_UNIT_DAT_OLD

create table IBSUBCLASS_UNIT_DAT_OLD like IBSUBCLASS_UNIT_DAT

insert into IBSUBCLASS_UNIT_DAT_OLD select * from IBSUBCLASS_UNIT_DAT

DROP TABLE IBSUBCLASS_UNIT_DAT
CREATE TABLE IBSUBCLASS_UNIT_DAT( \
    IBYEAR               VARCHAR(4)    NOT NULL, \
    IBGRADE              VARCHAR(2)    NOT NULL, \
    IBCLASSCD            VARCHAR(2)    NOT NULL, \
    IBPRG_COURSE         VARCHAR(2)    NOT NULL, \
    IBCURRICULUM_CD      VARCHAR(2)    NOT NULL, \
    IBSUBCLASSCD         VARCHAR(6)    NOT NULL, \
    IBSEQ                SMALLINT      NOT NULL, \
    YEAR                 VARCHAR(4), \
    SEMESTER             VARCHAR(1), \
    GRADE                VARCHAR(2), \
    CLASSCD              VARCHAR(2), \
    SCHOOL_KIND          VARCHAR(2), \
    CURRICULUM_CD        VARCHAR(2), \
    SUBCLASSCD           VARCHAR(6), \
    LINK_NO              VARCHAR(30)   NOT NULL, \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE IBSUBCLASS_UNIT_DAT ADD CONSTRAINT PK_IBSUB_UNIT_D PRIMARY KEY (IBYEAR, IBGRADE, IBCLASSCD, IBPRG_COURSE, IBCURRICULUM_CD, IBSUBCLASSCD, IBSEQ)

insert into IBSUBCLASS_UNIT_DAT select * from IBSUBCLASS_UNIT_DAT_OLD
