-- $Id: 99935d35ec7e06f0405cb014429a362c6180bb6b $

DROP TABLE COLLEGE_MST_OLD
RENAME TABLE COLLEGE_MST TO COLLEGE_MST_OLD
CREATE TABLE COLLEGE_MST( \
    SCHOOL_CD         CHAR(8)       NOT NULL, \
    SCHOOL_NAME       VARCHAR(120), \
    SCHOOL_NAME_SHOW1 VARCHAR(120), \
    SCHOOL_NAME_SHOW2 VARCHAR(120), \
    SCHOOL_GROUP      VARCHAR(2), \
    BUNAME            VARCHAR(120), \
    KANAME            VARCHAR(120), \
    SCHOOL_SORT       CHAR(2), \
    BUNYA             CHAR(2), \
    AREA_NAME         VARCHAR(30), \
    CAMPUS_ADDR_CD    VARCHAR(2), \
    ZIPCD             VARCHAR(8), \
    ADDR1             VARCHAR(90), \
    ADDR2             VARCHAR(90), \
    TELNO             VARCHAR(16), \
    GREDES            VARCHAR(120), \
    BASE_SCORE        VARCHAR(20), \
    NECESSARY_SCORE   VARCHAR(20), \
    REGISTERCD        VARCHAR(10), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO COLLEGE_MST \
    SELECT \
        SCHOOL_CD, \
        SCHOOL_NAME, \
        SCHOOL_NAME_SHOW1, \
        SCHOOL_NAME_SHOW2, \
        SCHOOL_GROUP, \
        BUNAME, \
        KANAME, \
        SCHOOL_SORT, \
        BUNYA, \
        AREA_NAME, \
        CAMPUS_ADDR_CD, \
        ZIPCD, \
        ADDR1, \
        ADDR2, \
        TELNO, \
        GREDES, \
        CAST(NULL AS VARCHAR(20)) AS BASE_SCORE, \
        CAST(NULL AS VARCHAR(20)) AS NECESSARY_SCORE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        COLLEGE_MST_OLD

ALTER TABLE COLLEGE_MST ADD CONSTRAINT PK_COLLEGE_MST PRIMARY KEY (SCHOOL_CD)