-- $Id: e556c24a48e3bb580f62e7c0f41bb4de19f4d5b1 $

drop   table SCHREG_QUALIFIED_BANK_DAT_OLD
rename table SCHREG_QUALIFIED_BANK_DAT TO SCHREG_QUALIFIED_BANK_DAT_OLD

create table SCHREG_QUALIFIED_BANK_DAT \
   (SCHREGNO        VARCHAR(8)   NOT NULL, \
    CLASSCD         VARCHAR(2)   NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)   NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)   NOT NULL, \
    SUBCLASSCD      VARCHAR(6)   NOT NULL, \
    SEQ             SMALLINT     NOT NULL, \
    REGDDATE        DATE         NOT NULL, \
    REGDYEAR        VARCHAR(4)   NOT NULL, \
    MINUTES         SMALLINT     NOT NULL, \
    REMARK          VARCHAR(90), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
   ) IN USR1DMS INDEX IN IDX1DMS

insert into SCHREG_QUALIFIED_BANK_DAT \
    select \
        SCHREGNO, \
        LEFT(SUBCLASSCD, 2) AS CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        SEQ, \
        REGDDATE, \
        REGDYEAR, \
        MINUTES, \
        REMARK, \
        REGISTERCD, \
        UPDATED \
    from SCHREG_QUALIFIED_BANK_DAT_OLD

alter table SCHREG_QUALIFIED_BANK_DAT add constraint PK_SCH_QUAL_BANK primary key (SCHREGNO,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SEQ)

