-- $Id: 48a933510b4cbfee7a4bd410bf93a27fd6b86e7b $

DROP TABLE STANDARD_CREDIT_MST_OLD
RENAME TABLE STANDARD_CREDIT_MST TO STANDARD_CREDIT_MST_OLD
CREATE TABLE STANDARD_CREDIT_MST( \
     CLASSCD        VARCHAR(2) NOT NULL, \
     SCHOOL_KIND    VARCHAR(2) NOT NULL, \
     CURRICULUM_CD  VARCHAR(2) NOT NULL, \
     SUBCLASSCD     VARCHAR(6) NOT NULL, \
     CREDITS        SMALLINT, \
     REGISTERCD     VARCHAR(8), \
     UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO STANDARD_CREDIT_MST \
    SELECT \
        CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        CREDITS, \
        REGISTERCD, \
        UPDATED \
    FROM \
        STANDARD_CREDIT_MST_OLD

alter table STANDARD_CREDIT_MST add constraint PK_STN_CREDIT_MST primary key (CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)
