-- $Id: 89ef7535d5b4ab841eb2a5daccb9389ca87183be $

DROP TABLE SEMESTER_MST_OLD
RENAME TABLE SEMESTER_MST TO SEMESTER_MST_OLD
CREATE TABLE SEMESTER_MST( \
    YEAR         VARCHAR(4)    NOT NULL, \
    SEMESTER     VARCHAR(1)    NOT NULL, \
    SEMESTERNAME VARCHAR(30), \
    SDATE        DATE, \
    EDATE        DATE, \
    REGISTERCD   VARCHAR(8), \
    UPDATED      TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SEMESTER_MST \
    SELECT \
        YEAR, \
        SEMESTER, \
        SEMESTERNAME, \
        SDATE, \
        EDATE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SEMESTER_MST_OLD

ALTER TABLE SEMESTER_MST ADD CONSTRAINT PK_SEMESTER_MST PRIMARY KEY (YEAR,SEMESTER)