-- $Id: 79d02c20097df2c13d734d7661e22506c404c9cf $

DROP TABLE TESTITEM_MST_OLD
RENAME TABLE TESTITEM_MST TO TESTITEM_MST_OLD
CREATE TABLE TESTITEM_MST( \
    YEAR            VARCHAR(4)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    TESTKINDCD      VARCHAR(2)    NOT NULL, \
    TESTITEMCD      VARCHAR(2)    NOT NULL, \
    TESTITEMNAME    VARCHAR(30), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

insert into TESTITEM_MST \
SELECT \
    YEAR, \
    LEFT(SUBCLASSCD, 2) AS CLASSCD, \
    'H' AS SCHOOL_KIND, \
    '2' AS CURRICULUM_CD, \
    SUBCLASSCD, \
    TESTKINDCD, \
    TESTITEMCD, \
    TESTITEMNAME, \
    REGISTERCD, \
    UPDATED \
FROM \
    TESTITEM_MST_OLD

ALTER TABLE TESTITEM_MST ADD CONSTRAINT PK_TESTITEM_MST PRIMARY KEY (YEAR, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, TESTKINDCD, TESTITEMCD)