-- kanji=漢字
-- $Id: f5992a8c2818bba300cceb2116b5c5c89a0c866d $

DROP TABLE MEDEXAM_DISEASE_ADDITION4_DAT_OLD
RENAME TABLE MEDEXAM_DISEASE_ADDITION4_DAT TO MEDEXAM_DISEASE_ADDITION4_DAT_OLD
CREATE TABLE MEDEXAM_DISEASE_ADDITION4_DAT( \
    EDBOARD_SCHOOLCD    VARCHAR(12)   NOT NULL, \
    YEAR                VARCHAR(4)    NOT NULL, \
    DISEASECD           VARCHAR(3)    NOT NULL, \
    GRADE               VARCHAR(2)    NOT NULL, \
    HR_CLASS            VARCHAR(3)    NOT NULL, \
    ACTION_S_DATE       DATE          NOT NULL, \
    ACTION_E_DATE       DATE, \
    PATIENT_COUNT       SMALLINT, \
    ABSENCE_COUNT       SMALLINT, \
    PRESENCE_COUNT      SMALLINT, \
    SYMPTOM01           VARCHAR(1), \
    SYMPTOM01_REMARK    VARCHAR(150), \
    SYMPTOM02           VARCHAR(1), \
    SYMPTOM03           VARCHAR(1), \
    SYMPTOM04           VARCHAR(1), \
    SYMPTOM05           VARCHAR(1), \
    SYMPTOM06           VARCHAR(1), \
    SYMPTOM07           VARCHAR(1), \
    SYMPTOM08           VARCHAR(1), \
    SYMPTOM09           VARCHAR(1), \
    SYMPTOM10           VARCHAR(1), \
    SYMPTOM11           VARCHAR(1), \
    SYMPTOM12           VARCHAR(1), \
    SYMPTOM12_REMARK    VARCHAR(150), \
    REMARK              VARCHAR(150), \
    REGISTERCD          VARCHAR(8), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO MEDEXAM_DISEASE_ADDITION4_DAT \
    SELECT \
        EDBOARD_SCHOOLCD, \
        YEAR, \
        DISEASECD, \
        GRADE, \
        HR_CLASS, \
        ACTION_S_DATE, \
        ACTION_E_DATE, \
        PATIENT_TOTAL_COUNT AS PATIENT_COUNT, \
        ABSENCE_TOTAL_COUNT AS ABSENCE_COUNT, \
        CAST(NULL AS SMALLINT) AS PRESENCE_COUNT, \
        SYMPTOM01, \
        SYMPTOM01_REMARK, \
        SYMPTOM02, \
        SYMPTOM03, \
        SYMPTOM04, \
        SYMPTOM05, \
        SYMPTOM06, \
        SYMPTOM07, \
        SYMPTOM08, \
        SYMPTOM09, \
        SYMPTOM10, \
        SYMPTOM11, \
        SYMPTOM12, \
        SYMPTOM12_REMARK, \
        CAST(NULL AS VARCHAR(150)) AS REMARK, \
        REGISTERCD, \
        UPDATED \
    FROM \
        MEDEXAM_DISEASE_ADDITION4_DAT_OLD

ALTER TABLE MEDEXAM_DISEASE_ADDITION4_DAT ADD CONSTRAINT PK_MEDEXAM_D_A4_D PRIMARY KEY (EDBOARD_SCHOOLCD,YEAR,DISEASECD,GRADE,HR_CLASS,ACTION_S_DATE)