-- $Id: 4fef5299690074872ab0c4077b809ceb9067de1c $

DROP TABLE GRD_HEXAM_ENTREMARK_DAT_OLD
RENAME TABLE GRD_HEXAM_ENTREMARK_DAT TO GRD_HEXAM_ENTREMARK_DAT_OLD
CREATE TABLE GRD_HEXAM_ENTREMARK_DAT( \
    YEAR             VARCHAR(4)    NOT NULL, \
    SCHREGNO         VARCHAR(8)    NOT NULL, \
    ANNUAL           VARCHAR(2)    NOT NULL, \
    ATTENDREC_REMARK VARCHAR(238), \
    SPECIALACTREC    VARCHAR(700), \
    TRAIN_REF        VARCHAR(1248), \
    TRAIN_REF1       VARCHAR(453), \
    TRAIN_REF2       VARCHAR(520), \
    TRAIN_REF3       VARCHAR(800), \
    TOTALSTUDYACT    VARCHAR(746), \
    TOTALSTUDYVAL    VARCHAR(746), \
    CALSSACT         VARCHAR(300), \
    STUDENTACT       VARCHAR(218), \
    CLUBACT          VARCHAR(225), \
    SCHOOLEVENT      VARCHAR(218), \
    TOTALSTUDYACT_SLASH_FLG     VARCHAR(1), \
    TOTALSTUDYVAL_SLASH_FLG     VARCHAR(1), \
    ATTENDREC_REMARK_SLASH_FLG  VARCHAR(1), \
    REGISTERCD       VARCHAR(10), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO GRD_HEXAM_ENTREMARK_DAT \
    SELECT \
        YEAR, \
        SCHREGNO, \
        ANNUAL, \
        ATTENDREC_REMARK, \
        SPECIALACTREC, \
        TRAIN_REF, \
        TRAIN_REF1, \
        TRAIN_REF2, \
        TRAIN_REF3, \
        TOTALSTUDYACT, \
        TOTALSTUDYVAL, \
        CALSSACT, \
        STUDENTACT, \
        CLUBACT, \
        SCHOOLEVENT, \
        TOTALSTUDYACT_SLASH_FLG, \
        TOTALSTUDYVAL_SLASH_FLG, \
        ATTENDREC_REMARK_SLASH_FLG, \
        REGISTERCD, \
        UPDATED \
    FROM \
        GRD_HEXAM_ENTREMARK_DAT_OLD

ALTER TABLE GRD_HEXAM_ENTREMARK_DAT ADD CONSTRAINT SQL090925155104150 PRIMARY KEY (YEAR,SCHREGNO)
