-- $Id: 2fcb2dda9876b1d78164b685bf2e25cd6d4dc309 $

DROP TABLE COMB_GCALC_DAT_OLD
RENAME TABLE COMB_GCALC_DAT TO COMB_GCALC_DAT_OLD
CREATE TABLE COMB_GCALC_DAT( \
    YEAR                        VARCHAR(4) NOT NULL, \
    COMBINED_CLASSCD            VARCHAR(2) NOT NULL, \
    COMBINED_SCHOOL_KIND        VARCHAR(2) NOT NULL, \
    COMBINED_CURRICULUM_CD      VARCHAR(2) NOT NULL, \
    COMBINED_SUBCLASSCD         VARCHAR(6) NOT NULL, \
    GVAL_CALC                   VARCHAR(1), \
    REGISTERCD                  VARCHAR(8), \
    UPDATED                     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) in usr1dms index in idx1dms

INSERT INTO COMB_GCALC_DAT \
    SELECT \
        YEAR, \
        LEFT(COMBINED_SUBCLASSCD, 2) AS COMBINED_CLASSCD, \
        'H' AS COMBINED_SCHOOL_KIND, \
        '2' AS COMBINED_CURRICULUM_CD, \
        COMBINED_SUBCLASSCD, \
        GVAL_CALC, \
        REGISTERCD, \
        UPDATED \
    FROM \
        COMB_GCALC_DAT_OLD

alter table COMB_GCALC_DAT add constraint PK_COM_GC_DAT \
primary key (YEAR, COMBINED_CLASSCD, COMBINED_SCHOOL_KIND, COMBINED_CURRICULUM_CD, COMBINED_SUBCLASSCD)
