-- kanji=漢字
-- $Id: cba232dab07bed55492991650cdf9cceb348c2a0 $

DROP TABLE REPORT_DISEASE_ADDITION4_DAT_OLD
RENAME TABLE REPORT_DISEASE_ADDITION4_DAT TO REPORT_DISEASE_ADDITION4_DAT_OLD
CREATE TABLE REPORT_DISEASE_ADDITION4_DAT( \
    EDBOARD_SCHOOLCD VARCHAR(12)   NOT NULL, \
    YEAR             VARCHAR(4)    NOT NULL, \
    DISEASECD        VARCHAR(3)    NOT NULL, \
    GRADE            VARCHAR(2)    NOT NULL, \
    HR_CLASS         VARCHAR(3)    NOT NULL, \
    ACTION_S_DATE    DATE          NOT NULL, \
    EXECUTE_DATE     DATE, \
    REGISTERCD       VARCHAR(8), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO REPORT_DISEASE_ADDITION4_DAT \
    SELECT \
        EDBOARD_SCHOOLCD, \
        YEAR, \
        DISEASECD, \
        GRADE, \
        HR_CLASS, \
        EXECUTE_DATE AS ACTION_S_DATE, \
        EXECUTE_DATE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        REPORT_DISEASE_ADDITION4_DAT_OLD

ALTER TABLE REPORT_DISEASE_ADDITION4_DAT ADD CONSTRAINT PK_REPORT_D_A4_D PRIMARY KEY (EDBOARD_SCHOOLCD,YEAR,DISEASECD,GRADE,HR_CLASS,ACTION_S_DATE)