-- kanji=´Á»ú
-- $Id: c587e2f51de7e7d995a47a8b53d6a8976c4b1aad $

DROP TABLE BANK_MST_OLD
CREATE TABLE BANK_MST_OLD LIKE BANK_MST
INSERT INTO BANK_MST_OLD SELECT * FROM BANK_MST

DROP TABLE BANK_MST

CREATE TABLE BANK_MST ( \
    BANKCD              VARCHAR(4)      NOT NULL, \
    BRANCHCD            VARCHAR(3)      NOT NULL, \
    BANKNAME            VARCHAR(90), \
    BANKNAME_KANA       VARCHAR(90), \
    BANKNAME_ROMAJI     VARCHAR(180), \
    BRANCHNAME          VARCHAR(90), \
    BRANCHNAME_KANA     VARCHAR(90), \
    BRANCHNAME_ROMAJI   VARCHAR(180), \
    BANKZIPCD           VARCHAR(8), \
    BANKADDR1           VARCHAR(150), \
    BANKADDR2           VARCHAR(150), \
    BANKTELNO           VARCHAR(14), \
    BANKFAXNO           VARCHAR(14), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE BANK_MST ADD CONSTRAINT PK_BANK_MST PRIMARY KEY (BANKCD,BRANCHCD)

INSERT INTO BANK_MST \
SELECT \
    BANKCD              , \
    BRANCHCD            , \
    BANKNAME            , \
    BANKNAME_KANA       , \
    CAST(NULL AS VARCHAR(180)) AS BANKNAME_ROMAJI     , \
    BRANCHNAME          , \
    BRANCHNAME_KANA     , \
    CAST(NULL AS VARCHAR(180)) AS BRANCHNAME_ROMAJI   , \
    BANKZIPCD           , \
    BANKADDR1           , \
    BANKADDR2           , \
    BANKTELNO           , \
    BANKFAXNO           , \
    REGISTERCD, \
    UPDATED \
FROM BANK_MST_OLD
