-- $Id: 1550096120939ac5dbb4127cd0a1a2f3dc157cec $

drop table COMMITTEE_MST_OLD
create table COMMITTEE_MST_OLD like COMMITTEE_MST
insert into COMMITTEE_MST_OLD select * from COMMITTEE_MST

DROP TABLE COMMITTEE_MST

CREATE TABLE COMMITTEE_MST \
(  \
        "SCHOOLCD"              VARCHAR(12)      NOT NULL, \
        "SCHOOL_KIND"           VARCHAR(2)       NOT NULL, \
        "COMMITTEE_FLG"         VARCHAR(1)       NOT NULL, \
        "COMMITTEECD"           VARCHAR(4)       NOT NULL, \
        "COMMITTEENAME"         VARCHAR(45), \
        "REGISTERCD"            VARCHAR(10), \
        "UPDATED"               TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COMMITTEE_MST  \
ADD CONSTRAINT PK_COMMITTEE_MST  \
PRIMARY KEY  \
(SCHOOLCD, SCHOOL_KIND, COMMITTEE_FLG, COMMITTEECD)

insert into COMMITTEE_MST \
select \
        SCHOOLCD, \
        SCHOOL_KIND, \
        COMMITTEE_FLG, \
        COMMITTEECD, \
        COMMITTEENAME, \
        REGISTERCD, \
        UPDATED \
from COMMITTEE_MST_OLD
