-- $Id: d162b3d97721b4c22475bdf6556701761670c16f $

drop table USER_MST_OLD
create table USER_MST_OLD like USER_MST
insert into USER_MST_OLD select * from USER_MST

DROP TABLE USER_MST

CREATE TABLE USER_MST( \
    SCHOOLCD       VARCHAR(12) NOT NULL, \
    SCHOOL_KIND    VARCHAR(2)  NOT NULL, \
    STAFFCD        VARCHAR(10)  NOT NULL, \
    USERID         VARCHAR(32), \
    PASSWD         VARCHAR(32), \
    INVALID_FLG    VARCHAR(1), \
    PWDTERMCHK_FLG VARCHAR(1), \
    USE_LDAP       VARCHAR(2), \
    CHG_PWD_FLG    VARCHAR(1), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO USER_MST \
    SELECT \
        SCHOOLCD, \
        SCHOOL_KIND, \
        STAFFCD, \
        USERID, \
        PASSWD, \
        INVALID_FLG, \
        PWDTERMCHK_FLG, \
        USE_LDAP, \
        cast(null as VARCHAR(1)) as CHG_PWD_FLG, \
        REGISTERCD, \
        UPDATED \
    FROM \
        USER_MST_OLD

ALTER TABLE USER_MST ADD CONSTRAINT PK_USER_MST PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, STAFFCD)
