-- $Id: 9fda9b064682d2308f8240d3089f00dd130bacb4 $

DROP TABLE RECORD_RANK_SDIV_DAT_OLD
RENAME TABLE RECORD_RANK_SDIV_DAT TO RECORD_RANK_SDIV_DAT_OLD
CREATE TABLE RECORD_RANK_SDIV_DAT( \
    YEAR                  VARCHAR(4)    NOT NULL, \
    SEMESTER              VARCHAR(1)    NOT NULL, \
    TESTKINDCD            VARCHAR(2)    NOT NULL, \
    TESTITEMCD            VARCHAR(2)    NOT NULL, \
    SCORE_DIV             VARCHAR(2)    NOT NULL, \
    CLASSCD               VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND           VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD         VARCHAR(2)    NOT NULL, \
    SUBCLASSCD            VARCHAR(6)    NOT NULL, \
    SCHREGNO              VARCHAR(8)    NOT NULL, \
    SCORE                 SMALLINT, \
    AVG                   DECIMAL(8,5), \
    GRADE_RANK            SMALLINT, \
    GRADE_AVG_RANK        SMALLINT, \
    GRADE_DEVIATION       DECIMAL(4,1), \
    GRADE_DEVIATION_RANK  SMALLINT, \
    CLASS_RANK            SMALLINT, \
    CLASS_AVG_RANK        SMALLINT, \
    CLASS_DEVIATION       DECIMAL(4,1), \
    CLASS_DEVIATION_RANK  SMALLINT, \
    COURSE_RANK           SMALLINT, \
    COURSE_AVG_RANK       SMALLINT, \
    COURSE_DEVIATION      DECIMAL(4,1), \
    COURSE_DEVIATION_RANK SMALLINT, \
    MAJOR_RANK            SMALLINT, \
    MAJOR_AVG_RANK        SMALLINT, \
    MAJOR_DEVIATION       DECIMAL(4,1), \
    MAJOR_DEVIATION_RANK  SMALLINT, \
    COURSE_GROUP_RANK           SMALLINT, \
    COURSE_GROUP_AVG_RANK       SMALLINT, \
    COURSE_GROUP_DEVIATION      DECIMAL(4,1), \
    COURSE_GROUP_DEVIATION_RANK SMALLINT, \
    CHAIR_GROUP_RANK            SMALLINT, \
    CHAIR_GROUP_AVG_RANK        SMALLINT, \
    CHAIR_GROUP_DEVIATION       DECIMAL(4,1), \
    CHAIR_GROUP_DEVIATION_RANK  SMALLINT, \
    REGISTERCD            VARCHAR(10), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_RANK_SDIV_DAT ADD CONSTRAINT PK_REC_RANK_SD_DAT PRIMARY KEY (YEAR,SEMESTER,TESTKINDCD,TESTITEMCD,SCORE_DIV,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO)

INSERT INTO RECORD_RANK_SDIV_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        TESTKINDCD, \
        TESTITEMCD, \
        SCORE_DIV, \
        CLASSCD, \
        SCHOOL_KIND, \
        CURRICULUM_CD, \
        SUBCLASSCD, \
        SCHREGNO, \
        SCORE, \
        AVG, \
        GRADE_RANK, \
        GRADE_AVG_RANK, \
        GRADE_DEVIATION, \
        GRADE_DEVIATION_RANK, \
        CLASS_RANK, \
        CLASS_AVG_RANK, \
        CLASS_DEVIATION, \
        CLASS_DEVIATION_RANK, \
        COURSE_RANK, \
        COURSE_AVG_RANK, \
        COURSE_DEVIATION, \
        COURSE_DEVIATION_RANK, \
        MAJOR_RANK, \
        MAJOR_AVG_RANK, \
        MAJOR_DEVIATION, \
        MAJOR_DEVIATION_RANK, \
        COURSE_GROUP_RANK, \
        COURSE_GROUP_AVG_RANK, \
        COURSE_GROUP_DEVIATION, \
        COURSE_GROUP_DEVIATION_RANK, \
        CHAIR_GROUP_RANK, \
        CHAIR_GROUP_AVG_RANK, \
        CHAIR_GROUP_DEVIATION, \
        CHAIR_GROUP_DEVIATION_RANK, \
        REGISTERCD, \
        UPDATED \
    FROM \
        RECORD_RANK_SDIV_DAT_OLD

INSERT INTO RECORD_RANK_DETAIL_SDIV_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        TESTKINDCD, \
        TESTITEMCD, \
        SCORE_DIV, \
        CLASSCD, \
        SCHOOL_KIND, \
        CURRICULUM_CD, \
        SUBCLASSCD, \
        SCHREGNO, \
        'A' AS RANK_DIV, \
        COURSE_GROUP_CL_RANK AS RANK, \
        COURSE_GROUP_CL_AVG_RANK AS AVG_RANK, \
        COURSE_GROUP_CL_DEVIATION AS DEVIATION, \
        COURSE_GROUP_CL_DEVIATION_RANK AS DEVIATION_RANK, \
        REGISTERCD, \
        UPDATED \
    FROM \
        RECORD_RANK_SDIV_DAT_OLD \

