-- $Id: cd41ac32787592803ebe91cad51d8077d3b1855d $

DROP TABLE QUALIFIED_RANK_DAT_OLD
RENAME TABLE QUALIFIED_RANK_DAT TO QUALIFIED_RANK_DAT_OLD
CREATE TABLE QUALIFIED_RANK_DAT( \
    QUALIFIED_CD  VARCHAR(4)    NOT NULL, \
    RANK          VARCHAR(3)    NOT NULL, \
    NOT_PRINT     VARCHAR(1), \
    SCORE         SMALLINT, \
    REGISTERCD    VARCHAR(10), \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE QUALIFIED_RANK_DAT ADD CONSTRAINT PK_QUALI_RANK_DAT PRIMARY KEY (QUALIFIED_CD,RANK)

INSERT INTO QUALIFIED_RANK_DAT \
    SELECT \
        QUALIFIED_CD  , \
        RANK          , \
        CAST(NULL AS VARCHAR(1)) AS NOT_PRINT   , \
        CAST(NULL AS SMALLINT) AS SCORE         , \
        REGISTERCD    , \
        UPDATED         \
    FROM \
        QUALIFIED_RANK_DAT_OLD
