-- $Id: cb82a102c1c0ebe03b18ccdda84fd1093b1559ae $

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CAREERGUIDANCE_RECORD_DAT \
ALTER COLUMN \
    TEAM_MEMBERS \
SET DATA TYPE varchar(150)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CAREERGUIDANCE_RECORD_DAT \
ALTER COLUMN \
    MEETING_SUMMARY \
SET DATA TYPE varchar(600)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CAREERGUIDANCE_RECORD_DAT \
ALTER COLUMN \
    WORK_TRAINING_GOAL \
SET DATA TYPE varchar(600)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CAREERGUIDANCE_RECORD_DAT \
ALTER COLUMN \
    WORK_TRAINING_SUPPORT \
SET DATA TYPE varchar(600)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CAREERGUIDANCE_RECORD_DAT \
ALTER COLUMN \
    WORK_TRAINING_SUPPORT_TARGET \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CAREERGUIDANCE_RECORD_DAT \
ALTER COLUMN \
    WORK_TRAINING_RESULT \
SET DATA TYPE varchar(600)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CAREERGUIDANCE_RECORD_DAT \
ALTER COLUMN \
    WORK_TRAINING_CHALLENGE \
SET DATA TYPE varchar(600)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CAREERGUIDANCE_RECORD_DAT \
ALTER COLUMN \
    CAREER_GUIDANCE_RESULT \
SET DATA TYPE varchar(600)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CAREERGUIDANCE_RECORD_DAT \
ALTER COLUMN \
    CAREER_GUIDANCE_CHALLENGE \
SET DATA TYPE varchar(600)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CAREERGUIDANCE_RECORD_DAT \
ALTER COLUMN \
    COURSE_CONTENTS \
SET DATA TYPE varchar(450)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CAREERGUIDANCE_RECORD_DAT \
ALTER COLUMN \
    REMARK \
SET DATA TYPE varchar(630)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CAREERGUIDANCE_RECORD_DAT \
ALTER COLUMN \
    REGISTERCD \
SET DATA TYPE varchar(10)

