-- $Id: ba9e541438f0398daf23f1743c0d6b55a94056cf $

DROP TABLE GUARDIAN2_HIST_DAT_OLD
RENAME TABLE GUARDIAN2_HIST_DAT TO GUARDIAN2_HIST_DAT_OLD
CREATE TABLE GUARDIAN2_HIST_DAT( \
    SCHREGNO            VARCHAR(8)    NOT NULL, \
    ISSUEDATE           DATE          NOT NULL, \
    EXPIREDATE          DATE, \
    RELATIONSHIP        VARCHAR(2)    NOT NULL, \
    GUARD_NAME          VARCHAR(120), \
    GUARD_KANA          VARCHAR(240), \
    GUARD_REAL_NAME     VARCHAR(120), \
    GUARD_REAL_KANA     VARCHAR(240), \
    GUARD_SEX           VARCHAR(1), \
    GUARD_BIRTHDAY      DATE, \
    RELATIONSHIP_FLG    VARCHAR(1), \
    GUARD_NAME_FLG      VARCHAR(1), \
    GUARD_KANA_FLG      VARCHAR(1), \
    GUARD_REAL_NAME_FLG VARCHAR(120), \
    GUARD_REAL_KANA_FLG VARCHAR(240), \
    GUARD_SEX_FLG       VARCHAR(1), \
    GUARD_BIRTHDAY_FLG  VARCHAR(1), \
    REGISTERCD          VARCHAR(8), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO GUARDIAN2_HIST_DAT \
    SELECT \
        SCHREGNO, \
        ISSUEDATE, \
        EXPIREDATE, \
        RELATIONSHIP, \
        GUARD_NAME, \
        GUARD_KANA, \
        GUARD_REAL_NAME, \
        GUARD_REAL_KANA, \
        GUARD_SEX, \
        GUARD_BIRTHDAY, \
        RELATIONSHIP_FLG, \
        GUARD_NAME_FLG, \
        GUARD_KANA_FLG, \
        GUARD_REAL_NAME_FLG, \
        GUARD_REAL_KANA_FLG, \
        GUARD_SEX_FLG, \
        GUARD_BIRTHDAY_FLG, \
        REGISTERCD, \
        UPDATED \
    FROM \
        GUARDIAN2_HIST_DAT_OLD

ALTER TABLE GUARDIAN2_HIST_DAT ADD CONSTRAINT PK_GUARDIAN2_HIST PRIMARY KEY (SCHREGNO,ISSUEDATE)