-- $Id: 456d86c256e0aab013ef17c85a8f61f59cab9843 $

drop table EDBOARD_STAFF_WORK_HIST_DAT_OLD
create table EDBOARD_STAFF_WORK_HIST_DAT_OLD LIKE EDBOARD_STAFF_WORK_HIST_DAT
insert into EDBOARD_STAFF_WORK_HIST_DAT_OLD SELECT * FROM EDBOARD_STAFF_WORK_HIST_DAT

drop table EDBOARD_STAFF_WORK_HIST_DAT

CREATE TABLE EDBOARD_STAFF_WORK_HIST_DAT( \
    STAFFCD             VARCHAR(10) NOT NULL, \
    FROM_DATE           DATE        NOT NULL, \
    WORK_DIV            VARCHAR(1)  NOT NULL, \
    FROM_DIV            VARCHAR(2)  NOT NULL, \
    FROM_SCHOOLCD       VARCHAR(12), \
    FROM_COURSECD       VARCHAR(1), \
    TO_DATE             DATE, \
    TO_DIV              VARCHAR(2), \
    TO_SCHOOLCD         VARCHAR(12), \
    TO_COURSECD         VARCHAR(1), \
    REMARK              VARCHAR(150), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO EDBOARD_STAFF_WORK_HIST_DAT \
    SELECT \
        STAFFCD, \
        SDATE, \
        '0' AS WORK_DIV, \
        '02' AS FROM_DIV, \
        EDBOARD_SCHOOLCD, \
        CAST(NULL AS VARCHAR(1)), \
        EDATE, \
        CAST(NULL AS VARCHAR(2)), \
        CAST(NULL AS VARCHAR(12)), \
        CAST(NULL AS VARCHAR(1)), \
        REASON, \
        REGISTERCD, \
        UPDATED \
    FROM \
        EDBOARD_STAFF_WORK_HIST_DAT_OLD

ALTER TABLE EDBOARD_STAFF_WORK_HIST_DAT ADD CONSTRAINT PK_EDB_WORK_HIST PRIMARY KEY (STAFFCD, FROM_DATE, WORK_DIV)
