-- $Id: 05ae0bfef469f68b23465cf4b3cdcc1561756cc5 $

DROP TABLE GRD_HEXAM_EMPREMARK_DAT_OLD
RENAME TABLE GRD_HEXAM_EMPREMARK_DAT TO GRD_HEXAM_EMPREMARK_DAT_OLD
CREATE TABLE GRD_HEXAM_EMPREMARK_DAT( \
    SCHREGNO             VARCHAR(8)    NOT NULL, \
    JOBHUNT_REC          VARCHAR(618), \
    JOBHUNT_RECOMMEND    VARCHAR(2000), \
    JOBHUNT_ABSENCE      VARCHAR(190), \
    JOBHUNT_HEALTHREMARK VARCHAR(130), \
    REGISTERCD           VARCHAR(10), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO GRD_HEXAM_EMPREMARK_DAT \
    SELECT \
        SCHREGNO, \
        JOBHUNT_REC, \
        JOBHUNT_RECOMMEND, \
        JOBHUNT_ABSENCE, \
        JOBHUNT_HEALTHREMARK, \
        REGISTERCD, \
        UPDATED \
    FROM \
        GRD_HEXAM_EMPREMARK_DAT_OLD

ALTER TABLE GRD_HEXAM_EMPREMARK_DAT ADD CONSTRAINT PK_GRD_HEXAMEMP PRIMARY KEY (SCHREGNO)