-- $Id: 701bef04298757e8d487d5f5a10e544b68263741 $

DROP TABLE SUBCLASS_ADJUST_DAT_OLD
RENAME TABLE SUBCLASS_ADJUST_DAT TO SUBCLASS_ADJUST_DAT_OLD
CREATE TABLE SUBCLASS_ADJUST_DAT( \
    YEAR          VARCHAR(4) NOT NULL, \
    SEMESTER      VARCHAR(1) NOT NULL, \
    GRADE         VARCHAR(2) NOT NULL, \
    CLASSCD       VARCHAR(2) NOT NULL, \
    SCHOOL_KIND   VARCHAR(2) NOT NULL, \
    CURRICULUM_CD VARCHAR(2) NOT NULL, \
    SUBCLASSCD    VARCHAR(6) NOT NULL, \
    VALUE         SMALLINT, \
    REGISTERCD    VARCHAR(8),  \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) in usr1dms index in idx1dms

INSERT INTO SUBCLASS_ADJUST_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        GRADE, \
        LEFT(SUBCLASSCD, 2) AS CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        VALUE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SUBCLASS_ADJUST_DAT_OLD

alter table SUBCLASS_ADJUST_DAT \
add constraint PK_SUB_AD_DAT \
primary key ( YEAR, SEMESTER, GRADE, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)
