-- $Id: 91f54dd380b6ee43185ae3b744a20328927e55c8 $

DROP TABLE SCH_CHR_COUNTFLG_OLD
RENAME TABLE SCH_CHR_COUNTFLG TO SCH_CHR_COUNTFLG_OLD
CREATE TABLE SCH_CHR_COUNTFLG( \
    EXECUTEDATE DATE          NOT NULL, \
    PERIODCD    VARCHAR(1)    NOT NULL, \
    CHAIRCD     VARCHAR(7)    NOT NULL, \
    GRADE       VARCHAR(2)    NOT NULL, \
    HR_CLASS    VARCHAR(3)    NOT NULL, \
    COUNTFLG    VARCHAR(1), \
    LESSON_MODE VARCHAR(2)    NOT NULL, \
    REGISTERCD  VARCHAR(8), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SCH_CHR_COUNTFLG \
    SELECT \
        EXECUTEDATE, \
        PERIODCD, \
        CHAIRCD, \
        GRADE, \
        HR_CLASS, \
        COUNTFLG, \
        CAST('00' AS VARCHAR(2)) AS LESSON_MODE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SCH_CHR_COUNTFLG_OLD

ALTER TABLE SCH_CHR_COUNTFLG ADD CONSTRAINT PK_SCH_CHR_COUNT PRIMARY KEY (EXECUTEDATE,PERIODCD,CHAIRCD,GRADE,HR_CLASS)