-- kanji=漢字
-- $Id: ef97a2193c5a5656658dd48d754f5f7590a6bb08 $

DROP TABLE COURSE_GROUP_CD_HDAT_OLD
RENAME TABLE COURSE_GROUP_HDAT TO COURSE_GROUP_CD_HDAT_OLD
CREATE TABLE COURSE_GROUP_CD_HDAT( \
    YEAR       VARCHAR(4)    NOT NULL, \
    GRADE      VARCHAR(2)    NOT NULL, \
    GROUP_CD   VARCHAR(3)    NOT NULL, \
    GROUP_NAME VARCHAR(60), \
    GROUP_ABBV VARCHAR(60), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO COURSE_GROUP_CD_HDAT \
    SELECT \
        YEAR, \
        GRADE, \
        GROUP_CD, \
        GROUP_NAME, \
        GROUP_ABBV, \
        REGISTERCD, \
        UPDATED \
    FROM \
        COURSE_GROUP_CD_HDAT_OLD

ALTER TABLE COURSE_GROUP_CD_HDAT ADD CONSTRAINT PK_CSE_GRP_CD_HDAT PRIMARY KEY (YEAR,GRADE,GROUP_CD)