-- kanji=漢字
-- $Id: 444c1a04c3321e41e7ef5441d28d3575adae74a3 $

DROP TABLE MAJOR_MST_OLD
CREATE TABLE MAJOR_MST_OLD LIKE MAJOR_MST
INSERT INTO MAJOR_MST_OLD SELECT * FROM MAJOR_MST
DROP TABLE MAJOR_MST
CREATE TABLE MAJOR_MST( \
    COURSECD    VARCHAR(1)    NOT NULL, \
    MAJORCD     VARCHAR(3)    NOT NULL, \
    MAJORNAME   VARCHAR(60), \
    MAJORNAME2  VARCHAR(60), \
    MAJORNAME3  VARCHAR(60), \
    MAJORABBV   VARCHAR(6), \
    MAJORENG    VARCHAR(45), \
    MAJORBANKCD VARCHAR(2), \
    REGISTERCD  VARCHAR(10), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS


INSERT INTO MAJOR_MST \
    SELECT \
        COURSECD, \
        MAJORCD, \
        MAJORNAME, \
        MAJORNAME2, \
        MAJORNAME3, \
        MAJORABBV, \
        MAJORENG, \
        MAJORBANKCD, \
        REGISTERCD, \
        UPDATED \
    FROM \
        MAJOR_MST_OLD
ALTER TABLE MAJOR_MST ADD CONSTRAINT PK_MAJOR_MST PRIMARY KEY (COURSECD,MAJORCD)
