-- $Id: 601f228487b489be43bc2c371d2ac25689a44242 $

DROP TABLE RECORD_DOCUMENT_KIND_DAT_OLD
RENAME TABLE RECORD_DOCUMENT_KIND_DAT TO RECORD_DOCUMENT_KIND_DAT_OLD
CREATE TABLE RECORD_DOCUMENT_KIND_DAT( \
    YEAR            VARCHAR(4)    NOT NULL, \
    SEMESTER        VARCHAR(1)    NOT NULL, \
    TESTKINDCD      VARCHAR(2)    NOT NULL, \
    TESTITEMCD      VARCHAR(2)    NOT NULL, \
    GRADE           VARCHAR(2)    NOT NULL, \
    HR_CLASS        VARCHAR(3)    NOT NULL, \
    COURSECD        VARCHAR(1)    NOT NULL, \
    MAJORCD         VARCHAR(3)    NOT NULL, \
    COURSECODE      VARCHAR(4)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    KIND_DIV        VARCHAR(1)    NOT NULL, \
    FOOTNOTE        VARCHAR(1050), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO RECORD_DOCUMENT_KIND_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        TESTKINDCD, \
        TESTITEMCD, \
        GRADE, \
        HR_CLASS, \
        COURSECD, \
        MAJORCD, \
        COURSECODE, \
        LEFT(SUBCLASSCD, 2) AS CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        KIND_DIV, \
        FOOTNOTE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        RECORD_DOCUMENT_KIND_DAT_OLD

ALTER TABLE RECORD_DOCUMENT_KIND_DAT ADD CONSTRAINT PK_RECORD_D_K_DAT PRIMARY KEY (YEAR,SEMESTER,TESTKINDCD,TESTITEMCD,GRADE,HR_CLASS,COURSECD,MAJORCD,COURSECODE,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,KIND_DIV)
