-- kanji=漢字
-- $Id: aaf9fbf02ffd6881b2cf8d3714bd8989a89bba74 $

DROP TABLE STUDYREC_PROV_FLG_DAT_OLD

RENAME TABLE STUDYREC_PROV_FLG_DAT TO STUDYREC_PROV_FLG_DAT_OLD

CREATE TABLE STUDYREC_PROV_FLG_DAT ( \
    SCHOOLCD       VARCHAR(1)    NOT NULL, \
    YEAR           VARCHAR(4) NOT NULL, \
    SCHREGNO       VARCHAR(8) NOT NULL, \
    CLASSCD        VARCHAR(2) NOT NULL, \
    SCHOOL_KIND    VARCHAR(2) NOT NULL, \
    CURRICULUM_CD  VARCHAR(2) NOT NULL, \
    SUBCLASSCD     VARCHAR(6) NOT NULL, \
    PROV_FLG       VARCHAR(1), \
    PROV_SEMESTER   VARCHAR(1), \
    PROV_TESTKINDCD VARCHAR(2), \
    PROV_TESTITEMCD VARCHAR(2), \
    PROV_SCORE_DIV  VARCHAR(2), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO STUDYREC_PROV_FLG_DAT \
    SELECT \
        SCHOOLCD, \
        YEAR, \
        SCHREGNO, \
        CLASSCD, \
        SCHOOL_KIND, \
        CURRICULUM_CD, \
        SUBCLASSCD, \
        PROV_FLG, \
        CAST(NULL AS VARCHAR(1)) AS PROV_SEMESTER, \
        CAST(NULL AS VARCHAR(2)) AS PROV_TESTKINDCD, \
        CAST(NULL AS VARCHAR(2)) AS PROV_TESTITEMCD, \
        CAST(NULL AS VARCHAR(2)) AS PROV_SCORE_DIV, \
        REGISTERCD, \
        UPDATED \
    FROM \
        STUDYREC_PROV_FLG_DAT_OLD

ALTER TABLE STUDYREC_PROV_FLG_DAT ADD CONSTRAINT PK_STUDY_PRO_FLG_D \
      PRIMARY KEY (SCHOOLCD,YEAR,SCHREGNO,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)
