-- $Id: 054e4d0ee7e4839d7d676a916817da646c55bab8 $

DROP TABLE SCHREG_ABSENCE_HIGH_DAT_OLD
RENAME TABLE SCHREG_ABSENCE_HIGH_DAT TO SCHREG_ABSENCE_HIGH_DAT_OLD
CREATE TABLE SCHREG_ABSENCE_HIGH_DAT( \
    YEAR              VARCHAR(4)    NOT NULL, \
    DIV               VARCHAR(1)    NOT NULL, \
    CLASSCD           VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND       VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD     VARCHAR(2)    NOT NULL, \
    SUBCLASSCD        VARCHAR(6)    NOT NULL, \
    SCHREGNO          VARCHAR(8)    NOT NULL, \
    COMP_ABSENCE_HIGH DECIMAL(4,1), \
    GET_ABSENCE_HIGH  DECIMAL(4,1), \
    LESSON            SMALLINT, \
    APPOINTED_DATE    DATE, \
    REGISTERCD        VARCHAR(8), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SCHREG_ABSENCE_HIGH_DAT \
    SELECT \
        YEAR, \
        DIV, \
        LEFT(SUBCLASSCD, 2) AS CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        SCHREGNO, \
        COMP_ABSENCE_HIGH, \
        GET_ABSENCE_HIGH, \
        LESSON, \
        APPOINTED_DATE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SCHREG_ABSENCE_HIGH_DAT_OLD

ALTER TABLE SCHREG_ABSENCE_HIGH_DAT ADD CONSTRAINT PK_SCHREG_A_H_DAT PRIMARY KEY (YEAR,DIV,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO)