-- $Id: 57614e7eb2a8733c72050a1324c95887a987c000 $

DROP TABLE SUBCLASS_REPLACE_COMBINED_DAT_OLD
RENAME TABLE SUBCLASS_REPLACE_COMBINED_DAT TO SUBCLASS_REPLACE_COMBINED_DAT_OLD
CREATE TABLE SUBCLASS_REPLACE_COMBINED_DAT( \
    REPLACECD                 VARCHAR(1) NOT NULL, \
    YEAR                      VARCHAR(4) NOT NULL, \
    COMBINED_CLASSCD          VARCHAR(2) NOT NULL, \
    COMBINED_SCHOOL_KIND      VARCHAR(2) NOT NULL, \
    COMBINED_CURRICULUM_CD    VARCHAR(2) NOT NULL, \
    COMBINED_SUBCLASSCD       VARCHAR(6) NOT NULL, \
    ATTEND_CLASSCD            VARCHAR(2) NOT NULL, \
    ATTEND_SCHOOL_KIND        VARCHAR(2) NOT NULL, \
    ATTEND_CURRICULUM_CD      VARCHAR(2) NOT NULL, \
    ATTEND_SUBCLASSCD         VARCHAR(6) NOT NULL, \
    CALCULATE_CREDIT_FLG      VARCHAR(1), \
    STUDYREC_CREATE_FLG       VARCHAR(1), \
    PRINT_FLG1                VARCHAR(1), \
    PRINT_FLG2                VARCHAR(1), \
    PRINT_FLG3                VARCHAR(1), \
    WEIGHTING                 DECIMAL(3,2), \
    REGISTERCD                VARCHAR(8), \
    UPDATED                   TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) in usr1dms index in idx1dms

INSERT INTO SUBCLASS_REPLACE_COMBINED_DAT \
    SELECT \
        REPLACECD, \
        YEAR, \
        COMBINED_CLASSCD, \
        COMBINED_SCHOOL_KIND, \
        COMBINED_CURRICULUM_CD, \
        COMBINED_SUBCLASSCD, \
        ATTEND_CLASSCD, \
        ATTEND_SCHOOL_KIND, \
        ATTEND_CURRICULUM_CD, \
        ATTEND_SUBCLASSCD, \
        CALCULATE_CREDIT_FLG, \
        STUDYREC_CREATE_FLG, \
        PRINT_FLG1, \
        PRINT_FLG2, \
        PRINT_FLG3, \
        CAST(NULL AS DECIMAL(3,2)), \
        REGISTERCD, \
        UPDATED \
    FROM \
        SUBCLASS_REPLACE_COMBINED_DAT_OLD

alter table SUBCLASS_REPLACE_COMBINED_DAT add constraint PK_SUBREPCOMB_DAT \
        primary key (YEAR, COMBINED_CLASSCD, COMBINED_SCHOOL_KIND, COMBINED_CURRICULUM_CD, COMBINED_SUBCLASSCD, ATTEND_CLASSCD, ATTEND_SCHOOL_KIND, ATTEND_CURRICULUM_CD, ATTEND_SUBCLASSCD)
