-- $Id: 78c729ba79785a29e45b1e01ec7fa8bcbd1a4265 $

DROP TABLE COLLEGE_CAMPUS_ADDR_DAT_OLD
RENAME TABLE COLLEGE_CAMPUS_ADDR_DAT TO COLLEGE_CAMPUS_ADDR_DAT_OLD
CREATE TABLE COLLEGE_CAMPUS_ADDR_DAT( \
    SCHOOL_CD      VARCHAR(8)    NOT NULL, \
    CAMPUS_ADDR_CD VARCHAR(2)    NOT NULL, \
    PREF_CD        VARCHAR(2), \
    ZIPCD          VARCHAR(8), \
    ADDR1          VARCHAR(90), \
    ADDR2          VARCHAR(90), \
    TELNO          VARCHAR(16), \
    REGISTERCD     VARCHAR(8), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO COLLEGE_CAMPUS_ADDR_DAT \
    SELECT \
        SCHOOL_CD, \
        CAMPUS_ADDR_CD, \
        CAST(NULL AS VARCHAR(2)) AS PREF_CD, \
        ZIPCD, \
        ADDR1, \
        ADDR2, \
        TELNO, \
        REGISTERCD, \
        UPDATED \
    FROM \
        COLLEGE_CAMPUS_ADDR_DAT_OLD

ALTER TABLE COLLEGE_CAMPUS_ADDR_DAT ADD CONSTRAINT PK_COLLEGE_C_A_DAT PRIMARY KEY (SCHOOL_CD,CAMPUS_ADDR_CD)