-- $Id: f4f928edd68260e2076caf91a1a47803627c4aaa $
DROP TABLE EDBOARD_FINSCHOOL_DAT_OLD
CREATE TABLE EDBOARD_FINSCHOOL_DAT_OLD LIKE EDBOARD_FINSCHOOL_DAT
INSERT INTO EDBOARD_FINSCHOOL_DAT_OLD SELECT * FROM EDBOARD_FINSCHOOL_DAT

DROP TABLE EDBOARD_FINSCHOOL_DAT
CREATE TABLE EDBOARD_FINSCHOOL_DAT( \
    EDBOARD_SCHOOLCD    VARCHAR(12)  NOT NULL, \
    FINSCHOOLCD         VARCHAR(12)  NOT NULL, \
    EDBOARD_FLG         VARCHAR(1), \
    REGISTERCD          VARCHAR(8), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS


INSERT INTO EDBOARD_FINSCHOOL_DAT \
    SELECT \
        * \
    FROM \
        EDBOARD_FINSCHOOL_DAT_OLD

ALTER TABLE EDBOARD_FINSCHOOL_DAT ADD CONSTRAINT PK_ED_FINSCHL_DAT PRIMARY KEY (EDBOARD_SCHOOLCD, FINSCHOOLCD)