-- $Id: 95c7342a3cce6f7779cf86b1c11d19f280667a9a $

drop table HTRAINREMARK_DETAIL_DAT_OLD
create table HTRAINREMARK_DETAIL_DAT_OLD like HTRAINREMARK_DETAIL_DAT
insert into HTRAINREMARK_DETAIL_DAT_OLD select * from HTRAINREMARK_DETAIL_DAT

DROP TABLE HTRAINREMARK_DETAIL_DAT

CREATE TABLE HTRAINREMARK_DETAIL_DAT( \
    YEAR             VARCHAR(4)    NOT NULL, \
    SCHREGNO         VARCHAR(8)    NOT NULL, \
    TRAIN_REF1       VARCHAR(1740), \
    TRAIN_REF2       VARCHAR(453), \
    TRAIN_REF3       VARCHAR(453), \
    REGISTERCD       VARCHAR(10), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HTRAINREMARK_DETAIL_DAT ADD CONSTRAINT PK_HTRAINREMARK_DE PRIMARY KEY (YEAR, SCHREGNO)

insert into HTRAINREMARK_DETAIL_DAT select * from HTRAINREMARK_DETAIL_DAT_OLD
