-- $Id: 1bccd71b462ea4c9d5fd7952352b4fc37ece77a9 $

drop table COMMITTEE_ADVISER_DAT_OLD
create table COMMITTEE_ADVISER_DAT_OLD like COMMITTEE_ADVISER_DAT
insert into COMMITTEE_ADVISER_DAT_OLD select * from COMMITTEE_ADVISER_DAT

DROP TABLE COMMITTEE_ADVISER_DAT

CREATE TABLE COMMITTEE_ADVISER_DAT \
(  \
        "SCHOOLCD"      VARCHAR(12)     NOT NULL, \
        "SCHOOL_KIND"   VARCHAR(2)      NOT NULL, \
        "YEAR"          VARCHAR(4)      NOT NULL, \
        "COMMITTEE_FLG" VARCHAR(1)      NOT NULL, \
        "COMMITTEECD"   VARCHAR(4)      NOT NULL, \
        "ADVISER"       VARCHAR(10)      NOT NULL, \
        "COMMITTEEDIV"  VARCHAR(2), \
        "REGISTERCD"    VARCHAR(10), \
        "UPDATED"       TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE COMMITTEE_ADVISER_DAT  \
ADD CONSTRAINT PK_COMMITTEE_AD  \
PRIMARY KEY  \
(SCHOOLCD, SCHOOL_KIND, YEAR, COMMITTEE_FLG, COMMITTEECD, ADVISER)

insert into COMMITTEE_ADVISER_DAT \
select \
        '000000000000' AS SCHOOLCD, \
        'H' AS SCHOOL_KIND, \
        YEAR, \
        COMMITTEE_FLG, \
        COMMITTEECD, \
        ADVISER, \
        COMMITTEEDIV, \
        REGISTERCD, \
        UPDATED \
from COMMITTEE_ADVISER_DAT_OLD
