-- $Id: f2cef5418b62b368b348b024cb53a0764326cbc1 $

drop table USERGROUP_DAT_OLD
create table USERGROUP_DAT_OLD like USERGROUP_DAT
insert into USERGROUP_DAT_OLD select * from USERGROUP_DAT

DROP TABLE USERGROUP_DAT
CREATE TABLE USERGROUP_DAT( \
    YEAR           VARCHAR(4)  NOT NULL, \
    SCHOOLCD       VARCHAR(12) NOT NULL, \
    SCHOOL_KIND    VARCHAR(2)  NOT NULL, \
    GROUPCD        VARCHAR(4)  NOT NULL, \
    STAFFCD        VARCHAR(10) NOT NULL, \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO USERGROUP_DAT \
    SELECT \
        YEAR, \
        '000000000000', \
        'H', \
        GROUPCD, \
        STAFFCD, \
        REGISTERCD, \
        UPDATED \
    FROM \
        USERGROUP_DAT_OLD

ALTER TABLE USERGROUP_DAT ADD CONSTRAINT PK_USERGROUP_DAT PRIMARY KEY (YEAR, SCHOOLCD, SCHOOL_KIND, GROUPCD, STAFFCD)