-- $Id: 3b4a84fd5bf099377bb25216d67b3eac3ee8bbe4 $

DROP TABLE HEXAM_PHYSICAL_AVG_DAT_OLD
RENAME TABLE HEXAM_PHYSICAL_AVG_DAT TO HEXAM_PHYSICAL_AVG_DAT_OLD
CREATE TABLE HEXAM_PHYSICAL_AVG_DAT( \
    YEAR                 VARCHAR(4)    NOT NULL, \
    SEX                  VARCHAR(1)    NOT NULL, \
    NENREI_YEAR          SMALLINT      NOT NULL, \
    NENREI_MONTH         SMALLINT      NOT NULL, \
    HEIGHT_AVG           DECIMAL(4, 1), \
    HEIGHT_SD            DECIMAL(4, 1), \
    WEIGHT_AVG           DECIMAL(4, 1), \
    WEIGHT_SD            DECIMAL(4, 1), \
    STD_WEIGHT_KEISU_A   DECIMAL(6, 3), \
    STD_WEIGHT_KEISU_B   DECIMAL(6, 3), \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE HEXAM_PHYSICAL_AVG_DAT ADD CONSTRAINT PK_HEXAM_P_AVG_DAT PRIMARY KEY (YEAR, SEX, NENREI_YEAR, NENREI_MONTH)

INSERT INTO HEXAM_PHYSICAL_AVG_DAT \
    SELECT \
        YEAR, \
        SEX, \
        NENREI_YEAR, \
        NENREI_MONTH, \
        HEIGHT_AVG, \
        HEIGHT_SD, \
        WEIGHT_AVG, \
        WEIGHT_SD, \
        CAST(NULL AS DECIMAL(6, 3)), \
        CAST(NULL AS DECIMAL(6, 3)), \
        REGISTERCD, \
        UPDATED \
    FROM \
        HEXAM_PHYSICAL_AVG_DAT_OLD
