-- $Id: 9a44bd797e12ed90918d56e21dd00e3155152243 $

DROP TABLE SUBCLASS_STD_SELECT_DAT_OLD
RENAME TABLE SUBCLASS_STD_SELECT_DAT TO SUBCLASS_STD_SELECT_DAT_OLD
CREATE TABLE SUBCLASS_STD_SELECT_DAT( \
    YEAR            VARCHAR(4) NOT NULL, \
    SEMESTER        VARCHAR(1) NOT NULL, \
    RIREKI_CODE     VARCHAR(2) NOT NULL, \
    GROUPCD         VARCHAR(3) NOT NULL, \
    CLASSCD         VARCHAR(2) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    CURRICULUM_CD   VARCHAR(2) NOT NULL, \
    SUBCLASSCD      VARCHAR(6) NOT NULL, \
    SCHREGNO        VARCHAR(8) NOT NULL, \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) in usr1dms index in idx1dms

INSERT INTO SUBCLASS_STD_SELECT_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        '01' AS RIREKI_CODE, \
        GROUPCD, \
        CLASSCD, \
        SCHOOL_KIND, \
        CURRICULUM_CD, \
        SUBCLASSCD, \
        SCHREGNO, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SUBCLASS_STD_SELECT_DAT_OLD

alter table SUBCLASS_STD_SELECT_DAT add constraint PK_SUBCLASS_SSD \
primary key (YEAR,SEMESTER,RIREKI_CODE,GROUPCD,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO)
