-- kanji=´Á»ú
-- $Id: 3f5d47b8fe4561119dc5352105cb345ca7f743f6 $

DROP TABLE HREPORTREMARK_DETAIL_DAT_OLD
RENAME TABLE HREPORTREMARK_DETAIL_DAT TO HREPORTREMARK_DETAIL_DAT_OLD
CREATE TABLE HREPORTREMARK_DETAIL_DAT \
    (YEAR                 VARCHAR(4) NOT NULL, \
     SEMESTER             VARCHAR(1) NOT NULL, \
     SCHREGNO             VARCHAR(8) NOT NULL, \
     DIV                  VARCHAR(2) NOT NULL, \
     CODE                 VARCHAR(2) NOT NULL, \
     REMARK1              VARCHAR(1500), \
     REMARK2              VARCHAR(1500), \
     REMARK3              VARCHAR(1500), \
     REMARK4              VARCHAR(3000), \
     REGISTERCD           VARCHAR(8), \
     UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS
    
INSERT INTO HREPORTREMARK_DETAIL_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        SCHREGNO, \
        DIV, \
        CODE, \
        REMARK1, \
        REMARK2, \
        REMARK3, \
        CAST(NULL AS VARCHAR(3000)) AS REMARK4, \
        REGISTERCD, \
        UPDATED \
    FROM \
        HREPORTREMARK_DETAIL_DAT_OLD

ALTER TABLE HREPORTREMARK_DETAIL_DAT ADD CONSTRAINT PK_HREP_DETAIL_DAT PRIMARY KEY (YEAR, SEMESTER, SCHREGNO, DIV, CODE)
