-- $Id: bb285fa909a1deecddf54baf67909e45061db814 $


drop table SCHREG_CHALLENGED_PROFILE_WELFARE_RECORD_DAT_OLD

rename table SCHREG_CHALLENGED_PROFILE_WELFARE_RECORD_DAT to SCHREG_CHALLENGED_PROFILE_WELFARE_RECORD_DAT_OLD

create table SCHREG_CHALLENGED_PROFILE_WELFARE_RECORD_DAT( \
    SCHREGNO                 VARCHAR(8)    NOT NULL, \
    RECORD_DATE              VARCHAR(10)   NOT NULL, \
    RECORD_DIV               VARCHAR(1)    NOT NULL, \
    RECORD_NO                VARCHAR(1)    NOT NULL, \
    RECORD_SEQ               SMALLINT      NOT NULL, \
    SERVICE_NAME             VARCHAR(105) , \
    ITEMCD                   VARCHAR(3)   , \
    ITEMCD2                  VARCHAR(3)   , \
    ITEMCD3                  VARCHAR(3)   , \
    SUPPLY_DATE              DATE         , \
    CENTERCD                 VARCHAR(5)   , \
    SERVICE_CENTER_TEXT      VARCHAR(300) , \
    SERVICE_CENTERCD         VARCHAR(10)  , \
    SERVICE_CENTERCD_EDABAN  VARCHAR(2)   , \
    SERVICE_CHARGE  VARCHAR(15)   , \
    WELFARE_REMARK           VARCHAR(120) , \
    REGISTERCD               VARCHAR(10)  , \
    UPDATED                  TIMESTAMP     DEFAULT CURRENT TIMESTAMP \
 ) in usr1dms index in idx1dms

alter table SCHREG_CHALLENGED_PROFILE_WELFARE_RECORD_DAT add constraint PK_CHAL_PROF_WRD primary key (SCHREGNO,RECORD_DATE,RECORD_DIV,RECORD_NO,RECORD_SEQ)

insert into SCHREG_CHALLENGED_PROFILE_WELFARE_RECORD_DAT( \
    SCHREGNO, \
    RECORD_DATE, \
    RECORD_DIV, \
    RECORD_NO, \
    RECORD_SEQ, \
    SERVICE_NAME, \
    ITEMCD, \
    ITEMCD2, \
    ITEMCD3, \
    SUPPLY_DATE, \
    CENTERCD, \
    SERVICE_CENTER_TEXT, \
    SERVICE_CENTERCD, \
    SERVICE_CENTERCD_EDABAN, \
    SERVICE_CHARGE, \
    WELFARE_REMARK, \
    REGISTERCD, \
    UPDATED \
 ) select  \
    SCHREGNO, \
    RECORD_DATE, \
    RECORD_DIV, \
    RECORD_NO, \
    RECORD_SEQ, \
    SERVICE_NAME, \
    ITEMCD, \
    ITEMCD2, \
    ITEMCD3, \
    SUPPLY_DATE, \
    CENTERCD, \
    CAST(NULL AS VARCHAR(1)) AS SERVICE_CENTER_TEXT, \
    SERVICE_CENTERCD, \
    SERVICE_CENTERCD_EDABAN, \
    SERVICE_CHARGE, \
    WELFARE_REMARK, \
    REGISTERCD, \
    UPDATED \
 from SCHREG_CHALLENGED_PROFILE_WELFARE_RECORD_DAT_OLD

