-- $Id: 69dc642bf2f4698ed71f713f53afbe2bd48e37c8 $

drop table SCHREG_NAME_SETUP_DAT_OLD
create table SCHREG_NAME_SETUP_DAT_OLD like SCHREG_NAME_SETUP_DAT
insert into SCHREG_NAME_SETUP_DAT_OLD select * from SCHREG_NAME_SETUP_DAT

DROP TABLE SCHREG_NAME_SETUP_DAT
CREATE TABLE SCHREG_NAME_SETUP_DAT( \
    SCHREGNO            VARCHAR(8)    NOT NULL, \
    DIV                 VARCHAR(2)    NOT NULL, \
    NAME_OUTPUT_FLG     VARCHAR(1), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SCHREG_NAME_SETUP_DAT ADD CONSTRAINT PK_SCHREG_N_S_DAT PRIMARY KEY (SCHREGNO,DIV)

insert into SCHREG_NAME_SETUP_DAT \
  select \
        SCHREGNO, \
        DIV, \
        NAME_OUTPUT_FLG, \
        REGISTERCD, \
        UPDATED \
  from SCHREG_NAME_SETUP_DAT_OLD
