-- kanji=漢字
-- $Id: 69bcc3397df1ef0b4699b01b176870824564f94b $

DROP TABLE JOBTYPE_L_MST_OLD
RENAME TABLE JOBTYPE_L_MST TO JOBTYPE_L_MST_OLD
CREATE TABLE JOBTYPE_L_MST( \
    JOBTYPE_LCD        VARCHAR(2)    NOT NULL, \
    JOBTYPE_LNAME      VARCHAR(150), \
    JOBTYPE_LNAME_KANA VARCHAR(300), \
    REGISTERCD         VARCHAR(10), \
    UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS


INSERT INTO JOBTYPE_L_MST \
    SELECT \
        JOBTYPE_LCD, \
        JOBTYPE_LNAME, \
        JOBTYPE_LNAME_KANA, \
        REGISTERCD, \
        UPDATED \
    FROM \
        JOBTYPE_L_MST_OLD
ALTER TABLE JOBTYPE_L_MST ADD CONSTRAINT PK_JOBTYPE_L_MST PRIMARY KEY (JOBTYPE_LCD)