-- $Id: 7f6465eb90c56104fed022cd62494b6cb3d6b035 $

DROP TABLE RELATIVEASSESS_MST_OLD
RENAME TABLE RELATIVEASSESS_MST TO RELATIVEASSESS_MST_OLD
CREATE TABLE RELATIVEASSESS_MST( \
     GRADE          VARCHAR(2)   NOT NULL, \
     CLASSCD        VARCHAR(2)   NOT NULL, \
     SCHOOL_KIND    VARCHAR(2)   NOT NULL, \
     CURRICULUM_CD  VARCHAR(2)   NOT NULL, \
     SUBCLASSCD     VARCHAR(6)   NOT NULL, \
     ASSESSCD       VARCHAR(1)   NOT NULL, \
     ASSESSLEVEL    SMALLINT     NOT NULL, \
     ASSESSMARK     VARCHAR(6), \
     ASSESSLOW      DECIMAL(4,1), \
     ASSESSHIGH     DECIMAL(4,1), \
     REGISTERCD     VARCHAR(8), \
     UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) in usr1dms index in idx1dms

INSERT INTO RELATIVEASSESS_MST \
    SELECT \
        GRADE, \
        LEFT(SUBCLASSCD, 2) AS CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        ASSESSCD, \
        ASSESSLEVEL, \
        ASSESSMARK, \
        ASSESSLOW, \
        ASSESSHIGH, \
        REGISTERCD, \
        UPDATED \
    FROM \
        RELATIVEASSESS_MST_OLD

alter table RELATIVEASSESS_MST add constraint pk_relaassess_mst primary key \
    (GRADE, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, ASSESSCD, ASSESSLEVEL)