-- $Id: 8b04ea04cf7e69ef172541ae2a9109bfc0931e3e $

DROP TABLE ATTEND_SUBCLASS_SPECIAL_DAT_OLD
RENAME TABLE ATTEND_SUBCLASS_SPECIAL_DAT TO ATTEND_SUBCLASS_SPECIAL_DAT_OLD
CREATE TABLE ATTEND_SUBCLASS_SPECIAL_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    SPECIAL_GROUP_CD    VARCHAR(3) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    CURRICULUM_CD       VARCHAR(2) NOT NULL, \
    SUBCLASSCD          VARCHAR(6) NOT NULL, \
    MINUTES             VARCHAR(3), \
    REGISTERCD          VARCHAR(8), \
    UPDATED             timestamp default current timestamp \
) in usr1dms index in idx1dms

INSERT INTO ATTEND_SUBCLASS_SPECIAL_DAT \
    SELECT \
        YEAR, \
        SPECIAL_GROUP_CD, \
        LEFT(SUBCLASSCD, 2) AS CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        MINUTES, \
        REGISTERCD, \
        UPDATED \
    FROM \
        ATTEND_SUBCLASS_SPECIAL_DAT_OLD

alter table ATTEND_SUBCLASS_SPECIAL_DAT add constraint PK_ATTND_SS_DAT \
primary key (YEAR,SPECIAL_GROUP_CD,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)
