-- $Id: 9423567ed647372d362ead6696542c7239620722 $

ALTER TABLE HREPORT_GUIDANCE_ITEM_NAME_DAT ALTER COLUMN ITEM_REMARK1 SET DATA TYPE varchar(120)
ALTER TABLE HREPORT_GUIDANCE_ITEM_NAME_DAT ALTER COLUMN ITEM_REMARK2 SET DATA TYPE varchar(120)
ALTER TABLE HREPORT_GUIDANCE_ITEM_NAME_DAT ALTER COLUMN ITEM_REMARK3 SET DATA TYPE varchar(120)
ALTER TABLE HREPORT_GUIDANCE_ITEM_NAME_DAT ALTER COLUMN ITEM_REMARK4 SET DATA TYPE varchar(120)
ALTER TABLE HREPORT_GUIDANCE_ITEM_NAME_DAT ALTER COLUMN ITEM_REMARK5 SET DATA TYPE varchar(120)
ALTER TABLE HREPORT_GUIDANCE_ITEM_NAME_DAT ALTER COLUMN ITEM_REMARK6 SET DATA TYPE varchar(120)
ALTER TABLE HREPORT_GUIDANCE_ITEM_NAME_DAT ALTER COLUMN ITEM_REMARK7 SET DATA TYPE varchar(120)
ALTER TABLE HREPORT_GUIDANCE_ITEM_NAME_DAT ALTER COLUMN ITEM_REMARK8 SET DATA TYPE varchar(120)

