-- kanji=漢字
-- $Id: f1c46ae00ee43fe2668e2a3d386bac79f62ed653 $

DROP TABLE JOBTYPE_M_MST_OLD
RENAME TABLE JOBTYPE_M_MST TO JOBTYPE_M_MST_OLD
CREATE TABLE JOBTYPE_M_MST( \
    JOBTYPE_LCD        VARCHAR(2)    NOT NULL, \
    JOBTYPE_MCD        VARCHAR(2)    NOT NULL, \
    JOBTYPE_MNAME      VARCHAR(150), \
    JOBTYPE_MNAME_KANA VARCHAR(300), \
    REGISTERCD         VARCHAR(10), \
    UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS


INSERT INTO JOBTYPE_M_MST \
    SELECT \
        JOBTYPE_LCD, \
        JOBTYPE_MCD, \
        JOBTYPE_MNAME, \
        JOBTYPE_MNAME_KANA, \
        REGISTERCD, \
        UPDATED \
    FROM \
        JOBTYPE_M_MST_OLD
ALTER TABLE JOBTYPE_M_MST ADD CONSTRAINT PK_JOBTYPE_M_MST PRIMARY KEY (JOBTYPE_LCD,JOBTYPE_MCD)