-- $Id: bc15f3479ce9ba8b918e34121af46a660763a3ca $

DROP TABLE PRGINFO_PROPERTIES_OLD
RENAME TABLE PRGINFO_PROPERTIES TO PRGINFO_PROPERTIES_OLD
CREATE TABLE PRGINFO_PROPERTIES( \
    PROGRAMID      VARCHAR(20)   NOT NULL, \
    NAME           VARCHAR(50)   NOT NULL, \
    VALUE          VARCHAR(300), \
    SORT           SMALLINT    , \
    REMARK         VARCHAR(300), \
    COMMENT_1      VARCHAR(300), \
    COMMENT_2      VARCHAR(300), \
    COMMENT_3      VARCHAR(300), \
    COMMENT_4      VARCHAR(300), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE PRGINFO_PROPERTIES ADD CONSTRAINT PK_PROPERTIES PRIMARY KEY (PROGRAMID, NAME)
