-- $Id: ec14aea48e1c14d0753ac32407a673945d922212 $

DROP TABLE GUARANTOR_ADDRESS_DAT_OLD
RENAME TABLE GUARANTOR_ADDRESS_DAT TO GUARANTOR_ADDRESS_DAT_OLD
CREATE TABLE GUARANTOR_ADDRESS_DAT( \
    SCHREGNO               VARCHAR(8)    NOT NULL, \
    ISSUEDATE              DATE          NOT NULL, \
    EXPIREDATE             DATE, \
    GUARANTOR_ZIPCD        VARCHAR(8), \
    GUARANTOR_ADDR1        VARCHAR(150), \
    GUARANTOR_ADDR2        VARCHAR(150), \
    GUARANTOR_ADDR_FLG     VARCHAR(1), \
    GUARANTOR_TELNO        VARCHAR(14), \
    REGISTERCD             VARCHAR(8), \
    UPDATED                TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO GUARANTOR_ADDRESS_DAT \
    SELECT \
        SCHREGNO, \
        ISSUEDATE, \
        EXPIREDATE, \
        GUARANTOR_ZIPCD, \
        GUARANTOR_ADDR1, \
        GUARANTOR_ADDR2, \
        GUARANTOR_ADDR_FLG, \
        GUARANTOR_TELNO, \
        REGISTERCD, \
        UPDATED \
    FROM \
        GUARANTOR_ADDRESS_DAT_OLD

ALTER TABLE GUARANTOR_ADDRESS_DAT ADD CONSTRAINT PK_GUARANTOR_ADD PRIMARY KEY (SCHREGNO, ISSUEDATE)