-- $Id: a0cc33dcc1debc16c04680193b11f776d9e54396 $

DROP TABLE HREPORT_GUIDANCE_GROUP_UNIT_DAT_OLD
RENAME TABLE HREPORT_GUIDANCE_GROUP_UNIT_DAT TO HREPORT_GUIDANCE_GROUP_UNIT_DAT_OLD
CREATE TABLE HREPORT_GUIDANCE_GROUP_UNIT_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    SEMESTER            VARCHAR(1) NOT NULL, \
    GAKUBU_SCHOOL_KIND  VARCHAR(2) NOT NULL, \
    GHR_CD              VARCHAR(2) NOT NULL, \
    GRADE               VARCHAR(2) NOT NULL, \
    HR_CLASS            VARCHAR(3) NOT NULL, \
    CONDITION           VARCHAR(1) NOT NULL, \
    GROUPCD             VARCHAR(4) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    CURRICULUM_CD       VARCHAR(2) NOT NULL, \
    SUBCLASSCD          VARCHAR(6) NOT NULL, \
    UNITCD              VARCHAR(2) NOT NULL, \
    GROUP_REMARK1       VARCHAR(708), \
    GROUP_REMARK2       VARCHAR(708), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO HREPORT_GUIDANCE_GROUP_UNIT_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        GAKUBU_SCHOOL_KIND, \
        GHR_CD, \
        GRADE, \
        HR_CLASS, \
        CONDITION, \
        GROUPCD, \
        CLASSCD, \
        SCHOOL_KIND, \
        CURRICULUM_CD, \
        SUBCLASSCD, \
        UNITCD, \
        GROUP_REMARK1, \
        CAST(NULL AS VARCHAR(708)) AS GROUP_REMARK2, \
        REGISTERCD, \
        UPDATED \
    FROM \
        HREPORT_GUIDANCE_GROUP_UNIT_DAT_OLD

ALTER TABLE HREPORT_GUIDANCE_GROUP_UNIT_DAT ADD CONSTRAINT PK_HREP_GUID_UNIT PRIMARY KEY (YEAR, SEMESTER, GAKUBU_SCHOOL_KIND, GHR_CD, GRADE, HR_CLASS, CONDITION, GROUPCD, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, UNITCD)