-- $Id: 15f0823f091e9929725690816296d06e9ac1ab24 $

DROP TABLE SUBCLASS_SEMVAL_PERCENT_SDIV_DAT_OLD

RENAME TABLE SUBCLASS_SEMVAL_PERCENT_SDIV_DAT TO SUBCLASS_SEMVAL_PERCENT_SDIV_DAT_OLD

CREATE TABLE SUBCLASS_SEMVAL_PERCENT_SDIV_DAT( \
    YEAR                     VARCHAR(4)   NOT NULL, \
    SEMESTER                 VARCHAR(1)   NOT NULL, \
    GRADE                    VARCHAR(2)   NOT NULL, \
    COURSECODE               VARCHAR(4)   NOT NULL, \
    GROUP_CD                 VARCHAR(3)   NOT NULL, \
    CLASSCD                  VARCHAR(2)   NOT NULL, \
    SCHOOL_KIND              VARCHAR(2)   NOT NULL, \
    CURRICULUM_CD            VARCHAR(2)   NOT NULL, \
    SUBCLASSCD               VARCHAR(6)   NOT NULL, \
    COMBINED_TESTKINDCD      VARCHAR(2)   NOT NULL, \
    COMBINED_TESTITEMCD      VARCHAR(2)   NOT NULL, \
    COMBINED_SCORE_DIV       VARCHAR(2)   NOT NULL, \
    SEQ                      SMALLINT     NOT NULL, \
    TESTDIV                  VARCHAR(1)  , \
    ATTEND_SEMESTER          VARCHAR(1)   NOT NULL, \
    ATTEND_TESTKINDCD        VARCHAR(2)   NOT NULL, \
    ATTEND_TESTITEMCD        VARCHAR(2)   NOT NULL, \
    ATTEND_SCORE_DIV         VARCHAR(2)   NOT NULL, \
    PROFICIENCYDIV           VARCHAR(2)  , \
    PROFICIENCYCD            VARCHAR(4)  , \
    PROFICIENCY_SUBCLASS_CD  VARCHAR(6)  , \
    PERCENT                  SMALLINT    , \
    PERFECT                  SMALLINT    , \
    REGISTERCD               VARCHAR(10) , \
    UPDATED                  TIMESTAMP    DEFAULT CURRENT TIMESTAMP \
 ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE SUBCLASS_SEMVAL_PERCENT_SDIV_DAT ADD CONSTRAINT PK_SEM_PERCSDIVD PRIMARY KEY (YEAR,SEMESTER,GRADE,COURSECODE,GROUP_CD,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,COMBINED_TESTKINDCD,COMBINED_TESTITEMCD,COMBINED_SCORE_DIV,SEQ)

INSERT INTO SUBCLASS_SEMVAL_PERCENT_SDIV_DAT( \
    YEAR, \
    SEMESTER, \
    GRADE, \
    COURSECODE, \
    GROUP_CD, \
    CLASSCD, \
    SCHOOL_KIND, \
    CURRICULUM_CD, \
    SUBCLASSCD, \
    COMBINED_TESTKINDCD, \
    COMBINED_TESTITEMCD, \
    COMBINED_SCORE_DIV, \
    SEQ, \
    TESTDIV, \
    ATTEND_SEMESTER, \
    ATTEND_TESTKINDCD, \
    ATTEND_TESTITEMCD, \
    ATTEND_SCORE_DIV, \
    PROFICIENCYDIV, \
    PROFICIENCYCD, \
    PROFICIENCY_SUBCLASS_CD, \
    PERCENT, \
    PERFECT, \
    REGISTERCD, \
    UPDATED \
 ) SELECT  \
    YEAR, \
    SEMESTER, \
    GRADE, \
    COURSECODE, \
    GROUP_CD, \
    SET_CLASSCD, \
    SET_SCHOOL_KIND, \
    SET_CURRICULUM_CD, \
    SET_SUBCLASSCD, \
    COMBINED_TESTKINDCD, \
    COMBINED_TESTITEMCD, \
    COMBINED_SCORE_DIV, \
    SEQ, \
    TESTDIV, \
    SEMESTER, \
    ATTEND_TESTKINDCD, \
    ATTEND_TESTITEMCD, \
    ATTEND_SCORE_DIV, \
    PROFICIENCYDIV, \
    PROFICIENCYCD, \
    PROFICIENCY_SUBCLASS_CD, \
    PERCENT, \
    PERFECT, \
    REGISTERCD, \
    UPDATED \
 FROM SUBCLASS_SEMVAL_PERCENT_SDIV_DAT_OLD

