-- $Id: 54d721e4b82f3cfb87545e76ade7a9c855917e39 $

DROP TABLE HREPORTREMARK_P_DAT_OLD
RENAME TABLE HREPORTREMARK_P_DAT TO HREPORTREMARK_P_DAT_OLD
CREATE TABLE HREPORTREMARK_P_DAT( \
    YEAR             VARCHAR(4)    NOT NULL, \
    SEMESTER         VARCHAR(1)    NOT NULL, \
    SCHREGNO         VARCHAR(8)    NOT NULL, \
    TOTALSTUDYTIME   VARCHAR(500), \
    SPECIALACTREMARK VARCHAR(323), \
    COMMUNICATION    VARCHAR(500), \
    REMARK1          VARCHAR(323), \
    REMARK2          VARCHAR(323), \
    REMARK3          VARCHAR(780), \
    FOREIGNLANGACT   VARCHAR(450), \
    ATTENDREC_REMARK VARCHAR(242), \
    REGISTERCD       VARCHAR(8), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO HREPORTREMARK_P_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        SCHREGNO, \
        TOTALSTUDYTIME, \
        SPECIALACTREMARK, \
        COMMUNICATION, \
        REMARK1, \
        REMARK2, \
        REMARK3, \
        FOREIGNLANGACT, \
        CAST(NULL AS VARCHAR(242)) AS ATTENDREC_REMARK, \
        REGISTERCD, \
        UPDATED \
    FROM \
        HREPORTREMARK_P_DAT_OLD

ALTER TABLE HREPORTREMARK_P_DAT ADD CONSTRAINT PK_HREPORTREMARKP PRIMARY KEY (YEAR,SEMESTER,SCHREGNO)