-- $Id: 1dd51cb1162375d37772dcd7af4d2f6e0e80bdba $

DROP TABLE RECORD_DOCUMENT_DAT_OLD
RENAME TABLE RECORD_DOCUMENT_DAT TO RECORD_DOCUMENT_DAT_OLD
CREATE TABLE RECORD_DOCUMENT_DAT( \
    YEAR            VARCHAR(4) NOT NULL, \
    SEMESTER        VARCHAR(1) NOT NULL, \
    TESTKINDCD      VARCHAR(2) NOT NULL, \
    TESTITEMCD      VARCHAR(2) NOT NULL, \
    GRADE           VARCHAR(2) NOT NULL, \
    COURSECD        VARCHAR(1) NOT NULL, \
    MAJORCD         VARCHAR(3) NOT NULL, \
    COURSECODE      VARCHAR(4) NOT NULL, \
    CLASSCD         VARCHAR(2) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    CURRICULUM_CD   VARCHAR(2) NOT NULL, \
    SUBCLASSCD      VARCHAR(6) NOT NULL, \
    FOOTNOTE        VARCHAR(1050), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) in usr1dms index in idx1dms

INSERT INTO RECORD_DOCUMENT_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        TESTKINDCD, \
        TESTITEMCD, \
        GRADE, \
        COURSECD, \
        MAJORCD, \
        COURSECODE, \
        LEFT(SUBCLASSCD, 2) AS CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        FOOTNOTE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        RECORD_DOCUMENT_DAT_OLD

alter table RECORD_DOCUMENT_DAT add constraint pk_record_doc_dat \
      primary key (YEAR, SEMESTER, TESTKINDCD, TESTITEMCD, GRADE, COURSECD, MAJORCD, COURSECODE, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)
