-- kanji=漢字
-- $Id: 346d508d8b3a7a1dd2e414804110ed820dc66972 $

DROP TABLE RECORD_PROV_FLG_DAT_OLD

RENAME TABLE RECORD_PROV_FLG_DAT TO RECORD_PROV_FLG_DAT_OLD

CREATE TABLE RECORD_PROV_FLG_DAT ( \
    YEAR           VARCHAR(4) NOT NULL, \
    CLASSCD        VARCHAR(2) NOT NULL, \
    SCHOOL_KIND    VARCHAR(2) NOT NULL, \
    CURRICULUM_CD  VARCHAR(2) NOT NULL, \
    SUBCLASSCD     VARCHAR(6) NOT NULL, \
    SCHREGNO       VARCHAR(8) NOT NULL, \
    PROV_FLG       VARCHAR(1), \
    PROV_SEMESTER   VARCHAR(1), \
    PROV_TESTKINDCD VARCHAR(2), \
    PROV_TESTITEMCD VARCHAR(2), \
    PROV_SCORE_DIV  VARCHAR(2), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO RECORD_PROV_FLG_DAT \
    SELECT \
        YEAR, \
        CLASSCD, \
        SCHOOL_KIND, \
        CURRICULUM_CD, \
        SUBCLASSCD, \
        SCHREGNO, \
        PROV_FLG, \
        CAST(NULL AS VARCHAR(1)) AS PROV_SEMESTER, \
        CAST(NULL AS VARCHAR(2)) AS PROV_TESTKINDCD, \
        CAST(NULL AS VARCHAR(2)) AS PROV_TESTITEMCD, \
        CAST(NULL AS VARCHAR(2)) AS PROV_SCORE_DIV, \
        REGISTERCD, \
        UPDATED \
    FROM \
        RECORD_PROV_FLG_DAT_OLD

ALTER TABLE RECORD_PROV_FLG_DAT ADD CONSTRAINT PK_REC_PRO_FLG_DT \
      PRIMARY KEY (YEAR,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO)
