-- $Id: f7424be5f61d3d23a96db68bd32313ce49d728a3 $

drop table SCHOOL_DIARY_DAT_OLD
create table SCHOOL_DIARY_DAT_OLD like SCHOOL_DIARY_DAT
insert into SCHOOL_DIARY_DAT_OLD select * from SCHOOL_DIARY_DAT

DROP TABLE SCHOOL_DIARY_DAT

CREATE TABLE SCHOOL_DIARY_DAT( \
    SCHOOLCD        VARCHAR(12) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)  NOT NULL, \
    DIARY_DATE      DATE        NOT NULL, \
    WEATHER         VARCHAR(1), \
    WEATHER2        VARCHAR(1), \
    NEWS            VARCHAR(3000), \
    STAFFNEWS       VARCHAR(2000), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SCHOOL_DIARY_DAT \
    SELECT \
        SCHOOLCD, \
        SCHOOL_KIND, \
        DIARY_DATE, \
        WEATHER, \
        WEATHER2, \
        NEWS, \
        STAFFNEWS, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SCHOOL_DIARY_DAT_OLD

ALTER TABLE SCHOOL_DIARY_DAT ADD CONSTRAINT PK_SCHOOL_DIARY PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, DIARY_DATE)
