-- $Id: 75ea7c81f0e8b49f866dca0442a99d48318972a7 $

drop table SCHOOL_DIARY_DETAIL_SEQ_DAT_OLD
create table SCHOOL_DIARY_DETAIL_SEQ_DAT_OLD like SCHOOL_DIARY_DETAIL_SEQ_DAT
insert into SCHOOL_DIARY_DETAIL_SEQ_DAT_OLD select * from SCHOOL_DIARY_DETAIL_SEQ_DAT

drop table SCHOOL_DIARY_DETAIL_SEQ_DAT

CREATE TABLE SCHOOL_DIARY_DETAIL_SEQ_DAT( \
    SCHOOLCD        VARCHAR(12) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)  NOT NULL, \
    DIARY_DATE      DATE        NOT NULL, \
    SEQ             VARCHAR(3)  NOT NULL, \
    REMARK1         VARCHAR(678), \
    REMARK2         VARCHAR(678), \
    REMARK3         VARCHAR(1428), \
    REMARK4         VARCHAR(678), \
    REMARK5         VARCHAR(678), \
    REMARK6         VARCHAR(474), \
    REMARK7         VARCHAR(474), \
    REMARK8         VARCHAR(474), \
    REMARK9         VARCHAR(338), \
    REMARK10        VARCHAR(338), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SCHOOL_DIARY_DETAIL_SEQ_DAT \
    SELECT \
        SCHOOLCD, \
        SCHOOL_KIND, \
        DIARY_DATE, \
        SEQ, \
        REMARK1, \
        REMARK2, \
        REMARK3, \
        REMARK4, \
        REMARK5, \
        REMARK6, \
        REMARK7, \
        REMARK8, \
        REMARK9, \
        REMARK10, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SCHOOL_DIARY_DETAIL_SEQ_DAT_OLD

ALTER TABLE SCHOOL_DIARY_DETAIL_SEQ_DAT ADD CONSTRAINT PK_SCHOOL_DIARSEQ PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, DIARY_DATE, SEQ)
