-- $Id: 418884ae4b816b7b79a44ae58b976f1fd46fba4c $

DROP TABLE GRD_ADDRESS_DAT_OLD
RENAME TABLE GRD_ADDRESS_DAT TO GRD_ADDRESS_DAT_OLD
CREATE TABLE GRD_ADDRESS_DAT( \
    SCHREGNO    VARCHAR(8)    NOT NULL, \
    ISSUEDATE   DATE          NOT NULL, \
    EXPIREDATE  DATE, \
    ZIPCD       VARCHAR(8), \
    AREACD      VARCHAR(2), \
    ADDR1       VARCHAR(150), \
    ADDR2       VARCHAR(150), \
    ADDR_FLG    VARCHAR(1), \
    ADDR1_ENG   VARCHAR(150), \
    ADDR2_ENG   VARCHAR(150), \
    TELNO       VARCHAR(14), \
    TELNO_MEMO  VARCHAR(24), \
    TELNO2      VARCHAR(14), \
    TELNO2_MEMO VARCHAR(24), \
    FAXNO       VARCHAR(14), \
    EMAIL       VARCHAR(20), \
    REGISTERCD  VARCHAR(10), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRD_ADDRESS_DAT ADD CONSTRAINT PK_GRD_ADDRESS PRIMARY KEY (SCHREGNO,ISSUEDATE)

INSERT INTO GRD_ADDRESS_DAT \
    SELECT \
        SCHREGNO, \
        ISSUEDATE, \
        EXPIREDATE, \
        ZIPCD, \
        AREACD, \
        ADDR1, \
        ADDR2, \
        ADDR_FLG, \
        ADDR1_ENG, \
        ADDR2_ENG, \
        TELNO, \
        CAST(NULL AS VARCHAR(24)) AS TELNO_MEMO, \
        CAST(NULL AS VARCHAR(14)) AS TELNO2, \
        CAST(NULL AS VARCHAR(24)) AS TELNO2_MEMO, \
        FAXNO, \
        EMAIL, \
        REGISTERCD, \
        UPDATED \
    FROM \
        GRD_ADDRESS_DAT_OLD

