-- $Id: 8963862a15c40464b15e5a60e22b8c5958b8ffd5 $

DROP TABLE PERFECT_RECORD_DAT_OLD
RENAME TABLE PERFECT_RECORD_DAT TO PERFECT_RECORD_DAT_OLD

create table PERFECT_RECORD_DAT \
(  \
    YEAR            VARCHAR(4) NOT NULL, \
    SEMESTER        VARCHAR(1) NOT NULL, \
    TESTKINDCD      VARCHAR(2) NOT NULL, \
    TESTITEMCD      VARCHAR(2) NOT NULL, \
    CLASSCD         VARCHAR(2) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    CURRICULUM_CD   VARCHAR(2) NOT NULL, \
    SUBCLASSCD      VARCHAR(6) NOT NULL, \
    DIV             VARCHAR(2) NOT NULL, \
    GRADE           VARCHAR(2) NOT NULL, \
    COURSECD        VARCHAR(1) NOT NULL, \
    MAJORCD         VARCHAR(3) NOT NULL, \
    COURSECODE      VARCHAR(4) NOT NULL, \
    PERFECT         SMALLINT, \
    PASS_SCORE      SMALLINT, \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) in usr1dms index in idx1dms

INSERT INTO PERFECT_RECORD_DAT \
        SELECT \
        YEAR, \
        SEMESTER, \
        TESTKINDCD, \
        TESTITEMCD, \
        CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        DIV, \
        GRADE, \
        COURSECD, \
        MAJORCD, \
        COURSECODE, \
        PERFECT, \
        PASS_SCORE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        PERFECT_RECORD_DAT_OLD


alter table PERFECT_RECORD_DAT add constraint PK_PERFECT_REC_DAT \
primary key (YEAR,SEMESTER,TESTKINDCD,TESTITEMCD,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,DIV,GRADE,COURSECD,MAJORCD,COURSECODE)
