-- $Id: 319e9017da74b1b61abc9b0c912055e376f38005 $

DROP TABLE ATTEND_PETITION_HDAT_OLD
RENAME TABLE ATTEND_PETITION_HDAT TO ATTEND_PETITION_HDAT_OLD
CREATE TABLE ATTEND_PETITION_HDAT( \
    YEAR           VARCHAR(4)    NOT NULL, \
    SEQNO          INTEGER       NOT NULL, \
    SCHREGNO       VARCHAR(8), \
    CONTACTERDIV   VARCHAR(1), \
    CONTACTER      VARCHAR(90), \
    CALLBACK       VARCHAR(1), \
    FIRSTDATE      TIMESTAMP DEFAULT CURRENT TIMESTAMP, \
    FIRSTREGISTER  VARCHAR(10), \
    FROMDATE       DATE, \
    FROMPERIOD     VARCHAR(1), \
    TODATE         DATE, \
    TOPERIOD       VARCHAR(1), \
    DI_CD          VARCHAR(2), \
    DI_REMARK_CD1  VARCHAR(30), \
    DI_REMARK_CD2  VARCHAR(30), \
    DI_REMARK_CD3  VARCHAR(30), \
    DI_REMARK_CD4  VARCHAR(30), \
    DI_REMARK_CD5  VARCHAR(30), \
    DI_REMARK_CD6  VARCHAR(30), \
    DI_REMARK_CD7  VARCHAR(30), \
    DI_REMARK_CD8  VARCHAR(30), \
    DI_REMARK_CD9  VARCHAR(30), \
    DI_REMARK_CD10 VARCHAR(30), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO ATTEND_PETITION_HDAT \
    SELECT \
        * \
    FROM \
        ATTEND_PETITION_HDAT_OLD

ALTER TABLE ATTEND_PETITION_HDAT ADD CONSTRAINT PK_ATTEND_P_HDAT PRIMARY KEY (YEAR,SEQNO)