-- $Id: 47337a499d6611bc4f0aebc95c4ebb09184e9b5e $

DROP TABLE COMB_GCALC_EXEC_DAT_OLD
RENAME TABLE COMB_GCALC_EXEC_DAT TO COMB_GCALC_EXEC_DAT_OLD
CREATE TABLE COMB_GCALC_EXEC_DAT( \
    CALC_DATE                   DATE NOT NULL, \
    CALC_TIME                   TIME NOT NULL, \
    COMBINED_CLASSCD            VARCHAR(2) NOT NULL, \
    COMBINED_SCHOOL_KIND        VARCHAR(2) NOT NULL, \
    COMBINED_CURRICULUM_CD      VARCHAR(2) NOT NULL, \
    COMBINED_SUBCLASSCD         VARCHAR(6) NOT NULL, \
    GVAL_CALC                   VARCHAR(1), \
    YEAR                        VARCHAR(4), \
    REGISTERCD                  VARCHAR(8), \
    UPDATED                     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) in usr1dms index in idx1dms

INSERT INTO COMB_GCALC_EXEC_DAT \
    SELECT \
        CALC_DATE, \
        CALC_TIME, \
        LEFT(COMBINED_SUBCLASSCD, 2) AS COMBINED_CLASSCD, \
        'H' AS COMBINED_SCHOOL_KIND, \
        '2' AS COMBINED_CURRICULUM_CD, \
        COMBINED_SUBCLASSCD, \
        GVAL_CALC, \
        YEAR, \
        REGISTERCD, \
        UPDATED \
    FROM \
        COMB_GCALC_EXEC_DAT_OLD

alter table COMB_GCALC_EXEC_DAT add constraint PK_COM_GC_EXE_DAT \
primary key (CALC_DATE, CALC_TIME, COMBINED_CLASSCD, COMBINED_SCHOOL_KIND, COMBINED_CURRICULUM_CD, COMBINED_SUBCLASSCD)
