-- $Id: 5f206b4f7a8b8782bdfa80796db841186565ee78 $

DROP TABLE POSITION_MST_OLD
RENAME TABLE POSITION_MST TO POSITION_MST_OLD
CREATE TABLE POSITION_MST( \
    POSITIONCD           VARCHAR(4)    NOT NULL, \
    POSITIONNAME         VARCHAR(60), \
    POSITIONABBV1        VARCHAR(60), \
    POSITIONABBV2        VARCHAR(60), \
    BASE_POSITIONNAME    VARCHAR(60), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO POSITION_MST \
    SELECT \
        POSITIONCD, \
        POSITIONNAME, \
        POSITIONABBV1, \
        POSITIONABBV2 , \
        CAST(NULL AS VARCHAR(60)) AS BASE_JOBNAME, \
        REGISTERCD, \
        UPDATED \
    FROM \
        POSITION_MST_OLD

ALTER TABLE POSITION_MST ADD CONSTRAINT PK_POSITION_MST PRIMARY KEY (POSITIONCD)