-- $Id: cb2d9c45f450af8f6d67d18c669fdbdaf9fdf605 $

DROP TABLE SCHREG_ABSENCE_HIGH_SPECIAL_DAT_OLD
RENAME TABLE SCHREG_ABSENCE_HIGH_SPECIAL_DAT TO SCHREG_ABSENCE_HIGH_SPECIAL_DAT_OLD
CREATE TABLE SCHREG_ABSENCE_HIGH_SPECIAL_DAT( \
    YEAR              VARCHAR(4)    NOT NULL, \
    DIV               VARCHAR(1)    NOT NULL, \
    SPECIAL_GROUP_CD  VARCHAR(3)    NOT NULL, \
    SCHREGNO          VARCHAR(8)    NOT NULL, \
    COMP_ABSENCE_HIGH DECIMAL(4,1), \
    GET_ABSENCE_HIGH  DECIMAL(4,1), \
    LESSON            SMALLINT, \
    APPOINTED_DATE    DATE, \
    REGISTERCD        VARCHAR(8), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SCHREG_ABSENCE_HIGH_SPECIAL_DAT \
    SELECT \
        YEAR, \
        DIV, \
        SPECIAL_GROUP_CD, \
        SCHREGNO, \
        COMP_ABSENCE_HIGH, \
        GET_ABSENCE_HIGH, \
        CAST(NULL AS SMALLINT) AS LESSON, \
        APPOINTED_DATE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SCHREG_ABSENCE_HIGH_SPECIAL_DAT_OLD

ALTER TABLE SCHREG_ABSENCE_HIGH_SPECIAL_DAT ADD CONSTRAINT PK_SCH_A_H_S_DAT PRIMARY KEY (YEAR,DIV,SPECIAL_GROUP_CD,SCHREGNO)