-- $Id: 3ee1dd2635af5ab2f3428df05bed8f46e0a788f5 $

DROP TABLE GRD_GUARDIAN2_DAT_OLD
RENAME TABLE GRD_GUARDIAN2_DAT TO GRD_GUARDIAN2_DAT_OLD
CREATE TABLE GRD_GUARDIAN2_DAT( \
    SCHREGNO               VARCHAR(8)    NOT NULL, \
    RELATIONSHIP           VARCHAR(2)    NOT NULL, \
    GUARD_NAME             VARCHAR(120), \
    GUARD_KANA             VARCHAR(240), \
    GUARD_REAL_NAME        VARCHAR(120), \
    GUARD_REAL_KANA        VARCHAR(240), \
    GUARD_SEX              VARCHAR(1), \
    GUARD_BIRTHDAY         DATE, \
    GUARD_ZIPCD            VARCHAR(8), \
    GUARD_ADDR1            VARCHAR(150), \
    GUARD_ADDR2            VARCHAR(150), \
    GUARD_TELNO            VARCHAR(14), \
    GUARD_TELNO2           VARCHAR(14), \
    GUARD_FAXNO            VARCHAR(14), \
    GUARD_E_MAIL           VARCHAR(50), \
    GUARD_JOBCD            VARCHAR(2), \
    GUARD_WORK_NAME        VARCHAR(120), \
    GUARD_WORK_TELNO       VARCHAR(14), \
    GUARANTOR_RELATIONSHIP VARCHAR(2), \
    GUARANTOR_NAME         VARCHAR(120), \
    GUARANTOR_KANA         VARCHAR(240), \
    GUARANTOR_REAL_NAME    VARCHAR(120), \
    GUARANTOR_REAL_KANA    VARCHAR(240), \
    GUARANTOR_SEX          VARCHAR(1), \
    GUARANTOR_ZIPCD        VARCHAR(8), \
    GUARANTOR_ADDR1        VARCHAR(150), \
    GUARANTOR_ADDR2        VARCHAR(150), \
    GUARANTOR_TELNO        VARCHAR(14), \
    GUARANTOR_JOBCD        VARCHAR(2), \
    PUBLIC_OFFICE          VARCHAR(30), \
    REGISTERCD             VARCHAR(10), \
    UPDATED                TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRD_GUARDIAN2_DAT ADD CONSTRAINT PK_GRD_GUARDIAN2 PRIMARY KEY (SCHREGNO)

INSERT INTO GRD_GUARDIAN2_DAT \
    SELECT \
        SCHREGNO, \
        RELATIONSHIP, \
        GUARD_NAME, \
        GUARD_KANA, \
        GUARD_REAL_NAME, \
        GUARD_REAL_KANA, \
        GUARD_SEX, \
        GUARD_BIRTHDAY, \
        GUARD_ZIPCD, \
        GUARD_ADDR1, \
        GUARD_ADDR2, \
        GUARD_TELNO, \
        CAST(NULL AS VARCHAR(14)) AS GUARD_TELNO2, \
        GUARD_FAXNO, \
        GUARD_E_MAIL, \
        GUARD_JOBCD, \
        GUARD_WORK_NAME, \
        GUARD_WORK_TELNO, \
        GUARANTOR_RELATIONSHIP, \
        GUARANTOR_NAME, \
        GUARANTOR_KANA, \
        GUARANTOR_REAL_NAME, \
        GUARANTOR_REAL_KANA, \
        GUARANTOR_SEX, \
        GUARANTOR_ZIPCD, \
        GUARANTOR_ADDR1, \
        GUARANTOR_ADDR2, \
        GUARANTOR_TELNO, \
        GUARANTOR_JOBCD, \
        PUBLIC_OFFICE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        GRD_GUARDIAN2_DAT_OLD

