-- $Id: c01bd4807877a0146d5667646338e06a6bd3a0ec $

DROP TABLE STUDYCLASSREMARK_DAT_OLD
RENAME TABLE STUDYCLASSREMARK_DAT TO STUDYCLASSREMARK_DAT_OLD
CREATE TABLE STUDYCLASSREMARK_DAT( \
     YEAR           VARCHAR(4)  NOT NULL, \
     SCHREGNO       VARCHAR(8)  NOT NULL, \
     CLASSCD        VARCHAR(2)  NOT NULL, \
     SCHOOL_KIND    VARCHAR(2)  NOT NULL, \
     CURRICULUM_CD  VARCHAR(2)  NOT NULL, \
     SUBCLASSCD     VARCHAR(6)  NOT NULL, \
     REMARK         VARCHAR(60), \
     REGISTERCD     VARCHAR(8), \
     UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
 ) in usr1dms index in idx1dms

INSERT INTO STUDYCLASSREMARK_DAT \
    SELECT \
        YEAR, \
        SCHREGNO, \
        CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        REMARK, \
        REGISTERCD, \
        UPDATED \
    FROM \
        STUDYCLASSREMARK_DAT_OLD

alter table STUDYCLASSREMARK_DAT add constraint pk_studyclassremar primary key \
  (YEAR, SCHREGNO, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)
