-- $Id: eb7ed038214c5b1a48ae62b70361932bec661c4b $

DROP TABLE SUBCLASS_SEMVAL_ADJUST_DAT_OLD
RENAME TABLE SUBCLASS_SEMVAL_ADJUST_DAT TO SUBCLASS_SEMVAL_ADJUST_DAT_OLD
CREATE TABLE SUBCLASS_SEMVAL_ADJUST_DAT( \
    YEAR       VARCHAR(4)    NOT NULL, \
    SEMESTER   VARCHAR(1)    NOT NULL, \
    GRADE      VARCHAR(2)    NOT NULL, \
    GROUP_CD   VARCHAR(3)    NOT NULL, \
    CLASSCD       VARCHAR(2) NOT NULL, \
    SCHOOL_KIND   VARCHAR(2) NOT NULL, \
    CURRICULUM_CD VARCHAR(2) NOT NULL, \
    SUBCLASSCD VARCHAR(6)    NOT NULL, \
    TOTAL      SMALLINT, \
    ADJUST     SMALLINT, \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SUBCLASS_SEMVAL_ADJUST_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        GRADE, \
		GROUP_CD, \
        LEFT(SUBCLASSCD, 2) AS CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        TOTAL, \
        ADJUST, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SUBCLASS_SEMVAL_ADJUST_DAT_OLD

ALTER TABLE SUBCLASS_SEMVAL_ADJUST_DAT ADD CONSTRAINT PK_SUB_SMV_ADJ_DAT PRIMARY KEY (YEAR,SEMESTER,GRADE,GROUP_CD,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)