-- $Id: 5c33c759b3e3a16949fed42d3535b1d984b6f429 $

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    CHALLENGED_NAMES \
SET DATA TYPE varchar(150)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    CHALLENGED_STATUS \
SET DATA TYPE varchar(390)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    ONES_HOPE_PRESENT \
SET DATA TYPE varchar(150)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    ONES_HOPE_CAREER \
SET DATA TYPE varchar(150)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    ONES_HOPE_AFTER_GRADUATION \
SET DATA TYPE varchar(150)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    GUARDIAN_HOPE_PRESENT \
SET DATA TYPE varchar(180)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    GUARDIAN_HOPE_CAREER \
SET DATA TYPE varchar(180)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    GUARDIAN_HOPE_AFTER_GRADUATION \
SET DATA TYPE varchar(180)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    MEDICAL_GOAL_AFTER_GRADUATION \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    MEDICAL_STATUS \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    MEDICAL_SHORT_TERM_GOAL \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    MEDICAL_TANGIBLE_SUPPORT \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    WELFARE_GOAL_AFTER_GRADUATION \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    WELFARE_STATUS \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    WELFARE_SHORT_TERM_GOAL \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    WELFARE_TANGIBLE_SUPPORT \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    WORK_GOAL_AFTER_GRADUATION \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    WORK_STATUS \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    WORK_SHORT_TERM_GOAL \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    WORK_TANGIBLE_SUPPORT \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    COMMU_GOAL_AFTER_GRADUATION \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    COMMU_STATUS \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    COMMU_SHORT_TERM_GOAL \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    COMMU_TANGIBLE_SUPPORT \
SET DATA TYPE varchar(120)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    TAKEOVER \
SET DATA TYPE varchar(720)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_MAIN_DAT \
ALTER COLUMN \
    REGISTERCD \
SET DATA TYPE varchar(10)
