-- $Id: c805ab7ce53ad090371f409657132fe8b11f2502 $

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CONSULTATION_RECORD_DAT \
ALTER COLUMN \
    MEETING_NAME \
SET DATA TYPE varchar(150)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CONSULTATION_RECORD_DAT \
ALTER COLUMN \
    TEAM_MEMBERS \
SET DATA TYPE varchar(150)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CONSULTATION_RECORD_DAT \
ALTER COLUMN \
    MEETING_SUMMARY \
SET DATA TYPE varchar(600)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CONSULTATION_RECORD_DAT \
ALTER COLUMN \
    REGISTERCD \
SET DATA TYPE varchar(10)
