-- kanji=漢字
-- $Id: 1ae86ab3e649ea4f1b920fe33bac2ba50e7b3ad6 $

DROP TABLE MAJOR_YDAT_OLD
CREATE TABLE MAJOR_YDAT_OLD LIKE MAJOR_YDAT
INSERT INTO MAJOR_YDAT_OLD SELECT * FROM MAJOR_YDAT
DROP TABLE MAJOR_YDAT
CREATE TABLE MAJOR_YDAT( \
    YEAR        VARCHAR(4)    NOT NULL, \
    COURSECD    VARCHAR(1)    NOT NULL, \
    MAJORCD     VARCHAR(3)    NOT NULL, \
    SCHOOLDIV   VARCHAR(1), \
    REGISTERCD  VARCHAR(8), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS


INSERT INTO MAJOR_YDAT \
    SELECT \
        YEAR, \
        COURSECD, \
        MAJORCD, \
        CAST (NULL AS VARCHAR(1)) AS SCHOOLDIV, \
        REGISTERCD, \
        UPDATED \
    FROM \
        MAJOR_YDAT_OLD
ALTER TABLE MAJOR_YDAT ADD CONSTRAINT PK_MAJOR_YDAT PRIMARY KEY (YEAR,COURSECD,MAJORCD)