-- kanji=´Á»ú
-- $Id: 4e2aea9384cf5aaa6357a9c0acb744c8b68d8b87 $

DROP TABLE INDUSTRY_S_MST_OLD
CREATE TABLE INDUSTRY_S_MST_OLD LIKE INDUSTRY_S_MST
INSERT INTO INDUSTRY_S_MST_OLD SELECT * FROM INDUSTRY_S_MST
DROP TABLE INDUSTRY_S_MST
CREATE TABLE INDUSTRY_S_MST( \
    INDUSTRY_LCD   VARCHAR(1)    NOT NULL, \
    INDUSTRY_MCD   VARCHAR(2)    NOT NULL, \
    INDUSTRY_SCD   VARCHAR(3)    NOT NULL, \
    INDUSTRY_SNAME VARCHAR(150), \
    NO_OUTPUT      VARCHAR(1), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS


INSERT INTO INDUSTRY_S_MST \
    SELECT \
        INDUSTRY_LCD, \
        INDUSTRY_MCD, \
        INDUSTRY_SCD, \
        INDUSTRY_SNAME, \
        NO_OUTPUT, \
        REGISTERCD, \
        UPDATED \
    FROM \
        INDUSTRY_S_MST_OLD
ALTER TABLE INDUSTRY_S_MST ADD CONSTRAINT PK_INDUSTRY_S_MST PRIMARY KEY (INDUSTRY_LCD,INDUSTRY_MCD,INDUSTRY_SCD)
