-- $Id: 16358cbd854f443aeffa486172bc332300e70672 $

DROP TABLE SCH_CHR_DAT_OLD
RENAME TABLE SCH_CHR_DAT TO SCH_CHR_DAT_OLD
CREATE TABLE SCH_CHR_DAT( \
    EXECUTEDATE DATE          NOT NULL, \
    PERIODCD    VARCHAR(1)    NOT NULL, \
    CHAIRCD     VARCHAR(7)    NOT NULL, \
    EXECUTED    VARCHAR(1), \
    EXECUTEDIV  VARCHAR(1), \
    DATADIV     VARCHAR(1), \
    YEAR        VARCHAR(4), \
    SEMESTER    VARCHAR(1), \
    ATTESTOR    VARCHAR(8), \
    REGISTERCD  VARCHAR(8), \
    UPDATED     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SCH_CHR_DAT \
    SELECT \
        EXECUTEDATE, \
        PERIODCD, \
        CHAIRCD, \
        EXECUTED, \
        CAST(NULL AS VARCHAR(1)) AS EXECUTEDIV, \
        DATADIV, \
        YEAR, \
        SEMESTER, \
        ATTESTOR, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SCH_CHR_DAT_OLD

ALTER TABLE SCH_CHR_DAT ADD CONSTRAINT PK_SCH_CHR_DAT PRIMARY KEY (EXECUTEDATE,PERIODCD,CHAIRCD)
