-- $Id: 630b17194983458c581c465db9da4cf901d08821 $

DROP TABLE STAFF_CLASS_MST_OLD
RENAME TABLE STAFF_CLASS_MST TO STAFF_CLASS_MST_OLD
CREATE TABLE STAFF_CLASS_MST( \
    STAFFCD         VARCHAR(8) NOT NULL, \
    CLASSCD         VARCHAR(2) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    SDATE           DATE NOT NULL, \
    EDATE           DATE NOT NULL, \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) in usr1dms index in idx1dms

INSERT INTO STAFF_CLASS_MST \
    SELECT \
        STAFFCD, \
        CLASSCD, \
        SCHOOL_KIND, \
        SDATE, \
        EDATE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        STAFF_CLASS_MST_OLD \
    WHERE \
        CURRICULUM_CD = '2'

alter table STAFF_CLASS_MST add constraint PK_STAFF_CLASS_MST primary key(STAFFCD, CLASSCD, SCHOOL_KIND, SDATE)
