-- $Id: 9e94d79522801dbd93b003def9fc3780e8dbe446 $

DROP TABLE TESTSCORE_DAT_OLD
RENAME TABLE TESTSCORE_DAT TO TESTSCORE_DAT_OLD
CREATE TABLE TESTSCORE_DAT( \
    YEAR            VARCHAR(4)    NOT NULL, \
    SEMESTER        VARCHAR(1)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    TESTKINDCD      VARCHAR(2)    NOT NULL, \
    TESTITEMCD      VARCHAR(2)    NOT NULL, \
    SCHREGNO        VARCHAR(8)    NOT NULL, \
    CHAIRCD         VARCHAR(7), \
    ATTEND_FLG      VARCHAR(1), \
    SCORE           smallint, \
    VALUE           smallint, \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

insert into TESTSCORE_DAT \
SELECT \
    YEAR, \
    SEMESTER, \
    LEFT(SUBCLASSCD, 2) AS CLASSCD, \
    'H' AS SCHOOL_KIND, \
    '2' AS CURRICULUM_CD, \
    SUBCLASSCD, \
    TESTKINDCD, \
    TESTITEMCD, \	
    SCHREGNO, \
    CHAIRCD, \
    ATTEND_FLG, \
    SCORE, \
    VALUE, \
    REGISTERCD, \
    UPDATED \
FROM \
    TESTSCORE_DAT_OLD

ALTER TABLE TESTSCORE_DAT ADD CONSTRAINT PK_TESTSCORE_DAT PRIMARY KEY (YEAR, SEMESTER, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, TESTKINDCD, TESTITEMCD, SCHREGNO)