-- kanji=漢字
-- $Id: 2857e51c9e96aea698f994ecf7e08fa1ebf110ba $

DROP TABLE RECORD_COPY_EXEC_DAT_OLD

RENAME TABLE RECORD_COPY_EXEC_DAT TO RECORD_COPY_EXEC_DAT_OLD

CREATE TABLE RECORD_COPY_EXEC_DAT( \
    CALC_DATE       DATE NOT NULL, \
    CALC_TIME       TIME NOT NULL, \
    PROGRAMID       VARCHAR(30), \
    YEAR            VARCHAR(4), \
    SEMESTER        VARCHAR(1), \
    SELECT_HR_CLASS VARCHAR(500), \
    SELECT_SUBCLASS VARCHAR(500), \
    SHORI_DIV       VARCHAR(1), \
    SAKI_TESTCD     VARCHAR(7), \
    MOTO_TESTCD     VARCHAR(7), \
    KARI_DIV        VARCHAR(1), \
    KARI_TESTCD     VARCHAR(7), \
    SOUGAKU_FLG     VARCHAR(2), \
    CONVERT_FLG     VARCHAR(2), \
    KEEKA_OVER_FLG  VARCHAR(2), \
    SIDOU_FLG       VARCHAR(2), \
    DELETE_FLG      VARCHAR(1), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO RECORD_COPY_EXEC_DAT \
SELECT \
    CALC_DATE, \
    CALC_TIME, \
    PROGRAMID, \
    YEAR, \
    SEMESTER, \
    SELECT_HR_CLASS, \
    SELECT_SUBCLASS, \
    SHORI_DIV, \
    SAKI_TESTCD, \
    MOTO_TESTCD, \
    KARI_DIV, \
    KARI_TESTCD, \
    SOUGAKU_FLG, \
    CONVERT_FLG, \
    KEEKA_OVER_FLG, \
    SIDOU_FLG, \
    CAST(NULL AS VARCHAR(1)) AS DELETE_FLG, \
    REGISTERCD, \
    UPDATED \
FROM \
    RECORD_COPY_EXEC_DAT_OLD

ALTER TABLE RECORD_COPY_EXEC_DAT ADD CONSTRAINT PK_REC_COPY_EXE_DT PRIMARY KEY (CALC_DATE,CALC_TIME)