-- $Id: 56c59f8c5bc98df56cb3330f0530945a854590c6 $

drop table CHALLENGED_SUPPORTPLAN_STATUS_DAT_OLD

rename table CHALLENGED_SUPPORTPLAN_STATUS_DAT to CHALLENGED_SUPPORTPLAN_STATUS_DAT_OLD

create table CHALLENGED_SUPPORTPLAN_STATUS_DAT( \
    YEAR           VARCHAR(4)   NOT NULL, \
    DATA_DIV       VARCHAR(2)   NOT NULL, \
    DATA_DIV_NAME  VARCHAR(120) , \
    STATUS_NAME    VARCHAR(120) , \
    STATUS2_NAME   VARCHAR(120) , \
    STATUS3_NAME   VARCHAR(120) , \
    STATUS4_NAME   VARCHAR(120) , \
    REGISTERCD     VARCHAR(10) , \
    UPDATED        TIMESTAMP    DEFAULT CURRENT TIMESTAMP \
 ) in usr1dms index in idx1dms

alter table CHALLENGED_SUPPORTPLAN_STATUS_DAT add constraint CHAL_SUP_ST_D primary key (YEAR,DATA_DIV)

insert into CHALLENGED_SUPPORTPLAN_STATUS_DAT( \
    YEAR, \
    DATA_DIV, \
    DATA_DIV_NAME, \
    STATUS_NAME, \
    STATUS2_NAME, \
    STATUS3_NAME, \
    STATUS4_NAME, \
    REGISTERCD, \
    UPDATED \
 ) select  \
    YEAR, \
    DATA_DIV, \
    DATA_DIV_NAME, \
    STATUS_NAME, \
    STATUS2_NAME, \
    STATUS3_NAME, \
    STATUS4_NAME, \
    REGISTERCD, \
    UPDATED \
 from CHALLENGED_SUPPORTPLAN_STATUS_DAT_OLD

