-- kanji=漢字
-- $Id: c3f6fa419d21b3ec27c7e4994cfd697b639302b4 $

DROP TABLE COURSE_GROUP_CD_DAT_OLD
RENAME TABLE COURSE_GROUP_DAT TO COURSE_GROUP_CD_DAT_OLD
CREATE TABLE COURSE_GROUP_CD_DAT( \
    YEAR       VARCHAR(4)    NOT NULL, \
    GRADE      VARCHAR(2)    NOT NULL, \
    GROUP_CD   VARCHAR(3)    NOT NULL, \
    COURSECD   VARCHAR(1)    NOT NULL, \
    MAJORCD    VARCHAR(3)    NOT NULL, \
    COURSECODE VARCHAR(4)    NOT NULL, \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO COURSE_GROUP_CD_DAT \
    SELECT \
        YEAR, \
        GRADE, \
        GROUP_CD, \
        COURSECD, \
        MAJORCD, \
        COURSECODE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        COURSE_GROUP_CD_DAT_OLD

ALTER TABLE COURSE_GROUP_CD_DAT ADD CONSTRAINT PK_CSE_GRP_CD_DAT PRIMARY KEY (YEAR,GRADE,GROUP_CD,COURSECD,MAJORCD,COURSECODE)