-- kanji=漢字
-- $Id: cd97e2c799edcea663d5fd70ebd7245c086cb2b5 $

DROP TABLE JOBTYPE_S_MST_OLD
RENAME TABLE JOBTYPE_S_MST TO JOBTYPE_S_MST_OLD
CREATE TABLE JOBTYPE_S_MST( \
    JOBTYPE_LCD        VARCHAR(2)    NOT NULL, \
    JOBTYPE_MCD        VARCHAR(2)    NOT NULL, \
    JOBTYPE_SCD        VARCHAR(3)    NOT NULL, \
    JOBTYPE_SNAME      VARCHAR(150)  , \
    JOBTYPE_SNAME_KANA VARCHAR(300)  , \
    REGISTERCD         VARCHAR(10)    , \
    UPDATED            TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS


INSERT INTO JOBTYPE_S_MST \
    SELECT \
        JOBTYPE_LCD, \
        JOBTYPE_MCD, \
        JOBTYPE_SCD, \
        JOBTYPE_SNAME, \
        JOBTYPE_SNAME_KANA, \
        REGISTERCD, \
        UPDATED \
    FROM \
        JOBTYPE_S_MST_OLD
ALTER TABLE JOBTYPE_S_MST ADD CONSTRAINT PK_JOBTYPE_S_MST PRIMARY KEY (JOBTYPE_LCD,JOBTYPE_MCD,JOBTYPE_SCD)