-- kanji=漢字
-- $Id: 10a1faa9c95cd4a703d82eca9b61fde492b93ace $

DROP TABLE COURSE_HOPE_DETAIL_DAT_OLD
CREATE TABLE COURSE_HOPE_DETAIL_DAT_OLD LIKE COURSE_HOPE_DETAIL_DAT
INSERT INTO COURSE_HOPE_DETAIL_DAT_OLD SELECT * FROM COURSE_HOPE_DETAIL_DAT
DROP TABLE COURSE_HOPE_DETAIL_DAT
CREATE TABLE COURSE_HOPE_DETAIL_DAT( \
    ENTRYDATE         DATE          NOT NULL, \
    SEQ               INTEGER       NOT NULL, \
    SCHREGNO          VARCHAR(8)    NOT NULL, \
    HOPE_NUM          INTEGER       NOT NULL, \
    SCHOOL_GROUP      VARCHAR(2), \
    FACULTY_GROUP     VARCHAR(3), \
    DEPARTMENT_GROUP  VARCHAR(3), \
    SCHOOL_CD         VARCHAR(12), \
    FACULTYCD         VARCHAR(3), \
    DEPARTMENTCD      VARCHAR(3), \
    HOWTOEXAM         INTEGER, \
    JOBTYPE_LCD       VARCHAR(2), \
    JOBTYPE_MCD       VARCHAR(2), \
    JOBTYPE_SCD       VARCHAR(3), \
    WORK_AREA         VARCHAR(1), \
    INTRODUCTION_DIV  VARCHAR(1), \
    REGISTERCD        VARCHAR(10), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS


INSERT INTO COURSE_HOPE_DETAIL_DAT \
    SELECT \
        * \
    FROM \
        COURSE_HOPE_DETAIL_DAT_OLD
ALTER TABLE COURSE_HOPE_DETAIL_DAT ADD CONSTRAINT PK_COURSE_HOPE_DET PRIMARY KEY (ENTRYDATE, SEQ, SCHREGNO, HOPE_NUM)