-- $Id: 3ad66e40b593da74efcfad5b3fe1b8c8a6bffa04 $

DROP TABLE GRD_GUARANTOR_ADDRESS_DAT_OLD
RENAME TABLE GRD_GUARANTOR_ADDRESS_DAT TO GRD_GUARANTOR_ADDRESS_DAT_OLD
CREATE TABLE GRD_GUARANTOR_ADDRESS_DAT( \
    SCHREGNO               VARCHAR(8)    NOT NULL, \
    ISSUEDATE              DATE          NOT NULL, \
    EXPIREDATE             DATE, \
    GUARANTOR_ZIPCD        VARCHAR(8), \
    GUARANTOR_ADDR1        VARCHAR(150), \
    GUARANTOR_ADDR2        VARCHAR(150), \
    GUARANTOR_ADDR_FLG     VARCHAR(1), \
    GUARANTOR_TELNO        VARCHAR(14), \
    REGISTERCD             VARCHAR(8), \
    UPDATED                TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO GRD_GUARANTOR_ADDRESS_DAT \
    SELECT \
        T1.SCHREGNO, \
        T1.ISSUEDATE, \
        T1.EXPIREDATE, \
        T1.GUARANTOR_ZIPCD, \
        T1.GUARANTOR_ADDR1, \
        T1.GUARANTOR_ADDR2, \
        T1.GUARANTOR_ADDR_FLG, \
        T1.GUARANTOR_TELNO, \
        T1.REGISTERCD, \
        T1.UPDATED \
    FROM \
        GRD_GUARANTOR_ADDRESS_DAT_OLD T1 

ALTER TABLE GRD_GUARANTOR_ADDRESS_DAT ADD CONSTRAINT PK_GRD_GUARANTOR_A PRIMARY KEY (SCHREGNO, ISSUEDATE)