-- $Id: 2b3291c04fd237d2a086e3e70d28aed356de5a04 $

DROP TABLE RECORD_REMARK_DAT_OLD
RENAME TABLE RECORD_REMARK_DAT TO RECORD_REMARK_DAT_OLD
CREATE TABLE RECORD_REMARK_DAT( \
    YEAR            VARCHAR(4)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    SCHREGNO        VARCHAR(8)    NOT NULL, \
    REMARK          VARCHAR(60), \
    RECOGNITION_FLG VARCHAR(1), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO RECORD_REMARK_DAT \
    SELECT \
        YEAR, \
        LEFT(SUBCLASSCD, 2) AS CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        SCHREGNO, \
        REMARK, \
        RECOGNITION_FLG, \
        REGISTERCD, \
        UPDATED \
    FROM \
        RECORD_REMARK_DAT_OLD

ALTER TABLE RECORD_REMARK_DAT ADD CONSTRAINT PK_REC_REMARK_DAT PRIMARY KEY (YEAR,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO)