-- $Id: e7b76f86ba2c508dd5a025d262d0384d5e878c0a $

DROP TABLE CLASS_REQUIRED_ERR_DAT_OLD
RENAME TABLE CLASS_REQUIRED_ERR_DAT TO CLASS_REQUIRED_ERR_DAT_OLD
CREATE TABLE CLASS_REQUIRED_ERR_DAT( \
     SCHREGNO       VARCHAR(8) NOT NULL, \
     CLASSCD        VARCHAR(2) NOT NULL, \
     SCHOOL_KIND    VARCHAR(2) NOT NULL, \
     REGISTERCD     VARCHAR(8), \
     UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) in usr1dms index in idx1dms

INSERT INTO CLASS_REQUIRED_ERR_DAT \
    SELECT \
        SCHREGNO, \
        CLASSCD, \
        SCHOOL_KIND, \
        REGISTERCD, \
        UPDATED \
    FROM \
        CLASS_REQUIRED_ERR_DAT_OLD \
    WHERE \
        CURRICULUM_CD = '2'

alter table CLASS_REQUIRED_ERR_DAT add constraint PK_CLASSREQUIRE primary key (SCHREGNO, CLASSCD, SCHOOL_KIND)
