-- $Id: 36bf24bc4e8c0dfa1122014590ff1e288931bf6d $

DROP TABLE STAFF_ADDRESS_DAT_OLD

RENAME TABLE STAFF_ADDRESS_DAT TO STAFF_ADDRESS_DAT_OLD

CREATE TABLE STAFF_ADDRESS_DAT( \
    STAFFCD      VARCHAR(10)   NOT NULL, \
    SDATE        DATE          NOT NULL, \
    EDATE        DATE         , \
    STAFFZIPCD   VARCHAR(8)   , \
    STAFFADDR1   VARCHAR(150) , \
    STAFFADDR2   VARCHAR(150) , \
    STAFFTELNO   VARCHAR(14)  , \
    STAFFFAXNO   VARCHAR(14)  , \
    STAFFE_MAIL  VARCHAR(50)  , \
    REGISTERCD   VARCHAR(10)  , \
    UPDATED      TIMESTAMP     DEFAULT CURRENT TIMESTAMP \
 ) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE STAFF_ADDRESS_DAT ADD CONSTRAINT PK_STAFF_ADDRESS PRIMARY KEY (STAFFCD,SDATE)

INSERT INTO STAFF_ADDRESS_DAT( \
    STAFFCD, \
    SDATE, \
    EDATE, \
    STAFFZIPCD, \
    STAFFADDR1, \
    STAFFADDR2, \
    STAFFTELNO, \
    STAFFFAXNO, \
    STAFFE_MAIL, \
    REGISTERCD, \
    UPDATED \
 ) SELECT  \
    STAFFCD, \
    SDATE, \
    EDATE, \
    STAFFZIPCD, \
    STAFFADDR1, \
    STAFFADDR2, \
    STAFFTELNO, \
    STAFFFAXNO, \
    STAFFE_MAIL, \
    REGISTERCD, \
    UPDATED \
 FROM STAFF_ADDRESS_DAT_OLD

