-- $Id: d6fb35e711c7ab4d1bc1c075ff662e13d6b5788c $

DROP TABLE HREPORT_GUIDANCE_SCHREG_UNIT_DAT_OLD
RENAME TABLE HREPORT_GUIDANCE_SCHREG_UNIT_DAT TO HREPORT_GUIDANCE_SCHREG_UNIT_DAT_OLD
CREATE TABLE HREPORT_GUIDANCE_SCHREG_UNIT_DAT( \
    YEAR                VARCHAR(4) NOT NULL, \
    SEMESTER            VARCHAR(1) NOT NULL, \
    SCHREGNO            VARCHAR(8) NOT NULL, \
    CLASSCD             VARCHAR(2) NOT NULL, \
    SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    CURRICULUM_CD       VARCHAR(2) NOT NULL, \
    SUBCLASSCD          VARCHAR(6) NOT NULL, \
    UNITCD              VARCHAR(2) NOT NULL, \
    GUIDANCE_PATTERN    VARCHAR(1) NOT NULL, \
    REMARK1             VARCHAR(708), \
    REMARK_VALUE1       VARCHAR(6), \
    REMARK2             VARCHAR(708), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO HREPORT_GUIDANCE_SCHREG_UNIT_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        SCHREGNO, \
        CLASSCD, \
        SCHOOL_KIND, \
        CURRICULUM_CD, \
        SUBCLASSCD, \
        UNITCD, \
        GUIDANCE_PATTERN, \
        REMARK1, \
        REMARK_VALUE1, \
        CAST(NULL AS VARCHAR(708)) AS REMARK2, \
        REGISTERCD, \
        UPDATED \
    FROM \
        HREPORT_GUIDANCE_SCHREG_UNIT_DAT_OLD

ALTER TABLE HREPORT_GUIDANCE_SCHREG_UNIT_DAT ADD CONSTRAINT PK_HRE_GUID_SCHUNI PRIMARY KEY (YEAR, SEMESTER, SCHREGNO, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, UNITCD)
