-- $Id: 0ca5a0aa7584009a30300a3b6e0e06063f8d0de9 $

DROP TABLE COURSE_MST_OLD
RENAME TABLE COURSE_MST TO COURSE_MST_OLD
CREATE TABLE COURSE_MST( \
    COURSECD   VARCHAR(1)    NOT NULL, \
    COURSENAME VARCHAR(60), \
    COURSEABBV VARCHAR(60), \
    COURSEENG  VARCHAR(10), \
    S_PERIODCD VARCHAR(1), \
    E_PERIODCD VARCHAR(1), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO COURSE_MST \
    SELECT \
        COURSECD, \
        COURSENAME, \
        COURSEABBV, \
        COURSEENG, \
        S_PERIODCD, \
        E_PERIODCD, \
        REGISTERCD, \
        UPDATED \
    FROM \
        COURSE_MST_OLD

ALTER TABLE COURSE_MST ADD CONSTRAINT PK_COURSE_MST PRIMARY KEY (COURSECD)