-- $Id: 613ee2f2c36283d3483eb5945b170710535c0825 $


drop table MENU_STAFF_MST_OLD
create table MENU_STAFF_MST_OLD like MENU_STAFF_MST
insert into MENU_STAFF_MST_OLD select * from MENU_STAFF_MST

DROP TABLE MENU_STAFF_MST

CREATE TABLE MENU_STAFF_MST( \
    SCHOOLCD        VARCHAR(12) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)  NOT NULL, \
    STAFFCD         VARCHAR(10) NOT NULL, \
    MENUID          VARCHAR(11) NOT NULL, \
    SUBMENUID       VARCHAR(1), \
    PARENTMENUID    VARCHAR(11), \
    MENUNAME        VARCHAR(120), \
    PROGRAMID       VARCHAR(20), \
    PROGRAMPATH     VARCHAR(40), \
    PROCESSCD       VARCHAR(1), \
    INVALID_FLG     VARCHAR(1), \
    PROGRAMMEMO     VARCHAR(3000), \
    SHOWORDER       SMALLINT, \
    SSL             VARCHAR(1), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO MENU_STAFF_MST \
    SELECT \
        '000000000000', \
        'H', \
        STAFFCD, \
        MENUID, \
        SUBMENUID, \
        PARENTMENUID, \
        MENUNAME, \
        PROGRAMID, \
        PROGRAMPATH, \
        PROCESSCD, \
        INVALID_FLG, \
        PROGRAMMEMO, \
        SHOWORDER, \
        SSL, \
        REGISTERCD, \
        UPDATED \
    FROM \
        MENU_STAFF_MST_OLD

ALTER TABLE MENU_STAFF_MST ADD CONSTRAINT PK_MENU_STAFF PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, STAFFCD, MENUID)
