-- $Id: 84043ad7b4f005cd52297503235ad6936aa903dd $

DROP TABLE JVIEWSTAT_REPORTREMARK_DAT_OLD
RENAME TABLE JVIEWSTAT_REPORTREMARK_DAT TO JVIEWSTAT_REPORTREMARK_DAT_OLD
create table JVIEWSTAT_REPORTREMARK_DAT(  \
    YEAR          VARCHAR(4)  NOT NULL, \
    SEMESTER      VARCHAR(1)  NOT NULL, \
    SCHREGNO      VARCHAR(8)  NOT NULL, \
    CLASSCD       VARCHAR(2)  NOT NULL, \
    SCHOOL_KIND   VARCHAR(2)  NOT NULL, \
    CURRICULUM_CD VARCHAR(2)  NOT NULL, \
    SUBCLASSCD    VARCHAR(6)  NOT NULL, \
    REMARK1       VARCHAR(780),  \
    REMARK2       VARCHAR(780),  \
    REMARK3       VARCHAR(780),  \
    REGISTERCD    VARCHAR(8),  \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) in usr1dms index in idx1dms

INSERT INTO JVIEWSTAT_REPORTREMARK_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        SCHREGNO, \
        LEFT(SUBCLASSCD, 2) AS CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
	    REMARK1, \
	    REMARK2, \
	    REMARK3, \
        REGISTERCD, \
        UPDATED \
    FROM \
        JVIEWSTAT_REPORTREMARK_DAT_OLD

alter table JVIEWSTAT_REPORTREMARK_DAT  \
add constraint pk_jviewstat_rep  \
primary key  \
(YEAR, SEMESTER, SCHREGNO, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD)
