-- $Id: a12dcc7c369e10f82c071bc4f1f748d77375303d $

drop table SCHOOL_MST_OLD
create table SCHOOL_MST_OLD like SCHOOL_MST
insert into SCHOOL_MST_OLD select * from SCHOOL_MST

DROP TABLE SCHOOL_MST

CREATE TABLE SCHOOL_MST( \
    YEAR              VARCHAR(4)    NOT NULL, \
    SCHOOLCD          VARCHAR(12) not null, \
    SCHOOL_KIND       VARCHAR(2) not null, \
    FOUNDEDYEAR       VARCHAR(4), \
    PRESENT_EST       VARCHAR(3), \
    CLASSIFICATION    VARCHAR(6), \
    SCHOOLNAME1       VARCHAR(90), \
    SCHOOLNAME2       VARCHAR(90), \
    SCHOOLNAME3       VARCHAR(90), \
    SCHOOLNAME_ENG    VARCHAR(60), \
    SCHOOLZIPCD       VARCHAR(8), \
    SCHOOLADDR1       VARCHAR(150), \
    SCHOOLADDR2       VARCHAR(150), \
    SCHOOLADDR1_ENG   VARCHAR(150), \
    SCHOOLADDR2_ENG   VARCHAR(150), \
    SCHOOLTELNO       VARCHAR(14), \
    SCHOOLFAXNO       VARCHAR(14), \
    SCHOOLMAIL        VARCHAR(50), \
    SCHOOLURL         VARCHAR(50), \
    SCHOOLDIV         VARCHAR(1), \
    SEMESTERDIV       VARCHAR(1), \
    GRADE_HVAL        VARCHAR(2), \
    ENTRANCE_DATE     DATE, \
    GRADUATE_DATE     DATE, \
    GRAD_CREDITS      SMALLINT, \
    GRAD_COMP_CREDITS SMALLINT, \
    SEMES_ASSESSCD    VARCHAR(1), \
    SEMES_FEARVAL     SMALLINT, \
    GRADE_FEARVAL     SMALLINT, \
    ABSENT_COV        VARCHAR(1), \
    ABSENT_COV_LATE   SMALLINT, \
    GVAL_CALC         VARCHAR(1), \
    SUB_OFFDAYS       VARCHAR(1), \
    SUB_ABSENT        VARCHAR(1), \
    SUB_SUSPEND       VARCHAR(1), \
    SUB_MOURNING      VARCHAR(1), \
    SUB_VIRUS         VARCHAR(1), \
    SEM_OFFDAYS       VARCHAR(1), \
    REGISTERCD        VARCHAR(10), \
    UPDATED           TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SCHOOL_MST \
    SELECT \
        YEAR, \
        '000000000000', \
        'H', \
        FOUNDEDYEAR, \
        PRESENT_EST, \
        CLASSIFICATION, \
        SCHOOLNAME1, \
        SCHOOLNAME2, \
        SCHOOLNAME3, \
        SCHOOLNAME_ENG, \
        SCHOOLZIPCD, \
        SCHOOLADDR1, \
        SCHOOLADDR2, \
        SCHOOLADDR1_ENG, \
        SCHOOLADDR2_ENG, \
        SCHOOLTELNO, \
        SCHOOLFAXNO, \
        SCHOOLMAIL, \
        SCHOOLURL, \
        SCHOOLDIV, \
        SEMESTERDIV, \
        GRADE_HVAL, \
        ENTRANCE_DATE, \
        GRADUATE_DATE, \
        GRAD_CREDITS, \
        GRAD_COMP_CREDITS, \
        SEMES_ASSESSCD, \
        SEMES_FEARVAL, \
        GRADE_FEARVAL, \
        ABSENT_COV, \
        ABSENT_COV_LATE, \
        GVAL_CALC, \
        SUB_OFFDAYS, \
        SUB_ABSENT, \
        SUB_SUSPEND, \
        SUB_MOURNING, \
        SUB_VIRUS, \
        SEM_OFFDAYS, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SCHOOL_MST_OLD

ALTER TABLE SCHOOL_MST ADD CONSTRAINT PK_SCHOOL_MST PRIMARY KEY (YEAR, SCHOOLCD, SCHOOL_KIND)
