-- $Id: 2038edd0722643c60e8708d9e6690d87ce2b5e1b $

DROP TABLE HTESTREMARK_DAT_OLD
RENAME TABLE HTESTREMARK_DAT TO HTESTREMARK_DAT_OLD
CREATE TABLE HTESTREMARK_DAT( \
    YEAR            VARCHAR(4)    NOT NULL, \
    SEMESTER        VARCHAR(1)    NOT NULL, \
    SCHREGNO        VARCHAR(8)    NOT NULL, \
    TESTKINDCD      VARCHAR(2)    NOT NULL, \
    TESTITEMCD      VARCHAR(2)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    DIV             VARCHAR(1)    NOT NULL, \
    REMARK     VARCHAR(150), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO HTESTREMARK_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        SCHREGNO, \
        TESTKINDCD, \
        TESTITEMCD, \
        LEFT(SUBCLASSCD, 2) AS CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        DIV, \
        REMARK, \
        REGISTERCD, \
        UPDATED \
    FROM \
        HTESTREMARK_DAT_OLD

ALTER TABLE HTESTREMARK_DAT ADD CONSTRAINT PK_HTESTREMARK_DAT PRIMARY KEY (YEAR,SEMESTER,SCHREGNO,TESTKINDCD,TESTITEMCD,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,DIV)