-- kanji=´Á»ú
-- $Id: daba685b293fce1f1abf3d506f0229376dd59b25 $

DROP TABLE GRD_STUDYRECREMARK_DAT_OLD
RENAME TABLE GRD_STUDYRECREMARK_DAT TO GRD_STUDYRECREMARK_DAT_OLD
CREATE TABLE GRD_STUDYRECREMARK_DAT( \
    YEAR            VARCHAR(4)    NOT NULL, \
    SCHREGNO        VARCHAR(8)    NOT NULL, \
    CLASSCD         VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND     VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD   VARCHAR(2)    NOT NULL, \
    SUBCLASSCD      VARCHAR(6)    NOT NULL, \
    REMARK          VARCHAR(150), \
    REGISTERCD      VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO GRD_STUDYRECREMARK_DAT \
    SELECT \
        YEAR, \
        SCHREGNO, \
        CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        REMARK, \
        REGISTERCD, \
        UPDATED \
    FROM \
        GRD_STUDYRECREMARK_DAT_OLD

ALTER TABLE GRD_STUDYRECREMARK_DAT ADD CONSTRAINT PK_GRD_STDRECREM PRIMARY KEY (YEAR,SCHREGNO,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)