-- $Id: 14229da3e04c9967ed7717f9afed976bb7e41084 $

DROP TABLE SPECIALACT_ATTEND_DAT_OLD
RENAME TABLE SPECIALACT_ATTEND_DAT TO SPECIALACT_ATTEND_DAT_OLD
CREATE TABLE SPECIALACT_ATTEND_DAT( \
    YEAR            VARCHAR(4) NOT NULL, \
    SEMESTER        VARCHAR(1) NOT NULL, \
    SCHREGNO        VARCHAR(8) NOT NULL, \
    CLASSCD         VARCHAR(2) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    CURRICULUM_CD   VARCHAR(2) NOT NULL, \
    SUBCLASSCD      VARCHAR(6) NOT NULL, \
    ATTENDDATE      DATE       NOT NULL, \
    PERIODF         VARCHAR(1) NOT NULL, \
    PERIODT         VARCHAR(1) NOT NULL, \
    CHAIRCD         VARCHAR(7), \
    CREDIT_TIME     DECIMAL(3,1), \
    REMARK          VARCHAR(90), \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) in usr1dms index in idx1dms

INSERT INTO SPECIALACT_ATTEND_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        SCHREGNO, \
        LEFT(SUBCLASSCD, 2) AS CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        ATTENDDATE, \
        PERIODF, \
        PERIODT, \
        CHAIRCD, \
        CREDIT_TIME, \
        REMARK, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SPECIALACT_ATTEND_DAT_OLD

alter table SPECIALACT_ATTEND_DAT add constraint PK_SPECIALACT_ATTE \
primary key (YEAR, SEMESTER, SCHREGNO, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, ATTENDDATE, PERIODF)
