-- $Id: 602502b4fb9382d165302239789d0285b7fa461b $

DROP TABLE EDBOARD_MAJOR_MST_OLD
CREATE TABLE EDBOARD_MAJOR_MST_OLD LIKE EDBOARD_MAJOR_MST
INSERT INTO EDBOARD_MAJOR_MST_OLD SELECT * FROM EDBOARD_MAJOR_MST

DROP TABLE EDBOARD_MAJOR_MST
CREATE TABLE EDBOARD_MAJOR_MST( \
    EDBOARD_SCHOOLCD    VARCHAR(12)     NOT NULL, \
    COURSECD            VARCHAR(1)      NOT NULL, \
    MAJORCD             VARCHAR(3)      NOT NULL, \
    MAJORNAME           VARCHAR(60), \
    MAJORNAME2          VARCHAR(60), \
    MAJORNAME3          VARCHAR(60), \
    MAJORABBV           VARCHAR(6), \
    MAJORENG            VARCHAR(45), \
    MAJORBANKCD         VARCHAR(2), \
    REGISTERCD          VARCHAR(10), \
    UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_MAJOR_MST ADD CONSTRAINT \
PK_ED_MAJOR_MST PRIMARY KEY (EDBOARD_SCHOOLCD, COURSECD, MAJORCD)


INSERT INTO EDBOARD_MAJOR_MST \
    SELECT \
    EDBOARD_SCHOOLCD, \
    COURSECD        , \
    MAJORCD         , \
    MAJORNAME       , \
    MAJORNAME2      , \
    MAJORNAME3      , \
    MAJORABBV       , \
    MAJORENG        , \
    MAJORBANKCD     , \
    REGISTERCD      , \
    UPDATED           \
    FROM \
        EDBOARD_MAJOR_MST_OLD

