-- $Id: 0e72d7d9397631900eb6453c22e496c9e2c7bd4c $

DROP TABLE SUBCLASS_SEMVAL_PERCENT_DAT_OLD
RENAME TABLE SUBCLASS_SEMVAL_PERCENT_DAT TO SUBCLASS_SEMVAL_PERCENT_DAT_OLD
CREATE TABLE SUBCLASS_SEMVAL_PERCENT_DAT( \
    YEAR                    VARCHAR(4)    NOT NULL, \
    SEMESTER                VARCHAR(1)    NOT NULL, \
    GRADE                   VARCHAR(2)    NOT NULL, \
    GROUP_CD                VARCHAR(3)    NOT NULL, \
    CLASSCD       			VARCHAR(2) 	  NOT NULL, \
    SCHOOL_KIND   			VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD 			VARCHAR(2)    NOT NULL, \
    SUBCLASSCD              VARCHAR(6)    NOT NULL, \
    SEQ                     SMALLINT      NOT NULL, \
    TESTDIV                 VARCHAR(1), \
    TESTKINDCD              VARCHAR(2), \
    TESTITEMCD              VARCHAR(2), \
    PROFICIENCYDIV          VARCHAR(2), \
    PROFICIENCYCD           VARCHAR(4), \
    PROFICIENCY_SUBCLASS_CD VARCHAR(6), \
    PERCENT                 SMALLINT, \
    PERFECT                 SMALLINT, \
    REGISTERCD              VARCHAR(8), \
    UPDATED                 TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SUBCLASS_SEMVAL_PERCENT_DAT \
    SELECT \
        YEAR, \
        SEMESTER, \
        GRADE, \
		GROUP_CD, \
        LEFT(SUBCLASSCD, 2) AS CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        SEQ, \
	    TESTDIV, \
	    TESTKINDCD, \
	    TESTITEMCD, \
	    PROFICIENCYDIV, \
	    PROFICIENCYCD, \
	    PROFICIENCY_SUBCLASS_CD, \
	    PERCENT, \
	    PERFECT, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SUBCLASS_SEMVAL_PERCENT_DAT_OLD

ALTER TABLE SUBCLASS_SEMVAL_PERCENT_DAT ADD CONSTRAINT PK_SUB_SMV_PER_DAT PRIMARY KEY (YEAR,SEMESTER,GRADE,GROUP_CD,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SEQ)