-- $Id: d9dedf433b1505ead393903c5d7119c3584fc198 $

DROP TABLE LICENSE_GROUP_STD_YDAT_OLD
RENAME TABLE LICENSE_GROUP_STD_YDAT TO LICENSE_GROUP_STD_YDAT_OLD
CREATE TABLE LICENSE_GROUP_STD_YDAT( \
    YEAR           VARCHAR(4) NOT NULL, \
    GROUP_DIV      VARCHAR(2) NOT NULL, \
    SCHREGNO       VARCHAR(8) NOT NULL, \
    SELECT_DIV     VARCHAR(1) NOT NULL, \
    REMARK1        VARCHAR(1), \
    REMARK2        VARCHAR(1), \
    REMARK3        VARCHAR(1), \
    REMARK4        VARCHAR(1), \
    REMARK5        VARCHAR(1), \
    REMARK6        VARCHAR(1), \
    REMARK7        VARCHAR(1), \
    REMARK8        VARCHAR(1), \
    REMARK9        VARCHAR(1), \
    REMARK10       VARCHAR(150), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE LICENSE_GROUP_STD_YDAT ADD CONSTRAINT PK_LI_GP_STD_YDAT PRIMARY KEY (YEAR, GROUP_DIV, SCHREGNO, SELECT_DIV)

INSERT INTO LICENSE_GROUP_STD_YDAT \
    SELECT \
        * \
    FROM \
        LICENSE_GROUP_STD_YDAT_OLD

