-- $Id: c96d4db97a1e4d441f3c4f257abcd1831aa177bc $

DROP TABLE RECORD_TOTALSTUDYTIME_DAT_OLD
RENAME TABLE RECORD_TOTALSTUDYTIME_DAT TO RECORD_TOTALSTUDYTIME_DAT_OLD
CREATE TABLE RECORD_TOTALSTUDYTIME_DAT( \
    YEAR                VARCHAR(4)     NOT NULL, \
    SEMESTER            VARCHAR(1)     NOT NULL, \
    CLASSCD             VARCHAR(2)     NOT NULL, \
    SCHOOL_KIND         VARCHAR(2)     NOT NULL, \
    CURRICULUM_CD       VARCHAR(2)     NOT NULL, \
    SUBCLASSCD          VARCHAR(6)     NOT NULL, \
    SCHREGNO            VARCHAR(8)     NOT NULL, \
    TOTALSTUDYTIME      VARCHAR(1900) , \
    TOTALSTUDYTIME_FLG  VARCHAR(1)    , \
    TOTALSTUDYACT       VARCHAR(1200) , \
    REMARK1             VARCHAR(1200) , \
    REGISTERCD          VARCHAR(10)   , \
    UPDATED             TIMESTAMP      DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE RECORD_TOTALSTUDYTIME_DAT ADD CONSTRAINT PK_RECORD_TOTA_DAT PRIMARY KEY (YEAR,SEMESTER,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD,SCHREGNO)

INSERT INTO RECORD_TOTALSTUDYTIME_DAT( \
    YEAR, \
    SEMESTER, \
    CLASSCD, \
    SCHOOL_KIND, \
    CURRICULUM_CD, \
    SUBCLASSCD, \
    SCHREGNO, \
    TOTALSTUDYTIME, \
    TOTALSTUDYTIME_FLG, \
    TOTALSTUDYACT, \
    REMARK, \
    REGISTERCD, \
    UPDATED \
 ) SELECT  \
    YEAR, \
    SEMESTER, \
    CLASSCD, \
    SCHOOL_KIND, \
    CURRICULUM_CD, \
    SUBCLASSCD, \
    SCHREGNO, \
    TOTALSTUDYTIME, \
    TOTALSTUDYTIME_FLG, \
    TOTALSTUDYACT, \
    REMARK, \
    REGISTERCD, \
    UPDATED \
 FROM RECORD_TOTALSTUDYTIME_DAT_OLD

