-- $Id: b6f5f7361188b00b8e422c2bc41a639d70f18520 $

DROP TABLE RECORD_CHKFIN_DAT_OLD
RENAME TABLE RECORD_CHKFIN_DAT TO RECORD_CHKFIN_DAT_OLD
CREATE TABLE RECORD_CHKFIN_DAT( \
    YEAR            VARCHAR (4) NOT NULL, \
    SEMESTER        VARCHAR (1) NOT NULL, \
    CLASSCD         VARCHAR (2) NOT NULL, \
    SCHOOL_KIND     VARCHAR (2) NOT NULL, \
    CURRICULUM_CD   VARCHAR (2) NOT NULL, \
    SUBCLASSCD      VARCHAR (6) NOT NULL, \
    CHAIRCD         VARCHAR (7) NOT NULL, \
    TESTKINDCD      VARCHAR (2) NOT NULL, \
    TESTITEMCD      VARCHAR (2) NOT NULL, \
    RECORD_DIV      VARCHAR (1) NOT NULL, \
    EXECUTEDATE     DATE, \
    EXECUTED        VARCHAR (1), \
    REGISTERCD      VARCHAR (8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) in usr1dms index in idx1dms

insert into RECORD_CHKFIN_DAT \
SELECT \
    YEAR, \
    SEMESTER, \
    LEFT(SUBCLASSCD, 2) AS CLASSCD, \
    'H' AS SCHOOL_KIND, \
    '2' AS CURRICULUM_CD, \
    SUBCLASSCD, \
    CHAIRCD, \
    TESTKINDCD, \
    TESTITEMCD, \
    RECORD_DIV, \
    EXECUTEDATE, \
    EXECUTED, \
    REGISTERCD, \
    UPDATED \
FROM \
    RECORD_CHKFIN_DAT_OLD

alter table RECORD_CHKFIN_DAT add constraint PK_RECORD_CF_DAT \
primary key (YEAR, SEMESTER, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, CHAIRCD, TESTKINDCD, TESTITEMCD, RECORD_DIV)
