-- $Id: c55e3de41146baed796a1e8d3e6c84d4314d1051 $

DROP TABLE DUTYSHARE_MST_OLD
RENAME TABLE DUTYSHARE_MST TO DUTYSHARE_MST_OLD
CREATE TABLE DUTYSHARE_MST( \
    DUTYSHARECD      VARCHAR(4)    NOT NULL, \
    SHARENAME       VARCHAR(24), \
    BASE_SHARENAME  VARCHAR(60), \
    REGISTERCD VARCHAR(8), \
    UPDATED    TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO DUTYSHARE_MST \
    SELECT \
        DUTYSHARECD, \
        SHARENAME, \
        CAST(NULL AS VARCHAR(60)) AS BASE_SHARENAME, \
        REGISTERCD, \
        UPDATED \
    FROM \
        DUTYSHARE_MST_OLD

ALTER TABLE DUTYSHARE_MST ADD CONSTRAINT PK_DUTYSHARE_MST PRIMARY KEY (DUTYSHARECD)
