-- $Id: ab84d54f49c02780557afc1a2b1ca47a00316a59 $

DROP TABLE SUBCLASS_REPLACE_SUBSTITUTION_MAJOR_DAT_OLD
RENAME TABLE SUBCLASS_REPLACE_SUBSTITUTION_MAJOR_DAT TO SUBCLASS_REPLACE_SUBSTITUTION_MAJOR_DAT_OLD
CREATE TABLE SUBCLASS_REPLACE_SUBSTITUTION_MAJOR_DAT( \
    YEAR                        VARCHAR(4) NOT NULL, \
    SUBSTITUTION_CLASSCD        VARCHAR(2) NOT NULL, \
    SUBSTITUTION_SCHOOL_KIND    VARCHAR(2) NOT NULL, \
    SUBSTITUTION_CURRICULUM_CD  VARCHAR(2) NOT NULL, \
    SUBSTITUTION_SUBCLASSCD     VARCHAR(6) NOT NULL, \
    ATTEND_CLASSCD              VARCHAR(2) NOT NULL, \
    ATTEND_SCHOOL_KIND          VARCHAR(2) NOT NULL, \
    ATTEND_CURRICULUM_CD        VARCHAR(2) NOT NULL, \
    ATTEND_SUBCLASSCD           VARCHAR(6) NOT NULL, \
    GRADE                       VARCHAR(2) NOT NULL, \
    COURSECD                    VARCHAR(1) NOT NULL, \
    MAJORCD                     VARCHAR(3) NOT NULL, \
    COURSECODE                  VARCHAR(4) NOT NULL, \
    REGISTERCD                  VARCHAR(8), \
    UPDATED                     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SUBCLASS_REPLACE_SUBSTITUTION_MAJOR_DAT \
    SELECT \
        YEAR, \
        LEFT(SUBSTITUTION_SUBCLASSCD, 2) AS SUBSTITUTION_CLASSCD, \
        'H' AS SUBSTITUTION_SCHOOL_KIND, \
        '2' AS SUBSTITUTION_CURRICULUM_CD, \
        SUBSTITUTION_SUBCLASSCD, \
        LEFT(ATTEND_SUBCLASSCD, 2) AS ATTEND_CLASSCD, \
        'H' AS ATTEND_SCHOOL_KIND, \
        '2' AS ATTEND_CURRICULUM_CD, \
        ATTEND_SUBCLASSCD, \
        GRADE, \
        COURSECD, \
        MAJORCD, \
        COURSECODE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SUBCLASS_REPLACE_SUBSTITUTION_MAJOR_DAT_OLD

ALTER TABLE SUBCLASS_REPLACE_SUBSTITUTION_MAJOR_DAT ADD CONSTRAINT SUBCLASS_R_S_M_DAT PRIMARY KEY (YEAR, SUBSTITUTION_CLASSCD, SUBSTITUTION_SCHOOL_KIND, SUBSTITUTION_CURRICULUM_CD, SUBSTITUTION_SUBCLASSCD, ATTEND_CLASSCD, ATTEND_SCHOOL_KIND, ATTEND_CURRICULUM_CD, ATTEND_SUBCLASSCD, GRADE, COURSECD, MAJORCD, COURSECODE)