
DROP TABLE GROUPAUTH_DAT_OLD
RENAME TABLE GROUPAUTH_DAT TO GROUPAUTH_DAT_OLD
CREATE TABLE GROUPAUTH_DAT( \
    SCHOOLCD        VARCHAR(12) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    GROUPCD         VARCHAR(4) NOT NULL, \
    MENUID          VARCHAR(11) NOT NULL, \
    GROUPAUTH       VARCHAR(1), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO GROUPAUTH_DAT \
    SELECT \
        '000000000000', \
        'H', \
        GROUPCD, \
        MENUID, \
        GROUPAUTH, \
        REGISTERCD, \
        UPDATED \
    FROM \
        GROUPAUTH_DAT_OLD
ALTER TABLE GROUPAUTH_DAT ADD CONSTRAINT PK_GROUPAUTH_DAT PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, GROUPCD, MENUID)
