-- $Id: 554285db8abbf75abe887cd68abbff43cded599e $

DROP TABLE EVENT_MST_OLD
RENAME TABLE EVENT_MST TO EVENT_MST_OLD
CREATE TABLE EVENT_MST \
    (SCHOOL_KIND         VARCHAR(2)  NOT NULL, \
     DATA_DIV            VARCHAR(1)  NOT NULL, \
     GRADE               VARCHAR(2)  NOT NULL, \
     COURSECD            VARCHAR(1)  NOT NULL, \
     MAJORCD             VARCHAR(3)  NOT NULL, \
     EXECUTEDATE         DATE  NOT NULL, \
     HR_CLASS            VARCHAR(3)  NOT NULL, \
     HR_CLASS_DIV        VARCHAR(1)  NOT NULL, \
     HOLIDAY_FLG         VARCHAR(1), \
     EVENT_FLG           VARCHAR(1), \
     REMARK1             VARCHAR(150), \
     REMARK2             VARCHAR(150), \
     REGISTERCD          VARCHAR(10), \
     UPDATED             TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO EVENT_MST \
    SELECT \
        SCHOOL_KIND, \
        DATA_DIV, \
        GRADE, \
        COURSECD, \
        MAJORCD, \
        EXECUTEDATE, \
        '000' AS HR_CLASS, \
        '1' AS HR_CLASS_DIV, \
        HOLIDAY_FLG, \
        EVENT_FLG, \
        REMARK1, \
        REMARK2, \
        REGISTERCD, \
        UPDATED \
    FROM \
        EVENT_MST_OLD

ALTER TABLE EVENT_MST ADD CONSTRAINT PK_EVENT_MST PRIMARY KEY (SCHOOL_KIND,DATA_DIV,GRADE,COURSECD,MAJORCD,EXECUTEDATE,HR_CLASS,HR_CLASS_DIV)
