
drop table USERAUTH_DAT_OLD
create table USERAUTH_DAT_OLD like USERAUTH_DAT
insert into USERAUTH_DAT_OLD select * from USERAUTH_DAT

DROP TABLE USERAUTH_DAT

CREATE TABLE USERAUTH_DAT( \
    SCHOOLCD        VARCHAR(12) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    STAFFCD         VARCHAR(10) NOT NULL, \
    MENUID          VARCHAR(11) NOT NULL, \
    USERAUTH        VARCHAR(1), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO USERAUTH_DAT \
    SELECT \
        '000000000000', \
        'H', \
        STAFFCD, \
        MENUID, \
        USERAUTH, \
        REGISTERCD, \
        UPDATED \
    FROM \
        USERAUTH_DAT_OLD
ALTER TABLE USERAUTH_DAT ADD CONSTRAINT PK_USERAUTH_DAT PRIMARY KEY (SCHOOLCD, SCHOOL_KIND, STAFFCD, MENUID)
