-- $Id: b9d952bbfb81012e1e82dbd6ff9cec3e89f76309 $

DROP TABLE SPECIAL_REASON_TEST_DAT_OLD
RENAME TABLE SPECIAL_REASON_TEST_DAT TO SPECIAL_REASON_TEST_DAT_OLD
CREATE TABLE SPECIAL_REASON_TEST_DAT( \
    YEAR            VARCHAR(4) NOT NULL, \
    SEMESTER        VARCHAR(1) NOT NULL, \
    TESTKINDCD      VARCHAR(2) NOT NULL, \
    TESTITEMCD      VARCHAR(2) NOT NULL, \
    SCORE_DIV       VARCHAR(2) NOT NULL, \
    REASON_DIV      VARCHAR(2) NOT NULL, \
    CLASSCD         VARCHAR(2) NOT NULL, \
    SCHOOL_KIND     VARCHAR(2) NOT NULL, \
    CURRICULUM_CD   VARCHAR(2) NOT NULL, \
    SUBCLASSCD      VARCHAR(6) NOT NULL, \
    SCHREGNO        VARCHAR(8) NOT NULL, \
    REMARK          VARCHAR(240), \
    REGISTERCD      VARCHAR(10), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SPECIAL_REASON_TEST_DAT \
    SELECT \
	    YEAR, \
	    SEMESTER, \
	    TESTKINDCD, \
	    TESTITEMCD, \
	    SCORE_DIV, \
	    REASON_DIV, \
	    '00' AS CLASSCD, \
	    '00' AS SCHOOL_KIND, \
	    '00' AS CURRICULUM_CD, \
	    '000000' AS SUBCLASSCD, \
	    SCHREGNO, \
	    REMARK, \
	    REGISTERCD, \
	    UPDATED \
    FROM \
        SPECIAL_REASON_TEST_DAT_OLD

ALTER TABLE SPECIAL_REASON_TEST_DAT ADD CONSTRAINT PK_SPECIAL_REA_DAT PRIMARY KEY (YEAR, SEMESTER, TESTKINDCD, TESTITEMCD, SCORE_DIV, REASON_DIV, CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, SCHREGNO)

