-- $Id: 1a1191d89c640571d382d23f84b418dbf40775ff $

drop table EDBOARD_SCHOOL_MST_OLD
create table EDBOARD_SCHOOL_MST_OLD like EDBOARD_SCHOOL_MST
insert into EDBOARD_SCHOOL_MST_OLD select * from EDBOARD_SCHOOL_MST

drop table EDBOARD_SCHOOL_MST

CREATE TABLE EDBOARD_SCHOOL_MST( \
    EDBOARD_SCHOOLCD      VARCHAR(12)    NOT NULL, \
    EDBOARD_SCHOOLNAME    VARCHAR(60)    NOT NULL, \
    LINK_ADDR             VARCHAR(60), \
    DBNAME                VARCHAR(10), \
    REMARK                VARCHAR(60), \
    GROUPWARE_SCHOOLCD    VARCHAR(12)    NOT NULL, \
    REGISTERCD            VARCHAR(8), \
    UPDATED               TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE EDBOARD_SCHOOL_MST ADD CONSTRAINT PK_EDBOARD_SCHOOL PRIMARY KEY (EDBOARD_SCHOOLCD)

insert into EDBOARD_SCHOOL_MST \
    SELECT \
        EDBOARD_SCHOOLCD, \
        EDBOARD_SCHOOLNAME, \
        LINK_ADDR, \
        DBNAME, \
        REMARK, \
        '000000000000' AS GROUPWARE_SCHOOLCD, \
        REGISTERCD, \
        UPDATED \
    FROM \
        EDBOARD_SCHOOL_MST_OLD
