-- kanji=Š¿Žš
-- $Id: 2b80c830f223e70508bb22b2ce88e8eea51ff65d $

DROP TABLE GRD_HEXAM_ENTREMARK_HDAT_OLD
CREATE TABLE GRD_HEXAM_ENTREMARK_HDAT_OLD LIKE GRD_HEXAM_ENTREMARK_HDAT
INSERT INTO GRD_HEXAM_ENTREMARK_HDAT_OLD SELECT * FROM GRD_HEXAM_ENTREMARK_HDAT
DROP TABLE GRD_HEXAM_ENTREMARK_HDAT
CREATE TABLE GRD_HEXAM_ENTREMARK_HDAT( \
    SCHREGNO       VARCHAR(8)    NOT NULL, \
    COMMENTEX_A_CD VARCHAR(1), \
    DISEASE        VARCHAR(259), \
    DOC_REMARK     VARCHAR(90), \
    TR_REMARK      VARCHAR(159), \
    TOTALSTUDYACT  VARCHAR(746), \
    TOTALSTUDYVAL  VARCHAR(845), \
    BEHAVEREC_REMARK           VARCHAR(845), \
    HEALTHREC                  VARCHAR(845), \
    SPECIALACTREC              VARCHAR(845), \
    TRIN_REF                   VARCHAR(1248), \
    REMARK                     VARCHAR(1500), \
    REMARK2                    VARCHAR(500), \
    TOTALSTUDYACT_SLASH_FLG    VARCHAR(1), \
    TOTALSTUDYVAL_SLASH_FLG    VARCHAR(1), \
    REGISTERCD     VARCHAR(10), \
    UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

ALTER TABLE GRD_HEXAM_ENTREMARK_HDAT ADD CONSTRAINT PK_GRD_HEXAMENTH PRIMARY KEY (SCHREGNO)

INSERT INTO GRD_HEXAM_ENTREMARK_HDAT \
    SELECT \
        SCHREGNO, \
        COMMENTEX_A_CD, \
        DISEASE, \
        DOC_REMARK, \
        TR_REMARK, \
        TOTALSTUDYACT, \
        TOTALSTUDYVAL, \
        BEHAVEREC_REMARK, \
        HEALTHREC, \
        SPECIALACTREC, \
        TRIN_REF, \
        REMARK, \
        REMARK2, \
        TOTALSTUDYACT_SLASH_FLG, \
        TOTALSTUDYVAL_SLASH_FLG, \
        REGISTERCD, \
        UPDATED \
    FROM \
        GRD_HEXAM_ENTREMARK_HDAT_OLD
