-- kanji=漢字
-- $Id: a37c56f58c9c906e2a84e718c51307c856190297 $

DROP TABLE QUESTIONNAIRE_YDAT_OLD
CREATE TABLE QUESTIONNAIRE_YDAT_OLD LIKE QUESTIONNAIRE_YDAT
INSERT INTO QUESTIONNAIRE_YDAT_OLD SELECT * FROM QUESTIONNAIRE_YDAT
DROP TABLE QUESTIONNAIRE_YDAT
CREATE TABLE QUESTIONNAIRE_YDAT( \
    YEAR            VARCHAR(4)    NOT NULL, \
    QUESTIONNAIRECD VARCHAR(2)    NOT NULL, \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS


INSERT INTO QUESTIONNAIRE_YDAT \
    SELECT \
        YEAR, \
        QUESTIONNAIRECD, \
        REGISTERCD, \
        UPDATED \
    FROM \
        QUESTIONNAIRE_YDAT_OLD
ALTER TABLE QUESTIONNAIRE_YDAT ADD CONSTRAINT PK_QUESTIONNAIRE_Y PRIMARY KEY (YEAR,QUESTIONNAIRECD)