-- $Id: 13b799acc00dd1ff734e9f99f58b16268c11f9dc $

drop   table ADMIN_CONTROL_DAT_OLD
create table ADMIN_CONTROL_DAT_OLD like ADMIN_CONTROL_DAT
insert into ADMIN_CONTROL_DAT_OLD select * from ADMIN_CONTROL_DAT

DROP TABLE ADMIN_CONTROL_DAT
CREATE TABLE ADMIN_CONTROL_DAT  \
(  \
        "YEAR"          VARCHAR(4)      NOT NULL, \
        "SCHOOL_KIND"   VARCHAR(2)      NOT NULL, \
        "CONTROL_FLG"   VARCHAR(1)      NOT NULL, \
        "CONTROL_CODE"  VARCHAR(4)      NOT NULL, \
        "REGISTERCD"    VARCHAR(10),  \
        "UPDATED"       TIMESTAMP DEFAULT CURRENT TIMESTAMP  \
) IN USR1DMS INDEX IN IDX1DMS


ALTER TABLE ADMIN_CONTROL_DAT  \
ADD CONSTRAINT PK_ADMIN_CONL_DAT  \
PRIMARY KEY  \
( \
YEAR, \
SCHOOL_KIND, \
CONTROL_FLG, \
CONTROL_CODE \
)

insert into ADMIN_CONTROL_DAT select YEAR, 'H', CONTROL_FLG, CONTROL_CODE, REGISTERCD, UPDATED from ADMIN_CONTROL_DAT_OLD
