-- $Id: 9b062bf4726d1f4ecd313a5a2d2124ce641ad7d8 $

DROP TABLE TESTITEM_MST_COUNTFLG_NEW_OLD
RENAME TABLE TESTITEM_MST_COUNTFLG_NEW TO TESTITEM_MST_COUNTFLG_NEW_OLD
CREATE TABLE TESTITEM_MST_COUNTFLG_NEW( \
    YEAR            VARCHAR(4)    NOT NULL, \
    SEMESTER        VARCHAR(1)    NOT NULL, \
    TESTKINDCD      VARCHAR(2)    NOT NULL, \
    TESTITEMCD      VARCHAR(2)    NOT NULL, \
    TESTITEMNAME    VARCHAR(30), \
    COUNTFLG        VARCHAR(1), \
    SEMESTER_DETAIL VARCHAR(1), \
    TEST_START_DATE DATE, \
    TEST_END_DATE   DATE, \
    REGISTERCD      VARCHAR(8), \
    UPDATED         TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO TESTITEM_MST_COUNTFLG_NEW \
    SELECT \
        YEAR, \
        SEMESTER, \
        TESTKINDCD, \
        TESTITEMCD, \
        TESTITEMNAME, \
        COUNTFLG, \
        SEMESTER_DETAIL, \
        CAST(NULL AS DATE) AS TEST_START_DATE, \
        CAST(NULL AS DATE) AS TEST_END_DATE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        TESTITEM_MST_COUNTFLG_NEW_OLD

ALTER TABLE TESTITEM_MST_COUNTFLG_NEW ADD CONSTRAINT PK_TESTITEM_M_CF_N PRIMARY KEY (YEAR,SEMESTER,TESTKINDCD,TESTITEMCD)