-- $Id: 0b5e3b6a5267ab6b5021b89d9cc2922e05af431e $

DROP TABLE CREDIT_SPECIAL_MST_OLD
RENAME TABLE CREDIT_SPECIAL_MST TO CREDIT_SPECIAL_MST_OLD
CREATE TABLE CREDIT_SPECIAL_MST( \
    YEAR                 VARCHAR(4)    NOT NULL, \
    COURSECD             VARCHAR(1)    NOT NULL, \
    MAJORCD              VARCHAR(3)    NOT NULL, \
    GRADE                VARCHAR(2)    NOT NULL, \
    COURSECODE           VARCHAR(4)    NOT NULL, \
    SPECIAL_GROUP_CD     VARCHAR(3)    NOT NULL, \
    CREDITS              SMALLINT, \
    ABSENCE_HIGH         DECIMAL(4,1), \
    GET_ABSENCE_HIGH     DECIMAL(4,1), \
    ABSENCE_WARN         SMALLINT, \
    ABSENCE_WARN2        SMALLINT, \
    ABSENCE_WARN3        SMALLINT, \
    REQUIRE_FLG          VARCHAR(1), \
    AUTHORIZE_FLG        VARCHAR(1), \
    COMP_UNCONDITION_FLG VARCHAR(1), \
    REGISTERCD           VARCHAR(8), \
    UPDATED              TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO CREDIT_SPECIAL_MST \
    SELECT \
        YEAR, \
        COURSECD, \
        MAJORCD, \
        GRADE, \
        COURSECODE, \
        SPECIAL_GROUP_CD, \
        CREDITS, \
        ABSENCE_HIGH, \
        GET_ABSENCE_HIGH, \
        ABSENCE_WARN, \
        ABSENCE_WARN AS ABSENCE_WARN2, \
        ABSENCE_WARN AS ABSENCE_WARN3, \
        REQUIRE_FLG, \
        AUTHORIZE_FLG, \
        COMP_UNCONDITION_FLG, \
        REGISTERCD, \
        UPDATED \
    FROM \
        CREDIT_SPECIAL_MST_OLD

ALTER TABLE CREDIT_SPECIAL_MST ADD CONSTRAINT PK_CREDIT_SPE_MST PRIMARY KEY (YEAR,COURSECD,MAJORCD,GRADE,COURSECODE,SPECIAL_GROUP_CD)