-- $Id: c30c12a75f78c4778923c3e208741c4d2c1ae53e $

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CHECK_RECORD_DAT \
ALTER COLUMN \
    CHECK_REMARK \
SET DATA TYPE varchar(900)

ALTER TABLE \
    SCHREG_CHALLENGED_TRANSITION_SUPPORTPLAN_CHECK_RECORD_DAT \
ALTER COLUMN \
    REGISTERCD \
SET DATA TYPE varchar(10)
