-- $Id: b71ce14e6d0f37bf6251913bc3e60b1ce9eb6665 $

DROP TABLE SCHREG_STUDYREC_DAT_OLD
RENAME TABLE SCHREG_STUDYREC_DAT TO SCHREG_STUDYREC_DAT_OLD
CREATE TABLE SCHREG_STUDYREC_DAT( \
    SCHOOLCD         VARCHAR(1)    NOT NULL, \
    YEAR             VARCHAR(4)    NOT NULL, \
    SCHREGNO         VARCHAR(8)    NOT NULL, \
    ANNUAL           VARCHAR(2)    NOT NULL, \
    CLASSCD          VARCHAR(2)    NOT NULL, \
    SCHOOL_KIND      VARCHAR(2)    NOT NULL, \
    CURRICULUM_CD    VARCHAR(2)    NOT NULL, \
    SUBCLASSCD       VARCHAR(6)    NOT NULL, \
    CLASSNAME        VARCHAR(30), \
    CLASSABBV        VARCHAR(15), \
    CLASSNAME_ENG    VARCHAR(40), \
    CLASSABBV_ENG    VARCHAR(30), \
    SUBCLASSES       SMALLINT, \
    SUBCLASSNAME     VARCHAR(90), \
    SUBCLASSABBV     VARCHAR(90), \
    SUBCLASSNAME_ENG VARCHAR(40), \
    SUBCLASSABBV_ENG VARCHAR(20), \
    VALUATION        SMALLINT, \
    GET_CREDIT       SMALLINT, \
    ADD_CREDIT       SMALLINT, \
    COMP_CREDIT      SMALLINT, \
    PRINT_FLG        VARCHAR(1), \
    REGISTERCD       VARCHAR(8), \
    UPDATED          TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SCHREG_STUDYREC_DAT \
    SELECT \
        SCHOOLCD, \
        YEAR, \
        SCHREGNO, \
        ANNUAL, \
        CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        CLASSNAME, \
        CLASSABBV, \
        CLASSNAME_ENG, \
        CLASSABBV_ENG, \
        SUBCLASSES, \
        SUBCLASSNAME, \
        SUBCLASSABBV, \
        SUBCLASSNAME_ENG, \
        SUBCLASSABBV_ENG, \
        VALUATION, \
        GET_CREDIT, \
        ADD_CREDIT, \
        COMP_CREDIT, \
        PRINT_FLG, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SCHREG_STUDYREC_DAT_OLD

ALTER TABLE SCHREG_STUDYREC_DAT ADD CONSTRAINT PK_SCHREG_STUDYREC PRIMARY KEY (SCHOOLCD,YEAR,SCHREGNO,ANNUAL,CLASSCD,SCHOOL_KIND,CURRICULUM_CD,SUBCLASSCD)