-- $Id: 0776f88e92ab9ef435494296c81c2fd03f432f9b $

DROP TABLE SUBCLASS_REQUIRED_STUDY_DAT_OLD
RENAME TABLE SUBCLASS_REQUIRED_STUDY_DAT TO SUBCLASS_REQUIRED_STUDY_DAT_OLD
create table SUBCLASS_REQUIRED_STUDY_DAT( \
     CLASSCD        VARCHAR(2) NOT NULL, \
     SCHOOL_KIND    VARCHAR(2) NOT NULL, \
     CURRICULUM_CD  VARCHAR(2) NOT NULL, \
     SUBCLASSCD     VARCHAR(6) NOT NULL, \
     COURSECD       VARCHAR(1) NOT NULL, \
     MAJORCD        VARCHAR(3) NOT NULL, \
     SEQ            VARCHAR(2) NOT NULL, \
     REGISTERCD     VARCHAR(8), \
     UPDATED        TIMESTAMP DEFAULT CURRENT TIMESTAMP \
    ) in usr1dms index in idx1dms

INSERT INTO SUBCLASS_REQUIRED_STUDY_DAT \
    SELECT \
        CLASSCD, \
        'H' AS SCHOOL_KIND, \
        '2' AS CURRICULUM_CD, \
        SUBCLASSCD, \
        COURSECD, \
        MAJORCD, \
        SEQ, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SUBCLASS_REQUIRED_STUDY_DAT_OLD

alter table SUBCLASS_REQUIRED_STUDY_DAT add constraint PK_SUBREQUIRE primary key \
(CLASSCD, SCHOOL_KIND, CURRICULUM_CD, SUBCLASSCD, COURSECD, MAJORCD, SEQ)
