-- $Id: e7096ceb333b16d143e1650a798ee7cb20d4c583 $

DROP TABLE SCHREG_QUALIFIED_HOBBY_DAT_OLD
RENAME TABLE SCHREG_QUALIFIED_HOBBY_DAT TO SCHREG_QUALIFIED_HOBBY_DAT_OLD
CREATE TABLE SCHREG_QUALIFIED_HOBBY_DAT( \
    YEAR          VARCHAR(4)    NOT NULL, \
    SCHREGNO      VARCHAR(8)    NOT NULL, \
    SEQ           SMALLINT      NOT NULL, \
    REGDDATE      DATE          NOT NULL, \
    CLASSCD       VARCHAR(2), \
    SCHOOL_KIND   VARCHAR(2), \
    CURRICULUM_CD VARCHAR(2), \
    SUBCLASSCD    VARCHAR(6), \
    CONDITION_DIV VARCHAR(1), \
    QUALIFIED_CD  VARCHAR(4), \
    CONTENTS      VARCHAR(90), \
    RANK          VARCHAR(3), \
    REMARK        VARCHAR(90), \
    CREDITS       SMALLINT, \
    CERTIFICATE   VARCHAR(1), \
    SCORE         SMALLINT, \
    REGISTERCD    VARCHAR(10), \
    UPDATED       TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) IN USR1DMS INDEX IN IDX1DMS

INSERT INTO SCHREG_QUALIFIED_HOBBY_DAT \
    SELECT \
        YEAR, \
        SCHREGNO, \
        SEQ, \
        REGDDATE, \
        CLASSCD, \
        SCHOOL_KIND, \
        CURRICULUM_CD, \
        SUBCLASSCD, \
        CONDITION_DIV, \
        QUALIFIED_CD, \
        CONTENTS, \
        RANK, \
        REMARK, \
        CREDITS, \
        CERTIFICATE, \
        CAST(NULL AS SMALLINT) AS SCORE, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SCHREG_QUALIFIED_HOBBY_DAT_OLD

ALTER TABLE SCHREG_QUALIFIED_HOBBY_DAT ADD CONSTRAINT PK_SCH_QUAL_H_DAT PRIMARY KEY (YEAR,SCHREGNO,SEQ)