-- $Id: f06244e0a4ed8715e630d160029cf51d2311872a $

DROP TABLE SUBCLASS_REPLACE_DAT_OLD
RENAME TABLE SUBCLASS_REPLACE_DAT TO SUBCLASS_REPLACE_DAT_OLD
CREATE TABLE SUBCLASS_REPLACE_DAT( \
    REPLACECD                   VARCHAR(1) NOT NULL, \
    YEAR                        VARCHAR(4) NOT NULL, \
    ANNUAL                      VARCHAR(2) NOT NULL, \
    ATTEND_CLASSCD              VARCHAR(2) NOT NULL, \
    ATTEND_SCHOOL_KIND          VARCHAR(2) NOT NULL, \
    ATTEND_CURRICULUM_CD        VARCHAR(2) NOT NULL, \
    ATTEND_SUBCLASSCD           VARCHAR(6) NOT NULL, \
    GRADING_CLASSCD             VARCHAR(2) NOT NULL, \
    GRADING_SCHOOL_KIND         VARCHAR(2) NOT NULL, \
    GRADING_CURRICULUM_CD       VARCHAR(2) NOT NULL, \
    GRADING_SUBCLASSCD          VARCHAR(6) NOT NULL, \
    REGISTERCD                  VARCHAR(8), \
    UPDATED                     TIMESTAMP DEFAULT CURRENT TIMESTAMP \
) in usr1dms index in idx1dms

INSERT INTO SUBCLASS_REPLACE_DAT \
    SELECT \
        REPLACECD, \
        YEAR, \
        ANNUAL, \
        LEFT(ATTEND_SUBCLASSCD, 2) AS ATTEND_CLASSCD, \
        'H' AS ATTEND_SCHOOL_KIND, \
        '2' AS ATTEND_CURRICULUM_CD, \
        ATTEND_SUBCLASSCD, \
        LEFT(GRADING_SUBCLASSCD, 2) AS GRADING_CLASSCD, \
        'H' AS GRADING_SCHOOL_KIND, \
        '2' AS GRADING_CURRICULUM_CD, \
        GRADING_SUBCLASSCD, \
        REGISTERCD, \
        UPDATED \
    FROM \
        SUBCLASS_REPLACE_DAT_OLD

alter table SUBCLASS_REPLACE_DAT add constraint PK_SUBCLASS_RP_DAT \
        primary key (REPLACECD, YEAR, ANNUAL, ATTEND_CLASSCD, ATTEND_SCHOOL_KIND, ATTEND_CURRICULUM_CD, ATTEND_SUBCLASSCD, GRADING_CLASSCD, GRADING_SCHOOL_KIND, GRADING_CURRICULUM_CD, GRADING_SUBCLASSCD)
